### ISSUE TITLE
Namespace filter for service discovery

### ISSUE THREAD

**Issue by vchegwidden** [spring-cloud/spring-cloud-kubernetes#1000]
This request is to add the ability to filter/limit namespaces to use for service discovery in the `DiscoveryClient` through a property

When working as a tenant on a shared cluster we don't have permissions to view resources in all namespaces. We also don't have permissions to create cluster roles and cluster rolebindings.
In these situations you can't use the `spring.cloud.kubernetes.discovery.all-namespaces=true` property since it will throw an exception when trying to get resources in namespaces you don't have access to.
Not having the option to list namespaces to take into consideration means you would be limited to a single namespace for all your deployments, which isn't great...

I've been trying to run Spring boot admin in a cluster where my access is limited to only the namespaces I own. When trying to use the `DiscoveryClient` and setting `all-namespaces=true` the following exception is thrown since the service account doesn't have the correct permissions

```
"stack_trace":"i.f.k.c.KubernetesClientException: Failure executing: GET at: https://<nodeIP>/api/v1/namespaces/some-namespace/services. 
    Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. services is forbidden: 
    User \"system:serviceaccount:sba:spring-boot-admin\" cannot list resource \"services\" in API group \"\" in the namespace \"some-namespace\".
```

The work-around I've used is to implement my own `DiscoveryClient` that takes a list of namespaces from a property, then overriding the behaviour of `getServices` and `getEndpointList` to only look in the namespaces supplied (Note I've only tested this with the fabric8 client)

It would however be great if this was included out of the box.

```
@Value("#{'${spring.cloud.kubernetes.discovery.filter-namespaces:}'.split(',')}")
private List<String> filteredNamespaces;

@Override
public List<String> getServices(Predicate<Service> filter) {
    if (filteredNamespaces.isEmpty()) {
        return super.getServices(filter);
    }

    List<String> services = new ArrayList<>();
    for (String ns : filteredNamespaces) {
        services.addAll(
            this.client.services()
                .inNamespace(ns).list().getItems().stream().filter(filter).map(s -> s.getMetadata().getName().toList());
    }
}

@Override
public List<Endpoints> getEndPointsList(String serviceId) {
    if (filteredNamespaces.isEmpty()) {
        return super.getEndpointList(serviceId);
    }

    List<Endpoints> endpoints = new ArrayList<>();
    for (String ns : filteredNamespaces) {
        endpoints.addAll(
            this.client.endpoints()
                .inNamespace(ns).withField("metadata.name", seviceId).withLabels(properties.getServiceLabels().list().getItems());
    }
}

```

**Comment by wind57** [comment]
this is for sure doable, and it is on my radar, just dropping a note here.

**Comment by mehdikhelif** [comment]
That would be really a nice improvement

**Comment by bj-1795** [comment]
hi @mbialkowski1 is there any progress on this one?

**Comment by wind57** [comment]
The PR is in review, I assume a few weeks and it will be part of main. No gurantees whatsoever. The thing is, its going to be part of main branch, jdk-17 only.

**Comment by vbose** [comment]
Also, spring.cloud.kubernetes.discover.filter: "metadata.labels['spring-boot']" does not have any effect. It discovers all services regardless. Any workaround for this issue as well is available? We use spring-cloud-starter-kubernetes-fabric8 dependency in the pom.

**Comment by wind57** [comment]
Looks like a diff issue, please raise a separate issue. Thank you.

**Comment by luisalves00** [comment]
> Also, spring.cloud.kubernetes.discover.filter: "metadata.labels['spring-boot']" does not have any effect. It discovers all services regardless. Any workaround for this issue as well is available? We use spring-cloud-starter-kubernetes-fabric8 dependency in the pom.

is there a solution yet? I'm using fabric8 client as well. I was expecting the following to work:

```yaml
spring:
    cloud:
        kubernetes:
            discovery:
                all-namespaces: true
                filter: "#root.metadata.namespace matches '^uat.*$'"
```

It fails on the health part when we have and invalid SpEL, but seems that it doesn't filter the service even when the [filter seems to be applied on the code](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/9364fb9f4c19eef5ea74656c6d3d8db309a74ad9/spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesDiscoveryClient.java#L288)

Not sure if helps but also found somehow related issue: [990](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/990)

**Comment by luisalves00** [comment]
Opened a new [ticket ](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1182) as this one is closed.
