### ISSUE TITLE
Kubernetes Discovery Issue

### ISSUE THREAD

**Issue by gpinolo** [spring-cloud/spring-cloud-kubernetes#1008]
**Describe the bug**

With following dependencies:

```xml
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-kubernetes-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
```

the application startup fails with the following error

```text
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method kubernetesReactiveDiscoveryClientHealthIndicator in org.springframework.cloud.kubernetes.discovery.KubernetesDiscoveryClientAutoConfiguration$Reactive required a bean of type 'org.springframework.cloud.kubernetes.discovery.KubernetesReactiveDiscoveryClient' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.cloud.kubernetes.discovery.KubernetesReactiveDiscoveryClient' in your configuration.

```

Consider replacing first argument _KubernetesReactiveDiscoveryClient client_ of [kubernetesReactiveDiscoveryClientHealthIndicator](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/01eaac9e43708b7386dc11bb234c5d537a2dc8c2/spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientAutoConfiguration.java#L104)
with _ReactiveDiscoveryClient client_.

**Sample**
A simple app to reproduce the error is available [here](https://github.com/gpinolo/kubernetesDiscoveryIssue)

**Comment by wind57** [comment]
would be it work for you if you would disable it via: 

```
spring.cloud.discovery.client.health-indicator.enabled=false
```

?

**Comment by gpinolo** [comment]
> would it work for you if you would disable it via:
> 
> ```
> spring.cloud.discovery.client.health-indicator.enabled=false
> ```
> 
> ?

Setting this property the application start succesfully

**Comment by wind57** [comment]
if this works for you, then we can close this ticket. wdyt?

**Comment by gpinolo** [comment]
> if this works for you, then we can close this ticket. wdyt?

Replacing first argument KubernetesReactiveDiscoveryClient client of [kubernetesReactiveDiscoveryClientHealthIndicator](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/01eaac9e43708b7386dc11bb234c5d537a2dc8c2/spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientAutoConfiguration.java#L104)
with ReactiveDiscoveryClient client would definitely solve the problem

**Comment by wind57** [comment]
it might, I am not very sure to be honest. I propose to leave this one open for some time, and when I gets my hands onto that specific code, we will take a much closer look.

**Comment by gpinolo** [comment]
Ok. This [simple app](https://github.com/gpinolo/kubernetesDiscoveryIssue) can help you to analyze the problem. 
I look forward to hearing from you

Bye

**Comment by satyam-bala** [comment]
Iam also facing the same issue.   Appreciate if you find any solution.  Even tried to add "spring.cloud.discovery.client.health-indicator.enabled=false"  not solving.

***************************
APPLICATION FAILED TO START
***************************
Description:
Parameter 0 of method kubernetesReactiveDiscoveryClientHealthIndicator in org.springframework.cloud.kubernetes.discovery.KubernetesDiscoveryClientAutoConfiguration$Reactive required a bean of type 'org.springframework.cloud.kubernetes.discovery.KubernetesReactiveDiscoveryClient' that could not be found.

Action:
Consider defining a bean of type 'org.springframework.cloud.kubernetes.discovery.KubernetesReactiveDiscoveryClient' in your configuration.

**Comment by ryanjbaxter** [comment]
Why do you have `spring-boot-starter-web` on the classpath as well?  Can you please remove it and also use `spring-cloud-starter-kubernetes-discovery` and try again?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
