### ISSUE TITLE
spring.cloud.kubernetes.client.namespace

### ISSUE THREAD

**Issue by Jacuo** [spring-cloud/spring-cloud-kubernetes#1022]
**Describe the bug**
Kubernetes client doesn't respect _spring.cloud.kubernetes.client.namespace_ property
I have configured property _spring.cloud.kubernetes.client.namespace_ , but when I log 
_kubernetesDiscoveryClient.getClient().getNamespace()_ it logs not configured namespace, but namespace in which application pod exists
To be more confused documentation https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/appendix.html
shows default value for _spring.cloud.kubernetes.client.namespace_  "true" (?)
I am using _org.springframework.cloud:spring-cloud-starter-parent:2020.0.3_

**Comment by ryanjbaxter** [comment]
Can you please try and reproduce this with Spring Cloud 2021.0.2?

**Comment by Jacuo** [comment]
It is not so easy to change version to 2021 release train. 
I will try 
Anyway on 2020.0.5 it is the same result

**Comment by ryanjbaxter** [comment]
Support for 2020.0.x ended recently so you will need to upgrade

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
