### ISSUE TITLE
upgrade to fabric8 version 6 

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1048]
specifically, I would like to play around JUnit extension that are provided, some of the features should simplify our unit tests quite a lot.

**Comment by henrik242** [comment]
@wind57 This would be awesome! Especially after the soon-to-be-released  6.1.0 which includes a much needed fix: https://github.com/fabric8io/kubernetes-client/pull/4264

Have you looked more into this?

**Comment by wind57** [comment]
not yet, there are more pending things on my plate.

**Comment by henrik242** [comment]
Ok, thanks for the swift reply! Would it be possible to update just the version without needing to touch the junit extensions? Are there breaking changes that need to be addressed?

**Comment by manusa** [comment]
Versión 6 has a few breaking changes, there aren't that many, but I guess it'll be a little bit more involved than just bumping the version number.

**Comment by henrik242** [comment]
[6.1.1](https://github.com/fabric8io/kubernetes-client/releases/tag/v6.1.1) has been released, by the way

**Comment by henrik242** [comment]
@wind57 Has the list of pending things gotten any openings yet?

**Comment by wind57** [comment]
its complicated for me to answer this question to be honest, please bare in mind that I am not part of Spring team, I am just a random contributor. There was just a release of version `3.x.x` of this project, which is a major release and adding such changes on top of that need very, but I mean very careful coding, as we can't introduce any breaking changes. Considering the amount of modules we have, this ain't little work.

While I do have it on my TODO list, I have not yet started it. That's about the response I can provide for now. I am sorry it's not the one you would expect.

**Comment by henrik242** [comment]
Thanks for the insight!

**Comment by wind57** [comment]
@henrik242 this is WIP, see [here](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/1164) :)
