### ISSUE TITLE
The client configuration bean requires additional settings

### ISSUE THREAD

**Issue by iocanel** [spring-cloud/spring-cloud-kubernetes#105]
Currently its out of sync with https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java

Some properties of interest are the proxy related properties which are definitely missing.

**Comment by spencergibb** [comment]
@iocanel, @geoand or @salaboy anyone want to give it a go?

**Comment by geoand** [comment]
I will assign it to me and take a look (hopefully within the week)
