### ISSUE TITLE
two beans doing the same logical thing

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1059]
Scenario: we want to use config-watcher to be able to restart our services, think about it as the `ActuatorRefreshKafkaIT`. For that we will use `spring-cloud-kubernetes-client-config` (used inside the watcher project/image). So when a change in config map is detected - it will trigger `KubernetesClientEventBasedConfigMapChangeDetector` and thus its `onEvent` method too. 

At the same time, `ConfigMapWatcherChangeDetector` will be triggered also, as it extends `KubernetesClientEventBasedConfigMapChangeDetector`, but overrides `onEvent`.

As such, there is a possibility that _both_ beans will shutdown (as an example) the application. We need to make sure that watcher disables `KubernetesClientEventBasedConfigMapChangeDetector` via a flag for example, basically something like this:

```
	protected void onEvent(V1ConfigMap configMap) {
   
                // !!!!!!!! here !!!!!!!
                if (<SOME_FLAG>) {
                      log.debug("watcher will trigger the restart, this is a NOOP")
                      return;
                }

		log.debug(() -> "onEvent configMap: " + configMap.toString());
		boolean changed = changed(locateMapPropertySources(this.propertySourceLocator, this.environment),
				findPropertySources(KubernetesClientConfigMapPropertySource.class));
		if (changed) {
			log.info(() -> "Configuration change detected, reloading properties.");
			reloadProperties();
		}
		else {
			log.warn(() -> "Configuration change was not detected.");
		}

	}
```

Does this make sense? thank you.

**Comment by ryanjbaxter** [comment]
So only disable `KubernetesClientEventBasedConfigMapChangeDetector` in the config watcher?

**Comment by wind57** [comment]
sorry, I am confused, what do you mean?

**Comment by ryanjbaxter** [comment]
You are saying we should only have ConfigMapWatcherChangeDetector run it's onEvent method right?

**Comment by wind57** [comment]
correct.

**Comment by ryanjbaxter** [comment]
But wouldn't `KubernetesClientEventBasedConfigMapChangeDetector` only refresh the configuration is the configuration of the config watcher changed?

**Comment by wind57** [comment]
sorry, it might be the fact that its 12 PM over here... I'll think about this a bit more and will reply.

**Comment by wind57** [comment]
you're right. Sorry, I messed things up. Indeed `KubernetesClientEventBasedConfigMapChangeDetector` is part of the watcher image, so this is not really a bug, but more of an enhancement.

**Comment by ryanjbaxter** [comment]
Why is this a bug then?  What if you want the configuration to be automatically updated for the config watcher?
