### ISSUE TITLE
Latest build failure - maven resolution issue

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1073]
The latest build failure revealed a very interesting bug (imo) that we have.

Our `spring-cloud-kubernetes-configserver` has such a dependency without a version:

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
		</dependency>
```

This dependency is taken from our root `pom.xml` (via 2 more parents), specifically from:

```
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-config-dependencies</artifactId>
				<version>${spring-cloud-config.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
```

which resides under `dependencyManagement`, where `spring-cloud-config.version` == `4.0.0-SNAPSHOT`. 

Internally, `spring-cloud-config-server` depends on micrometer, like so (this is just an example I made locally to be able to reproduce):

```
[INFO] org.example:spring-transitive-dependecy-issue:jar:1.0-SNAPSHOT
[INFO] \- org.springframework.cloud:spring-cloud-config-server:jar:4.0.0-SNAPSHOT:compile
[INFO]    \- io.micrometer:micrometer-observation:jar:1.10.0-M3:compile
[INFO]       \- io.micrometer:micrometer-commons:jar:1.10.0-M3:compile
```

In our project though, we have a parent in our root `pom.xml`:

```
    <parent>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-build</artifactId>
        <version>4.0.0-SNAPSHOT</version>
    </parent>
```

and this one causes the version to be overridden, so it becomes:

```
[INFO] org.example:spring-transitive-dependecy-issue:jar:1.0-SNAPSHOT
[INFO] \- org.springframework.cloud:spring-cloud-config-server:jar:4.0.0-SNAPSHOT:compile
[INFO]    \- io.micrometer:micrometer-observation:jar:1.10.0-SNAPSHOT:compile (version managed from 1.10.0-M3)
[INFO]       \- io.micrometer:micrometer-commons:jar:1.10.0-SNAPSHOT:compile
```

because at the moment `spring-cloud-build` -> `spring-cloud-build-dependencies` -> `spring-boot-dependencies:3.0.0-SNAPSHOT` (parent) -> `<micrometer.version>1.10.0-SNAPSHOT</micrometer.version>`.

This is a bug, we should never depend on micrometer from `spring-cloud-build` (parent of our main `pom.xml`), but only on the `spring-cloud-config-dependencies` (from `dependencyManagement`).

The beauty is that maven does not allow exclusions from parents, afaik, so at the moment I don't really know how to fix this.

**Comment by ryanjbaxter** [comment]
Once I fixed spring-cloud-config this appeared to fix everything.  It should all work now.

**Comment by wind57** [comment]
where? what did you fix exactly?

**Comment by wind57** [comment]
nvm, I see it. let me try to understand what you did

**Comment by wind57** [comment]
ah yes! I did not know that was an option :D you now rely on whatever spring-boot provides - this is indeed the most correct way to fix this, but I was not even sure this is a possibility. 

thx a lot for looking into this and fixing it!

**Comment by ryanjbaxter** [comment]
Yeah it was some legacy stuff before boot had the dependency management for micrometer
