### ISSUE TITLE
We have two kubernetes native discovery implementations

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1086]
There has to be a reason for this, but I can't figure it out yet. We have two implementations for discovery:

- `spring-cloud-kubernetes-discovery`
- `spring-cloud-kubrnetes-client-discovery`

We even have a starter : `spring-cloud-starter-kubernetes-discoveryclient` that uses `spring-cloud-kubernetes-discovery` that does not have counter part in fabric8... 

It seems to me that `spring-cloud-kubernetes-discovery` is outdated, and I am inclined to think like this because 

`spring-cloud-kubernetes-discoveryserver` uses `spring-cloud-starter-kubernetes-client` that is based on `spring-cloud-kubernetes-client-discovery`. 

---

I don't think that the documentation is accurate either, as it says:

>  spring-cloud-starter-kubernetes-discoveryclient is designed to be used with the [Spring Cloud Kubernetes DiscoveryServer](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#spring-cloud-kubernetes-discoveryserver).

and this is not the case. 

Any hints here would make me a sane persona again :) thank you

**Comment by ryanjbaxter** [comment]
If you look at `spring-cloud-kubernetes-discovery` it is essentially a rest client that talks to `spring-cloud-kubernetes-discoveryserver` to implement a `DiscoveryClient`.  `spring-cloud-kubernetes-discoveryserver` uses `spring-cloud-kubrnetes-client-discovery` to fetch Kubernetes service information from the API server.  The goal of `spring-cloud-kubernetes-discovery` and `spring-cloud-kubernetes-discoveryserver` is to provide users with a `DiscoveryClient` implementation that doesn't rely on the API server directly (the just need to deploy the discovery server).

**Comment by wind57** [comment]
makes sense! I just could not connect the dots, thank you.
