### ISSUE TITLE
Current build fails

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1102]
Our current build fails, because of two issues:

- one because of micrometer + spring-boot (that I have already fixed and will explain in the PR)
- because we need the latest `spring-cloud-config`.

The second one is something I can't do anything about, unfortunately :( 

We need the latest `4.0.0-SNAPSHOT` of `spring-cloud-config` and I know this because I build it locally and run a test that fails in our current build and it passes. May be more verbose is this:

- delete `4.0.0-SNAPSHOT` of `spring-cloud-config` from my maven repo, refresh our project, run a failing test - it fails.
- delete `4.0.0-SNAPSHOT` of `spring-cloud-config` from my maven repo, build `spring-cloud-config` on my machine so that it ends up in my maven local repo, run the failing test - it passes.

I hope I make sense here.

@ryanjbaxter can you may be try to trigger a build of that project? Unless this is already known by you folks, of course.

**Comment by ryanjbaxter** [comment]
We have a number of issues with the main builds of Spring Cloud due to some Spring Boot issues.  

This is one I am working with Boot on
https://github.com/spring-projects/spring-boot/issues/32676#event-7572194478

I am waiting for the Boot build to finish to try the latest snapshot.
This one is blocking spring cloud config
https://github.com/spring-projects/spring-vault/pull/728

**Comment by wind57** [comment]
Excellent! I was losing my mind today. thank you soo much!

P.S. The micrometer dependency is really easy to fix in our case, but I assume spring-boot will go on a diff route

**Comment by wind57** [comment]
Ryan that vault issue seems to be closed, safe to trigger a spring-cloud-build build?

**Comment by ryanjbaxter** [comment]
Everything should build now.  We found another problem with Spring Cloud Config which appears to be a problem in Spring Framework.  We commented out the tests so we could get a snapshot build of Config.  It looks like K8S is green now as well.

https://github.com/spring-projects/spring-framework/issues/29333
