### ISSUE TITLE
upgrade to spring-boot-3.0.0-RC1

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1109]
Ryan, this is more of a question, really. We will be upgrading to 3.0.0-RC1 of Spring boot when it is out, correct? I saw the due date as October 20.

The reason I am asking is that there is a fix there for `@DefaultValue` that I would require... thank you and sorry for spamming a bit!

**Comment by ryanjbaxter** [comment]
Yes we will do that as soon as its released.  Although we are on SNAPSHOTS so the fix should be included there right now I would think.

**Comment by wind57** [comment]
you're right, thx fix is there, I just tested. thank you

**Comment by wind57** [comment]
and RC-1 is out, but I have 3 more PRs to move to records... can we merge those and then move to RC1. Just asking, not trying to be rude in any shape or form. I'll work even today to stay late in order for the to be part of `main`...

**Comment by ryanjbaxter** [comment]
Why do you need them to be merged first before you move to RC1?

**Comment by wind57** [comment]
these are breaking changes, didn't you say we will not accept any more breaking changes?

**Comment by ryanjbaxter** [comment]
I was saying that in regards to Spring Cloud releasing 2022.0.0-RC1 not Spring Boot.  Does that make sense?

**Comment by wind57** [comment]
oh!! I am an idiot, makes all the sense in the world.

**Comment by ryanjbaxter** [comment]
No worries at all.  Like I said the plan is to do our release next week so you have time.  Go home and rest ;)
