### ISSUE TITLE
ConfigMaps cannot hot load Spring Boot service

### ISSUE THREAD

**Issue by Charles1007** [spring-cloud/spring-cloud-kubernetes#1114]
**Describe the bug**
2022-10-18 11:18:40.023 WARN  [OkHttp https://[fd11:1111:1111:15::1]/...] [org.springframework.cloud.kubernetes.config.reload.ConfigurationChangeDetector:102] o.s.c.k.c.r.EventBasedConfigurationChangeDetector - The current number of ConfigMap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place

spring cloud version:Hoxton.SR8
spring boot version:2.3.4.RELEASE
spring-cloud-starter-kubernetes-config:1.1.9.RELEASE

**Comment by kunCharles** [comment]
@royclarkson Hello, has this problem been fixed？

**Comment by wind57** [comment]
unfortunately, with the limited provided information, this would be impossible "to fix" :( is there a way for you to provide an actual sample that reproduces the problem?

**Comment by kunCharles** [comment]
> unfortunately, with the limited provided information, this would be impossible "to fix" :( is there a way for you to provide an actual sample that reproduces the problem?

Sorry, for some reasons, the code cannot be disclosed. I would like to ask what the changed function parameters refer to in the following methods?

`	private void onEvent(ConfigMap configMap) {
		boolean changed = changed(
				locateMapPropertySources(this.configMapPropertySourceLocator,
						this.environment),
				findPropertySources(ConfigMapPropertySource.class));
		if (changed) {
			this.log.info("Detected change in config maps");
			reloadProperties();
		}
	}`

**Comment by wind57** [comment]
imho, you should not try to understand the code too much as it will take quite some time to explain.

The easier way for you to understand what is going on is to enable debug mode. For the `locateMapPropertySources` we have such debug logs:

```
this.log.debug("locateMapPropertySources");
this.log.debug(String.format("environment: %s", environment));
this.log.debug(String.format("sources: %s", result));
```

and for the `findPropertySources` :

```
this.log.debug("findPropertySources");
this.log.debug(String.format("environment: %s", this.environment));
this.log.debug(String.format("environment sources: %s", sources));
```

So this should give you a good starting point. Also the `changed` method has some good debug logging:


```
	public boolean changed(List<? extends MapPropertySource> left, List<? extends MapPropertySource> right) {
		if (left.size() != right.size()) {
			this.log.warn("The current number of ConfigMap PropertySources does not match "
					+ "the ones loaded from the Kubernetes - No reload will take place");

			if (log.isDebugEnabled()) {
				this.log.debug(String.format("source 1: %d", left.size()));
				left.forEach(item -> log.debug(item));

				this.log.debug(String.format("source 2: %d", right.size()));
				right.forEach(item -> log.debug(item));
			}
			return false;
		}

		for (int i = 0; i < left.size(); i++) {
			if (changed(left.get(i), right.get(i))) {
				return true;
			}
		}
		return false;
	}
```

**Comment by kunCharles** [comment]
> imho, you should not try to understand the code too much as it will take quite some time to explain.
> 
> The easier way for you to understand what is going on is to enable debug mode. For the `locateMapPropertySources` we have such debug logs:
> 
> ```
> this.log.debug("locateMapPropertySources");
> this.log.debug(String.format("environment: %s", environment));
> this.log.debug(String.format("sources: %s", result));
> ```
> 
> and for the `findPropertySources` :
> 
> ```
> this.log.debug("findPropertySources");
> this.log.debug(String.format("environment: %s", this.environment));
> this.log.debug(String.format("environment sources: %s", sources));
> ```
> 
> So this should give you a good starting point. Also the `changed` method has some good debug logging:
> 
> ```
> 	public boolean changed(List<? extends MapPropertySource> left, List<? extends MapPropertySource> right) {
> 		if (left.size() != right.size()) {
> 			this.log.warn("The current number of ConfigMap PropertySources does not match "
> 					+ "the ones loaded from the Kubernetes - No reload will take place");
> 
> 			if (log.isDebugEnabled()) {
> 				this.log.debug(String.format("source 1: %d", left.size()));
> 				left.forEach(item -> log.debug(item));
> 
> 				this.log.debug(String.format("source 2: %d", right.size()));
> 				right.forEach(item -> log.debug(item));
> 			}
> 			return false;
> 		}
> 
> 		for (int i = 0; i < left.size(); i++) {
> 			if (changed(left.get(i), right.get(i))) {
> 				return true;
> 			}
> 		}
> 		return false;
> 	}
> ```

thanks, because the code needs to run in k8s environment, I can't debug it locally, can you provide a package to type the above log into (lspring-cloud-starter-kubernetes-config.jar)

**Comment by Charles1007** [comment]
Can you provide a feasible demo that can hot load configmap？

**Comment by wind57** [comment]
> thanks, because the code needs to run in k8s environment, I can't debug it locally

I was implying that you should enable spring DEBUG logs and deploy the watcher, then analyze the logs. This [issue](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1099) for example, has the needed instructions. 

> Can you provide a feasible demo that can hot load configmap？

We have integration tests that you can take a look at. And I don't really get your point about "feasible". From your example, reload, in general, works. Once you enable debug logs, you will have a picture of what the cause of the problem is.

**Comment by Charles1007** [comment]
> > thanks, because the code needs to run in k8s environment, I can't debug it locally
> 
> I was implying that you should enable spring DEBUG logs and deploy the watcher, then analyze the logs. This [issue](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1099) for example, has the needed instructions.
> 
> > Can you provide a feasible demo that can hot load configmap？
> 
> We have integration tests that you can take a look at. And I don't really get your point about "feasible". From your example, reload, in general, works. Once you enable debug logs, you will have a picture of what the cause of the problem is.

Thank you. I know how to debug, but the local idea does not work in the remote K8S environment. I mean, can you type a jar to me for the above logs. In this way, I can check the pod logs in the remote K8S environment to troubleshoot the problem.

**Comment by wind57** [comment]
> Thank you. I know how to debug, but the local idea does not work in the remote K8S environment

Please read what I wrote and look at the issue I linked. You need to deploy a watcher image _with debug level enabled_, then look at the logs of that pod. You do not need to do any remote debugging in the cluster.

**Comment by Charles1007** [comment]
> 2022-10-18 11:18:40.023 WARN [OkHttp https://[fd11:1111:1111:15::1]/...] [org.springframework.cloud.kubernetes.config.reload.ConfigurationChangeDetector:102] o.s.c.k.c.r.EventBasedConfigurationChangeDetector - The current number of ConfigMap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place

ok，I need to look into what you're saying.

The above alarm is generated when I modify the configuration and run the kubectl apply -f xx.configmap command. (2022-10-18 11:18:40.023 WARN [OkHttp https://[fd11:1111:1111:15::1]/... [org.springframework.cloud.kubernetes.config.reload.ConfigurationChangeDetector:102] o.s.c.k.c.r.EventBasedConfigurationChangeDetector - The current number of ConfigMap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place)

When I run "curl-g-6-X POST http://[ipv6]:port/actuator/refresh", I observed that the configuration is reloaded.

**Comment by Charles1007** [comment]
> 2022-10-18 11:18:40.023 WARN [OkHttp https://[fd11:1111:1111:15::1]/...] [org.springframework.cloud.kubernetes.config.reload.ConfigurationChangeDetector:102] o.s.c.k.c.r.EventBasedConfigurationChangeDetector - The current number of ConfigMap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place

ok，I need to look into what you're saying.

The above alarm is generated when I modify the configuration and run the kubectl apply -f xx.configmap command. (2022-10-18 11:18:40.023 WARN [OkHttp https://[fd11:1111:1111:15::1]/... [org.springframework.cloud.kubernetes.config.reload.ConfigurationChangeDetector:102] o.s.c.k.c.r.EventBasedConfigurationChangeDetector - The current number of ConfigMap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place)

When I run "curl-g-6-X POST http://[ipv6]:port/actuator/refresh", I observed that the configuration is reloaded.

**Comment by Charles1007** [comment]
I have solved this problem by lowering the spring boot and spring cloud versions. I guess it is due to some dependency conflicts with Spring-cloud-starter-Kubernetes-config. Thank you very much.[https://github.com/spring-cloud/spring-cloud-kubernetes/issues/524](url)
