### ISSUE TITLE
Build Failure related to JsonFactory

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1115]
I assume this is already raised Ryan?

`org.springframework.http.codec.json.Jackson2Tokenizer` internally tries to use `com.fasterxml.jackson.core.JsonFactory::createNonBlockingByteBufferParser`, a method that does not exist. 

So build fails.  Most probably a recent spring-boot change...

**Comment by ryanjbaxter** [comment]
We were caught in some kind of no mans land.  There was a change made in spring framework and boot hadn't caught up.

https://github.com/spring-projects/spring-framework/commit/f99c02fc941c92ca01d45fe2ebb2dd5318f471b2#diff-c57ebb0237ed9b5365dd70c1bea3008a84fbc106a16bcd7b6e3a926e4a9a67cfR249

We are past that but there is another problem in spring framework with micrometer.  I am trying to narrow that down now.
