### ISSUE TITLE
Kubernetes Discovery Question

### ISSUE THREAD

**Issue by czy006** [spring-cloud/spring-cloud-kubernetes#1116]
Can SpringCloud K8S discovery not depend on **spring-cloud-discover-server**,j ust use k8s API to discovery it?

now if I not set **discovery-server-url** 

![image](https://user-images.githubusercontent.com/28348735/197093817-edcdb5bc-7029-4f14-94ca-5f7a46c013f9.png)

will be throw exp :

![image](https://user-images.githubusercontent.com/28348735/197093265-fbf59af0-c57f-4a74-a13a-442b21f247c6.png)

but I found example is not need to set it can discovery it

**Comment by ryanjbaxter** [comment]
Yes you need to us spring-cloud-starter-kubernetes-[client or fabric8]

**Comment by czy006** [comment]
Thanks
