### ISSUE TITLE
Add source code location for Spring Cloud Kubernetes Config Watcher and Spring Cloud Config Server for Kubernetes

### ISSUE THREAD

**Issue by Alos** [spring-cloud/spring-cloud-kubernetes#1125]
Add source code location for Spring Cloud Kubernetes Config Watcher and Spring Cloud Config Server for Kubernetes in the documentation.

**Comment by ryanjbaxter** [comment]
You mean here?
https://github.com/spring-cloud/spring-cloud-kubernetes/tree/main/spring-cloud-kubernetes-controllers

Can you elaborate on why this would be useful?

**Comment by Alos** [comment]
Users might not want to blindly install random images into their clusters and might prefer to build from source.
