### ISSUE TITLE
Remove redundant initialization attributes of variables

### ISSUE THREAD

**Issue by weihubeats** [spring-cloud/spring-cloud-kubernetes#1130]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/42484192/200797775-a2bb4538-1ca1-44b3-9beb-d66638f7ffd8.png">
List<V1Service> services no need to initialize to null
**Describe alternatives you've considered**
Remove redundant initialization attributes of variables
**Additional context**

**Comment by wind57** [comment]
@ryanjbaxter  this also can be closed
