### ISSUE TITLE
Running spring cloud kubernetes locally

### ISSUE THREAD

**Issue by weihubeats** [spring-cloud/spring-cloud-kubernetes#1134]
If I want to run spring cloud kubernetes service discovery locally, is there any good way to do it? I have minikube installed on my local mac, but it still reports an error on startup
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/42484192/200997312-4106fead-4e73-4d99-997c-4a48eb729311.png">
Is there any good help document, thank you very much

**Comment by ryanjbaxter** [comment]
This is not a critical error it's informative...logged as 'INFO'.

**Comment by weihubeats** [comment]
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/42484192/201067265-04cfe1e5-b73d-4a47-9e3d-ecf886fd236a.png">

This looks like the connection is not minikube

**Comment by ryanjbaxter** [comment]
That is a some kind of other issue.  What version of spring cloud are you using?  
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.
