### ISSUE TITLE
Whether to consider support for specifying multiple namespace service discovery

### ISSUE THREAD

**Issue by weihubeats** [spring-cloud/spring-cloud-kubernetes#1148]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
Whether to consider support for specifying multiple namespace service discovery, now it seems to support only single namespace service discovery or all namespace service discovery

**Comment by wind57** [comment]
see [this](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/1113). There is already a proposed PR for this, we have not yet reviewed it yet

**Comment by weihubeats** [comment]
ok
