### ISSUE TITLE
Add Labels And Annotations From Pods To ServiceInstance Metadata

### ISSUE THREAD

**Issue by weihubeats** [spring-cloud/spring-cloud-kubernetes#1162]
Is there a good way to get the pod's label if I want to. I might want to go through different pod tags to do rule routing

I see that the label in the metadata of the ServiceInstance I get seems to be the label of the kubernetes service

**Comment by weihubeats** [comment]
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/42484192/205862891-8ef44d8b-0d64-45df-a418-ca4ce2c75d98.png">
I want to get the tags of each pod, but I found that method
```java
// KubernetesInformerDiscoveryClient
public List<ServiceInstance> getInstances(String serviceId)
```
 does not have these tags, the tags of his original data are the tags of the service in kubernetes and not the tags of the pods

**Comment by wind57** [comment]
it starts to make sense, but what is the point in you having the labels of the pods? this is what I don't get

**Comment by weihubeats** [comment]
Because I might want to do a grayscale release, selecting the pods with grayscale labels from multiple pods in a service by labels them

**Comment by wind57** [comment]
Seems like you want to get also the pods and their metadata from an underlying `ServiceInstance`. This is doable, I guess, but I need also @ryanjbaxter thoughts here.

**Comment by ryanjbaxter** [comment]
I can possibly see the use case.  If we do this though, I wonder what the impact would be to the existing labels and annotations (could they conflict?).  Also we would have to correlates the endpoints to the pods, which i am not particularly clear how to do, not to say its impossible.

**Comment by weihubeats** [comment]
We now want to use spring cloud kubernetes to implement grayscale or swimlane features, is there any good advice from the community?

**Comment by weihubeats** [comment]
I can submit a pr if needed, I think it is available through V1PodList

**Comment by ryanjbaxter** [comment]
A PR would be welcome

**Comment by wind57** [comment]
`DefaultKubernetesServiceInstance` has a field `Map<String, Map<String, String>> podMetadata`.

All 3 clients return such metadata, if it is requested. This can be closed @ryanjbaxter
