### ISSUE TITLE
Use minikube with --vm-driver=none to run our integration tests on Travis 

### ISSUE THREAD

**Issue by cmoulliard** [spring-cloud/spring-cloud-kubernetes#117]
Minikube offers the possibility to run in an existing provisioned VM as this is the case when we use Travis, ... 

https://github.com/kubernetes/minikube#linux-ci-installation-which-supports-running-in-a-vm-example-w-kubectl-installation

Example of such travis file : https://github.com/jaegertracing/jaeger-kubernetes/blob/master/.travis.yml

**Comment by spencergibb** [comment]
No longer using travis.
