### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1172]
As part of [this PR](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/1002/files), you added some important documentation : 

```
To enable this functionality you need to set `spring.config.import=kubernetes:` in your application's configuration properties.
Currently you can not specify a ConfigMap or Secret to load using `spring.config.import`, by default Spring Cloud Kubernetes
will load a ConfigMap and/or Secret based on the `spring.application.name` property.  If `spring.application.name` is not set it will
load a ConfigMap and/or Secret with the name `application`.

If you would like to load Kubernetes `PropertySource`s during the bootstrap phase like it worked prior to the 3.0.x release
you can either add `spring-cloud-starter-bootstrap` to your application's classpath or set `spring.cloud.bootstrap.enabled=true`
as an environment variable.
```

While triaging a different issue, I wanted to refer to it on the website, but it's not there, see [here](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#kubernetes-propertysource-implementations).

I would expect for it to be present. @ryanjbaxter do you happen to know what is going on? thank you.

**Comment by ryanjbaxter** [comment]
`/current` points to the 2.1.x docs because that is the current GA release.  The 3.0.0 docs are here
https://docs.spring.io/spring-cloud-kubernetes/docs/3.0.0-RC3/reference/html/#kubernetes-propertysource-implementations
