### ISSUE TITLE
spring-cloud-kubernetes-fabric8-leader doesn't receive OnGrantedEvent and OnRevokedEvent events after upgrading to Kubernetes to 1.23

### ISSUE THREAD

**Issue by johanhaleby** [spring-cloud/spring-cloud-kubernetes#1180]
After upgrading our GKE cluster from 1.22 to v1-23-13-gke-900 we no longer get any `OnGrantedEvent` or `OnRevokedEvent`'s when using `spring-cloud-kubernetes-fabric8-leader` version 2.1.5 or 3.0.0-RC3.

Our code looks like this:

```kotlin
@Service
class LeaderElectionService {
    private val log = loggerFor<LeaderElectionService>()
    
    val isLeader = AtomicBoolean(forceLeader)

    @EventListener
    fun onLeaderGranted(event: OnGrantedEvent){
        log.info("This node is now leader")
        isLeader.set(true)
    }

    @EventListener
    fun onLeaderRevoked(event: OnRevokedEvent) {
        log.info("This node is no longer the leader")
        isLeader.set(false)
    }
}
```

This used to work fine until we upgraded the cluster. We've tried setting the log level for `org.springframework.cloud.kubernetes.fabric8.leader` to `DEBUG`, but we don't see any logs whatsoever, so it's hard to know what's going on.

Any suggestions on how we can find more details?

**Comment by ryanjbaxter** [comment]
Is it only the kubernetes version that changed or did you also change Spring Cloud versions?  Have you tried on a vanilla kubernetes cluster (not on GKE)?

**Comment by johanhaleby** [comment]
@ryanjbaxter We've also upgraded to Spring Boot 3.0.0 and spring cloud 2021.0.5. But from what I can tell from looking at our internal logs, it seems to have worked until we upgraded the cluster. I've not tried running it outside GKE.

**Comment by ryanjbaxter** [comment]
Spring Cloud 2021.0.5 is not compatible with Spring Boot 3.0.0.  The compatible release (2022.0.0) should be released today/Monday.  You can try our last RC 2022.0.0-RC3 if you would like.

**Comment by johanhaleby** [comment]
@ryanjbaxter Oh I didn't know that. I'll give it a try.

**Comment by johanhaleby** [comment]
@ryanjbaxter It worked after upgrading to 2022.0.0. Thank you for your suggestion!
