### ISSUE TITLE
Enabling / disabling ConfigMap / Secrets property sources doesn't seem to work

### ISSUE THREAD

**Issue by metacosm** [spring-cloud/spring-cloud-kubernetes#119]
`spring.cloud.kubernetes.config.enabled` and `spring.cloud.kubernetes.secrets.enabled` are properly set but `AbstractConfigProperties.isEnabled` method doesn't appear to be used anywhere…

**Comment by spencergibb** [comment]
Did you put them in `bootstrap.properties`? See https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/BootstrapConfiguration.java

**Comment by metacosm** [comment]
@spencergibb I was basing my comment on the fact that `AbstractConfigProperties.isEnabled` method doesn't appear to be checked anywhere in the code but indeed, I had seen the conditional stuff in BootstrapConfiguration but somehow forgot about it… :)

**Comment by metacosm** [comment]
This, however, leads to other issues but I will open another issue.

**Comment by metacosm** [comment]
@spencergibb by the way, how do you debug the bootstrapping code? I.e. how do you attach a debugger to the pod being deployed so that you can step debug the property sources do their work?

**Comment by salaboy** [comment]
@metacosm that is more like a Kubernetes question.. I used telepresence.io to lunch the spring boot app locally and in that way have more control on the debugging process. 
Did you opened another issue?

**Comment by salaboy** [comment]
@metacosm can we close this issue?

**Comment by metacosm** [comment]
Can be closed. Thanks!
