### ISSUE TITLE
If different namespaces have the same service name, will they be treated as one service? Then merge these services and go load balancing

### ISSUE THREAD

**Issue by weihubeats** [spring-cloud/spring-cloud-kubernetes#1192]
**Describe the bug**
If different namespaces have the same service name, will they be treated as one service? Then merge these services and go load balancing

**Sample**
no

**Comment by wind57** [comment]
just a question, is this issue a duplicate of this one? https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1182 can you take a look please?

**Comment by weihubeats** [comment]
Okay, thank you very much.
