### ISSUE TITLE
wrong artifact name in doc

### ISSUE THREAD

**Issue by towi** [spring-cloud/spring-cloud-kubernetes#1205]
The documentation mentions the wrong artifact name in 

> If you have spring-cloud-bootstrap-starter on your classpath or are setting spring.cloud.bootstrap.enabled=true then you will have to set spring.main.cloud-platform should be set in bootstrap.{properties|yml} (or the profile specific one). Also note that these properties: spring.cloud.kubernetes.config.enabled and spring.cloud.kubernetes.secrets.enabled will only take effect when set in bootstrap.{properties|yml} when you have spring-cloud-bootstrap-starter on your classpath or are setting spring.cloud.bootstrap.enabled=true.

Instead of `spring-cloud-bootstrap-starter` it should be `spring-cloud-starter-bootstrap`.

**Comment by wind57** [comment]
indeed. thank you for raising this. PR is already out and should be integrated fairly soon.
