### ISSUE TITLE
3.0 changes on sourcing config in Kubernetes very unclear and confusing

### ISSUE THREAD

**Issue by stevendick-swissre** [spring-cloud/spring-cloud-kubernetes#1239]
I'm upgrading Spring Cloud Kubernetes Config from 2.1.x to 3.0.1 and I simply don't understand the documentation on the changes to sourcing properties inside Kubernetes.

We have an init container that generates a properties file at `/etc/ietv/config/application.properties`

With 2.1.x, this was configured in `boostrap-kubernetes.properties` using: `spring.cloud.kubernetes.config.paths=/etc/ietv/config/application.properties`

I've moved the `spring.cloud.kubernetes.config.paths=/etc/ietv/config/application.properties` setting to `application-kubernetes.properties` but this has no effect when run inside Kubernetes as the pod fails with missing properties that I know are defined in that properties file.

I know I can add a dependency on `spring-cloud-starter-bootstrap` to enable the old behaviour of sourcing the bootstrap properties files, but I want to understand the new default way of sourcing configuration.

**Comment by wind57** [comment]
eh, no, I don't think that moving that to `application-kubernetes.properties` will have any effect.

The "new way" that we have introduced in `3.x` is to use "config-data-loader", though it's support at the moment is a bit limited. The documentation is [here](https://docs.spring.io/spring-cloud-kubernetes/docs/3.0.0-RC3/reference/html/#kubernetes-propertysource-implementations). Notice this:

> Currently you can not specify a ConfigMap or Secret to load using spring.config.import, by default Spring Cloud Kubernetes will load a ConfigMap and/or Secret based on the spring.application.name property.

**Comment by stevendick-swissre** [comment]
Sounds like we stick with using `spring-cloud-starter-bootstrap` for now and check out how this evolves over time.
