### ISSUE TITLE
Provide a sanitizing function for secrets property sources to mask secret values in actuator output

### ISSUE THREAD

**Issue by breun** [spring-cloud/spring-cloud-kubernetes#1242]
After merging #1234, it would be nice if Spring Cloud Kubernetes would auto-configure a `SanitizingFunction` bean which sanitizes values that come from Spring Cloud Kubernetes' `SecretsPropertySource` instances. This sanitizing function will then get applied by Spring Boot to mask the secret values in actuator output when `management.endpoint.configprops.show-values` is set to `WHEN_AUTHORIZED` or `ALWAYS`. Regular configuration properties would then be visible in actuator output, but secrets will always be masked, regardless of the visibility of regular properties.

If you believe there might be valid use cases for showing secrets in actuator output, the creation of this sanitizing function could be done conditionally on some property, so users could opt-in to not masking secrets if they really want/need to, but for security reasons I think masking secret values by default would be very desirable.

See [Actuator Endpoints Sanitization](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#actuator-endpoints-sanitization) in the Spring Boot 3.0 migration guide for more information.

**Comment by ryanjbaxter** [comment]
Now I am even more confused 🤣

When I tested this they were already sanitized, so why would we need our own?

**Comment by breun** [comment]
Spring Boot 3.0 doesn't show any configuration property by default (`management.endpoint.configprops.show-values=NEVER`), but it doesn't distinguish between 'regular' configuration properties and secrets. When we set the actuator visibility to `WHEN_AUTHORIZED` or `ALWAYS`, we also see secrets in actuator output. Sadly there is no concept of 'secret configuration properties', so there is no `ALWAYS_EXCEPT_SECRETS` setting for instance.

I am proposing to let Spring Cloud Kubernetes provide a sanitizing function for secrets, so that when the actuator visibility is set to `WHEN_AUTHORIZED` or `ALWAYS`, secrets are still not shown (or at least by default).

**Comment by ryanjbaxter** [comment]
Understood, let's make this as waiting for votes and see if anyone else also wants this

**Comment by ryanjbaxter** [comment]
You can provide a fix, it just not critical
