### ISSUE TITLE
Spring cloud gateway with Kubernetes service discovery and Kubernetes loadbalancer jar dependencies

### ISSUE THREAD

**Issue by kkg82** [spring-cloud/spring-cloud-kubernetes#1245]
I am trying to Create a spring cloud gateway in Kubernetes environment to do Kubernetes service discovery 

I have added spring cloud starter gateway and spring-cloud-Kubernetes-all jars to my Pom.xml file

then while staring my application getting an errors as below

Caused by: Java.lang.classnotfoundexception. Org.springframework.cloud.Kubernetes.discovery.kubernetesdiscoveryproperties

any suggestions to resolve this issue

**Additional context**

**Comment by wind57** [comment]
We need a reproducible sample here, otherwise its pretty complicated to understand what is going on.

**Comment by kkg82** [comment]
@wind57  here is the gradle dependencies and application.yml

![5CCD33B9-6071-4329-BE90-F4DA120C4351](https://user-images.githubusercontent.com/126547097/222195595-c3d9f896-93c5-4618-b886-1aff51a69d4f.jpeg)
![28D85D74-6832-420B-B209-446A22B5A119](https://user-images.githubusercontent.com/126547097/222195622-7593eece-b5fe-40d7-9efa-7a6fcb2edd06.jpeg)

**Comment by kkg82** [comment]
@wind57 

error details

![C3F238A4-27F2-425E-A073-512666656C41](https://user-images.githubusercontent.com/126547097/222196430-bbc1cfa7-e034-49e0-abc6-c309a9725b8e.jpeg)

**Comment by wind57** [comment]
I need a reproducible example, like a github repo, that I can deploy/build/etc and see the exception that you are reporting. 

Also, can you upgrade to `2022.0.1` and see if it reproduces?

**Comment by kkg82** [comment]
@wind57 i upgraded to spring cloud version to 22.0.1 and still see the same issue.

is there any limitation we should use spring-cloud-starter-Kubernetes-fabric8-all ???

**Comment by wind57** [comment]
Again, without an example, it is impossible to answer. I have no idea what is going on. We also have quite a lot of integration tests that are not failing. If we want me to help you, please help me first and provide a minimal, reproducible example. Thank you.

**Comment by wind57** [comment]
btw, I noticed from your screenshot that you managing the `spring-cloud-starter-kubernetes-all` explicitly... Not only that, but you are using a very old version, one that we do not even have anymore in the repo. 

The correct dependency is either `spring-cloud-starter-kubernetes-client-all` or `spring-cloud-starter-kubernetes-fabric8-all` and that should be managed by the bom anyway. Please consult the docs a bit more.

**Comment by wind57** [comment]
did you solve your problem in the end? Or you still need some help here?

**Comment by wind57** [comment]
@ryanjbaxter imho, this can be closed also.

**Comment by ryanjbaxter** [comment]
I marked it as waiting for feedback, if the author does not respond in 2 weeks our bot will close it, thanks

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
