### ISSUE TITLE
kubernetes-leader-election-example: "No Node Port" error

### ISSUE THREAD

**Issue by shoner-sul** [spring-cloud/spring-cloud-kubernetes#1257]
**Describe the bug**
Following https://github.com/spring-cloud/spring-cloud-kubernetes/tree/main/spring-cloud-kubernetes-examples/kubernetes-leader-election-example , getting service URL failed with "No Node Port" error as below:

[spring-cloud-kubernetes-examples]$ kubectl apply -f deploy.yml 
service/kubernetes-leader-election-example created
serviceaccount/kubernetes-leader-election-example created
rolebinding.rbac.authorization.k8s.io/kubernetes-leader-election-example:view created
role.rbac.authorization.k8s.io/namespace-reader created
deployment.apps/kubernetes-leader-election-example created

[spring-cloud-kubernetes-examples]$ minikube service kubernetes-leader-election-example --url
  service default/kubernetes-leader-election-example has no node port

[spring-cloud-kubernetes-examples]$ minikube service list
|-------------|------------------------------------|--------------|-----|
|  NAMESPACE  |                NAME                | TARGET PORT  | URL |
|-------------|------------------------------------|--------------|-----|
| default     | kubernetes                         | No node port |
| default     | kubernetes-leader-election-example | No node port |
| kube-system | kube-dns                           | No node port |
|-------------|------------------------------------|--------------|-----|

**Sample**
Used https://github.com/spring-cloud/spring-cloud-kubernetes/tree/main/spring-cloud-kubernetes-examples/kubernetes-leader-election-example in main branch as is. "deploy.yml" file in the description above is a file created as instructed under "You can then deploy the application using the following yaml."

**Comment by shoner-sul** [comment]
github authentication problem. closing.

**Comment by ryanjbaxter** [comment]
Might want to read through this
https://minikube.sigs.k8s.io/docs/handbook/accessing/

**Comment by shoner-sul** [comment]
Before asking here, I've read the same document and tried step 1~4 of "Example of NodePort" part. It resulted same error "Connection refused". (I guessed that it was because of missing role settings in deployment process, which was present in YML file.)

It says in step 4 that there is a ssh tunnel, but ps command does not show any ssh process.

[shoner@shoner spring-cloud-kubernetes-examples]$ ps -ef | grep docker@127.0.0.1
shoner   1010161 1008796  0 06:10 pts/2    00:00:00 grep --color=auto docker@127.0.0.1
[shoner@shoner spring-cloud-kubernetes-examples]$ ps -ef | grep docker
root       25065       1  0 Mar16 ?        00:00:28 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
root      777207   25065  0 01:07 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 32788 -container-ip 192.168.49.2 -container-port 32443
root      777221   25065  0 01:07 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 32789 -container-ip 192.168.49.2 -container-port 8443
root      777234   25065  0 01:07 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 32790 -container-ip 192.168.49.2 -container-port 5000
root      777247   25065  0 01:07 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 32791 -container-ip 192.168.49.2 -container-port 2376
root      777261   25065  0 01:07 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 32792 -container-ip 192.168.49.2 -container-port 22
root      779140  777298  1 01:07 ?        00:05:48 /usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --default-ulimit=nofile=1048576:1048576 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=docker --insecure-registry 10.96.0.0/12
root      779354  777298  1 01:07 ?        00:05:51 /usr/bin/cri-dockerd --container-runtime-endpoint fd:// --network-plugin=cni --hairpin-mode=hairpin-veth
root      780713  777298  2 01:08 ?        00:08:03 /var/lib/minikube/binaries/v1.26.1/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpoint=/var/run/cri-dockerd.sock --hostname-override=minikube --image-service-endpoint=/var/run/cri-dockerd.sock --kubeconfig=/etc/kubernetes/kubelet.conf --node-ip=192.168.49.2
shoner   1010335 1008796  0 06:10 pts/2    00:00:00 grep --color=auto docker

**Comment by ryanjbaxter** [comment]
Can you try this and then try hitting localhost:8080?
` kubectl port-forward service/kubernetes-leader-election-example --address 0.0.0.0 8080:80`

**Comment by shoner-sul** [comment]
It says that the pod is not running correctly.

[shoner@shoner spring-cloud-kubernetes-examples]$ kubectl port-forward service/kubernetes-leader-election-example --address 0.0.0.0 8080:80
error: unable to forward port because pod is not running. Current status=Pending

It looks like a problem from minikube, not from the example itself.
I'm going to try https://www.datadoghq.com/blog/debug-kubernetes-pending-pods/
Thank you for your help.

Some warnings in minikube logs
--------
W0321 13:18:38.436927 1440230 cli_runner.go:211] docker network inspect minikube --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}}, "ContainerIPs": [{{range $k,$v := .Containers }}"{{$v.IPv4Address}}",{{end}}]}" returned with exit code 1
I0321 13:18:38.436991 1440230 network_create.go:281] running [docker network inspect minikube] to gather additional debugging logs...
I0321 13:18:38.437004 1440230 cli_runner.go:164] Run: docker network inspect minikube
W0321 13:18:38.475685 1440230 cli_runner.go:211] docker network inspect minikube returned with exit code 1
I0321 13:18:38.475696 1440230 network_create.go:284] error running [docker network inspect minikube]: docker network inspect minikube: exit status 1
stdout:
[]

stderr:
Error response from daemon: network minikube not found
I0321 13:18:38.475702 1440230 network_create.go:286] output of [docker network inspect minikube]: -- stdout --
[]
--------
W0321 13:18:48.983487 1440230 cgroups_linux.go:77] Your kernel does not support swap limit capabilities or the cgroup is not mounted.
