### ISSUE TITLE
Kubernetes Config Server evaluates application config map in wrong order

### ISSUE THREAD

**Issue by disimo74** [spring-cloud/spring-cloud-kubernetes#1287]
**Describe the bug**
I have an application myapp configured with a profile "prod" and the following configmaps with one a yaml properties defined:

- application
- application-prod
- myapp
- myapp-prod

If define a property in application I want that it can be overridden in this order by:
 application-prod, myapp, myapp-prod
 so I expect that the configmaps contents are returned in this order:

- myapp-prod
- myapp
- application-prod
- application

But when the application gets the configmaps the config server returns them in this order:

- application
- myapp-prod
- myapp
- application-prod

so the property defined in application cannot be overridden.

**Proposed solution**
I can fix this behavior moving the line 
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/ebffaf464e8dd87e4c512dca0c5a6dd249be2e2b/spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configserver/src/main/java/org/springframework/cloud/kubernetes/configserver/KubernetesEnvironmentRepository.java#L67
after the "if" block.

		try {
			StandardEnvironment springEnv = new StandardEnvironment();
			springEnv.setActiveProfiles(profiles);
			if (!"application".equalsIgnoreCase(application)) {
				addApplicationConfiguration(environment, springEnv, application);
			}
			addApplicationConfiguration(environment, springEnv, "application");
			return environment;
		}`
`

**Comment by ryanjbaxter** [comment]
That makes sense, would you like to submit a PR?  If so it should be submitted against the 2.1.x branch and we will merge it forward to main.

**Comment by disimo74** [comment]
Sure, here the PR
https://github.com/spring-cloud/spring-cloud-kubernetes/pull/1291
