### ISSUE TITLE
k8s discovery client inconsistent between reactive and blocking health indicators

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1298]
If you look in blocking vs reactive implementations of health of k8s native client, we currently do things differently. What I mean by that is, in `KubernetesInformerReactiveDiscoveryClientAutoConfiguration`:

```
ReactiveDiscoveryClientHealthIndicator healthIndicator = new ReactiveDiscoveryClientHealthIndicator(client,
				properties);
		InstanceRegisteredEvent<?> event = new InstanceRegisteredEvent<>(podUtils.currentPod(), null);
		healthIndicator.onApplicationEvent(event);
```

But in `KubernetesInformerDiscoveryClientAutoConfiguration` we use `KubernetesDiscoveryClientHealthIndicatorInitializer`, that has a post-construct in the form:

```
	@PostConstruct
	private void postConstruct() {
		LOG.debug(() -> "publishing InstanceRegisteredEvent");
		this.applicationEventPublisher.publishEvent(new InstanceRegisteredEvent<>(
				new RegisteredEventSource("kubernetes", podUtils.isInsideKubernetes(), podUtils.currentPod().get()),
				null));
	}
```

How come one publishes an event and one does not? And how come the blocking health does not have a bean of `DiscoveryClientHealthIndicator` to be on par with the reactive one? 

I am inclined to make them behave exactly the same, as I see this as a tiny bug. 

@ryanjbaxter I have several issues opened around health indicators that I would like to fix, but this is the first one I would like to get your input on. Thank you.

**Comment by ryanjbaxter** [comment]
I know I wrote this code but I cannot for the life of me figure out why I published an event in one case and just called the method in the other.  Maybe it has to do with the underlying implementation in the reactive and blocking cases...not sure.  To me it seems better to publish the event in both cases.

**Comment by wind57** [comment]
That's OK, that's why I'm here (I guess), to figure out these things and ask for your wisdom. 

I see things slightly differently. imo, we need to both to publish the event (so that a potential custom users `ApplicationListener` can listen to that) and provide a bean of type `ReactiveDiscoveryClientHealthIndicator/DiscoveryClientHealthIndicator`, so that user's `/health` endpoint would be correct. 

There are some other things that imho need to be done here, but I'll present a PR and we can debate them via the code if you do not mind.

**Comment by wind57** [comment]
I think I know why you did it like this! (I would have done it the same, so that is my best guess). The problem is that `DiscoveryClientHealthIndicator` is:

```
    public DiscoveryClientHealthIndicator(ObjectProvider<DiscoveryClient> discoveryClient, DiscoveryClientHealthIndicatorProperties properties) {
        this.discoveryClient = discoveryClient;
        this.properties = properties;
    }
```
it takes as input an `ObjectProvider<DiscoveryClient> discoveryClient`, unlike `ReactiveDiscoveryClientHealthIndicator` that takes a `ReactiveDiscoveryClient discoveryClient` as input.

One is simple to create, the other is not :) 

It would still be cool to align them properly.

**Comment by wind57** [comment]
I know why it was done like this, it took forever to understand. I will have a PR soon-ish, that fixes a bunch of these issues and I'll comment in the code.

**Comment by wind57** [comment]
this is a bug that will closed by an existing PR, too. Minor note for myself, not to forget to close this one too.

**Comment by wind57** [comment]
this one can be closed, because it was fixed in a previous merged PR
