### ISSUE TITLE
[Feature Request] Support for k8s Config Map with AOT

### ISSUE THREAD

**Issue by olivierboudet** [spring-cloud/spring-cloud-kubernetes#1299]
I saw in documentation that AOT support is out of scope for now. Is there an estimated time for this support ? I personnally just need the support for configmap configuration with Spring Cloud Config Client.

**Comment by ryanjbaxter** [comment]
We will be looking at it soon, but no solid timeframe as of yet.

**Comment by olivierboudet** [comment]
Hello @ryanjbaxter is there any news on this subject ? It is the only missing part to allow us to build our application in native mode.
Thanks

**Comment by ryanjbaxter** [comment]
Hoping to get to it in the second half of the year.
