### ISSUE TITLE
Does this work with Zuul? For automatic routes discovery? 

### ISSUE THREAD

**Issue by salaboy** [spring-cloud/spring-cloud-kubernetes#130]
If not, I can provide a PR if I get some pointers on how to add support for that.

**Comment by christophetd** [comment]
I got it working along with Zuul. 

Essentially you need to include the Kubernetes discovery client, annotate your main class with `@EnableDiscoveryClient` (and `@EnableZuulProxy` obviously), and add a Zuul route such as:

```
zuul.routes.myservice.path=/myservice/**
zuul.routes.myservice.serviceId=my-service
```

**Comment by Salaboy** [comment]
Well along Zuul is not the same as with Zuul :) I was expecting automatic routes discovery, that might require Zuul changes so it also knows how to go to the kubernetes registry to pick up the available services.

**Comment by christophetd** [comment]
I updated my previous post to include more details. However, I noticed that the list of services Zuul knows about doesn't update itself automatically if you add or remove a service from Kubernetes. The only solution I found to force it to update is to send a POST request to `/routes`, but there might be a better way.

**Comment by Salaboy** [comment]
yes.. it might be related with @RefreshScope (??)

**Comment by mehdikhelif** [comment]
The solution would be to have the KubernetesDiscoveryClient sending an HeartbeatEvent that would be intercepted in ZuulProxyConfiguration.ZuulDiscoveryRefreshListener

**Comment by mehdikhelif** [comment]
This looks related to issue #46

**Comment by doernbrackandre** [comment]
We ran into this issue as well. Is there any progress?

**Comment by Salaboy** [comment]
@doernbrackandre yeah, i switch to the new spring cloud gateway and it currently working with sc-k8s service discovery

**Comment by Salaboy** [comment]
@doernbrackandre probably not much, but I just want to share progress on the new gateway integration, which people might be interested if they are having issues with Zuul

**Comment by doernbrackandre** [comment]
ah, ok thanks. :) 

Currently, we are looking into this issue as well but probably we will stick to that workaround using a regular scheduler to emit a RoutesRefreshEvent like it was mentioned here

**Comment by spencergibb** [comment]
Closing in favor of #46
