### ISSUE TITLE
Automatically created an extra KubernetesClientConfigMapPropertySource {name='configmap.application.diep-customer'}

### ISSUE THREAD

**Issue by tianmingxing** [spring-cloud/spring-cloud-kubernetes#1307]
**Describe the bug**

I'm not sure why an invalid configuration occurred, after I made some adjustments to ConfigMap.

```
"Config Map normalized sources : [{ config-map name : 'null', namespace : 'null', prefix : '' }]"
```

<img width="996" alt="image" src="https://user-images.githubusercontent.com/5615719/232421023-4f8a9c8a-e20f-4ad0-b0dc-33afe4db7421.png">

**Comment by wind57** [comment]
it's impossible for me to understand what is going on here, to be honest. 

what where you trying to do, what client where you using, etc. A good description of the problem you are facing would mean more details for us to help you. Please provide them.

**Comment by wind57** [comment]
first things first, is it an option for you to try one of the versions `3.x.x` of `spring-cloud-starter-kubernetes-client-config`? Please not it requires java-17.

**Comment by tianmingxing** [comment]
This project has been in existence for a long time and relies on JDK11. I will not be allowed to upgrade directly.

**Comment by tianmingxing** [comment]
After changing the name of the main configuration file from application. yml to bootstrap. yml, the problem seems to have been resolved and needs to be observed again.
