### ISSUE TITLE
Can I disable KubernetesClientHealthIndicator detection?

### ISSUE THREAD

**Issue by tianmingxing** [spring-cloud/spring-cloud-kubernetes#1309]
**Is your feature request related to a problem? Please describe.**
Can I disable KubernetesClientHealthIndicator detection?

**Describe the solution you'd like**
By configuring parameters, it is possible to disable health checks. I mean that only this one test is active, while other health check items are still working.

**Describe alternatives you've considered**
none.

**Additional context**
org.springframework.cloud.kubernetes.client.KubernetesClientHealthIndicator

**Comment by wind57** [comment]
I assume you are still talking about version 2.1.x, correct? like in your previous issue...

**Comment by wind57** [comment]
that bean is annotated with `@ConditionalOnEnabledHealthIndicator("kubernetes")` in `KubernetesClientActuatorConfiguration`. As such, you can set:

```
management.health.kubernetes.enabled=false
```

to disable it.

**Comment by tianmingxing** [comment]
Thank you for remembering me!
I am going to try the above solution.

**Comment by wind57** [comment]
cool! if it works, just close this ticket.. thank you!
