### ISSUE TITLE
Improve documentation of loading properties from a Kubernetes ConfigMap

### ISSUE THREAD

**Issue by ogalimov** [spring-cloud/spring-cloud-kubernetes#1315]
Today we have configured our application to use properties from a Kubernetes ConfigMap using spring-cloud-kubernetes and we have found the correspoding documentation in [property-source-config.adoc](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/docs/src/main/asciidoc/property-source-config.adoc) to be a bit confusing.

I think there are two scenarios:

The first is, that you have a normal application.properties file in your project but want to load additional properties from a ConfigMap. In this case you would add spring.config.import=kubernetes:_name-of-ConfigMap_ to your application.properties. This functionality is provided by the class KubernetesClientConfigDataLocationResolver.

The second is, that you want to load some or all of the configuration from kubernetes during bootstrap. In this case you would have to activate bootstrap by one of the two well-described means. This functionality is configured in the class KubernetesClientBootstrapConfiguration.

Maybe I overlook something, but I think there is no way to make the configuration using spring.cloud.kubernetes.config.name (or the default spring.application.name) work without either activating spring.cloud.bootstrap.enabled or configuring the KubernetesClientConfigMapPropertySource manualy.

In the documentation however, I had the feeling that those two options are mixed together and an example for the first option is missing.

Especially the following sentence was not clear to us:
"To enable this functionality you need to set spring.config.import=kubernetes: in your application’s configuration properties. Currently you can not specify a ConfigMap or Secret to load using spring.config.import, by default Spring Cloud Kubernetes will load a ConfigMap and/or Secret based on the spring.application.name property. If spring.application.name is not set it will load a ConfigMap and/or Secret with the name application."

It implies, that the ConfigMap with the name of the application is loaded by default, while nothing is loaded by default, if bootstrap is not active.

**Comment by ryanjbaxter** [comment]
'spring.config.import=kubernetes:name-of-ConfigMap' is not valid.  Specifying the name of the configmap is not supported when using 'spring.config.import=kubernetes:'.  We did not implement support for that but may in the future.  

When using 'spring.config.import' we still look for a configmap based on 'spring.application.name' by default.  You can also use all the same configuration properties that you would use when using bootstrap. 

Does that help clarify things?

**Comment by wind57** [comment]
I was right about to comment kind of the same :)

**Comment by ogalimov** [comment]
Yes it does, thanks for the clarification. May be we could rephrase the sentense to be more clear.

**Comment by misaya98** [comment]
[main] ERROR org.springframework.boot.SpringApplication -- Application run failed
java.lang.IllegalStateException: Unable to load config data from 'kubernetes:'

why i got this error?
application.properties:
```
spring.application.name=provider-demo
spring.cloud.kubernetes.config.name=${spring.application.name}
spring.cloud.kubernetes.config.namespace=default
spring.config.import=kubernetes:
```

**Comment by wind57** [comment]
do you mind opening a new issue with a reproducible example explaining your set-up?
