### ISSUE TITLE
Our current tests are very un-balanced

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1339]
When we had circleci as the main pipeline, it had a nice feature to be able to split tests by time. This way, we had a pretty balanced run of tests of each individual instance.

Right now, we use github actions, and we only sort tests by name and split them across 32 instances. This turns out to be very imbalanced runs, some instances take 7 minutes to run, some up to 1/2 a hour. I am sure we can improve on this part of the pipeline and I will gladly take a look at this if you agree on such a feature.

**Comment by ryanjbaxter** [comment]
Yup
