### ISSUE TITLE
Bring back K8s manifests for watcher

### ISSUE THREAD

**Issue by dkirrane** [spring-cloud/spring-cloud-kubernetes#1360]
**Describe the bug**
The spring-cloud-kubernetes-configuration-watcher K8s manifests have been deleted in 3.x.
These were very useful for deploying it to Kubernetes. Can they be brought back?

https://github.com/spring-cloud/spring-cloud-kubernetes/tree/v2.1.7/spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/k8s

Dropped by commit `68134e06`

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
