### ISSUE TITLE
Incorrect overriding of array property

### ISSUE THREAD

**Issue by disimo74** [spring-cloud/spring-cloud-kubernetes#1362]
You can skip this comment and go to the next.

**Describe the bug**

I have an application configured with a default profile and a custom profile, when a define a property in the default profile I cannot overwrite it in the custom profile.
I find this problem using the spring-cloud-kubernetes-configserver images 2.1.7 and 3.0.3

**Sample**

Referring the test class KubernetesEnvironmentRepositoryTests, in the tests setup  there are a  store and a store-dev configuration.
If a call environmentRepository.findOne("stores", "dev", "") it retrieves the properties sources in this order:
- configmap.stores.default
- configmap.stores.dev
- configmap.application.default

so the store.default it's returned as first and the properties cannot be overridden by the dev profile.

I have not tested a multi-profile scenario, but I think the override should follow the order of the profile declaration.
For example if I configure the application with:
`spring.profiles.active=dev1,dev2`
 dev2 should override the properties in dev1 and default.
 In this example I expect the  properties sources will be retrieved in this order:
- configmap.stores.dev2
- configmap.stores.dev1
 - configmap.stores.default
- configmap.application.dev2
- configmap.application.dev1
- configmap.application.default

**Comment by disimo74** [comment]
I've done more tests and it seems the the problem is limited only on properties of type array. 
e.g
chart:
   - item1
   - item2
tomorrow I'll try to describe the strange behavior.

**Comment by disimo74** [comment]
Here two test cases with strange behavior:

### Test case 1
namespace=default
**config map: stores**
```
dummy:
  property:
    basket:
```
**configmap: stores-dev**
```
dummy:
  property:
    basket:
      - item2
      - item3
```
The property retrieved  with active profile dev are:
dummy.property.basket: []
so basket is empty but two item are expected.

### Test case 2
namespace=default
**config map: stores**
```
dummy:
  property:
    basket:
      - item1
 ```
**configmap: stores-dev**
```
dummy:
  property:
    basket:
      - item2
      - item3
```
The properties retrieved  with active profile dev are:
dummy.property.basket: [0]: item1
dummy.property.basket[1]: item3

so   item1 isn't overwritten and it's added item2, but the basket  should have item2 and item3 as elements.

**Comment by disimo74** [comment]
I think the problem is here:
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/22fb83d3c1675afb06a7405e82a21dd5c13f165f/spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientConfigMapPropertySource.java#L72

For Test case 1  the following maps will be merged

# map for stores.default
"dummy.property.bool2" -> {Boolean@5019} false
"dummy.property.basket" -> ""
"dummy.property.int2" -> {Integer@5022} 2
"dummy.property.string1" -> "a"
"dummy.property.string2" -> "b"

# map for stores.dev
"dummy.property.bool2" -> {Boolean@5000} true
"dummy.property.basket[0]" -> "item2"
"dummy.property.basket[1]" -> "item3"
"dummy.property.int2" -> {Integer@5006} 3
"dummy.property.string1" -> "a"
"dummy.property.string2" -> "b"

and the merged map is:
"dummy.property.bool2" -> {Boolean@5000} true
"dummy.property.basket" -> ""
"dummy.property.basket[0]" -> "item2"
"dummy.property.basket[1]" -> "item3"
"dummy.property.int2" -> {Integer@5006} 3
"dummy.property.string1" -> "a"
"dummy.property.string2" -> "b"

the single values properties are correctly overwritten, ma the basket property have this item:
"dummy.property.basket" -> ""
that prevents the overwriting

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
