### ISSUE TITLE
KubernetesCatalogWatch cannot discover restarted pods

### ISSUE THREAD

**Issue by molsza** [spring-cloud/spring-cloud-kubernetes#1369]
Version: spring-cloud-kubernetes-fabric8-discovery 2.1.5

When the pods experiencing failure  they are very quickly removed from the service endpoint lists, which is perfectly OK. 

The problem is that k8s restarting those pods without changing its name, which is the way how `KubernetesCatalogWatch` is discovering a change. If this happens in one `KubernetesCatalogWatch#catalogServicesWatch` cycle the change won't be discovered and instance will not get back to the endpoint pool, until something else trigger the refresh. 

In this way instance after instance can can be disabled till there are no more instances, which finally triggers the refresh.

**Comment by molsza** [comment]
If pod experience a failure, for example OOM or health checks fails for some time, then k8s is restarting the pod, It doesn't delete the old one and creates a new. It is the same pods in the same location, with the same name, just restart counter is increased. This can happen very fast - multiple seconds and pod is available again. That means that  `KubernetesCatalogWatch` will not see the differences between its executions (default 30s). 

In may case it is happening spring gateway and routing list. It is reacting very fast for failed endpoints and it is removing it from the routing list for good. So the whole traffic goes only to the subset instances, and the one which was restarted sits idle. This last for a long time until all instances will be restarted or there will be some changes that which trigger heartbeat event.

**Comment by molsza** [comment]
@wind57 that is exactly the case.

**Comment by ryanjbaxter** [comment]
If the pod is restarted in between the 30s interval how does the catalog watch remove it from the available instances, how would it know something changed?  

The gateway is just delegating to the discovery client.

**Comment by ryanjbaxter** [comment]
But how does the catalog Watch know anything changed if the pod restarted between the heartbeat interval?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
