### ISSUE TITLE
The pod ip change endpoint did not change

### ISSUE THREAD

**Issue by lss1457781731** [spring-cloud/spring-cloud-kubernetes#1383]
When the machine node fails, the above pod will be transferred to other nodes to start. The endpoint is still on the original pod node when the gateway requests

**Comment by ryanjbaxter** [comment]
Please provide additional details on the exact problem you are seeing.  If applicable please include a sample that would allow us to reproduce the problem.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
