### ISSUE TITLE
Running SCDF in 2 HA Kubernetes cluster 

### ISSUE THREAD

**Issue by charuni2018** [spring-cloud/spring-cloud-kubernetes#1397]
I would seek help to understand as how we can run a HA setup for the SCDF running on K8S, we would like to get this setup done by using the GTM/LTM setup, LTM will redirect to the NGINX for the PKS clusters. But how it can be achieved for the Production usage.
Thanks in advance

**Comment by ryanjbaxter** [comment]
You should open an issue here https://github.com/spring-cloud/spring-cloud-dataflow
