### ISSUE TITLE
fabric8 and k8s discovery treat instanceId (when not present in the underlying service) in a different manner

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1404]
When discovering services, we return a `List<ServiceInstance>`. That `ServiceInstance` has a field called: `instanceId`.

In both clients, we compute that field from:

```
V1Endpoints -> V1EndpointSubset -> V1EndpointAddress -> V1ObjectReference -> getUuid
```

Both fabric8 and k8s treat this the same way, except when this Uuid is not present. 

- fabric8 sets this `instanceId` to `null`
- k8s sets it to an empty String : ""

Since we started to delegate to the same code in commons, this is how it was observed.

---

In this particular case, I don't see a big issue here, imo: they should both set it to `null`, denoting that it is not present. wdyt?

**Comment by ryanjbaxter** [comment]
Agree
