### ISSUE TITLE
KubernetesDiscoveryClientAutoConfiguration will not create non-reactive DiscoveryClient Bean if WebClient is on the classpath

### ISSUE THREAD

**Issue by habelson** [spring-cloud/spring-cloud-kubernetes#1426]
**Describe the bug**
in Spring Cloud 2022.0.3, the non-reactive discovery client bean will not be created or autoconfigured if WebClient is on the classpath. This is due to the use of `@ConditionalOnMissingClass("org.springframework.web.reactive.function.client.WebClient")` .

I'm not sure what the official position is of Spring on this, but the existence of WebClient on the classpath is not a good indicator on if the app itself is reactive or not. More and more dependent libraries are preferring to use WebClient under the hood even for non-reactive (or libraries that support both), as well as Spring 6.x and Spring Boot 3.x seem to have gone down a path of correcting issues with the co-existence of spring-mvc and spring-webflux components on the classpath.

In my opinion, the decision of which DiscoveryClient bean to instantiate should be based on whether the app itself is reactive or not, rather than what is on the classpath.

Would the following annotations help in this regard?
`@ConditionalOnWebApplication(type=ConditionalOnWebApplication.Type.REACTIVE)`

`@ConditionalOnWebApplication(type=ConditionalOnWebApplication.Type.SERVLET)`

**Sample**
I cannot provide a sample at this time. But a simple non-reactive spring-mvc app that also has webflux on the classpath will not create the non-reactive DiscoveryClient, and will not be able to use the ReactiveDiscoveryClient that does get created in this case.

**Comment by ryanjbaxter** [comment]
Yes that’s what I meant 😉
