### ISSUE TITLE
Document starters

### ISSUE THREAD

**Issue by BarDweller** [spring-cloud/spring-cloud-kubernetes#146]
Testing spring-cloud-kubernetes, I've run into an issue where the ConfigMap values are not being used, and the application keeps using the values from `application.properties`.

If I swap my dependency of 
```
 		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-kubernetes</artifactId>
			<version>0.2.0.RELEASE</version>
		</dependency>
```
for
```
		<dependency>
			<groupId>io.fabric8</groupId>
			<artifactId>spring-cloud-starter-kubernetes</artifactId>
			<version>0.1.6</version>
		</dependency>
```
then the ConfigMap is used as expected, and the values are taken from there. 

I've got both @Value injection, and @ConfigurationProperties being used, both act identically. 

In the fabric8 case, I see the following log lines at app start. 
```
2018-01-17 13:48:42.368  INFO 9 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: ConfigMapPropertySource {name='configmap.test.default'}
2018-01-17 13:48:42.376  INFO 9 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: SecretsPropertySource {name='secrets.application.default'}
```

In the spring case, these lines are absent, no errors are present, no other mentions are made for ConfigMap. 

I have bootstrap.properties configured to contain my map name..
```
spring.cloud.kubernetes.config.name=test
spring.cloud.kubernetes.config.namespace=default
```

And I have also tested with a configmap in a different namespace, altering the bootstrap.properties namespace to match, with no change in behavior (works in fabric8, doesn't work on spring).

**Comment by BarDweller** [comment]
I think I may have found why.. 

Config was split off into it's own module, but the starter was never updated to include config. 

Adding 
```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-kubernetes-config</artifactId>
			<version>0.2.0.RELEASE</version>
		</dependency>
```

To my pom, lets configmaps work again as with fabric8. 

Either the starter needs an update, OR the docs need an update to say that the dependency for config needs to be added when using configmaps.

**Comment by spencergibb** [comment]
There's a new starter for config to match convention in other spring cloud projects

**Comment by BarDweller** [comment]
Indeed, but there's nothing in the documentation explaining that, and the existing documentation is unchanged from fabric8 and does not explain that apps being migrated from fabric8 to this project will have to update their dependencies due to config no longer being part of the starter. (None of the other starters really have any docs or guidance on what they provide, or when they should be used. )
