### ISSUE TITLE
Spring cloud kuberentes watcher spring boot 3.x help required

### ISSUE THREAD

**Issue by Nomi67** [spring-cloud/spring-cloud-kubernetes#1461]
Hi, 
I'm trying to implement spring cloud kubernetes in our projects. My main goals are to read configMap, secrets and enable reload using spring cloud kubernetes config watcher. 

Since there are very less examples available about how to use spring cloud for kubernetes apps, I read the documentation and figured out how to read secrets and configmap from k8s. There are 2 ways you can read these i.e 

1. Volume mount 
2. Kubernetes API

The 2nd one is not recommended due to security problems which can occur so I'm preferring 1st one. But when it comes to reloading properties using watcher then there is zero examples available with spring boot 3.x. 

While using below properties in bootstrap.properties I get below warning logs 
**bootstrap.properties**
`spring.cloud.kubernetes.discovery.enabled=false
spring.cloud.kubernetes.secrets.paths=/etc/secrets/secret-k8s
spring.cloud.kubernetes.secrets.fail-fast=true
spring.cloud.kubernetes.secrets.enabled=true`

**warning log**
`o.s.c.k.c.c.SecretsPropertySourceLocator : path support is deprecated and will be removed in a future release. Please use **spring.config.import**`

But I couldn't find any help about how to use this property with kubernetes using volume mounts.  

second thing is if possible could you please share an example of watcher with spring boot 3.x which should update mounted volume(secret/configmap) ? 

**build.gradle**
`dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation group: 'org.springframework.cloud', name: 'spring-cloud-starter-kubernetes-fabric8-config', version: '3.0.4'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}`

**Comment by ryanjbaxter** [comment]
> But I couldn't find any help about how to use this property with kubernetes using volume mounts.

`spring.config.import` is a Spring Boot property so its usage is documented in the Spring Boot documentation https://docs.spring.io/spring-boot/docs/3.1.4/reference/htmlsingle/#features.external-config.files

> second thing is if possible could you please share an example of watcher with spring boot 3.x which should update mounted volume(secret/configmap) ?

I am not sure what exactly you are looking for with regards to using the watcher and spring boot 3.x.
There is an integration test which provides an example of using the watcher
https://github.com/spring-cloud/spring-cloud-kubernetes/tree/main/spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-configuration-watcher-it

**Comment by Nomi67** [comment]
Hi @ryanjbaxter, thank you for first answer. And for second question I'm looking for help regarding. 

I want to mount my secrets and configmap to pod as mounted volume and reload them using spring cloud kubernetes config watcher via actuator end point not using amqp bus event.  But I couldn't find any example for this. Could you please share any example code for this use case ?

**Comment by ryanjbaxter** [comment]
Can you tell me what you have tried and what issue you are running into?

**Comment by ryanjbaxter** [comment]
This is epic thanks!  When I originally wrote the confg watcher I read some where on the k8s docs what the maximum time was before the values in the Pod would be updated, and I added a little bit to that to be safe as the default value.  I am having trouble finding that now, but this is a good explanation on the topic
https://ahmet.im/blog/kubernetes-secret-volumes-delay/

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Nomi67** [comment]
Hi @wind57 and @ryanjbaxter, Thank you for your help and detailed answer about config watcher. With your information I was able to use it correctly.
This issue can be closed now.

**Comment by AngelJava78** [comment]
@Nomi67 Could you solve the problem? I'm facing the same issue. Spring Cloud Kubernetes Configuration Watcher works fine with Spring Boot 2.x, but not with Spring Boot 3.x. I cloned this repository: https://github.com/alexdefelipe/spring-cloud-k8s-watcher-demo.git, but it has the same problem as my code. When updating the values of the ConfigMap, the application does not automatically update the configuration. I would appreciate some help to solve the issue with Spring Boot 3.x."
