### ISSUE TITLE
Documentation of IAM required IAM permissions for lead election when using in EKS?

### ISSUE THREAD

**Issue by efenderbosch-atg** [spring-cloud/spring-cloud-kubernetes#1465]
Is there a list of IAM permissions that the service role is required to have for leader election to work?

**Comment by ryanjbaxter** [comment]
IAM permissions?  No, you should not need to manipulate IAM permissions.

You will need to have the app use a service account that has permissions to  `get`, `list`, `watch`, `create`, `patch`, and `delete` ConfigMaps.   It also needs to `get`, `list`, and `watch` pods.

**Comment by efenderbosch-atg** [comment]
Can you point me to some documentation for that?

**Comment by ryanjbaxter** [comment]
We need to update the documentation to cover your question in this section
https://docs.spring.io/spring-cloud-kubernetes/docs/3.0.4/reference/html/#service-account

My previous comment was my best guess based on looking at the code.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
