### ISSUE TITLE
Permissions issue for Kubernetes API

### ISSUE THREAD

**Issue by deepank-sharma** [spring-cloud/spring-cloud-kubernetes#149]
When I deploy my app on the pre-prod cluster I keep getting the following error .

Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/customnamespace/services. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..

Is it something to do with the permissions on Kubernetes.
Do I need to grant some special permissions to the account to be able to query the K8S REST apis ?

**Comment by mactr0n** [comment]
This is likely because RBAC is enbaled for your cluster. So you have to define a role and a rolebinding for the "default" service account in the correspondign namespace. This should be documented!

**Comment by veludurai106** [comment]
@deepank-sharma  Please check this  https://github.com/fabric8io/fabric8/issues/6840

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
