### ISSUE TITLE
Lack of alternative for spring-cloud-kubernetes-config without (presumably deprecated) bootstrap.yml and lack of documentation for migrating it

### ISSUE THREAD

**Issue by nightswimmings** [spring-cloud/spring-cloud-kubernetes#1491]
I am a good citizen developer, and I realised spring-cloud-starter-kubernetes-fabric8-config does not include spring-cloud-bootstrap anymore in latest migration.  I could have added it again, but I wanted to check the reason and it seems bootstrap.yml mechanism is now deprecated and Spring Cloud ConfigData API is now expected as the way to do things, as you know. 

I spent quite a lot of time reading, and then I see that most people translates ConfigData API to a conventional Vault Hashicorp third-party app that must be installed in the cluster. Too much of an arch change for just making the code of my app compliant with latest expectations. Then I read that you can have a ConfigData API server embedded in the app itself if you use @EnableConfigServer, but I don't see any info on how to bind it to Kubernetes. Looks like it implies git as a source?

Instead I find out spring-cloud-kubernetes-configserver project but it is not clear if it can be used as an autoembedded server.

Finally I go back to https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/, in hopes of finding an alternative  usage that does not rely on bootstrap.yml but here there's no references to our use case. Boostrap.yml is referred all the time.

So, in risk of you considering this ticket as a veiled support request, I really do believe there should be a clear centralized guidance  on the simple way to migrate the old simple spring-cloud-kubernetes-config usage in the most simple compliant non-bootastrap.yaml way, without third-party servers (if that is possible). This business case is absolutely a must especially for Spring Cloud Dataflow Tasks, since we don't manage the deployment and sometimes we need them to "see" configmaps/servers. On a regular app we can manage their deployment.ymls to control the mounts. Deploying a configmap/secret manager component for a few tasks seems like an overkill, we really had no problem with them so far

**Comment by nightswimmings** [comment]
Hi Ryan!
I seem to understand the deprecation here
- https://spring.io/blog/2020/10/07/spring-cloud-2020-0-0-m4-aka-ilford-is-available where it is stated 
(The bootstrap phase is no longer enabled by default. If your project requires it, it can be re-enabled (...) spring.config.use-**legacy**-processing=true. (...) To do this without boostrap see the new features in Config, Consul, Vault and Zookeeper.)
- Here the change that motivated the removal of boostrap on sc-k8s-config https://github.com/spring-cloud/spring-cloud-kubernetes/pull/1002/files# (the title itself "Use ConfigData To Load Configuration From Kubernetes Instead Of Bootstrap" seems to imply the preferred way of doing things is by using ConfigData API)
- <img width="1514" alt="image" src="https://github.com/spring-cloud/spring-cloud-kubernetes/assets/9316403/7c563d58-2e30-45b5-a347-58b630595722">
- https://docs.spring.io/spring-cloud-vault/docs/current/reference/html/config-data.html#vault.configdata
- https://stackoverflow.com/questions/65063402/why-bootstrap-properties-is-ignored-by-spring-cloud-starter-config
- https://stackoverflow.com/questions/64994034/bootstrap-yml-configuration-not-processed-anymore-with-spring-cloud-2020-0 (legacy word is everywhere)
- https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#config-first-bootstrap
- https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#known-issues


So, I understand by your words this is all a big misunderstanding from my side, and despite new ConfigData API and server and the like, using bootstrap  mechanism for kubernetes-config is still perfectly legit as first-option.
I had already read before that part of the doc you sent me but it says:

_To enable this functionality you need to set spring.config.import=kubernetes: in your application’s configuration properties. **Currently you can not specify a ConfigMap or Secret to load using spring.config.import, by default Spring Cloud Kubernetes will load a ConfigMap and/or Secret based on the spring.application.name property. If spring.application.name is not set it will load a ConfigMap and/or Secret with the name application.**_ 

So unless docs are outdated, this means I cannot specifythe name of my configmaps secrets, or list them in precedence order. Besides,

_If you would like to load Kubernetes PropertySources **during the bootstrap phase** like it worked prior to the 3.0.x release you can either add spring-cloud-starter-bootstrap to your application’s classpath or set spring.cloud.bootstrap.enabled=true as an environment variable._

seems to imply that _spring.config.import=kubernetes:_ in order to read configmaps and secrets  can only be used after context initialization, and therefore, its the same as placing the properties in application.yml and not bootstrap.yml, which fails for me because some cm/secret properties are needed as external config with precedence

Either way, I really appreciate your previous response.

**Comment by nightswimmings** [comment]
So summing up, if the typical scenario where an app attempts to read configmaps/secrets directly from k8s in precedence for @Conditionals and the like (as if it was an env var), has a more preferred/state-of-the-art/simpler/ConvOverConfig way to do things, I'll appreciate hearing it!

**Comment by nightswimmings** [comment]
Thanks now it all fits!

**Comment by ryanjbaxter** [comment]
> 3. It is not feasible yet if I am reading from configmap/secrets that have custom names unrelated to my app

You should still be able to specify names of configmaps/secrets as well as which namespace they reside in that you want to include as a property source 

https://docs.spring.io/spring-cloud-kubernetes/docs/3.0.4/reference/html/#configmap-propertysource

**Comment by nightswimmings** [comment]
@ryanjbaxter  But if I don't use bootsrap.yml those are not lodaded in autconfiguration time no?

**Comment by ryanjbaxter** [comment]
Nope if you use spring.config.import and specify the names of the confit maps and secrets you want to load via the properties in the documentation those property value should be available via auto configuration

**Comment by nightswimmings** [comment]
@ryanjbaxter I did a test with a SCDF task setting application.yml as

spring:
  config:
    import=kubernetes:
  main:
    cloud-platform: kubernetes
  cloud:
    kubernetes:
      config:
        sources:
          - name: environment
          - name: infrastructure
      secrets:
        enable-api: true
        sources:
          - name: environment-secret
          - name: infrastructure-secret
          
  ..and the result is that as soon as my task initialize it fails when trying to locate the properties
`Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'X' in value \"${X}`

That does not happen if I place all `spring.cloud.*` properties in `bootstrap.yml` and enable  `spring.cloud.bootstrap.enabled=true`

**Comment by ryanjbaxter** [comment]
Can you provide a sample that reproduces the problem so I can take a look?

**Comment by nightswimmings** [comment]
I hope I can find some time, because if I am not wrong, the only way to test this at home is installing a whole Kubernetes cluster locally and configure it which I never did

**Comment by ryanjbaxter** [comment]
You can us a lightweight cluster like minikube or kind

**Comment by ryanjbaxter** [comment]
Thanks for the update.
`spring.cloud.bootstrap.enabled=true` must be set as either an environment variable or system property, it needs to be set before we load configuration properties.

**Comment by nightswimmings** [comment]
Ok, by adding
 
```
kubectl create secret generic test-secret --from-literal=test-secret-property=success
echo 'spring.cloud.kubernetes.secrets.enable-api=true' >> src/main/resources/application.properties
echo 'spring.cloud.kubernetes.secrets.name=test-secret' >> src/main/resources/application.properties
and printing @Value("${test-secret-property:none}") String testSecretProperty
```

looks like it cannot  find the secret, so all those errors I saw on unexpandable @Values were probably due to secrets, not configmaps

**Comment by nightswimmings** [comment]
Nope sorry, it was my fault, I was missing the update of the role to support secrets
kubectl create role configmap-reader --verb=get,list --resource=configmaps,services

**Comment by nightswimmings** [comment]
Hi @ryanjbaxter  Found a new cornercase on the following application.yml scenario:

```
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
    import: "kubernetes:"
  cloud:
    kubernetes:
      config:
        sources:
          - name: myconfigmap     # Contains "mydomain.custom.property: baz"
---

spring:
  main:
    cloud-platform: kubernetes
 mydomain:
   custom:
     property: "foo"  # Comment this and the value from configmap is retrieved
```
In this case, if mydomain.custom.property is defined in the application.yml as default, it takes precedence over the configmap one. Tested with Boot 3.2.2 and Cloud 2023.0.0

**Comment by ryanjbaxter** [comment]
If you switch the order the of the documents does that make a difference?

**Comment by nightswimmings** [comment]
Right, then it works as expected. 
Still, is it by design or a bug?
Thanks a lot @ryanjbaxter !

**Comment by nightswimmings** [comment]
I double checked the following truth table:

```
YAML_PROP   CONFIGMAP_PROP         App Runtime Value
                                                                         None
     x                                                                  Yaml
                                      x                                 Configmap
     x                               x                                 Configmap
```

**Comment by ryanjbaxter** [comment]
I am unsure how to interpret that, can you just provide the sample configurations?

**Comment by nightswimmings** [comment]
I used my project but I provided a sample in https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1491#issuecomment-1870987147

I'll try to explain the test above. Using the following application.yml in that particular order

```
spring:
  main:
    cloud-platform: kubernetes
 mydomain:
   custom:
     property: "foo"  
---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
    import: "kubernetes:"
  cloud:
    kubernetes:
      config:
        sources:
          - name: myconfigmap     # Contains "mydomain.custom.property: baz"

```

1.If I dont place mydomain.custom.property in either configmap nor application.yml, then @Value("${mydomain.custom.property}:none") shows "none" in runtime
2.If I dont place mydomain.custom.property in configmap but I do in application.yml, then @Value("${mydomain.custom.property}:none") shows the value from application.yml in runtime
3.If I place mydomain.custom.property in configmap but not in application.yml, then @Value("${mydomain.custom.property}:none") shows the value from the configmap in runtime
4.If I place mydomain.custom.property in configmap AND in application.yml, with different values, then @Value("${mydomain.custom.property}:none") shows the value from the configmap in runtime

Thats the truth table explained

**Comment by ryanjbaxter** [comment]
And you believe case 4 above is a bug?

**Comment by ryanjbaxter** [comment]
I believe whatever configuration is in the last document in your YAML will take precedence.  So if you have the configmap configuration last and it contains the property `mydomain.custom.property` it will win.  If you have the configmap first and specify the property `mdomain.custom.property` last it will take precedence over what is in the configmap.

**Comment by nightswimmings** [comment]
> And you believe case 4 above is a bug?

no, no, after I switched order then everything is as expected for me, as per the explanation of cases I did
The only problem for me was that it feels a bit counterintuitive to require to put that config at the end of the file. 
It should not matter whether it is before or after the main config, in my opinion

**Comment by ryanjbaxter** [comment]
This situation is a bit different though since the PropertySources that get created are part of the same file.  Spring Boot will read the documents in the file in the order they appear.  So if 

```spring:
  main:
    cloud-platform: kubernetes
mydomain:
  custom:
    property: "foo"  
```

is the first document it will create a `PropertySource` from this document.  If there is a document that comes after this that specifies confifuration from a Config Map or secret we will create a PropertySource from that and it will be placed after the first `PropertySource` in the list and will therefor have precedence.  While these are "external configurations" they are treaded more as internal configurations that get loaded from an external source.
