### ISSUE TITLE
question about kubernetes discovery controller image

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1526]
I don't understand a use-case and would like to ask for some feedback on it please. 

There is this discoveryserver image that exposes some endpoints for discovery client to access over http. I understand the usage of it: you deploy an image as a "server", then deploy a client - provide to it  "discoveryServerUrl" and it will find services over http. So far it all makes sense. 

The question I have has to do with namespaces. `discoveryserver` uses `KubernetesInformerReactiveDiscoveryClient` under the hood, which means it can be configured with : 

- all-namespaces
- one namespace
- selective namespaces

So basically you can deploy the server and tell it which namespaces to use (this is not documented or our side, but can be implied easily). The client in turn can be configured _also_ with namespaces, [see here](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java#L74). And client can filter services further, based on its _won_ filtering.

An example should make this far simler:

- server is configured to use namespaces `a` and `b`
- client says that he is interested in receiving services from namespace `a` only.

The rather interesting thing is that both the server and the client are configured with the same placeholder: 

`spring.cloud.kubernetes.discovery.namespaces`.

---

My question is why is there _additional_ filtering in clients. This filtering can be done on the server only. May be it has to do with RBAC? So that server is the only place that is configured with "winder" RBAC? What I mean is:

- discoveryserver is configured with "all-namespaces", as such some wide RBAC
- client-a wants only services from namespace `a`, more fine grained RBAC
- client-b wants only services from namespace `b`, more fine grained RBAC

But that would be a slim argument, since you can always deploy two different instances of discoveryserver and thus have different discoveryServerUrl...

**Comment by ryanjbaxter** [comment]
I think your understanding is correct.  It's to facilitate the use case where you have a discovery server for a cluster and then clients might only be interested in services for a specific namespace(s)
