### ISSUE TITLE
Change Kubernentes profile listener to listen for ApplicationStartingEvent

### ISSUE THREAD

**Issue by monkey1016** [spring-cloud/spring-cloud-kubernetes#155]
Hi,
Currently it listens for ApplicationEnvironmentPreparedEvent, which is too late to control some configuration based on `bootstrap` files that look for a specific profile:
https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/blob/88b7ea65ab509899acfaccf9addfd712b6f3308f/spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/profile/KubernetesProfileApplicationListener.java#L28

We'd like to disable and enable pulling configuration from ConfigMaps using `bootstrap.properties` files to avoid accidentally getting configuration from an OpenShift cluster someone has logged in to when doing local development.
Any objections to submitting a pull request that listens for `ApplicationStartingEvent`, which is a bit earlier in the startup process?

**Comment by spencergibb** [comment]
I'm afraid not. `ApplicationStartingEvent` does not have access to the spring `Environment`.
