### ISSUE TITLE
Spring Boot 3.2.x / Spring Cloud 2023.0.0 - bitbucket issues with Spring Cloud Kubernetes during maven test runs

### ISSUE THREAD

**Issue by wabrit** [spring-cloud/spring-cloud-kubernetes#1560]
Under e.g. Spring Boot 2.x / Spring Cloud Hoxton.SR10 I found that running maven tests as part of a BitBucket pipeline ran into issues where Spring Cloud automatically detected the presence of Kubernetes in the BB environment and tried to e.g. gather kubernetes ConfigMaps as property sources, leading to unexpected `NamespaceResolutionFailedException` when running tests.

In these circumstances this could be fixed by passing `spring.cloud.kubernetes.enabled=false` as a system property when invoking maven (e.g. via a `-D` switch to the maven command line, or within the `systemPropertyVariables` configuration of the maven-surefire-plugin). 

After uprevving to Spring Boot 3.2.1 / Spring Cloud 2023.0.0, I found that this mechanism no longer worked and I was getting `NamespaceResolutionFailedException` again on BB maven test runs.

I manged to fix the problem by adding a `src/test/resouces/bootstrap-kubernetes.yml` file in which Spring Cloud kubernetes was set disabled.

Is it expected that the previous mechanism no longer works, or is it more likely that I have misconfigured something?

**Comment by wabrit** [comment]
Is this really a duplicate? That linked bug seems to be mostly focused on earlier versions of SB/SC.

This is about SB 3.2.x / SC 2300.0.0. 

And I may be missing something, but its not at all clear to me that the resolution (which seems to be "closed due to lack of feedback") to that issue sheds any light on this one.

**Comment by ryanjbaxter** [comment]
> Is this really a duplicate? That linked bug seems to be mostly focused on earlier versions of SB/SC.

I assume you would get the same error using SB 3.1.x and SC 2022.0.x

Are your tests expected to pass even when not running on a K8S cluster?

**Comment by wabrit** [comment]
Yes that's right - the tests expect to pass with no dependency on k8s being present, and this is how they operated in SB 2.x. To this end, spring cloud kubernetes was disabled via a system property.

Under SB 3.2 it appears that this property no longer prevents spring cloud from attempting to locate e.g. ConfigMap property sources if it detects the presence of k8s (as is the case when running unit tests in BitBucket).

I have found an alternative approach as mentioned in the issue text above; whether this is a "bug" is moot - I'm more concerned that I understand whether this apparent change in behaviour is expected, and whether there is a better way of achieving what I need.

**Comment by ryanjbaxter** [comment]
Yes this was a breaking change in 2022.0.x 
https://docs.spring.io/spring-cloud-kubernetes/docs/3.0.4/reference/html/#breaking-changes-in-3-0-x

Are you loading ConfigMap using Bootstrap or using `spring.config.import`?

**Comment by wabrit** [comment]
Ah thanks! 

I'm using Bootstrap (setting `spring.cloud.kubernetes.config.sources` in `src/main/resources/bootstrap.yml`).

Previously I was disabling Spring Cloud kubernetes for unit tests using this configuration of the maven surefire plugin:

```xml
<systemPropertyVariables>
  <spring.cloud.kubernetes.enabled>false</spring.cloud.kubernetes.enabled>
</systemPropertyVariables>
```

That breaking change explains why this no longer works, so I guess I need to replace it with:

```xml
<systemPropertyVariables>
  <spring.main.cloud-platform>NONE</spring.main.cloud-platform>
</systemPropertyVariables>
```

**Comment by wabrit** [comment]
I've looked again in the linked issue, but it's not leaping out at me :-)

But in any case I'm happy that I now understand what changed and how to adjust to that change - thank you both for your help.

**Comment by ryanjbaxter** [comment]
Glad it’s clear now!
