### ISSUE TITLE
KubernetesCatalogWatch is triggered when spring.cloud.kubernetes.discovery.enabled is false

### ISSUE THREAD

**Issue by DG94** [spring-cloud/spring-cloud-kubernetes#1561]
Bug exists in Kubernetes Java Client implementation. When spring.cloud.kubernetes.discovery.enabled is set to false KubernetesCatalogWatch should not be created. All of the parameters of bean KubernetesCatalogWatch  don't exist when  spring.cloud.kubernetes.discovery.enabled=false,

Possible solution is to add @ConditionalOnKubernetesDiscoveryEnabled to https://github.com/spring-cloud/spring-cloud-kubernetes/blob/v3.1.0/spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/catalog/KubernetesCatalogWatchAutoConfiguration.java#L46 similar to KubernetesInformerDiscoveryClientAutoConfiguration

**Comment by DG94** [comment]
> I took a closer look and I think that you might be right. In the meanwhile, I found some other minor things we should do before I look at this one again. Let me open proper PRs and see what Ryan thinks about them and then I'll get back to this one.

Yes, sure. We've started exploring possiblilites to switch from eureka discovery to kubernetes discovery and we are still using one or another depending on the environment, Right now as a workaround we are injecting ${spring.cloud.kubernetes.discovery.enabled} to spring.cloud.kubernetes.discovery.catalog-services-watch.enabled

Thanks for your contribution to this project :)

**Comment by ryanjbaxter** [comment]
> seems fine with me to align these. wdyt?

agree
