### ISSUE TITLE
Unable to load properties from ConfigMap

### ISSUE THREAD

**Issue by sey** [spring-cloud/spring-cloud-kubernetes#1569]
I am following this documentation https://docs.spring.io/spring-cloud-kubernetes/reference/property-source-config/configmap-propertysource.html.  
I have published a sample code https://github.com/sey/kube-lab.  

I have tried many tutorials and examples out there and none of them prove to work as they advertise.  
I don't understand what I am missing.  

> The default behavior is to create a Fabric8ConfigMapPropertySource (or a KubernetesClientConfigMapPropertySource) based on a Kubernetes ConfigMap that has a metadata.name value of either the name of your Spring application (as defined by its spring.application.name property) or a custom name defined within the application.properties file under the following key: spring.cloud.kubernetes.config.name.

From the above excerpt of the documentation, I assumed Spring Cloud Kubernetes Config to be pretty straightforward. I just need to name both my app a `ConfigMap` with the same name and the properties within the ConfigMap should take precedence on the default properties packaged with my app.

Can you tell me what is wrong with my setup?

**Comment by ryanjbaxter** [comment]
From the docs:

> To enable this functionality you need to set the spring.config.import application configuration property to kubernetes: (escape with quotes when using yaml eg. "kubernetes:"). 

Please try adding `spring.config.import=kubernetes:` to your `application.properties`.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
