### ISSUE TITLE
The current number of ConfigMap PropertySources does not match the ones loaded from Kubernetes - No reload will take place

### ISSUE THREAD

**Issue by Charles1007** [spring-cloud/spring-cloud-kubernetes#1570]
**Describe the bug**
The current number of ConfigMap PropertySources does not match the ones loaded from Kubernetes - No reload will take place

**Sample**
2024-01-31 16:08:03.615 INFO  [traceId-] [spanId-] 
                [org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration:133] [main] o.s.c.b.c.PropertySourceBootstrapConfiguration - Located property source: [BootstrapPropertySource {name='bootstrapProperties-configmap.test1-configmap.test1'}]
2024-01-31 16:08:03.655 INFO  [traceId-] [spanId-] 
                [org.springframework.boot.SpringApplication:659] [main] com.example.test1.Test1Application - The following 1 profile is active: "kubernetes"
2024-01-31 16:08:04.824 INFO  [traceId-] [spanId-] 
                [org.springframework.cloud.context.scope.GenericScope:282] [main] o.springframework.cloud.context.scope.GenericScope - BeanFactory id=5cf03f73-59ad-3a59-a268-bfc871991b9e
2024-01-31 16:08:04.859 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.configuration.EnableEncryptablePropertiesBeanFactoryPostProcessor:44] [main] c.u.j.c.EnableEncryptablePropertiesBeanFactoryPostProcessor - Post-processing PropertySource instances
2024-01-31 16:08:04.860 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter:110] [main] c.u.j.EncryptablePropertySourceConverter - Converting PropertySource bootstrapProperties-configmap.test1-configmap.test1 [org.springframework.cloud.bootstrap.config.BootstrapPropertySource] to EncryptableEnumerablePropertySourceWrapper
2024-01-31 16:08:04.861 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter:105] [main] c.u.j.EncryptablePropertySourceConverter - Skipping PropertySource configurationProperties [class org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource
2024-01-31 16:08:04.861 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter:105] [main] c.u.j.EncryptablePropertySourceConverter - Skipping PropertySource servletConfigInitParams [class org.springframework.core.env.PropertySource$StubPropertySource
2024-01-31 16:08:04.862 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter:105] [main] c.u.j.EncryptablePropertySourceConverter - Skipping PropertySource servletContextInitParams [class org.springframework.core.env.PropertySource$StubPropertySource
2024-01-31 16:08:04.862 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter:110] [main] c.u.j.EncryptablePropertySourceConverter - Converting PropertySource systemProperties [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
2024-01-31 16:08:04.863 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter:110] [main] c.u.j.EncryptablePropertySourceConverter - Converting PropertySource systemEnvironment [org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource] to EncryptableSystemEnvironmentPropertySourceWrapper
2024-01-31 16:08:04.863 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter:110] [main] c.u.j.EncryptablePropertySourceConverter - Converting PropertySource random [org.springframework.boot.env.RandomValuePropertySource] to EncryptablePropertySourceWrapper
2024-01-31 16:08:04.864 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter:110] [main] c.u.j.EncryptablePropertySourceConverter - Converting PropertySource cachedrandom [org.springframework.cloud.util.random.CachedRandomPropertySource] to EncryptablePropertySourceWrapper
2024-01-31 16:08:04.865 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter:110] [main] c.u.j.EncryptablePropertySourceConverter - Converting PropertySource springCloudClientHostInfo [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2024-01-31 16:08:04.865 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter:110] [main] c.u.j.EncryptablePropertySourceConverter - Converting PropertySource KUBERNETES_NAMESPACE_PROPERTY_SOURCE [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2024-01-31 16:08:04.866 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter:110] [main] c.u.j.EncryptablePropertySourceConverter - Converting PropertySource Config resource 'file [/apps/test1/config/application.yml]' via location '/apps/test1/config/application.yml' [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
2024-01-31 16:08:04.867 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter:110] [main] c.u.j.EncryptablePropertySourceConverter - Converting PropertySource applicationConfig: [file:/apps/test1/config/application.yml] [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
2024-01-31 16:08:04.868 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter:110] [main] c.u.j.EncryptablePropertySourceConverter - Converting PropertySource logCorrelation [org.springframework.boot.actuate.autoconfigure.tracing.LogCorrelationEnvironmentPostProcessor$LogCorrelationPropertySource] to EncryptableEnumerablePropertySourceWrapper
2024-01-31 16:08:04.868 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter:110] [main] c.u.j.EncryptablePropertySourceConverter - Converting PropertySource springCloudDefaultProperties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2024-01-31 16:08:05.365 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.filter.DefaultLazyPropertyFilter:45] [main] c.u.j.filter.DefaultLazyPropertyFilter - Property Filter custom Bean not found with name 'encryptablePropertyFilter'. Initializing Default Property Filter
2024-01-31 16:08:05.375 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.resolver.DefaultLazyPropertyResolver:46] [main] c.u.j.resolver.DefaultLazyPropertyResolver - Property Resolver custom Bean not found with name 'encryptablePropertyResolver'. Initializing Default Property Resolver
2024-01-31 16:08:05.375 INFO  [traceId-] [spanId-] 
                [com.ulisesbocchio.jasyptspringboot.detector.DefaultLazyPropertyDetector:44] [main] c.u.j.detector.DefaultLazyPropertyDetector - Property Detector custom Bean not found with name 'encryptablePropertyDetector'. Initializing Default Property Detector
2024-01-31 16:08:05.654 INFO  [traceId-] [spanId-] 
                [org.springframework.boot.web.embedded.tomcat.TomcatWebServer:108] [main] o.s.boot.web.embedded.tomcat.TomcatWebServer - Tomcat initialized with port 1994 (http)
2024-01-31 16:08:05.664 INFO  [traceId-] [spanId-] 
                [org.apache.juli.logging.DirectJDKLog:173] [main] org.apache.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-1994"]
2024-01-31 16:08:05.667 INFO  [traceId-] [spanId-] 
                [org.apache.juli.logging.DirectJDKLog:173] [main] org.apache.catalina.core.StandardService - Starting service [Tomcat]
2024-01-31 16:08:05.667 INFO  [traceId-] [spanId-] 
                [org.apache.juli.logging.DirectJDKLog:173] [main] org.apache.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/10.1.16]
2024-01-31 16:08:05.713 INFO  [traceId-] [spanId-] 
                [org.apache.juli.logging.DirectJDKLog:173] [main] o.a.c.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
2024-01-31 16:08:05.713 INFO  [traceId-] [spanId-] 
                [org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext:296] [main] o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 2042 ms
2024-01-31 16:08:07.930 INFO  [traceId-] [spanId-] 
                [org.springframework.core.log.LogAccessor:174] [main] o.s.c.k.f.c.r.Fabric8EventBasedConfigMapChangeDetector - Kubernetes event-based configMap change detector activated
2024-01-31 16:08:08.075 WARN  [traceId-] [spanId-] 
                [org.springframework.core.log.LogAccessor:271] [main] o.s.c.k.commons.config.reload.ConfigReloadUtil - The current number of ConfigMap PropertySources does not match the ones loaded from Kubernetes - No reload will take place

**Comment by Charles1007** [comment]
<dependency>
            <groupId>com.github.ulisesbocchio</groupId>
            <artifactId>jasypt-spring-boot-starter</artifactId>
        </dependency>

**Comment by Charles1007** [comment]
When I excluded jasypt, the configuration was able to refresh
`<plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>com.github.ulisesbocchio</groupId>
                            <artifactId>jasypt-spring-boot-starter</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>`

**Comment by Charles1007** [comment]
![1706759469670](https://github.com/spring-cloud/spring-cloud-kubernetes/assets/9301844/4dd98e20-3167-4a4f-8a97-8c63d53c16eb)

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by Charles1007** [comment]
[test.zip](https://github.com/spring-cloud/spring-cloud-kubernetes/files/14518454/test.zip)
@wind57 This is my demo, please help me troubleshoot the problem, thank you

**Comment by ryanjbaxter** [comment]
I am not particularly fond of making a change like this for a specific library that does not appear to be maintained or widely used.  This opens up a "can of worms" where we are setting the precedence for supporting anything that wraps a property source.  IMO, the the bug is with the library that is trying to integrate in the Spring ecosystem and not on us.  If the library maintainers would like changes in the Spring ecosystem that would make it easier to integrate their library that is fine we can do that, but its impossible for Spring to accommodate every single library in one off situations like this.

**Comment by ryanjbaxter** [comment]
Potentially, not sure what the use case is here
