### ISSUE TITLE
Fabric8ProfileEnvironmentPostProcessor can freeze tests

### ISSUE THREAD

**Issue by kubav182** [spring-cloud/spring-cloud-kubernetes#1575]
I connect to remote k8s clusters in azure and use az login with kubelogin to store tokens.

App works fine it does not not need any real connection to cluster (i know because i must be on vpn to connect), but when new az login is required and cluster is set as current kube context it looks like there are instructions in org.springframework.cloud.kubernetes.fabric8.profile.Fabric8ProfileEnvironmentPostProcessor that somehow interacts with k8s env and it freezes for 15 minutes at the start when running tests or starting app locally (probably some timeout). There are no logs.

I use bootstrap properties with spring cloud kubernetes enabled false, but it has no effect. Everything works when I comment dependency fabric8 config or replace class in my jar with empty method returning false or use az login with get credentials to refresh token.

I have spring cloud version 2021.0.5, same behaviour for latest patch version and the class in the latest release looks very similar with different name.

I don't know how to disable this processor in standard way (I'm afraid it is not possible), but it really should not interact with kube env when i disable kubernetes in bootstrap properties. So please add some check for this property or let us override this behaviour in standard way.

Quite hard to provide example as you need kube cluster in context with invlid token.

**Comment by ryanjbaxter** [comment]
Am I understanding your correctly, are you using spring cloud 2021.0.5?

**Comment by kubav182** [comment]
yes I use 2021.0.5 and SB 2.7.X, I'm before upgrade to SB 3.2 and 2023.0.0, I can try on the latest version if you want, the code is very similar in this post processor, but there is instance of different class to connect kube

**Comment by kubav182** [comment]
So, it looks like the bug is in versions till 2021.0.9. 2022.x and 2023.x have no problem. Upgrade will resolve my issue. I'm not sure if you still support 2021.x.

**Comment by ryanjbaxter** [comment]
No we only support 2023.0.x at this point
