### ISSUE TITLE
spring-cloud-kubernetes version that support java 8

### ISSUE THREAD

**Issue by dniald** [spring-cloud/spring-cloud-kubernetes#1576]
i use java 8 in my project due to old legacy of the app. I try to use spring-cloud-starter-kubernetes-client but got the error below.

in pom.xml:
```
<!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-kubernetes-client -->
<dependency>
  <groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-kubernetes-client</artifactId>
	<version>3.1.0</version>
 </dependency>

```

Error logs:

<img width="1723" alt="image" src="https://github.com/spring-cloud/spring-cloud-kubernetes/assets/38592307/495c2d42-fd0d-4cd6-a066-151aec2339c3">

**Comment by ryanjbaxter** [comment]
We no longer support a version of Spring Cloud that supports Java 8.  We currently only support Spring Cloud 2023.0.x which requires Java 17.

**Comment by ryanjbaxter** [comment]
The last version of Spring Cloud which supported Java 8 is 2021.0.9, but like I said we no longer support that version

**Comment by dniald** [comment]
is this meaning this version below is the latest version that support java 8?


<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-client</artifactId>
    <version>2.0.4</version>
</dependency>

**Comment by ryanjbaxter** [comment]
I believe so
