### ISSUE TITLE
Feign Timeout not working

### ISSUE THREAD

**Issue by shahbour** [spring-cloud/spring-cloud-kubernetes#158]
Setting ribbon timeout is not working, I did the below but still, the command is run with ReadTimeout of 1000.

```
hystrix.command.default.execution.timeout.enabled: false
common.ribbon.ReadTimeout: 30000
ribbon.ReadTimeout: 20000
```

But when trying to set the configuration in the code it worked 

```
@Configuration
public class FeignConfigure {
    public static int connectTimeOutMillis = 12000;
    public static int readTimeOutMillis = 120000;

    @Bean
    public Request.Options options() {
        return new Request.Options(connectTimeOutMillis, readTimeOutMillis);
    }
}
```

**Comment by spencergibb** [comment]
If you are still having trouble, open a new issue in spring-cloud-openfeign and provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.
