### ISSUE TITLE
discoveryserver: endpoints are inconsistent: /apps/{name}, but /app/{name}/{instanceId}

### ISSUE THREAD

**Issue by codefromthecrypt** [spring-cloud/spring-cloud-kubernetes#1586]
**Describe the bug**

I spent time trying to figure out why my requests were 404 because I didn't assume that root paths would be different depending on whether you are getting an app or an instance of it.

**Sample**

Either of below is fine:

/apps
/app/zipkin
/app/zipkin/f2f5dea6-a14c-4660-9b0d-539e2ab23950

/apps
/apps/zipkin
/apps/zipkin/f2f5dea6-a14c-4660-9b0d-539e2ab23950

However, the rest controller paths are not consistent, so you have to do something very unintuitive. To the untrained eye, I might have to tell you the last is missing the 's'

/apps
/apps/zipkin
/app/zipkin/f2f5dea6-a14c-4660-9b0d-539e2ab23950

**Comment by ryanjbaxter** [comment]
Agree

**Comment by codefromthecrypt** [comment]
I was going to suggest the same thing, basically add another endpoint to the controller that calls the same function. Thanks folks!
