### ISSUE TITLE
Move from @Value for properties defaults to allow relaxed binding for defaults 

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-kubernetes#16]
@Value("${spring.application.name:unknown}")

**Comment by wind57** [comment]
this is present on :

```
	/** The service name of the local instance. */
	@Value("${spring.application.name:unknown}")
	private String serviceName = "unknown";
```

a field in `org.springframework.cloud.kubernetes.commons.discovery.KubernetesDiscoveryProperties.java`.

The only usage of the getter of that property is in `org.springframework.cloud.kubernetes.fabric8.registry.KubernetesRegistration`. That package should be removed entirely, but that is only possible in `2.x`, i.e.: on a major release.

I propose to make this change in a PR and keep it open until that time comes. This way, it will not go out of site; unless you see a problem to keep a PR open for some time.
