### ISSUE TITLE
Property reload from ConfigMap doesn't work

### ISSUE THREAD

**Issue by jerckov** [spring-cloud/spring-cloud-kubernetes#160]
I trying to configure `spring-clound-kubernetes` with my spring boot app by reload example https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-examples/kubernetes-reload-example in Kubernetes v1.7.1 (not in Openshift). My files:

`bootstrap.properties`
```
spring.application.name=demo
spring.cloud.kubernetes.reload.enabled=true
```

`config-map.yaml`
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
data:
  application.properties: |-
    bean.message=Hello World!
```
After apply deployment I can see in my `demo` app logs:
```
11:56:06.363 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from Kubernetes config...
11:56:06.392 [main] DEBUG io.fabric8.kubernetes.client.Config - Did not find Kubernetes config at: [/root/.kube/config]. Ignoring.
11:56:06.393 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from service account...
11:56:06.394 [main] DEBUG io.fabric8.kubernetes.client.Config - Found service account ca cert at: [/var/run/secrets/kubernetes.io/serviceaccount/ca.crt].
11:56:06.406 [main] DEBUG io.fabric8.kubernetes.client.Config - Found service account token at: [/var/run/secrets/kubernetes.io/serviceaccount/token].
11:56:06.407 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client namespace from Kubernetes service account namespace path...
11:56:06.407 [main] DEBUG io.fabric8.kubernetes.client.Config - Found service account namespace at: [/var/run/secrets/kubernetes.io/serviceaccount/namespace].

...
```
and I don't see
`The message is: Hello World!` 
but still
`The message is: a message that can be changed live` 
and no errors.

 It seems that app doesn't see my ConfigMap but it exists and has same name `demo` as property `spring.application.name`. What i doing wrong? Maybe I forget about something? There should be a additional configuration in deployment.yaml file? Or maybe some problem with permission for ServiceAccount, but as I know it should be changed only when we use Openshift?

**Comment by arana198** [comment]
The tutorial didn't work for me either. I had to use the following config on kubernetes to get it working, maybe try this out and see:

PS: Make sure the name of the config map matches the name of the spring boot application
`
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: reload-example
  name: reload-example
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: reload-example
  template: 
    metadata: 
      labels: 
        app: reload-example
    spec:
      containers: 
        - 
          image: oscet/example
          imagePullPolicy: Always
          name: reload-example
          volumeMounts: 
            - 
              mountPath: /deployments/config
              name: reload-example
              readOnly: true
      restartPolicy: OnFailure
      volumes: 
        - 
          configMap: 
            items: 
              - 
                key: application.properties
                path: application.properties
            name: reload-example
          name: reload-example

`

**Comment by Salaboy** [comment]
@jerckov @arana198 is this still an issue for you guys? This is working as expected for me with Kubernetes 1.9+ with the following properties: https://github.com/Salaboy/s1p_gateway/blob/master/src/main/resources/bootstrap.yml

@spencergibb I think that we can close this issue as well.

**Comment by geoand** [comment]
This is also working for me with the latest code

**Comment by inigonirmal** [comment]
This is not working for me? Any clue would be really appreciated? both event/polling reload strategy is not working. I see the app is getting the updated config map. But it is not getting applied on the bean. I dont see any error too.


Following are my env details:

inigonirmal@inigonirmal-desktop!$ minikube version
minikube version: v0.25.2
inigonirmal@inigonirmal-desktop!$ 
inigonirmal@inigonirmal-desktop!$ 
inigonirmal@inigonirmal-desktop!$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-21T21:48:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}


inigonirmal@inigonirmal-desktop!$  mvn dependency:tree | grep boot
[INFO] +- org.springframework.boot:spring-boot-starter:jar:2.1.0.BUILD-SNAPSHOT:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:2.1.0.BUILD-SNAPSHOT:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.1.0.BUILD-SNAPSHOT:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.1.0.BUILD-SNAPSHOT:compile
[INFO] +- org.springframework.boot:spring-boot-actuator:jar:2.1.0.BUILD-SNAPSHOT:compile
[INFO] +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.1.0.BUILD-SNAPSHOT:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.1.0.BUILD-SNAPSHOT:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.1.0.BUILD-SNAPSHOT:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.1.0.BUILD-SNAPSHOT:compile



inigonirmal@inigonirmal-desktop!$ mvn dependency:tree | grep kube
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ spring-cloud-kubernetes-example-reload ---
[INFO] org.springframework.cloud:spring-cloud-kubernetes-example-reload:jar:1.0.0.BUILD-SNAPSHOT
[INFO] +- org.springframework.cloud:spring-cloud-starter-kubernetes-config:jar:1.0.0.BUILD-SNAPSHOT:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-kubernetes-core:jar:1.0.0.BUILD-SNAPSHOT:compile
[INFO] |  |  +- io.fabric8:kubernetes-client:jar:3.1.10:compile
[INFO] |  |  |  +- io.fabric8:kubernetes-model:jar:2.0.8:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-kubernetes-config:jar:1.0.0.BUILD-SNAPSHOT:compile
inigonirmal@inigonirmal-desktop!$

**Comment by inigonirmal** [comment]
> This is also working for me with the latest code

Could you pls share the version of kube/springboot/cloud where it is working?

**Comment by geoand** [comment]
I just checked the `master` branch using the `reload-example` against Kubernetes 1.10

**Comment by pnkjsmwl** [comment]
Hi, does it work on Kubernetes version 1.12.9 ?
