### ISSUE TITLE
Future status of the `PropertySource Reload` feature

### ISSUE THREAD

**Issue by quang-do-se** [spring-cloud/spring-cloud-kubernetes#1607]
According to the documentation, the `PropertySource Reload` feature has been deprecated since the 2020.0 release.

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/e4a3454605b846a6c13fbe0f7c922a92fbc6a665/docs/modules/ROOT/pages/property-source-config/propertysource-reload.adoc?plain=1#L4

However, despite its deprecation, as of the latest Spring Cloud 2023.0 release, `PropertySource Reload` remains functional and is well maintained in `spring-cloud-starter-kubernetes-fabric8-config`.

Questions:
- Are there any plans to disable this feature in upcoming releases?
- Is it still safe to use this feature in production?

**Comment by ryanjbaxter** [comment]
Yes it is still available and will be for the 2023.0.x release train.  We cannot remove it (if we decide to) until the next major release (which we don't have a date for at this point).
