### ISSUE TITLE
Migrate @RibbonClient for spring-cloud-starter-kubernetes-discoveryclient

### ISSUE THREAD

**Issue by rcbandit111** [spring-cloud/spring-cloud-kubernetes#1653]
I want to  migrate `org.springframework.cloud.netflix.ribbon.RibbonClient` to other client compatible with Spring Boot 3.

Example:

```
org.springframework.cloud.netflix.ribbon.RibbonClient;

@RibbonClient(name = "tetst-client")
@Component
public class TestingClient {
....
}
```

I found that there is a ribblon client but looks like it's not maintained: https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.0.3.RELEASE/multi/multi__ribbon_discovery_in_kubernetes.html

What client I can use compatible with `spring-cloud-kubernetes-client-discovery`? I need also to support load balancing. 

@wind57 Can you advice, please?

**Comment by ryanjbaxter** [comment]
Spring Cloud Loadbalancer is the replacement for Spring Cloud Netflix Ribbon
https://docs.spring.io/spring-cloud-commons/reference/spring-cloud-commons/loadbalancer.html

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
