### ISSUE TITLE
NPE in KubernetesDiscoveryClient when endpoints are not available

### ISSUE THREAD

**Issue by dgradl-fl** [spring-cloud/spring-cloud-kubernetes#167]
On 0.2.0-RELEASE 
When KubernetesDiscoveryClient goes through services and discovers a service that has been scaled down or has no available endpoints it will throw a NPE.    The stack trace is below.    Essentially the endpoints API returns a 404 and thus has no subsets to map to the Endpoint object.

Caused by: java.lang.NullPointerException: null
at org.springframework.cloud.kubernetes.discovery.KubernetesDiscoveryClient.getInstances(KubernetesDiscoveryClient.java:85)
at org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient.getInstances(CompositeDiscoveryClient.java:47)

**Comment by dgradl-fl** [comment]
I worked around this by modifying it to deal with no endpoints as an EmptyList.  Not sure if this is the best place to address this issue or if the KubernetesClient should have different handling for a 404 on endpoints lookup. 

`return Optional.ofNullable(
                Optional.ofNullable(client.endpoints().withName(serviceId).get()).orElse(new Endpoints())
                        .getSubsets()).orElse(Collections.emptyList())
                .stream()`

**Comment by spencergibb** [comment]
is this still an issue?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by dgradl-fl** [comment]
No, I was able to remove my workaround with 0.3.0-RELEASE.
