### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by breun** [spring-cloud/spring-cloud-kubernetes#1675]
On https://spring.io/projects/spring-cloud-kubernetes#learn there are some broken links:

* 3.1.3 links to https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/, but the documentation for 3.1.3 is at https://docs.spring.io/spring-cloud-kubernetes/reference/3.1.3
* 3.1.4-SNAPSHOT links to https://docs.spring.io/spring-cloud-kubernetes/docs/3.1.4-SNAPSHOT/reference/html/, but the returns 404 Not Found.

The URL format for 3.1.x versions seems to be https://docs.spring.io/spring-cloud-kubernetes/reference/${version}, because these work:

* 3.1.3: https://docs.spring.io/spring-cloud-kubernetes/reference/3.1.3
* 3.1.4-SNAPSHOT: https://docs.spring.io/spring-cloud-kubernetes/reference/3.1.4-SNAPSHOT

**Comment by ryanjbaxter** [comment]
This should be fixed once the site updates
