### ISSUE TITLE
Unit Tests getting failed in org.springframework.cloud:spring-cloud-kubernetes-fabric8-discovery:3.1.3

### ISSUE THREAD

**Issue by imtavish04** [spring-cloud/spring-cloud-kubernetes#1684]
Hi team, 

I am trying to build "org.springframework.cloud:spring-cloud-kubernetes-fabric8-discovery:3.1.3" from source code. However the UTs are getting failed with the below error -> 

`[ERROR] /root/spring-cloud-kubernetes/spring-cloud-kubernetes-fabric8-discovery/src/test/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesDiscoveryClientUtilsTests.java:53: First sentence should end with a period. [JavadocStyle]
[ERROR] /root/spring-cloud-kubernetes/spring-cloud-kubernetes-fabric8-discovery/src/test/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesDiscoveryClientUtilsTests.java:72: First sentence should end with a period. [JavadocStyle]
[ERROR] /root/spring-cloud-kubernetes/spring-cloud-kubernetes-fabric8-discovery/src/test/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesDiscoveryClientUtilsTests.java:93: First sentence should end with a period. [JavadocStyle]
Audit done.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:23 min
[INFO] Finished at: 2024-08-06T11:42:28Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check (checkstyle-validation) on project spring-cloud-kubernetes-fabric8-discovery: Failed during checkstyle execution: There are 49 errors reported by Checkstyle 9.2.1 with checkstyle.xml ruleset. -> [Help 1]
`

I have tried to skip the checkstyle validation by using --Dcheckstyle.skip=true, but still not able to skip those. 

I am using Java 17. 

Please suggest if I am doing something wrong here.

**Comment by imtavish04** [comment]
I build it on v3.1.3 tag

**Comment by imtavish04** [comment]
You have skipped the tests. I also need to run tests

**Comment by imtavish04** [comment]
Is there any way I can skip the checkstyle validation?

**Comment by benson0303** [comment]
HI @wind57 ,

We are still stuck on this checkstyle issue... it would be great if we can get some workaround..

--Benson

**Comment by benson0303** [comment]
I dont think we can fork it, we have a closed env and no sharing policy.  We are still not able to resolve this.. 
we tried adding proxy explicitly but still its not picking for checkstyle...

**Comment by ryanjbaxter** [comment]
I wonder if you IDE is applying some formatting to the code that is causing checkstyle failures

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
