### ISSUE TITLE
The SpringCloud gateway is failing to call a Kubernetes service: "No servers available for service".

### ISSUE THREAD

**Issue by oasis-zhou** [spring-cloud/spring-cloud-kubernetes#1726]
SpringBoot version: 3.3.3
SpringCloud version: 2023.0.3
SpringCloud Kubernetes version: 3.1.3

When calling other services within the same namespace from the gateway, either through OpenFeign or RestTemplate, the first call is successful, but subsequent calls fail with the following error: o.s.cloud.loadbalancer.core.RoundRobinLoadBalancer [USER:] [TRACEID:] - No servers available for service

When the configuration is changed to: spring.cloud.kubernetes.loadbalancer.mode = service, all the calls are successful.

**Comment by oasis-zhou** [comment]
The cache configuration when the above error occurred was: spring.cloud.kubernetes.loadbalancer.enabled = false. When set to True, the same error occurs after the cache expires in 35 seconds.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
