### ISSUE TITLE
Context yield halts

### ISSUE THREAD

**Issue by asgarj0** [spring-cloud/spring-cloud-kubernetes#1783]
**Describe the bug**
spring-boot `3.3.5` with spring-cloud `2023.0.3`
I'm using the `spring-cloud-kubernetes-fabric8-leader` and while calling the `Context.yield()` method, the service halts. The leadership doesn't get revoked either as other instances of the service are fetching and logging the leader and it's still the same (have enabled debug level for this module).

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
