### ISSUE TITLE
0.2.1.RELEASE

### ISSUE THREAD

**Issue by iocanel** [spring-cloud/spring-cloud-kubernetes#198]
I created a branch called 0.2.x which is actually what we have in master without the spring-boot related commits.

I'd like us to have have 0.2.1.RELEASE for people who are not yet ready to move to SB 2.0.

**Comment by george24601** [comment]
Is there plan to do a 0.2.x release to include some bug fixes? Seems to me 0.3.0.RELEASE requires SB 2.0, and we are still on 1.5.X.

**Comment by spencergibb** [comment]
We certainly can. Reminder, 0.x releases are previews and are not officially supported. @iocanel anything else you want to get in 0.2.x before I do a release?

**Comment by iocanel** [comment]
I think we are fine.

**Comment by iocanel** [comment]
@spencergibb: Any news on that? Is it something  I could perform?

**Comment by cmoulliard** [comment]
@spencergibb Can we target to have this release ready this week `0.2.1` as we need it please ?

**Comment by spencergibb** [comment]
Closed 030b4d7cc6755a7035ca63dcb02781e93a7152ee
