### ISSUE TITLE
OnGrantedEvent not fired on leader pod restart

### ISSUE THREAD

**Issue by steven-sheehy** [spring-cloud/spring-cloud-kubernetes#210]
Assume you you have 2 pods (app-a and app-b) and app-a is currently elected leader. If app-a is terminated (for example via an OOMKilled), then it will restart with the same pod name app-a. The configmap will still show "leader.id.app: app-a". If it comes back up before app-b can even see that it's gone (which is most likely since restarts happen under 5s), then app-b will not revoke app-a. app-a will execute `LeadershipController.acquire()`  and retrieve the configmap, see that it is still the leader and and hit this code:

```java
  if (candidate.getId().equals(leader.getId())) {
    return true;
  }
```

Application code never receives OnGrantedEvent because it is only fired in case configmap is initially created or if follower revoked leader, neither of which happens in this scenario. Possible solutions:

1) Fire handleOnGranted(candidate) inside that if statement, but downside is it triggers an OnGrantedEvent every lease duration.
2) Keep state locally about leadership status and only fire if that changes.

**Comment by geoand** [comment]
Is this still an issue as #219 has been merged?

**Comment by gytis** [comment]
This shouldn't be an issue any more after merging this https://github.com/spring-cloud/spring-cloud-kubernetes/commit/ca80117f3590c9c6d3bac97419f5b30d195491f5#diff-8322b03d221fa577993ec51acbb43d83.
On the first all of `handleLeaderChange` after restart, `localLeader`will be `null` and `notifyOnGranted()` will be called: https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-leader/src/main/java/org/springframework/cloud/kubernetes/leader/LeadershipController.java#L143.
