### ISSUE TITLE
Is spring-cloud-kubernetes production ready?

### ISSUE THREAD

**Issue by Ziemowit** [spring-cloud/spring-cloud-kubernetes#213]
Hey it is not the issue but rather the question.

Does the project can be already used in Production? 
Version 0.3.0 and placement in spring-cloud-incubator points out that rather not...

If not is there any road-map or prediction when the 1st stable production-ready version more less could be ready?

Thank you in advance.

**Comment by spencergibb** [comment]
The project has moved out of incubator and the 1.0 release will be part of the Greenwich release train. Follow here for the tentative schedule https://github.com/spring-cloud/spring-cloud-release
