### ISSUE TITLE
KubernetesClientException on openshift online

### ISSUE THREAD

**Issue by victorherraiz** [spring-cloud/spring-cloud-kubernetes#225]
Trace:

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/*****-dev/pods/*****-customer-2-6trkc . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "*****-customer-2-6trkc" is forbidden: User "system:serviceaccount:*****-dev:default" cannot get pods in the namespace "*****-dev": User "system:serviceaccount:*****-dev:default" cannot get pods in project "*****-dev".
 
```

Executing the following command on openshift online

    oc policy add-role-to-user cluster-reader system:serviceaccount:*****-dev:default

results in the following error:

    Error from server (Forbidden): rolebindings.authorization.openshift.io "cluster-reader" is forbidden

is there any alternative valid for OpenShift online or  am I doing something wrong?

**Comment by victorherraiz** [comment]
@geoand that was my assumption too. Therefore, it that role is mandatory for the client, there is no support for OpenShift Online at the moment.

**Comment by geoand** [comment]
There are definitely limitations to what you can do with Openshift Online at the moment.

**Comment by spencergibb** [comment]
Closing as answered
