### ISSUE TITLE
PodUtils using HOSTNAME to detect K8S

### ISSUE THREAD

**Issue by skliche** [spring-cloud/spring-cloud-kubernetes#229]
We are running our spring boot and spring-cloud-kubernetes powered microservices on the IBM Container offering. Recently we upgraded to kubernetes worker nodes to 1.11.2_1514 and for some reasons the HOSTNAME env variable was not any longer available in the PODs. This caused that k8s was not detected by PodUtils and the kubernetes spring profile  was not enabled anymore by spring-cloud-kubernetes.

Of course we raised a ticket at IBM since the k8s documentation did not announce that and IBM also opened a pull request against containerd (see https://github.com/containerd/cri/pull/895) which should fix that. 

However I am not sure if that was an bug that is now fixed or the HOSTNAME env variable is maybe not the best idea to detect k8s. Therefore I am opening the issue as a heads up. Hope that is ok. :)

**Comment by ArtyomGabeev** [comment]
@skliche if you are sure that application is running inside k8s, I think you can simply specify pod environment variable:
`
SPRING_PROFILES_ACTIVE: "kubernetes"
`
In this case even if HOSTNAME env variable was not set, you will get correct profiles configuration.

**Comment by skliche** [comment]
What we actually did was to set the HOSTNAME variable in the pods, because for our workflow this was easier and containerd fixed that in new builds anyway. Still, I wanted to highlight the issue to the spring cloud project, because other users might also be affected and perhaps there is a more robust way to detect a k8s environment in PodUtils.

**Comment by spencergibb** [comment]
is this a documentation issue?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by skliche** [comment]
@spencergibb well the proposal of @ArtyomGabeev is a neat idea and that in connection with a description of how Spring Cloud Kubernetes is detecting a k8s environment is worth do be documented. 

However I opened this issue to discuss if there is a more robust way to auto-detect a k8s environment. I suggest to use the `KUBERNETES_SERVICE_HOST` environment variable instead.

**Comment by spencergibb** [comment]
I'm not sure @salaboy @geoand @iocanel any ideas?

**Comment by geoand** [comment]
Not from me unfortunately...

**Comment by iocanel** [comment]
@skliche: If you diable the service account, spring-cloud-kubernetes will not work at all, since it needs to talk to the apiserver. So, IMHO its the a really good candiadate for replacing the HOSTNAME env var.

**Comment by skliche** [comment]
Hm, if there are really no use-cases without the API server, then it is probably better than `KUBERNETES_SERVICE_HOST`

**Comment by ryanjbaxter** [comment]
I have not noticed this issue recently so I am going to close this issue
