### ISSUE TITLE
Create Istio awareness module

### ISSUE THREAD

**Issue by salaboy** [spring-cloud/spring-cloud-kubernetes#233]
Create a module that help Spring Cloud components to be aware that they are running in an Istio enabled environment to avoid clashes.

**Comment by geoand** [comment]
I would love to hear what you have in mind for this issue and I would be
willing to work on it

**Comment by Salaboy** [comment]
@geoand 👍 S1P is approaching fast, so what about if we have a chat after S1P ?(unless you are attending and we can have a chat face to face?) and we collaborate on this.

**Comment by geoand** [comment]
Unfortunately I won't be attending, so let me know after and we can talk.

Have fun at s1ps1p 😁

**Comment by geoand** [comment]
@salaboy do you have time to go talk some time soon about ideas like this?

Thanks

**Comment by salaboy** [comment]
@geoand yes I should have some time soon (sorry for my lack of communications.. still working on this but I have a beta2 release that I need to get out of the door). Can you write me an email to my personal account (same as my nickname here at gmail) to coordinate? Who else can we invite? @spencergibb do you wanna join?

**Comment by geoand** [comment]
@salaboy no worries, I know that finding time is extremely tough :)

I would think that @iocanel would probably want to be part of the talk about what you have in mind
