### ISSUE TITLE
Modernize and update testing frameworks

### ISSUE THREAD

**Issue by salaboy** [spring-cloud/spring-cloud-kubernetes#236]
Upgrade and unify how we test the different modules.

**Comment by geoand** [comment]
Are we thinking of using Spock as a means of implementing this task?

I would gladly participate in such an implementation :)

**Comment by salaboy** [comment]
@geoand Spock is an option. It will be great to use the WebTestClient as well for doing real tests against services running inside Kubernetes. Mocking is good, but I will feel better with myself if we build a nice test suite that we can run also against running environments. Does this make sense?

**Comment by geoand** [comment]
@salaboy I already opened one PR concerning the WebTestClient (see [this](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/241)).

Just to make sure I understood correctly, you would like to add an integration test suite that stands up an actual Kubernetes cluster (something like Minikube for example) and performs the tests against it?

**Comment by salaboy** [comment]
@geoand Great stuff about the WebTestClient, 
Regarding starting a minikube, I wouldn't say so.. it should work with a real cluster that is already running somewhere.. so we can point the test suite against an environment.

**Comment by spencergibb** [comment]
I want to move away from groovy. That will influence decisions.

**Comment by wind57** [comment]
@ryanjbaxter to me, this one can be closed?
