### ISSUE TITLE
Describe how to do integration tests with Kubernetes

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-kubernetes#24]
/cc @iocanel

**Comment by iocanel** [comment]
[Arquillian Cube](https://github.com/arquillian/arquillian-cube) provides a module for writing integration tests with Kubernetes.

At the moment it works great when the integration tests run **inside** Kubernetes. When tests are run **outside** of Kubernetes and use remote Kubernetes installation there are some limitations *(access services deployed on kubernetes from the outside requires either portforwarding, or custom dns / route configuration)*. This should be fixed soon by adding portforwarding support in the arquillian-cube kubernetes module. (See https://github.com/arquillian/arquillian-cube/pull/493).  

Until then its usability in this particular project is limited.

**Comment by geoand** [comment]
We have already added integration tests so closing this
