### ISSUE TITLE
Unable to list services

### ISSUE THREAD

**Issue by harishkadamudi** [spring-cloud/spring-cloud-kubernetes#243]
Following this guide, to run application- https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-examples/kubernetes-hello-world-example
I followed the instructions as detailed, when I executed below url, I got exception as pasted.
curl http://IP_OR_HOSTNAME/services
Exception:
There was an unexpected error (type=Internal Server Error, status=500).
Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/services. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. services is forbidden: User "system:serviceaccount:default:default" cannot list services in the namespace "default".

I did verify navigating to services, I see kubernetes-hello-world service.

**Comment by geoand** [comment]
This looks like a RBAC issue. See [this](https://kubernetes.io/docs/reference/access-authn-authz/rbac/) part of the Kubernetes documentation.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
