### ISSUE TITLE
Bad style in KubernetesDiscoveryClient

### ISSUE THREAD

**Issue by joshiste** [spring-cloud/spring-cloud-kubernetes#247]
This line:
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/c2dc809469bf547eec4508971a580a9722f042f5/spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java#L90
causes the `KubernetesServiceInstance` to return `null` for `getMetadata` in some cases. It is considered bad practice to return `null` for methods returning colllections - returning `emptyMap()` would be much better.

Also catching any `Throwable` in https://github.com/spring-cloud/spring-cloud-kubernetes/blob/c2dc809469bf547eec4508971a580a9722f042f5/spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java#L112 is also considered bad practice as this will swallow any exception without notice (even OutOfMemoryError). Imho only instances of `Exception` should be caught and be logged or rethrown.

**Comment by geoand** [comment]
#245 should fix the first issue

**Comment by geoand** [comment]
Closing as #245 has been merged
