### ISSUE TITLE
spring-cloud-starter-kubernetes-config: KubernetesHealthIndicator not registered

### ISSUE THREAD

**Issue by colin-shine** [spring-cloud/spring-cloud-kubernetes#250]
An application using `spring-cloud-starter-kubernetes` displays the kubernetes health indicator on `/actuator/health`, but this does not work when the  `spring-cloud-starter-kubernetes-config` starter is used

**Comment by colin-shine** [comment]
I have created two identical apps `demo1` and `demo2` that show the problem:
https://github.com/colin-shine/spring-cloud-kubernetes-issues

The only difference between the two app POMs is as follows:

demo1:
``` XML
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-kubernetes</artifactId>
</dependency>
```

demo2:
``` XML
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-kubernetes-config</artifactId>
</dependency>
```

As far as I can see, the config starter's `BootstrapConfiguration` imports the `KubernetesAutoConfiguration`, causing the `KubernetesHealthIndicator` bean to be registered in the bootstrap context. This seems to be having a weird effect on the `@ConditionalOnMissingBean`.

When I debug, I see 3 health indicator beans registered for `demo1`:
![image](https://user-images.githubusercontent.com/17406518/46812910-9e8d7480-cd6d-11e8-83fc-2b9ff80c064f.png)

but only 2 for demo2:
![image](https://user-images.githubusercontent.com/17406518/46812956-b7962580-cd6d-11e8-8acd-febb3ad45ebc.png)

**Comment by geoand** [comment]
@colin-shine Thanks for reporting and sharing a demo project!

I will check this out and let you know

**Comment by geoand** [comment]
@colin-shine I have found a potential work around that seems to work for use case. I still however need to add some tests in order to verify it.

I will pick it up again tomorrow
