### ISSUE TITLE
Why is Consuming Secrets via API not secure ? 

### ISSUE THREAD

**Issue by hazim1093** [spring-cloud/spring-cloud-kubernetes#252]
It is mentioned in the Readme: 

> Please note that by default, consuming Secrets via API (points 2 and 3 above) is not enabled for security reasons and it is recommend that containers share secrets via mounted volumes.

What are the security reasons due to which it is not enabled ? As I am thinking to consume secrets via API and I think it might be more secure as there won't be any file containing the secret mounted on the instance. 

Provided that we have correct RBAC and pod only reads its own secret, and that we have enabled encryption at REST, is it still not secure ? Why so ?

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by hazim1093** [comment]
The question is still unanswered though

**Comment by ryanjbaxter** [comment]
@geoand @salaboy any ideas?

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by geoand** [comment]
Not really sure why this was added in the first place. @iocanel , did you add this part perhaps?

**Comment by iocanel** [comment]
I didn't add it myself (not that I can recall). Maybe @nicolaferraro or @lburgazzoli did!

**Comment by nicolaferraro** [comment]
My memory can fail :)
But I recall that the meaning is not that it's not secure.. but simply that the standard "view" role doesn't allow reading secrets, only configmaps. You needed a "edit" role to read secrets, but that opened a wide range of other possibilities...

At the time of writing that sentence, fine grained RBAC was probably not implemented yet.

**Comment by lburgazzoli** [comment]
> My memory can fail :)
> But I recall that the meaning is not that it's not secure.. but simply that the standard "view" role doesn't allow reading secrets, only configmaps. You needed a "edit" role to read secrets, but that opened a wide range of other possibilities...
> 
> At the time of writing that sentence, fine grained RBAC was probably not implemented yet.

Another topic was that there were no way to limit what secrets an application were allowed to consume so potentially a malicious application could steal all the secrets in the namespace.

**Comment by iocanel** [comment]
Thanks for the clarifications.

**Comment by ryanjbaxter** [comment]
@lburgazzoli so is that still a concern today? (there is no way to limit access to secrets to specific apps)

**Comment by lburgazzoli** [comment]
This is what the official documentation says:

    https://kubernetes.io/docs/concepts/configuration/secret/#clients-that-use-the-secrets-api

So I think the default is correct

**Comment by ryanjbaxter** [comment]
So it sounds like the correct thing to do is to update the documentation to state the reasons for the limitations, agree?

**Comment by lburgazzoli** [comment]
I do agree

**Comment by hazim1093** [comment]
Thanks guys, really nice to know the reasons behind it. 
The doc was already updated with the link to official kubernetes documentation, I just rephrased it a bit to highlight risks and best practices when using this.

https://github.com/spring-cloud/spring-cloud-kubernetes/pull/412
