### ISSUE TITLE
Secrets can be read using API given proper RBAC is in place

### ISSUE THREAD

**Issue by rasheedamir** [spring-cloud/spring-cloud-kubernetes#268]
This statement in the README seems misleading:

```
Please note that by default, consuming Secrets via API (points 2 and 3 above) is not enabled for security reasons and it is recommend that containers share secrets via mounted volumes.
```

As if we use proper RBAC where pod is restricted only to read its on secrets then reading through API has no security concerns.

**Comment by salaboy** [comment]
@rasheedamir that is a true statement, but I guess that the README line was written thinking about the user not using RBAC. 
I can provide a fix for this for sure.. mentioning RBAC so it is clear..

**Comment by salaboy** [comment]
@spencergibb can you please review.. so we can close this issue?

**Comment by rasheedamir** [comment]
It will be awesome to get it to master; so, that its clear for new comers
