### ISSUE TITLE
Discovery Client should support secure instances

### ISSUE THREAD

**Issue by jochenchrist** [spring-cloud/spring-cloud-kubernetes#272]
`KubernetesServiceInstance` has a `secure` Flag to build the URI with https.

`KubernetesDiscoveryClient` always sets `secure=false`:
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/a277bf1d1b47e6f01ac97d9596d6a66777ca8e05/spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java#L120

**Feature Request**
Provide a way to configure a ServiceInstance as secure, e. g. by specifing a label or annotation.

**Comment by geoand** [comment]
@jochenchrist Very nice idea indeed!

I was wondering though, is the label or annotation you propose something ad-hoc that developers would set themselves for each of their microservices?
AFAIK, there is no standard way of "knowing" if the endpoint corresponds to HTTP or HTTPS

**Comment by jochenchrist** [comment]
Yes, I don't see a way to determine the secure flag.

So, it must be configured somehow.

Some ideas:
- Provide a property `spring.cloud.kubernetes.discovery.secured` to default all instances a secure
- Developer can set a label `secured: true` in the service deployment descriptor.
- A well known list of ports (443, 8443, ...) is set to default = true.

**Comment by geoand** [comment]
@jochenchrist I like the proposal. @iocanel WDYT?

**Comment by spencergibb** [comment]
We do similar in consul

**Comment by geoand** [comment]
@spencergibb good to know! Do you have relevant documentation on that?

**Comment by geoand** [comment]
I would like to do this after #291 has been merged so we can be sure nothing breaks
