### ISSUE TITLE
Spring Cloud Kuberneter Ref docs link gives 404

### ISSUE THREAD

**Issue by NajeebArif** [spring-cloud/spring-cloud-kubernetes#281]
Spring Cloud kubernetes Reference docs redirects to 404 not found page,
https://spring.io/projects/spring-cloud-kubernetes#learn

**Comment by ryanjbaxter** [comment]
Should be fixed

**Comment by NajeebArif** [comment]
Hi,

Link is working now.

Thanks and Regards
Najeeb Arif
