### ISSUE TITLE
Review logic of getInstances and improve doc

### ISSUE THREAD

**Issue by cmoulliard** [spring-cloud/spring-cloud-kubernetes#284]
### Review Logic

I' not sure that the code implemented within the [method - getInstances of the DiscoveryClient](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java#L82-L105) is consistent and follows user's reasoning

Here is the definition that I would like to suggest to discuss and implement. 

As a user, I would like to get all the endpoints available according to the following queries/options : 

```
A) Search for all the Services using empty `serviceName` (1)
OR
( 
    B) Search for all the Services having a `serviceName` 
    OR
    C) Search for all the services where `labels` OR `annotations` are defined
)
```
(1) : I don't think that the method `getInstances` without labels/annotations or serviceName is relevant excepted if you want to design a hub/proxy spring boot app able to parse incoming requests and map them to a target service

In most of the cases you will pass a `serviceName` or `label` to filter the list of the services registered on k8s and the list of endpoints associated will be then returned.

### Improve doc

I propose to enhance the `DiscoveryClient` part of the project of SCK as we don't detail/explain the different options available to fetch the services using or not a serviceName, labels/annotations,...

**Comment by geoand** [comment]
I agree that we should augment the capabilities of the discovery client. 
@salaboy can you please provide your input on this?

**Comment by geoand** [comment]
@salaboy instead of adding new methods, could we not just provide a predicate bean  (with a sensible default implementation) that would be applied?
And that way users would be able to supply their own implementations if needed.
WDYT?

**Comment by salaboy** [comment]
@geoand you mean a predicate inside the method itself? That would be an option.. but I still feel that the DiscoveryClient base interface should be expanded to support some kind of selectors (labels, annotations, etc).

**Comment by geoand** [comment]
The reason I am proposing using a predicate bean is because I am not sure we are supposed to enrich the interfaces, aren't part of Spring Cloud Commons @spencergibb ?

**Comment by salaboy** [comment]
@geoand yep.. I think as part of the evolution of Spring Cloud those interface will evolve ..  but you are totally right with checking with @spencergibb and @ryanjbaxter

**Comment by salaboy** [comment]
Further specification on how this should work, now I have a working example: 
1) ** Map<ServiceId, List<ServiceInstance>> getInstances(); ** 
   - Service service = client.services().withLabels(labels).list();
   - This will return multiple services and their replicas as Spring Cloud Service Instances
   - we can also apply selectors and annotations here
2) ** List<ServiceInstance> getInstances(String serviceId) ** 
   - Service service = client.services().withName(serviceId).get();
   - no need for labels here/annotations. if you know the name of the service that is enough filter. Notice that the signature of this method is returning all the "Endpoints"/replicas of a service. So even if it is a list it doesn't return multiple services, just a single service replicas.
   - This will transform from Kubernetes **Service Endpoints** to Spring Cloud **ServiceInstance**

We should do the same for the following method:
3) List<String> getServices()
   -  Service service = client.services().withLabels(labels).list();
   - here the labels must be applied to filter against the Kubernetes APIs and the result is the list of names of available services matching those labels
   - we can also apply selectors and annotations here

Notice that in the current implementation we are also checking that Kubernetes Services have at least one Endpoint (one replica that we can contact) to mimic Spring Cloud behaviour. That cost us one more API call

@cmoulliard @geoand what do you think about this initial approach. Is that covering your use cases? 
Regarding to @cmoulliard initial description, I think that we don't need : "B) Search for all the Services having a `serviceName`" unless we are planning to support something like a search with a LIKE operator.

**Comment by geoand** [comment]
@salaboy Sounds good to me!

Just one question, where would the labels and annotation be specified?

**Comment by salaboy** [comment]
@geoand configuration or by bean injection inside the method. Does that sounds right?

**Comment by geoand** [comment]
> @geoand configuration or by bean injection inside the method. Does that sounds right?

Yup, that sounds right to me :wink:

**Comment by geoand** [comment]
> @geoand configuration or by bean injection inside the method. Does that sounds right?

Personally, I would like to see something like I did in: https://github.com/spring-cloud/spring-cloud-kubernetes/pull/292, that is having a bean being injected into the client. That way advanced users can override it if need be
