### ISSUE TITLE
Use Duration for updatePeriod in LeaderProperties

### ISSUE THREAD

**Issue by manderson23** [spring-cloud/spring-cloud-kubernetes#289]
For consistency with Spring Boot (and other properties I have in my application) I'd like to specify this property using the flexible duration syntax (e.g. 5s).

Not sure if there are also other properties this would apply to in the project.

**Comment by spencergibb** [comment]
PRs welcome

**Comment by manderson23** [comment]
@geoand what is the schedule for final release?

**Comment by geoand** [comment]
I think `1.0.0.RC2` is planned for next week and `1.0.0.RELEASE` for January

**Comment by steven-sheehy** [comment]
@manderson23 Can this be closed?

**Comment by manderson23** [comment]
Yes

**Comment by spencergibb** [comment]
Closed via #294
