### ISSUE TITLE
LeadershipController.getLocalLeader throws NPE if localLeader is null

### ISSUE THREAD

**Issue by manderson23** [spring-cloud/spring-cloud-kubernetes#296]
If `localLeader` is null then a NPE will be thrown when `getLocalLeader()` is called since `Optional.of()` is used 

If truly `Optional` then `Optional.ofNullable()` should be used? I'm not clear on whether it is expected when running within K8s that `localLeader` should never be null. I noticed this while writing tests.

**Comment by geoand** [comment]
@gytis Do you have feedback on this?

**Comment by gytis** [comment]
It looks like a bug, nice catch.

**Comment by gytis** [comment]
I'll try to raise a PR today, if not will do it on Monday.

**Comment by geoand** [comment]
@gytis RC2 is next week, so no need to get this in today :P

**Comment by gytis** [comment]
Raised a PR https://github.com/spring-cloud/spring-cloud-kubernetes/pull/297

**Comment by ryanjbaxter** [comment]
Fixed via f335da6
