### ISSUE TITLE
Feature Request: testkit

### ISSUE THREAD

**Issue by TomasRup** [spring-cloud/spring-cloud-kubernetes#301]
Hey,

Don't you think it would be nice to add a testkit using which I could:
- write a test to check if ConfigMap, stored in my k8n environment, is read by the app?
- write a test to check if secrets, stored in my k8n environment, is read by the app?
- ditto for all the features that `spring-cloud-kubernetes.git` provides?

Now in order to make sure it works I need to commit and push and deploy to see if it works. And it means anyone in the team can easily break it as I can't cover these with tests (I can, but I'd need to write my own testkit).

So why not to add a generic testkit?

**Comment by spencergibb** [comment]
Can you explain more? We tests all those things in unit and integration tests. What would this look like? None of the other spring cloud projects provide something like this, so I'm hesitant to add.

**Comment by geoand** [comment]
@TomasRup I like your suggestion.
Do you have anything similar in mind that you like using?

FWIW, it's entirely possible to write both unit and integration tests for your Spring Cloud Kubernetes applications without a terrible amount of hassle.
See [here](https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-config/src/test) and [here](https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-integration-tests)

**Comment by TomasRup** [comment]
I'll try to give you an example from dev perspective:
- Let's say I'm building a new microservice based on spring boot that I will deploy to kubernetes environment
- I store some app configs in ConfigMap, I also have some usernames/password in kubernetes Secrets
- Now how do I test if my app will consume the configmap and secrets of kubernetes and do something with that? Right now I have to deploy to kubernetes and see
- But what if I could add a one more dependency, let's say `spring-cloud-kubernetes-testkit`
- Then I could add some configmap and secrets file to my `test/resources`
- Then I write tests that are ran in a simulated environment: configmap and secrets are wired and my app is started in a pod, I can do a http call to it (or whatever else).

This `spring-cloud-kubernetes-testkit` could be a wrapper with arquillian inside and a few annotations.

Spring is a lot about configuration rather than coding, though it's necessary to test how does the app work with a given config too. And does it even take the config in a given environment...

**Comment by spencergibb** [comment]
You could say the same thing for every other spring cloud project. I'm not sure this is something I want to invest in at the moment.  At that point you are testing this project.

**Comment by geoand** [comment]
I agree with @spencergibb on this

Also FWIW, you can easily spin up your Spring Cloud Kubernetes application without having it actually being deployed on the cluster. It can still talk to the API server (and this use ConfigMap, Secrets etc) in the exact same way as it would inside the cluster.

Personally I think that even if we did provide something like what you are describing, you would still not be sure everything is fine unless you test it against the actual cluster

**Comment by ryanjbaxter** [comment]
Closing due to lack of votes
