### ISSUE TITLE
CertificateParsingException when running junit test

### ISSUE THREAD

**Issue by YeisonMelo** [spring-cloud/spring-cloud-kubernetes#302]
Im using the latest version it deploys correctly but when i want to run Junit test, all them giving me this error: 

`com.bagheera.attendance.AttendanceServiceTests > schoolMixedAbsencesTest FAILED
    java.lang.IllegalStateException
        Caused by: io.fabric8.kubernetes.client.KubernetesClientException
            Caused by: java.security.cert.CertificateParsingException`

I have tried to disable kubernetes during test with: 
`  cloud:
    kubernetes:
      discovery:
        enabled: false
      enabled: false`

but this two disabled options are not even recognised/working, nothing changes. I get the same error.

` implementation('org.springframework.cloud:spring-cloud-starter-kubernetes-all')`

**Comment by geoand** [comment]
@YeisonMelo Can you please fix the formatting of the YAML you are showing?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
