### ISSUE TITLE
properties load not refresh in bean object

### ISSUE THREAD

**Issue by fgranato** [spring-cloud/spring-cloud-kubernetes#312]
I've created a spring.xml file that contains the beans which use/load the properties values from the application.yaml file injected in configMap via  @ConfigurationProperties in java class.
I'm able to load and initialize the beans in spring.xml with correct properties values at the start of container, but if I edit the values on configMap, the inizialized beans do not recognize the update and the beans are not be refresh.

### ConfigMap
kind: ConfigMap
apiVersion: v1
metadata:
  name: command-springboot
data:
  application.properties: |
    core.broker-username=admin
    core.broker-password=admin
    core.broker-url=failover://tcp://127.0.0.1:61616

### ConfigurationProperties
`@Configuration
@ConfigurationProperties(prefix = "core")
public class CommandConfig {
	private String brokerUsername;
	private String brokerPassword;
	private String brokerUrl;
`

### spring.xml

<bean id=\"jmsConnectionFactoryCORE\"
		class=\"org.apache.activemq.ActiveMQConnectionFactory\">
		<property name=\"brokerURL\" value=\"${core.broker-url}\" />
		<property name=\"userName\" value=\"${core.broker-username\}" />
		<property name=\"password\" value=\"${core.broker-password}\" />
	</bean>

**Comment by spencergibb** [comment]
I'm afraid spring-boot is built to use java configuration. There is not way to use `@RefreshScope` on an xml configuration.
