### ISSUE TITLE
Can we add a property to disable the kubernetes auto configure like what eureka does?

### ISSUE THREAD

**Issue by huangered** [spring-cloud/spring-cloud-kubernetes#313]
hi, dev, Can we add a property to disable the kubernetes auto configure like what eureka does?
because we have two environments(application.properties) which share same build.gradle like :

`
dependencies {
    implementation('org.springframework.cloud:spring-cloud-starter-openfeign')
    implementation('org.springframework.cloud:spring-cloud-starter-netflix-ribbon')
    implementation('org.springframework.boot:spring-boot-starter-web')
    implementation('org.springframework.boot:spring-boot-starter-actuator')
    implementation('org.springframework.cloud:spring-cloud-starter-kubernetes:0.3.0.RELEASE')
    implementation('org.springframework.cloud:spring-cloud-starter-kubernetes-ribbon:0.3.0.RELEASE')
    implementation('com.fasterxml.jackson.core:jackson-databind')
    implementation('com.fasterxml.jackson.dataformat:jackson-dataformat-xml')
    implementation('net.logstash.logback:logstash-logback-encoder:4.10')
    implementation('org.springframework.cloud:spring-cloud-starter-netflix-eureka-client')

}
`

eureka:
  client:
    enabled: false

that will disable load the eureka auto configure.
otherwise we need to use below , which is a little bad look.
`
spring:
  autoconfigure:
    exclude: org.springframework.cloud.kubernetes.discovery.KubernetesDiscoveryClientAutoConfiguration
`

just a suggestion

**Comment by geoand** [comment]
Hi @huangered 

Doesn't setting `spring.cloud.kubernetes.enabled` to `false` work?

**Comment by huangered** [comment]
@geoand. It still will load the auto configuration. That cause conflict because that be two discovery clients.

**Comment by geoand** [comment]
How about with `spring.cloud.kubernetes.discovery.enabled=false`?

Note that I am talking about `1.0.0.RELEASE`, not `0.3.0`

**Comment by huangered** [comment]
let me have a try.

**Comment by huangered** [comment]
oh, 1.0.0.RELEASE is released on Jan. 23, congratulation.

after look 1.0.0.RELESE code, the spring.cloud.kubernetes.enabled = false works, i will try to upgrade from 0.3.0 to 1.0.0.RELESE 

thanks @geoand  , that is perfect. i think we can close this issue.

**Comment by geoand** [comment]
You're welcome!

**Comment by matiasah** [comment]
Hello, I'm using Spring Cloud Consul on a dev profile, and Spring Cloud Kubernetes on a prod profile, and even though I disable Kubernetes discovery it errors trying to find a KubernetesClient bean.
