### ISSUE TITLE
spring-cloud-kubernetes-istio plan supports service mesh?

### ISSUE THREAD

**Issue by SoftwareKing** [spring-cloud/spring-cloud-kubernetes#315]
spring-cloud-kubernetes-istio plan supports service mesh?

**Comment by geoand** [comment]
What kind of support do you have in mind @SoftwareKing ?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
