### ISSUE TITLE
Is there a way to bypass Ribbon and request directly by host name, thus make envoy intercept the request and do service discovery and load-balancing in the case of Istio integration.

### ISSUE THREAD

**Issue by idouba** [spring-cloud/spring-cloud-kubernetes#318]
Ribbon get service and ServiceInstance and select a target IP to forward a request to service instance. In case of [kubernetes](https://github.com/spring-cloud/spring-cloud-kubernetes), it is like just replace discovery client from eureka to k8s, and get service instance list from kube-apiserver instead of eureka server. Thus ribbon interpret service name to podIp and send the request.

As for Istio, client side load-balancing should be provided by Envoy, which can do load-balancing for app besides SC based ones. In case of Istio&SpringCloud，it seems that ribbon should be disabled, and use service name directly, that is set the service name in HTTP Host: header will be ok. Is there a recommend config or annotation to do that safely .
And [spring-cloud-kubernetes-istio](https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-istio) is introduced a istio-client to interact with Istio APIs enabling us to discover traffic rules, not what requirement described before.

**Comment by idouba** [comment]
#https://github.com/spring-cloud/spring-cloud-kubernetes/issues/298

**Comment by idouba** [comment]
#https://github.com/spring-cloud/spring-cloud-kubernetes/issues/233
#https://github.com/spring-cloud/spring-cloud-kubernetes/issues/315

**Comment by geoand** [comment]
@spencergibb @salaboy Any comments?

**Comment by spencergibb** [comment]
You can certainly not use ribbon. There is no requirement.

**Comment by idouba** [comment]
@spencergibb Thanks. What's is SC‘s’ officially recommended solution to integrate Istio's data   plane envoy?  The main ideal may looks like this:
![image](https://user-images.githubusercontent.com/6693601/51879214-79b91d80-23ad-11e9-9d50-0b342cec4071.png)

**Comment by spencergibb** [comment]
I mean, not including ribbon and using dns names should just work.

**Comment by salaboy** [comment]
@idouba I remember that I got that working by just adding "http:" to the prefix instead of using "lb" that try to use ribbon. Can you check what is the prefix that you are using>?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by idouba** [comment]
Thanks @spencergibb , I have seen your suggestion of  [Spring Cloud: How to use Feign without Ribbon](https://stackoverflow.com/questions/27620338/spring-cloud-how-to-use-feign-without-ribbon/27659935#27659935 ), and `@FeignClient(url="http://example.com", name="example")` works.
But this require modify every method calling, is there a global method to disable lb and service discovery which infrastructure have provided,  springcloud app just need to call the remote producer microservice by serviceName, as the issue  https://github.com/spring-cloud/spring-cloud-netflix/issues/2801 reffed scenario
