### ISSUE TITLE
Discovery client not finding service instances unless default namespace set

### ISSUE THREAD

**Issue by arahlf** [spring-cloud/spring-cloud-kubernetes#321]
I'm trying to use the KubernetesDiscoveryClient on a cluster running in AKS. When I run:

    List<ServiceInstance> instances = discoveryClient.getInstances("my-service-id");

the list always comes back empty. After stepping through the code I realized it was because the URL it was building up looked like:

    /api/v1/endpoints/my-service-id

which was returning a 404. Playing around with the REST API, I realized the URL needed to have the namespace in it. So once I set this property in my Spring config file:

    spring.cloud.kubernetes.client.namespace=default

Then the URL it built up looked like:

    /api/v1/namespaces/default/endpoints/application-gateway

and my original method call worked as expected.

Is there any reason that the namespace property wouldn't default to "default"?

**Comment by geoand** [comment]
@arahlf Hi.

In my experience, the `default` namespace wouldn't be used all that often in production. It's much better to have separate contexts in separate namespaces were you can apply k8s security policies and others.
So setting the default to `default` might give the wrong impression

**Comment by arahlf** [comment]
Thanks for the reply.

I'm still pretty new to Kubernetes, so I guess I could see that -- I'll need to read up on namespaces more.

In the context of the discovery client being able to identify endpoint subsets, will it ever work or find anything when the namespace is null (as it is by default)? Just curious then if that perhaps should be a required config in that scenario, or under what circumstances that query does work without a namespace.

**Comment by geoand** [comment]
I *think* that the Kubernetes client uses the namespace in which the application is deployed in if no namespace is specified - @iocanel is that correct?

**Comment by arahlf** [comment]
In my case, the app was deployed in the default namespace, and it didn't seem to default to that. Not sure if that's somehow specific to my setup though.

**Comment by iocanel** [comment]
The client will use the "current" namespace unless explicitly specified. Make sure KUBERNETES_NAMESPACE is not breaking things for you.

**Comment by arahlf** [comment]
How does it find/use the current namespace? Is KUBERNETES_NAMESPACE a native Kubernetes thing, or does that come from the Java SDK being used?

**Comment by alvgarvilla** [comment]
Using empty constructor of `io.fabric8.kubernetes.client.AutoAdaptableKubernetesClient` it creates a default `io.fabric8.kubernetes.client.Config` through `io.fabric8.kubernetes.api.model.ConfigBuilder`:

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java#L47

In `io.fabric8.kubernetes.client.Config`, take a look at:

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L280

And 

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L494

**Comment by ryanjbaxter** [comment]
I have been running sc-k8s on minikube using the default namespace and have not seen this problem.  What version are you using?

**Comment by arahlf** [comment]
Ugh... I think what was happening was my deployment wasn't working right... so the instance wasn't actually running in the cluster like I thought, but was running on a machine that had kube config setup to point at the same cluster... so the KubernetesClient still found + used those credentials and the app's KuberentesDiscoveryClient was mostly working, but because it wasn't actually in the cluster like I thought, that's why the namespace wasn't found. Sorry for the confusion!
