### ISSUE TITLE
org.springframework.cloud:spring-cloud-kubernetes:pom:2.1.0.RC1 not found

### ISSUE THREAD

**Issue by jkubrynski** [spring-cloud/spring-cloud-kubernetes#322]
The pom for the starter parent is not released to spring-milestones. Currently, it's impossible to use spring-cloud-starter-kubernetes 2.1.0.RC1

**Comment by ryanjbaxter** [comment]
Spring Cloud Kubernetes is only at 1.0.0, see the releases in GitHub.

**Comment by jkubrynski** [comment]
But in the starter documentation you're mentioning 2.1.0.RC1. It also exists in the spring-milestones repository: https://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-starter-kubernetes/2.1.0.RC1/

**Comment by spencergibb** [comment]
@jkubrynski can you point to the docs where you see this?

**Comment by ryanjbaxter** [comment]
Ah yes, that was a mistake during the Greenwich.RC1 release.  There are no artifacts under that folder.  I cant see a way to delete the folder itself though.  Do see anything in our docs that is pointing you to that location or version?
