### ISSUE TITLE
Cannot Disable KubernetesServiceRegistry Bean Creation

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-kubernetes#325]
There should be a way to disable `KubernetesServiceRegistry` bean from being created.  It should at least be conditional on `spring.cloud.service-registry.auto-registration.enabled` being `true` and conditional on the class `AutoServiceRegistrationProperties`.  But I also think it should have its own kubernetes specific property for disabling the bean so that way you can support having two different service registration implementations on the classpath and only enable one based on deployment scenario.

**Comment by ryanjbaxter** [comment]
See Eureka implementation https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java#L321

**Comment by ryanjbaxter** [comment]
I am a little perplexed now that I am looking deeper into this.  

The class `KubernetesAutoServiceRegistration` which would auto register the client exists but is never used, so in theory the client should never register itself.  But that is apparently not true since clients do appear to register itself and can be discovered by other clients.  Is this just Kubernetes automatically registering the app when deployed?  @salaboy do you have any ideas?

**Comment by spencergibb** [comment]
Yeah, I can't remember why it exists, because the platform does registration. This was one of the reasons to split discovery and registration

**Comment by salaboy** [comment]
@ryanjbaxter yup.. in k8s if you create a service that will be reflected inside DiscoveryClient getServices(). 
That class was already there when I started looking at the project. My gut feeling is that it was created for supporting some edge cases when you run the app outside of the cluster and want to connect, but I am not 100% sure. We should remove it if it doesn't have a concrete use case.

**Comment by spencergibb** [comment]
Can't remove until a major release, but we can deprecate

**Comment by salaboy** [comment]
please do :)

**Comment by ryanjbaxter** [comment]
@spencergibb so in reality the property `spring.cloud.service-registry.auto-registration.enabled` is going to have no effect in Kubernetes

**Comment by spencergibb** [comment]
We can certainly make it disable the bean.

**Comment by ryanjbaxter** [comment]
> We can certainly make it disable the bean.

But that does't do what the property says it does.  It should stop the service from automatically registering with the service discovery service but as soon as a service is created for the app in Kubernetes it is registered, other services could now discover the service.  In essence the app has no control over whether it is registered or not.  Maybe the app could unregister itself?  @salaboy do you know?

In any case to the original point of this issue, I can seem to get things working by simply setting `spring.cloud.kubernetes.enabled=false` but this not only disables the `DiscoveryClient` but everything.  I think we probably want a more fine grained property that would just disable the discovery client autoconfig.

**Comment by spencergibb** [comment]
We can't prevent registration because it is a function of the platform, not spring cloud. Similar to CF.

**Comment by ryanjbaxter** [comment]
Right that is what I was saying above, so `spring.cloud.service-registry.auto-registration.enabled` seems like a useless property in this case

**Comment by spencergibb** [comment]
I see. :+1:

**Comment by ryanjbaxter** [comment]
I am going to close this for now as I think `spring.cloud.kubernetes.enable` is good enough at the moment for disabling the service registry bean.  The `KubernetesServiceRegistry` implementation infact does not do much so having it enabled does not really have any effect anyways, and I cannot come up with a use case where you specifically want to disable this bean while leaving the rest of the kubernetes functionality enabled.

I will create a separate documentation issue about `spring.cloud.service-registry.auto-registration.enabled` having no effect in Spring Cloud Kubernetes.
