### ISSUE TITLE
Add spring cloud kubernetes to properties appendix 

### ISSUE THREAD

**Issue by MichalFoksa** [spring-cloud/spring-cloud-kubernetes#330]
Can you PLS create a documentation of all possible application properties? 

I.e. something like: [Appendix A. Common application properties](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) from Spring documentation.

PS: Spring Cloud Kubernetes is very helpful - thumbs up!

**Comment by spencergibb** [comment]
It should be a part of it, is it not?

**Comment by MichalFoksa** [comment]
It is not. 

Try to search in  [Appendix A. Common application properties](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) for e.g.: `spring.cloud.kubernetes`

**Comment by spencergibb** [comment]
Sorry on mobile

**Comment by spencergibb** [comment]
We don't put them with boot, but with the spring cloud docs

**Comment by spencergibb** [comment]
https://cloud.spring.io/spring-cloud-static/Greenwich.RELEASE/multi/multi__appendix_compendium_of_configuration_properties.html

**Comment by MichalFoksa** [comment]
Thank you! I did not find these - there is a a lot of stuff.

Anyway: `spring.cloud.kubernetes` is not there :(

**Comment by MichalFoksa** [comment]
@spencergibb thanks!

**Comment by ryanjbaxter** [comment]
This should be fixed by https://github.com/spring-cloud-samples/scripts/commit/1a044f978b47addb0e8d8bd1987d33db88b9b757
