### ISSUE TITLE
Configuration Not Refreshed After Some Period Of Time When Running On GKE

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-kubernetes#331]
After a while a container running on GKE stops refreshing configuration data from config maps.  Once I kill the pod and recreate it, refresh starts working again.  

Here is the deployment for the app
https://github.com/ryanjbaxter/chaos-monkey-spring-boot-demo/blob/spring-cloud-kubernetes/bestseller-toys/bestseller-toys-deployment.yml

Here is the config map 
https://github.com/ryanjbaxter/chaos-monkey-spring-boot-demo/blob/spring-cloud-kubernetes/bestseller-toys/configmap.yml

Let it run for a while (unsure how long, but a day seems to be enough time) and then change `chaos.monkey.enabled` to `true` and you will not see the change when you hit `/actuator/env`.

**Comment by JKerwood** [comment]
+1

**Comment by JKerwood** [comment]
My problem was the version of io.fabric8.kubernetes-client.  I needed to upgrade due to the version of my k8s cluster https://github.com/fabric8io/kubernetes-client#compatibility-matrix  After upgrade my watch worked even after needing a reconnect of the socket.
