### ISSUE TITLE
Kubernetes discovery not usable with multi-port services

### ISSUE THREAD

**Issue by jkubrynski** [spring-cloud/spring-cloud-kubernetes#341]
I've checked the #104 but it wasn't in fact resolved. I can define ports in metadata, however, all load balancers are using the port from the `ServiceInstance.getPort` method. If we have more than one port it works randomly. The solution would be to specify the `name` of the `default` port, which will be used if more than one port is defined for a given service. Current implementation looks like that `s.getPorts().stream().findFirst().orElseThrow(IllegalStateException::new)`

I can submit a PR if you'd decide it's a valid solution.

**Comment by ryanjbaxter** [comment]
Yes would love a PR
