### ISSUE TITLE
Optionally return Kubernetes services instead of service instances by getInstances().

### ISSUE THREAD

**Issue by MichalFoksa** [spring-cloud/spring-cloud-kubernetes#344]
Is there a interest in feature where `KubernetesDiscoveryClient.getInstances(String serviceId)` optionally returns Kubernetes services instead of service instances (made of EndpointAddress and EndpointPort) as it is now?

This approach is beneficial:
- when client load balancing is not needed/wanted.
- it allows [`ExternaName` type of Services](https://kubernetes.io/docs/concepts/services-networking/#externalname) discovery. They do not have any instance, hence they are not discoverable at the moment.

      kind: Service
         apiVersion: v1
      metadata:
        name: my-service
        namespace: prod
      spec:
        type: ExternalName
        externalName: my.database.example.com

-  Namespace would be a property of returned "service instance", hence allowing to build service uri in format `{servicename}.{namespace}.svc.cluster.local`, hence helping to fix issue with SSL validation: #278 .

Switch between returning service instance and service itself would be configurable.

Link to [implementation draft](https://github.com/MichalFoksa/demo-swagger-aggregator/blob/65b212018346485e2963bb822b3734e5a08e26d0/src/main/java/net/michalfoksa/cloud/kubernetes/discovery/KubernetesServiceDiscoveryClient.java#L78). 

Example how instance could look like. `bodyshop` and `paintshop` are Kubernetes services and `bodyshop-link` is `ExternalName` type service. Metadata is union of labels and annotation as it is already now.

    [{
        "type": "ClusterIP",
        "name": "bodyshop",
        "namespace": "jx-staging",
        "clusterIP": "10.31.254.82",
        "externalName": null,
        "secure": false,
        "metadata": {
            "port.http": "80",
            "fabric8.io/expose": "true",
            "chart": "bodyshop-0.0.2",
            "fabric8.io/exposeUrl": "http://bodyshop.jx-staging.jx-e1.cp1.michalfoksa.net",
            "fabric8.io/ingress.annotations": "kubernetes.io/ingress.class: nginx"
        },
        "instanceId": "jx-staging/bodyshop",
        "serviceId": "bodyshop",
        "uri": "http://10.31.254.82:80",
        "host": "10.31.254.82",
        "port": 80,
        "scheme": null
    },{
        "type": "ClusterIP",
        "name": "paintshop",
        "namespace": "jx-staging",
        "clusterIP": "10.31.254.147",
        "externalName": null,
        "secure": false,
        "metadata": {
            "port.http": "80",
            "fabric8.io/expose": "true",
            "chart": "paintshop-0.0.2",
            "fabric8.io/exposeUrl": "http://paintshop.jx-staging.jx-e1.cp1.michalfoksa.net",
            "fabric8.io/ingress.annotations": "kubernetes.io/ingress.class: nginx"
        },
        "instanceId": "jx-staging/paintshop",
        "serviceId": "paintshop",
        "uri": "http://10.31.254.147:80",
        "host": "10.31.254.147",
        "port": 80,
        "scheme": null
    },{
    
        "type": "ExternalName",
        "name": "bodyshop-link",
        "namespace": "jx-staging",
        "clusterIP": null,
        "externalName": "bodyshop.jx-staging.svc.cluster.local",
        "secure": false,
        "metadata": {
            "port.http": "80"
        },
        "serviceId": "bodyshop-link",
        "uri": "http://bodyshop.jx-staging.svc.cluster.local:80",
        "instanceId": "jx-staging/bodyshop-link",
        "host": "bodyshop.jx-staging.svc.cluster.local",
        "port": 80,
        "scheme": null
    }]

**Comment by geoand** [comment]
Hi @MichalFoksa ,

I see this could make sense. How do you envision that it would apply to certain services and not others?

**Comment by MichalFoksa** [comment]
Hi @geoand ,

My idea at the moment is all or nothing. Either you receive instances, or services.

**Comment by geoand** [comment]
Thats sounds good to me @MichalFoksa. @salaboy any thoughts?

**Comment by salaboy** [comment]
Hmm... I will need to think about this.. and I can see that @spencergibb marked this for team discussion.. so I think that we need to discuss this further.

**Comment by nickbr23** [comment]
I've been playing around with SCK for a few days now and I've found that the discovery mechanism works perfectly when running without Istio, but when running with Istio it returns 404s.

I'm currently having to bypass the discovery client and pass in kubernetes service information to get it working with Istio.

If we can get the kubernetes services back from the discovery client then it'd work perfectly.

https://github.com/IBM/spring-cloud-kubernetes-with-istio sums it up really well.

**Comment by spencergibb** [comment]
@nickbr23, yes we are well aware of that doc.

**Comment by germm** [comment]
TLS Hostname verification issue can be solved if `KubernetesServerList` and `KubernetesServiceInstance` could be configured to use the pod hostname instead of the IP:

`<pod-ip-dashed>.<namespace>.pod.cluster.local`

See  also [comment for issue 275](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/278#issuecomment-478294275)

**Comment by spencergibb** [comment]
I think we're ok making this an option.

**Comment by ryanjbaxter** [comment]
closed via f0eab0e
