### ISSUE TITLE
Profile Specific Configuration Not Loaded

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-kubernetes#347]
In my add I have some kubernetes specific configuration contained within a file called `application-kubernetes.yml`.  When I deploy my app in minikube the configuration from this file is not loaded, even though the `kubernetes` profile appears to be enabled.

If however I specify the `kubernetes` profile as an environment variable in my `deployment.yml` then the configuration appears to loaded fine.

You can use this deployment file to reproduce the problem.
https://github.com/ryanjbaxter/chaos-monkey-spring-boot-demo/blob/spring-cloud-kubernetes/bestseller-toys/bestseller-toys-deployment.yml

If you deploy that and then go to `/actuator/env` you will see the `kubernetes` profile enabled and you should see properties coming from `application-kubernetes.yml`.

If you then remove the `env` properties in that deployment and then deploy the application again and again hit `/actuator/env` you will still see the `kubernetes` profile enabled, but the properties from `application-kubernetes.yml` will not be added.

**Comment by geoand** [comment]
I was able to reproduce this issue.
So the gist is that although Spring Cloud Kubernetes properly adds the `kubernetes` profile, this profile seems to have no effect on the properties being loaded.

One can also easily reproduce this without having to have the application deployed on Kubernetes, simply change `KubernetesProfileApplicationListener#addKubernetesProfile` to:

```
	void addKubernetesProfile(ConfigurableEnvironment environment) {
		environment.addActiveProfile(KUBERNETES_PROFILE);
	}
```

Is there some Spring Boot thing that we need to be doing in to get the profile to have an effect on which files will be used to load properties?

**Comment by spencergibb** [comment]
Is it an ordering issue maybe?

**Comment by geoand** [comment]
That's as my first as well but when I tried to change the order value it didn't have any effect

**Comment by ryanjbaxter** [comment]
I had a breif conversation with @philwebb about this yesterday and he suggested

> Phillip Webb [2:33 PM]
Looking at `ConfigFileApplicationListener.initializeProfiles` I think Boot should find it. Try debugging `getOtherActiveProfiles` and check that it actually finds it
@rbaxter It might be an ordering issue. I think your listener should be fine, but worth sticking a couple of breakpoints in `KubernetesProfileApplicationListener` and `ConfigFileApplicationListener` to make sure

I had not had a chance to try it though

**Comment by geoand** [comment]
I'll give it a go tomorrow

**Comment by geoand** [comment]
OK, so here is what I got:

`getOtherActiveProfiles` get's called in `ConfigFileApplicationListener#initializeProfiles`, which itself executes when the `ApplicationEnvironmentPreparedEvent` event is fired.

However at that point none of the listeners have executed. The initializers get executed as part of `SpringApplication.prepareContext`.
So is what we are trying to do unsupported by Spring Boot or is there perhaps some other feature we should be using?

**Comment by spencergibb** [comment]
Environment post processor?

**Comment by geoand** [comment]
I'll give it a shot
