### ISSUE TITLE
spring.cloud.service-registry.auto-registration.enabled has no impact in Spring Cloud Kubernetes

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-kubernetes#348]
Since registration of a service is controlled by the platform in Kubernetes, setting `spring.cloud.service-registry.auto-registration.enabled` has no impact un this case.  We should document this.

**Comment by javendo** [comment]
Does the same thing happens with the serviceName? I mean, it doesn't matter if I have added the spring.application.name property, in the end it will get the service name. Is it right?

**Comment by ryanjbaxter** [comment]
I believe that is true

**Comment by javendo** [comment]
Is there any plan to allow us to control the serviceName it will be registered? If not, I think it should be added in the docs like it was done for autoregistration enable.

**Comment by spencergibb** [comment]
How can this project control what was registered to kubernetes?

**Comment by ryanjbaxter** [comment]
You can control the service name that gets registered, it uses the service name in your deployment file when you deploy the app to kubernetes.  We should probably document that `spring.application.name` has no effect on this though. https://github.com/spring-cloud/spring-cloud-kubernetes/issues/354
