### ISSUE TITLE
restart-context at same time 

### ISSUE THREAD

**Issue by bestpayAmes** [spring-cloud/spring-cloud-kubernetes#350]
when configmap changes, applicationcontext of all application instance will restart;
this will be a disaster;because this time will doesn't have service;

**Comment by geoand** [comment]
Hi @bestpayAmes 

That is actually a very good comment. @spencergibb @iocanel should we add some random wait time before restarting the context in order to lower the chance of all instances being down at the same time?

**Comment by spencergibb** [comment]
The application context shouldn't be restarting

**Comment by geoand** [comment]
WDYM @spencergibb? We restart the context when we detect a configmap change in order to apply config changes.

**Comment by bestpayAmes** [comment]
@spencergibb do you mean  only REFRESH can be used ; RESTART_CONTEXT and SHUTDOWN can not be used? why do you provider these two strategy?

**Comment by spencergibb** [comment]
If we're restarting the context that needs to change. Refresh is available and it doesn't need to restart.

**Comment by geoand** [comment]
The default strategy is `ReloadStrategy.REFRESH`.
However the concern raised by this issue is still valid IMHO. Even if refresh takes 0.5 seconds, it's still possible for it to happen at roughly the same time for all instances of the running app.
That's why I propose we add a random wait time (with a configurable max) in order to be able to spread out the refreshes

**Comment by spencergibb** [comment]
We've not had this come up before with any other configuration services. If we are refreshing or restarting the context, we shouldn't.

**Comment by spencergibb** [comment]
Looking at where that constant is used, refresh doesn't mean refreshing the application context it means clear refresh scope and rebind config properties. This shouldn't cause delays.

**Comment by spencergibb** [comment]
I think it's ok to add an enhancement for a configurable random wait for the restart case. Default to a second or two.

**Comment by geoand** [comment]
I can do this :)
