### ISSUE TITLE
Enable Kubernetes Discovery Client for Spring Cloud Vault at Bootstrap Stage

### ISSUE THREAD

**Issue by vxavictor513** [spring-cloud/spring-cloud-kubernetes#353]
The current bootstrap logic only configure discovery client for Spring Cloud Config. This is to add support for Spring Cloud Vault.

**Comment by ryanjbaxter** [comment]
Coming back to this, I dont think this belongs in this repo, is it specific to Spring Cloud Kubernetes in any way?  Seems like this is a general Spring Cloud Config request.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
