### ISSUE TITLE
KubernetesDiscoveryClientAutoConfiguration should enable Scheduling

### ISSUE THREAD

**Issue by germm** [spring-cloud/spring-cloud-kubernetes#385]
The scheduled Method `catalogServicesWatch()` in `KubernetesCatalogWatch` is not executed if the Annotation `@EnableScheduling` is not explicitly set by the user. This was alerady part of the discussion in #254 

IMHO, the `KubernetesDiscoveryClientAutoConfiguration` should enable Scheduling unless kubernetesCatalogWatch is disabled by the user.

**Comment by ryanjbaxter** [comment]
We don't have any precedence for adding `@EnableScheduling` as part of auto configuration in other Spring Cloud projects or in Spring Boot itself as far as we can see.  If there are other `@Scheduled` annotations in the app I wouldn't expect those to automatically be scheduled just because Spring Cloud Kubernetes is on the classpath.  We should however at the very least document the fact that it is needed in order to make the functionality work.

**Comment by germm** [comment]
Many thanks for your answer. Mentioning the fact in the documentation makes the situation better.

I understand your reason for not automatically enable scheduling but a search for `EnableScheduling` shows that this is not consequently handled this way. The following auto configurations do enable scheuduling:
- [ConfigReloadAutoConfiguration](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigReloadAutoConfiguration.java)
- [HystrixStreamAutoConfiguration](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-hystrix-stream/src/main/java/org/springframework/cloud/netflix/hystrix/stream/HystrixStreamAutoConfiguration.java)

**Comment by spencergibb** [comment]
I'll argue those are the exceptions and should probably be removed.

**Comment by ryanjbaxter** [comment]
`ConfigReloadAutoConfiguration` is only enabled if `spring.cloud.kubernetes.reload.enabled` is set to true so it is not on by default.  We should probably remove `@EnableScheduling` from that class as well.

**Comment by joshiste** [comment]
Did you thought about not relying on the `@Scheduled` at all? Imho a single threaded task scheduler for the `KubernetesCatalogWatch` would do the job and doesn't require any other condfigurations, or further steps from the developer... and no update to the documentation...
