### ISSUE TITLE
An error occurred when applying k8s in spring boot admin

### ISSUE THREAD

**Issue by hero-zhanghao** [spring-cloud/spring-cloud-kubernetes#386]
I followed the spring boot admin example [(Spring Boot Admin with Spring Cloud Kubernetes Discovery and Config)](https://github.com/salaboy/showcase-admin-tool) in the document to change the existing project.When started in minkube, get the following exception:

![image](https://user-images.githubusercontent.com/16066564/55717609-45588200-5a2c-11e9-932c-420e96cadff4.png)

I don't know what I did wrong, I didn't start the project about the need for certificate

**Comment by hero-zhanghao** [comment]
This situation seems to be caused by reading the default kubernetes service. Is there any way to avoid it?

**Comment by hero-zhanghao** [comment]
Another problem is that inside spring boot admin, from time to time when accessing actuator service, 401 error will appear, and sometimes retry will be improved, like this:

![image](https://user-images.githubusercontent.com/16066564/55719719-7edfbc00-5a31-11e9-9323-ec2bebea1853.png)

![image](https://user-images.githubusercontent.com/16066564/55719738-8c954180-5a31-11e9-895b-7401e943e3f4.png)

**Comment by spencergibb** [comment]
You know we don't maintain spring boot admin?

**Comment by hero-zhanghao** [comment]
I know, but I think this is not the problem of spring boot admin. On the original environment, there is no problem with eureka. The above problem only appears after being transferred to the environment of k8s

**Comment by geoand** [comment]
Perhaps @salaboy has some insight? It was his getting started that was used after all :)

**Comment by spencergibb** [comment]
Can you please paste the stack trace, not an image of it?

**Comment by spencergibb** [comment]
Now that I can see stack trace image, it's an ssl error. Not sure what spring cloud kubernetes has to do with it.

**Comment by geoand** [comment]
I don't understand which part of the code is making the call, it is certainly not Spring Cloud Kubernetes since the client doesn't use Netty.

**Comment by hero-zhanghao** [comment]
I think it's reading into Kubernetes and turning on the SSL service.
![image](https://user-images.githubusercontent.com/16066564/55769155-4f24c880-5ab2-11e9-9e8c-6605ffc13cbf.png)
In my minikube environment, there is a service named Kubernetes. It should be returned by the spring cloud Kubernetes DiscoveryClient. Up to now, I think this is the problem of spring boot admin. Admin should filter out the project that does not belong to spring boot

**Comment by spencergibb** [comment]
Spring Cloud Kubernetes has a way to filter. On mobile, but you can look in docs.

**Comment by hero-zhanghao** [comment]
I tried to find the document you said, but I didn't find it. Can you give me some help? 
thanks

**Comment by spencergibb** [comment]
Tomorrow. You can filter by Kubernetes labels

**Comment by geoand** [comment]
You can try and play with:

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryProperties.java#L47

or 

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/43078596907a92c6b7a6fe2466c029aaa145e336/spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryProperties.java#L61

**Comment by hero-zhanghao** [comment]
Thank you very much. I will try to use this configuration. Better yet, it is described in the documentation
