### ISSUE TITLE
KubernetesServerList Not Working With Telepresence

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-kubernetes#390]
Fair warning this issue with be sparse with details, I need to dig into the issue some more.

I am running an app using Spring Cloud Gateway and Spring Cloud Kubernetes with Ribbon in Kubernetes.  I want to swap out the pod running in kubernetes with an instance of the app runnning locally using Telepresence 

https://www.telepresence.io/tutorials/intellij

When I do this and the Gateways tries to proxy requests to services running in Kubernetes it seems like `KubernetesServerList` is returning servers with incorrect IP addresses.  I suspect it is something with the Fabric8io kubernetes client and how it should be configured to work with Telepresence but I am not sure exactly what yet

**Comment by shawnliujw** [comment]
same issue here

**Comment by ryanjbaxter** [comment]
@shawnliujw it is actually not an issue at all.  SC K8S is returning the POD IP address instead of the service IP address.  There is an issue open to allow the user to configure the service discovery client to use the service IP addresses instead https://github.com/spring-cloud/spring-cloud-kubernetes/issues/344.  

To make things work I needed to tell Telepresence to also proxy IP addresses within the range of the pods, so something like `telepresence --also-proxy 172.17.0.0/24 --mount /tmp/known --swap-deployment gateway --env-json gateway_env.json`.

What I think I would like to do is add a module, something like devtools, that would take care of some of these gotchas when using Telepresence.  Something that would automatically apply environment variables and properly configure the Fabric8io client under the covers.
