### ISSUE TITLE
Ribbon logging too much

### ISSUE THREAD

**Issue by Alos** [spring-cloud/spring-cloud-kubernetes#393]
After adding:

```
<dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-kubernetes-ribbon</artifactId>
</dependency>
```
Services continuously log:

`"Did not find any endpoints in ribbon in namespace...."` continuously while the application is running in my K8s cluster.

**Comment by ryanjbaxter** [comment]
What version?  Is everything working other than the logging?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Alos** [comment]
We are using Spring Cloud Greenwich.RELEASE

**Comment by spencergibb** [comment]
Can you post samples of the full log statements?

> Is everything working other than the logging?

Have you tried tuning the logging for ribbon?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Alos** [comment]
The log statement:

`2019-06-21 17:57:41.237  WARN [artifact-service,,,] 1 --- [erListUpdater-0] o.s.c.k.ribbon.KubernetesServerList: Did not find any endpoints in ribbon in namespace [<my namespace>] for name [localhost] and portName [null]`

Everything else appears to work ok. I've tried to add: 

```org.springframework.cloud.kubernetes.ribbon.KubernetesServerList: OFF```

in my `application.yaml`

I've tried with other logging levels too.

**Comment by spencergibb** [comment]
You're saying you've tried setting log levels and it is not working?

**Comment by Alos** [comment]
Yes, but upon further inspection. It looks like the class logging this is `KubernetesEndpointsServerList` not `KubernetesServerList`

**Comment by spencergibb** [comment]
`KubernetesEndpointsServerList` does not exist in Greenwich.

**Comment by spencergibb** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by Alos** [comment]
You are right I've fixed the issue by correctly setting the logging level to `ERROR`:

```YAML
logging:
  level:
    org.springframework.cloud.kubernetes.ribbon.KubernetesServerList: ERROR
```

I just hope I'm not masking another issue.
