### ISSUE TITLE
Service-to-service integration with Google Cloud Run

### ISSUE THREAD

**Issue by wer-mathurin** [spring-cloud/spring-cloud-kubernetes#417]
The use case is when we want to enable service-to-service security. When Cloud Run is call from another service running inside kubernetes, you must get a token before calling the service, like this:

`var receivingURL = "THE URL OF THE CLOUD RUN";`
`var url = "http://metadata/computeMetadata/v1/instance/service-accounts/default/identity?audience=";`

`var token = client.build().get().uri(url+receivingURL).header("Metadata-Flavor", "Google").retrieve().bodyToMono(String.class);`

`var mono= token.flatMap( t -> client.build().get().uri(receivingURL).header("Authorization", "Bearer " + t).retrieve().bodyToMono(String.class));`

From a development perspective, we would like to use the DiscoveryClient wonderful capability but, be able to add the needed header  by configuration, only when running inside Kubernetes.  Any ideas to prevent adding this extra code in the code, because this is not needed when running locally!

Potential solution:
1) Add Kubernetes configuration to be able to apply a filter only when running inside Kubernetes (a running POD)

`public class ExampleHandlerFilterFunction implements HandlerFilterFunction<ServerResponse, ServerResponse> {`

`@Override
public Mono<ServerResponse> filter(ServerRequest serverRequest, HandlerFunction<ServerResponse> handlerFunction) {`

`var receivingURL = "YOUR GOOGLE CLOUD RUN URL";`
`var url = "http://metadata/computeMetadata/v1/instance/service-accounts/default/identity?audience=";`
            	
`final WebClient.Builder builder = WebClient.builder();`
`var token = builder.build().get().uri(url+receivingURL).header("Metadata-Flavor", "Google").retrieve().bodyToMono(String.class);`

`var newRequest = ServerRequest.from(serverRequest);`
`return token.flatMap(t-> handlerFunction.handle(newRequest.header("Authorization", "Bearer " + t).build()));`
`return handlerFunction.handle(serverRequest);`
`}`

**Comment by geoand** [comment]
Hi,

I would suggest taking a look at:
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/35f4e1f94e0a05663a833d85eae2f6d5736883a2/spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/KubernetesHealthIndicator.java#L41

to see how to determine whether the application is running inside the
cluster or not.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by wer-mathurin** [comment]
Maybe I was not enough clear on what kind of enhancement I was looking for.  

There is two flavors of Google Cloud Run.  My problem is with the one not running inside my "own" managed kubenertes cluster.  The DiscoverClient can't work because it does not registered itself inside the cluster since is not in the **my** cluster but a Google managed one.  

I was just wondering if it was possible to simplify the developer experience by hiding branching logic when I'm running the code locally on the developer workstation and when it run on production.  For now we are using @Profile to activate the filter to rewrite the original request.  But maybe is more related to GCP specifics stuff rather than Kubernetes.  Maybe adding something like @EnableCloudRun(name="NAME_OF_CLOUD_RUN").  So the starter can add logic to detect if it run locally or not and add the security filter when require (this can be specify in a application.yml, something like => google.cloud.run.public = false)

**Comment by spencergibb** [comment]
So far we've tried to shy away from doing things for specific flavors of k8s such as open shift. Not sure how different this would be. I still don't understand what is different.

**Comment by wer-mathurin** [comment]
Another clarification on my side !  We are calling the Cloud Run entry-point from another Kubernetes cluster.  

When the service deployed on Cloud Run is not public, you need to add a Bearer token to the header.  That's why we need to tell **the calling** service in our case to add the header "only" when the calling service is running "inside" a real cluster, because the header is not require when running locally.  That's why in the original post I was wondering If we can add a filter base on "running inside kubernetes".  And this is not tie to any flavor of k8s.

**Comment by ryanjbaxter** [comment]
So couldnt you do something based on when the `kubernetes` profile is enabled?

**Comment by wer-mathurin** [comment]
Thx for your reply.  Very good idea.  The component(filter) will be
register only when this profile is enable.  So this cover 50% of what need
to be done.  The other part is the name of the service is different when
running in development mode and in production.

**Comment by ryanjbaxter** [comment]
@spencergibb would this be something that maybe can be included in the cloud specific projects?

**Comment by wer-mathurin** [comment]
The core concept to generalize is how we can facilitate Multi Cloud code
development.  The initial thread is only one use case.
Another use case can be.  I have a service A deploy to Cloud Foundry and a
service B deployed to Google Cloud Run. And the service B need to call
service A.

**Comment by spencergibb** [comment]
I still am not quite sure what your filter that you mention does. Maybe you could post or describe exactly what it does.

Most spring cloud libraries are purpose built for a specific technology, in this case, k8s. Spring Cloud commons is the place where any abstraction across platforms would live.

**Comment by wer-mathurin** [comment]
The filter I was talking is specific to Google, so not right for an
abstraction...I totally agree.  And using the @Profile annotation does the
job.  FYI : The filter is adding a header with a bearer token, and this is
only needed when running into production.  Because when the Service_B* is
running locally (not deployed in a cluster) it does not have the security
constraint*, it is only a basic Spring Boot application.

But applying the filter was only 50% of the problem.

The other "ugly" thing happen when:
Service_B need to call Service_A.

Let use a simple example:

This work like a charm with  @EnableDiscoveryClient  when everything is
running inside the *same *Kubernetes Cluster:
webClient.uri("https://Service_A/something")

But not when the Service_A is running in a different cluster than the
Service_B.
So as a developer, I need to add some branching logic when we need to call
Service_B.

If ( runningInsideKubernetes ){

client = *WebClient.builder()*.build().uri("
https://THE_SERVICE_A_PUBLIC_ADDRESS/something")  // If @EnableDiscoveryClient
is enable we can't use the bean (because it will not find the service)

} else{

*builder*.build().uri("https://Service_A/something") // If
@EnableDiscoveryClient
is enable we can use the bean ( it will find the service)

}

I hope it clarify the problem.

**Comment by ryanjbaxter** [comment]
I dont see federating services across clusters as being a concern of Spring Cloud K8S, that seems more like a platform concern.
