### ISSUE TITLE
KubernetesProfileEnvironmentPostProcessor should be conditional on spring.cloud.kubernetes.enabled

### ISSUE THREAD

**Issue by stefanocke** [spring-cloud/spring-cloud-kubernetes#420]
Several configuration classes like KubernetesAutoConfiguration and KubernetesDiscoveryClientAutoConfiguration are condtional on spring.cloud.kubernetes.enabled.
This allows to "switch off" kubernetes client completely in non-k8s environments.

But, KubernetesProfileEnvironmentPostProcessor is currently not conditional.
So, it always runs and for example creates a DefaultKubernetesClient which in turn can lead to k8s-related warnings,  for example in **io.fabric8.kubernetes.client.Config.tryServiceAccount**

In my case, I have seen the following:
```
Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
```

It would be nice to have KubernetesProfileEnvironmentPostProcessor  conditional on spring.cloud.kubernetes.enabled, too,  to avoid that kind of warnings in non-k8s enironments.

**Comment by geoand** [comment]
Thanks for opening the issue.

Can you please provide the entire log line? 
I am thinking perhaps we need to change the logging level since I don't think we can't really turn off the post processor

**Comment by stefanocke** [comment]
@geoand , the complete message is the one above.  It is from  io.fabric8.kubernetes.client.Config.tryServiceAccount.

I think, the logging level there is quite appropriate.  (And btw, it is not in spring-cloud-kubernetes anyway.)  
Why not to turn off the PostProcessor in a situation where Kubernetes Client shall be switched off completely?

**Comment by geoand** [comment]
@stefanocke yeah, makes sense. I opened #421
