### ISSUE TITLE
Kubernetes Discovery Client Catalog watch not enabled

### ISSUE THREAD

**Issue by Incarnation-p-lee** [spring-cloud/spring-cloud-kubernetes#431]
Is there any way to learn what is the interval time of Discovery client heartbeat ? As well as how to configure it.

**Comment by Incarnation-p-lee** [comment]
After some investigation, it looks that the catalogWatch with `@Scheduled` is not working due to there is
not `@EnableScheduling` from DiscoveryClient AutoConfiguration. Could you please help to confirm this issue ? And then I can file one PR for this.

As well as related [issue](https://github.com/spring-cloud/spring-cloud-gateway/issues/1182) from spring cloud gateway.

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/abbe91a91fccfedd1f40d6eda46c3f0fbe7d8013/spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatch.java#L61

**Comment by ryanjbaxter** [comment]
From the docs 

> Spring Cloud Kubernetes can also watch the Kubernetes service catalog for changes and update the DiscoveryClient implementation accordingly. In order to enable this functionality you need to add @EnableScheduling on a configuration class in your application.

Duplicates #385

**Comment by Incarnation-p-lee** [comment]
So the default behavior is different with eureka discovery client, right ? It is by design or some reason backend ?

**Comment by ryanjbaxter** [comment]
It is an implementation detail

**Comment by Incarnation-p-lee** [comment]
OK. I see. Thanks a lot.
