### ISSUE TITLE
about serviceAccount for configmap

### ISSUE THREAD

**Issue by damon008** [spring-cloud/spring-cloud-kubernetes#442]
Hi, about serviceAccount, I want to ask how to use configmap if the env of k8s not contains serviceAccount?

**Comment by geoand** [comment]
Hi,

ServiceAccount does not have anything to do with env vars. I propose you read the Kubernetes documentation which although large, does a great job at making all the concepts clear

**Comment by damon008** [comment]
@geoand how to understand this:
--
You should check the security configuration section. To access config maps from inside a pod you need to have the correct Kubernetes service accounts, roles and role bindings.
--

**Comment by geoand** [comment]
The Kubernetes security fundamentals can be a little daunting, but TBH, one really needs to go through the docs and understand the fundamentals. There is just know way around that - same as any other complex system 🙂

**Comment by damon008** [comment]
@geoand  cloud not understand what you say.what you say is not I want

**Comment by geoand** [comment]
My point is that you really need to understand the Kubernetes Security primitives first

**Comment by damon008** [comment]
Our k8s server env: server: http://10.10.1.5:8080，not set ServiceAccount, so depend spring-cloud-starter-kubernetes-config, one error:
...
2019-08-02 05:40:13.369  WARN 1 --- [           main] io.fabric8.kubernetes.client.Config      : Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
'''

**Comment by damon008** [comment]
How to solve ?
2019-08-02 05:40:13.369 WARN 1 --- [ main] io.fabric8.kubernetes.client.Config : Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.

**Comment by geoand** [comment]
If that happens when you run locally, then it's not a problem. It's basically saying that it didn't find the Service Account token in the expected location - which will obviously happpen if you are running locally and not in a proper Kubernetes cluster

**Comment by damon008** [comment]
it's not a problem？
then, how to get config infos from configmap?
Do you know what I mean?
...

2019-08-02 07:27:43.313  WARN 1 --- [           main] io.fabric8.kubernetes.client.Config      : Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
2019-08-02 07:27:43.315  WARN 1 --- [           main] io.fabric8.kubernetes.client.Config      : Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
2019-08-02 07:27:43.316  WARN 1 --- [           main] o.s.c.k.KubernetesAutoConfiguration      : No namespace has been detected. Please specify KUBERNETES_NAMESPACE env var, or use a later kubernetes version (1.3 or later)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.6.RELEASE)

2019-08-02 07:27:43.546  WARN 1 --- [           main] o.s.c.k.config.ConfigMapPropertySource   : Can't read configMap with name: [springcloudk8sconfigdemo] in namespace:[null]. Ignoring

....

**Comment by damon008** [comment]
@geoand get null ,You know?

**Comment by damon008** [comment]
@geoand  How to solve this for I can get some msg, not null from configmap?

**Comment by damon008** [comment]
2019-08-02 07:27:43.546 WARN 1 --- [ main] o.s.c.k.config.ConfigMapPropertySource : Can't read configMap with name: [springcloudk8sconfigdemo] in namespace:[null]. Ignoring

**Comment by geoand** [comment]
I suggest you take a look at:

https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-integration-tests/simple-configmap

and 

https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-examples/kubernetes-reload-example

**Comment by damon008** [comment]
@geoand  Because of our k8s cluster  env maybe not same,whether or not be useful what you say?

**Comment by geoand** [comment]
It's hard to tell with the given information. I suggest that you take it step by step following the two small examples I added above

**Comment by damon008** [comment]
My configmap :
kind: ConfigMap
apiVersion: v1
metadata:
  name: springcloudk8sconfigdemo
data:
  application.yml: |-
    greeting:
      message: Say Hello to the World
    farewell:
      message: Say Goodbye
    ---
    spring:
      profiles: dev
    greeting:
      message: Say Hello to the Developers
    farewell:
      message: Say Goodbye to the Developers
    ---
    spring:
      profiles: test
    greeting:
      message: Say Hello to the Test
    farewell:
      message: Say Goodbye to the Test
    ---
    spring:
      profiles: prod
    greeting:
      message: Say Hello to the Prod
    farewell:
      message: Say Goodbye to the Prod

I want to get greeting.message in dev, Always get null , not "Say Hello to the Developers" in my k8s cluster env.

**Comment by damon008** [comment]
@geoand  Do you know what is the reason of my configmap not be found? I feel what you provided can not solve my question.

**Comment by geoand** [comment]
I do not, sorry.
I suggest to remove the profiles, get it to work that way and move from there

**Comment by damon008** [comment]
What you provided:
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-integration-tests/simple-configmap/src/main/fabric8/deployment.yml

I can not understand this ,why,and this test can be useful?

**Comment by damon008** [comment]
My log:
2019-08-02 08:59:01.698  WARN 1 --- [pool-1-thread-1] o.s.c.k.config.ConfigMapPropertySource   : Can't read configMap with name: [springcloudk8sconfigdemo] in namespace:[null]. Ignoring
2019-08-02 08:59:06.715  WARN 1 --- [pool-1-thread-1] o.s.c.k.config.ConfigMapPropertySource   : Can't read configMap with name: [springcloudk8sconfigdemo] in namespace:[null]. Ignoring
2019-08-02 08:59:11.732  WARN 1 --- [pool-1-thread-1] o.s.c.k.config.ConfigMapPropertySource   : Can't read configMap with name: [springcloudk8sconfigdemo] in namespace:[null]. Ignoring
2019-08-02 08:59:16.749  WARN 1 --- [pool-1-thread-1] o.s.c.k.config.ConfigMapPropertySource   : Can't read configMap with name: [springcloudk8sconfigdemo] in namespace:[null]. Ignoring

Always can not get value ,is null. like this:
![image](https://user-images.githubusercontent.com/25023599/62358327-0d2eff00-b547-11e9-9d72-68945535b6ee.png)

**Comment by damon008** [comment]
And these:
![image](https://user-images.githubusercontent.com/25023599/62358534-7f074880-b547-11e9-8bc8-b595db92fb97.png),
In our k8s cluster,not have Service Account，so:
role ，rb，sa should have?

**Comment by damon008** [comment]
I think the reason for Failure to Get Configuration Information is this:
Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
what you think?@geoand
why Can't read configMap with name: [springcloudk8sconfigdemo] in namespace:[null]. Ignoring?

**Comment by damon008** [comment]
@geoand  Can you show the Test for a complete Demo？contains deployment.yml,bootstrap.yml and so on.

**Comment by geoand** [comment]
The integration test https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-integration-tests/simple-configmap/ has complete scenario that is used as an integration test.

application.yml is [here](https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-integration-tests/simple-configmap/src/main/resources/application.yml), bootstrap.yaml is [here](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-integration-tests/simple-configmap/src/main/resources/bootstrap.yaml) and the configmap that is applied is [here](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-integration-tests/simple-configmap/src/test/resources/config-map.yml)

**Comment by damon008** [comment]
sa.yml and role.yml and so on ,Does need these?

**Comment by damon008** [comment]
@geoand 
I try what you provided, show my logs :
My configmap name is springcloudk8sconfigdemo
Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
Can't read configMap with name: [springcloudk8sconfigdemo] in namespace:[null]. Ignoring

**Comment by geoand** [comment]
`sa.yaml` and `role.yaml` are not provided in the integration test (they are not needed since the user is an admin user).

You need to make sure that the ServiceAccount that is being used to run the application can `view` ConfigMaps, see [this](https://github.com/spring-cloud/spring-cloud-kubernetes#security-configurations-inside-kubernetes).

**Comment by damon008** [comment]
your means is : the ServiceAccount must have and must access SA to get configmap infos?

**Comment by geoand** [comment]
SA is the ServiceAccount :)

Like I said before, I strongly believe one needs to understand the basic Kubernetes RBAC concepts before working with this kind of thing.

**Comment by damon008** [comment]
@geoand 
Your means is:
 the basic Kubernetes RBAC must have?

**Comment by damon008** [comment]
@geoand 
I create a SA，name is config-reader，but SECRETS is null , how to make it easy to solve the question of gettting configmap
NAME                  SECRETS   AGE
config-reader         0         1d
default               0         2d
frameworkcontroller   0         2d

**Comment by geoand** [comment]
I don't feel that this session is being very productive. 
Please read the Kubernetes docs on how RBAC is handled on the platform in general and also the docs of this project that explain what RBAC concepts are relevant. 
I am confident that once you have done that and have grokked everything that is going on, you'll be able to fix your issue without much hassle
