### ISSUE TITLE
springcloud-k8s-config

### ISSUE THREAD

**Issue by damon008** [spring-cloud/spring-cloud-kubernetes#443]
about springcloud-k8s-config, configmap only use bootstrap.yml or bootstrap.properties,application.yml or application.properties not can?

**Comment by damon008** [comment]
How to solve this log error:
Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.

**Comment by davidkarlsen** [comment]
you need to deploy the pod so that it mounts service account tokens

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
