### ISSUE TITLE
Multiple Properties In One ConfigMap

### ISSUE THREAD

**Issue by x-fauzan-x** [spring-cloud/spring-cloud-kubernetes#447]
Can i use the same configmap for multiple properties files ?
like this

`apiVersion: v1
kind: ConfigMap
metadata:
  name: MS_NAME.sentry.properties
  namespace: default
data:
  application.properties: |-  
  sentry.properties: |-
`

Or I must create a configmap for every properties like on readme toturial ?

**Comment by TYsewyn** [comment]
Have you tried it? Do you have some issues with that configuration?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by x-fauzan-x** [comment]
It worked actually . I 'm asking just to make sure, because it's not on the readme page

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
