### ISSUE TITLE
Health indicator should support being disabled

### ISSUE THREAD

**Issue by cydergoth** [spring-cloud/spring-cloud-kubernetes#449]
Health indicator bean for actuator is missing the annotation 

`@ConditionalOnEnabledHealthIndicator("your-health")
`
so can't be disabled in scenarios where we don't need it.

See : https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/KubernetesAutoConfiguration.java#L160

**Comment by spencergibb** [comment]
PRs welcome. The value in the annotation isn't needed by default.

**Comment by cydergoth** [comment]
As a workaround you can use this in your application bootstrap class:

```
    @Autowired
    private HealthCheckRegistry healthCheckRegistry;

 @EventListener
    public void onApplicationEvent(ContextRefreshedEvent event) {
        healthCheckRegistry.unregister("kubernetes"); // Deregister the kubernetes integration healthcheck as we don't
        // want to disable processing if the kubernetes API is temporarily unreachable
    }

```

**Comment by eddumelendez** [comment]
I can take this issue :)

**Comment by neonomaly** [comment]
This issue has been reproduced in spring-cloud-kubernetes-fabric8-autoconfig:2.0.3. Please reopen it. Thanks!

**Comment by spencergibb** [comment]
No, this was two years ago, we'll use the new issue to track.
