### ISSUE TITLE
Is reload only work on `ConfigurationProperties`?

### ISSUE THREAD

**Issue by jast90** [spring-cloud/spring-cloud-kubernetes#459]
I have a properties named `oauth-server` ,I use it by another properties in my `application.properties` ,finally I use it in my java code by `@Value` .I change the kubernetes config map, the change not reload.Is reload only work on `ConfigurationProperties`?

**Comment by spencergibb** [comment]
`@Value` doesn't get updated automatically. Mark the bean `@RefreshScope` or use `@ConfigurationProperties`.

**Comment by jast90** [comment]
Thank you for your reply，I should read more reference
