### ISSUE TITLE
Missing 'spring-boot-configuration-processor' dependency on Spring Cloud Kubernetes Discovery

### ISSUE THREAD

**Issue by fmonorchio** [spring-cloud/spring-cloud-kubernetes#464]
I have notice that the discovery module doesn't have the configuration processor dependency for IDE autocomplete on KubernetesDiscoveryProperties.

**Comment by geoand** [comment]
Hi,

Would you like to contribute a fix for the issue?

Thanks

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by fmonorchio** [comment]
Sorry for the late reply.
Sure. I'll try to fix the problem.

**Comment by ryanjbaxter** [comment]
closed via 99c6969
