### ISSUE TITLE
refresh config for dynamic

### ISSUE THREAD

**Issue by damon008** [spring-cloud/spring-cloud-kubernetes#469]
Do you provide a method to refresh configMap for dynamic without reboot app?

**Comment by geoand** [comment]
Is should be covered in the README: https://github.com/spring-cloud/spring-cloud-kubernetes#53-propertysource-reload

**Comment by damon008** [comment]
Does it work at once?

**Comment by geoand** [comment]
What do you mean `at once`?

**Comment by damon008** [comment]
> What do you mean by `at once`?

Get the latest config immediately when happens.

**Comment by geoand** [comment]
There are a couple strategies available. One is polling from the app itself and one is getting updates when the API server. The latter would be really quick under normal circumstances

**Comment by damon008** [comment]
> > What do you mean by `at once`?
> 
> Get the latest config immediately when happens.

do not reboot app or wait for sometime

**Comment by geoand** [comment]
The Spring context refresh will take some time of course, but it shouldn't be long unless you have a very large application

**Comment by damon008** [comment]
> There are a couple strategies available. One is polling from the app itself and one is getting updates when the API server. The latter would be really quick under normal circumstances

how to set up strategies

**Comment by damon008** [comment]
> The Spring context refresh will take some time of course, but it shouldn't be long unless you have a very large application

I want to get latest config when update without reboot app and need not wait.

**Comment by geoand** [comment]
All the information is in the README I linked. You can also see an example here: https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-integration-tests/simple-configmap/src/main/resources/bootstrap.yaml
