### ISSUE TITLE
Check that we don't close watches unless we really need to.

### ISSUE THREAD

**Issue by iocanel** [spring-cloud/spring-cloud-kubernetes#471]
Users reported this:

https://github.com/fabric8io/kubernetes-client/issues/1602

This is probably an issue in the user code itself or in `sck`.

Let's make sure that we properly handle `Watch` instances and we never close() them while the application is running.

**Comment by ryanjbaxter** [comment]
@iocanel the only two places I see where we call `.close()` are
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/1.0.x/spring-cloud-kubernetes-leader/src/main/java/org/springframework/cloud/kubernetes/leader/PodReadinessWatcher.java#L76

and

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/1.0.x/spring-cloud-kubernetes-leader/src/main/java/org/springframework/cloud/kubernetes/leader/LeaderRecordWatcher.java#L73

In your opinion, should we no be calling `close` and instead letting the user be responsible for that?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
