### ISSUE TITLE
DiscoveryClient watch the service catalog for changes and update does not work correctly, when all-namespaces: true

### ISSUE THREAD

**Issue by claitonp** [spring-cloud/spring-cloud-kubernetes#472]
DiscoveryClient watch the service catalog for changes and update.

This current code returns only the endpoints of the current namespace.
`List<Endpoints> endpoints = client.endpoints().list().getItems(); `

To return all endpoints according to filters and labels, when using all-namespaces: true, use the code below:
```
Map<String, String> serviceLabels = properties.getServiceLabels();
List<Endpoints> endpointsList = properties.isAllNamespaces() ?
     client.endpoints().inAnyNamespace().withLabels(serviceLabels).list().getItems()
	: client.endpoints().list().getItems();
```

spring-cloud-kubernetes
version:1.0.4.BUILD-SNAPSHOT
```

package org.springframework.cloud.kubernetes.discovery;
public class KubernetesCatalogWatch implements ApplicationEventPublisherAware {
...
  public void catalogServicesWatch() {
    
    // bug
   //  List<Endpoints> endpoints = client.endpoints().list().getItems(); 

   //adjusted
   Map<String, String> serviceLabels = properties.getServiceLabels();
   List<Endpoints> endpointsList = properties.isAllNamespaces() ?
     client.endpoints().inAnyNamespace().withLabels(serviceLabels).list().getItems()
	: client.endpoints().list().getItems();
  
  }
}``
```

**Comment by spencergibb** [comment]
Please say what is happening. "Does not work correctly" isn't helpful at all.

**Comment by claitonp** [comment]
In this case, only services / pods where the application namespace is returned. You should return all instances when using the: discovery.all-namespaces option.

**Comment by claitonp** [comment]
when using the: **discovery.all-namespace: true**

To work properly, replace the line below:

` List<Endpoints> endpoints = client.endpoints().list().getItems(); `

**replace to:**

```
Map<String, String> serviceLabels = properties.getServiceLabels();
   List<Endpoints> endpointsList = properties.isAllNamespaces() ?
     client.endpoints().inAnyNamespace().withLabels(serviceLabels).list().getItems()
	: client.endpoints().list().getItems();
```

**Comment by Capone1983** [comment]
Has this been fixed?

I have the same issue.

**Comment by ryanjbaxter** [comment]
@Haybu mind taking a look at this one?
