### ISSUE TITLE
spring.cloud.kubernetes.reload.monitoring-secrets not working

### ISSUE THREAD

**Issue by Joshhw** [spring-cloud/spring-cloud-kubernetes#475]
When enabling monitoring-secrets within the bootstrap.yaml the changes to secrets doesn't get reflected in the spring boot app. Here is a [link to a repository](https://github.com/Joshhw/monitoring-secrets-demo) trying to utilize it.

**Comment by ajay2799** [comment]
Having the same problem. Any workaround?

**Comment by Joshhw** [comment]
> Having the same problem. Any workaround?

I have yet to find a solution.

**Comment by ryanjbaxter** [comment]
Can you try with the latest Hoxton RELEASE (SR3)?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
