### ISSUE TITLE
gateway is not routing for Spring Cloud Hoxton.M3 release using kubernetes service discovery

### ISSUE THREAD

**Issue by nitishkumar71** [spring-cloud/spring-cloud-kubernetes#479]
Hello,
I was trying to use spring cloud gateway with kubernetes service discovery on minikube for **Spring Cloud Hoxton.M3**. We are able to get list of all services which are registered in kubernetes using ```DiscoveryClient```. We have created one custom endpoint **<minikube_IP:node_port>/services**, which gives the list of all services, but when we send request for any of the service routes, gateway is giving error 404.
![image](https://user-images.githubusercontent.com/11610230/67149250-b83d9200-f2c6-11e9-9db3-802670efe430.png)

**Steps to Reproduce**

1. Download Github [Repo](https://github.com/nitishkumar71/spring-cloud-hoxton-m3-issue)
2. Start minikube and set minikube docker to build image
 ```
minikub start
eval $(minikube docker-env)
```
3. run deployment script ``` ./deploy-script.sh```. It will create 3 docker images, their deployment and services. It will also create service account and their respesctive role with rolebinding.
4. to get list of all services, ping to **<minikube_IP:node_port>/services**
5. call **<minikube_IP:node_port>/booking-service/hello**, which will throw 404.

When we check ```/actuator/gateway/routes``` endpoint, it gives empty result. But when we rollback to Hoxton.M2, routing is working correctly in gateway.

**Steps to clean up**

1. run cleanup script ```./clean-up.sh```
2. stop minikube ```minikube stop```

Please let me know if I can be of any help here.

**Comment by TYsewyn** [comment]
Hi @nitishkumar71! Thanks for creating this issue!
Could you please verify this again with `Hoxton.BUILD-SNAPSHOT` or `Hoxton.RC1`?

Gateway uses the reactive service discovery by default since `2.2.0.M3`, and [this bug](https://github.com/spring-cloud/spring-cloud-commons/issues/617) caused to only take the services (and thus routes) from `application.properties|yml` into account.

**Comment by nitishkumar71** [comment]
Hi @TYsewyn 
I can confirm this is working with `Hoxton.RC1`. Hence, closing the issue.
Thanks for your efforts.
