### ISSUE TITLE
Add a 'watch-service' option to reload.mode

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-kubernetes#481]
It would be nice to have a WatchService keep track of any file changes to config/secret paths that are backed by a volume mount. When file changes are detected it could reload context the same way that 'polling' reload mode works today.

**Comment by ryanjbaxter** [comment]
I think this is a duplicate of what is proposed in https://github.com/spring-cloud/spring-cloud-kubernetes/issues/190
