### ISSUE TITLE
how to implement load balancing at spring-cloud-gateway so that traffic is evenly distributed across multiple downstream services deployed in kubernetes

### ISSUE THREAD

**Issue by VaishaliNankani** [spring-cloud/spring-cloud-kubernetes#484]
we have spring-cloud-gateway as the apigateway for multiple down stream micro services deployed in kubernetes environment. wherein each micro service has multiple pods.

when HTTP2 traffic is going via spring-cloud-gateway only one same pod of each microservice is selected for forwarding HTTP2 traffic even when all pods ip addresses are being returned in DNS response to spring-cloud-gateway.so load balancing is not happening at spring cloud gateway between pods of the  microservice . I deployed downstream service as both headless service as well as clusterIP but  load balancing is not happening in either case.

spring-cloud-kubernetes-ribbon can be used to load balance the traffic between service endpoints but in that case ribbonclient needs to be aware of the service name and only one annotation i can add (@RibbonClient(name="downstream-servicename"))  in sprin-cloud-apigateway,but i need load balancing for multiple down stream services for HTTP2 Traffic.so not sure how to use it for my use case

so my requirement is :
(1)spring-cloud-gateway should be able to discover the down stream services deployed in the kubernetes namespace
(2)should be able to discover the endpoints  corresponding to down stream services  .
(3)load balance the HTTP 2 traffic between endpoints of the down stream service.

let me know how to achieve this using spring-cloud-kubernetes project

**Comment by ryanjbaxter** [comment]
Spring Cloud Gateway currently doesnt support http2 https://github.com/spring-cloud/spring-cloud-gateway/issues/7

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
