### ISSUE TITLE
BlockingLoadBalancerClient does not work with KubernetesDiscoveryClient

### ISSUE THREAD

**Issue by ArtyomGabeev** [spring-cloud/spring-cloud-kubernetes#486]
Hi,

I'm trying to migrate from ribbon LB to newly introduced blocking LB.

Here is a test replicating the issue:
```java
    @Test
    public void testReconstructURIForK8S() {
        ServiceInstance instance = new KubernetesServiceInstance("auth-server", "auth-server",
                new EndpointAddress("hostname", "127.0.0.1", "nodeName", null),
                new EndpointPort("http", 8091, "tcp"),
                Collections.emptyMap(),
                false);
        URI uri = LoadBalancerUriTools.reconstructURI(new TruncateSchemaServiceInstance(instance),
                URI.create("http://auth-server/oauth/token"));

        assertThat(uri.toString()).isEqualTo("http://127.0.0.1:8091/oauth/token");
    }
```

Fails with:
```
   001:  "java.lang.IllegalStateException: Could not create URI object: Expected hostname at index 7: http://://127.0.0.1:8091/oauth/token"     
   002:  "at org.springframework.web.util.HierarchicalUriComponents.toUri(HierarchicalUriComponents.java:514)"     
   003:  "at org.springframework.cloud.client.loadbalancer.LoadBalancerUriTools.doReconstructURI(LoadBalancerUriTools.java:111)"     
   004:  "at org.springframework.cloud.client.loadbalancer.LoadBalancerUriTools.reconstructURI(LoadBalancerUriTools.java:95)"     
   005:  "at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient.reconstructURI(BlockingLoadBalancerClient.java:75)"     
   006:  "at org.springframework.cloud.client.loadbalancer.ServiceRequestWrapper.getURI(ServiceRequestWrapper.java:43)"     
   007:  "at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:97)"     
   008:  "at org.springframework.cloud.client.loadbalancer.LoadBalancerRequestFactory.lambda$createRequest$0(LoadBalancerRequestFactory.java:61)"     
   009:  "at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient.execute(BlockingLoadBalancerClient.java:62)"     
```

The issue is that KubernetesServiceInstance returns for schema either "http://" or "https://".
Current implementation of LoadBalancerUriTools except schema to be "http" or "https".

I've checked implementation of ServiceIntance for Eureka, it returns null when getSchema is called.

Should we fix issue in KubernetesServiceInstance or adjust LoadBalancerUriTools to trim "://" during URI reconstruction? (second one looks more safe).

Thanks,
Artyom

**Comment by ArtyomGabeev** [comment]
@OlgaMaciaszek , hi Olga

What do you think about this issue? Should I fix it in LoadBalancerUriTools?

Thanks

**Comment by baev** [comment]
> Should we fix issue in KubernetesServiceInstance or adjust LoadBalancerUriTools to trim "://" during URI reconstruction? (second one looks more safe).

my vote for removing `://` from `KubernetesServiceInstance` side (scheme is a URI part without `://` https://tools.ietf.org/html/rfc3986#section-3.1)

**Comment by TYsewyn** [comment]
Unfortunately we can't change the returned value of `getScheme` at this moment since that introduces a breaking change. AFAIK the only viable option would be to adapt `LoadBalancerUriTools` to strip `://` from the scheme like @ArtyomGabeev already proposed.
Please keep your first PR open so we can merge this once we start working on the next major release.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by OlgaMaciaszek** [comment]
@ArtyomGabeev sure, feel free to provide a PR.

**Comment by bradfordChiang** [comment]
I'm having the same issue here. when will this PR be merged?

**Comment by ArtyomGabeev** [comment]
I've opened another PR to trim double slash in util class.

We are not closing this one, probably on next major release we will be able to merge it as well.

**Comment by spencergibb** [comment]
Wait, why can't we fix kubernetes service instance? I don't want work around in a common library for this one's bug.

**Comment by ArtyomGabeev** [comment]
@spencergibb here is the PR for kubernetes service instance: https://github.com/spring-cloud/spring-cloud-kubernetes/pull/494

**Comment by ArtyomGabeev** [comment]
Hi, @TYsewyn @spencergibb 
Are we waiting for next major release to get it merged?

Thanks
