### ISSUE TITLE
Can I use kubernetes service locally？

### ISSUE THREAD

**Issue by snakeeeeeeeee** [spring-cloud/spring-cloud-kubernetes#487]
I want to connect and debug the kubernetes service on the server during development, but I don't know what to do

**Comment by akuma8** [comment]
What do you mean by 

> debug the kubernetes service

 You can forward the pod's port to your local machine.

**Comment by golonzovsky** [comment]
you can either use `kubectl port-forward svc/service-name port:port` or `telepresence`, but not sure it has something to do with this repo if I got this question correctly

**Comment by ryanjbaxter** [comment]
You can also use something like Skaffold which will take care of the port forwarding and also open a remote debug port.  However this has nothing to do with this project specifically so I am going to close this issue.
