### ISSUE TITLE
how to debug in 'java main' way 

### ISSUE THREAD

**Issue by zzzhy** [spring-cloud/spring-cloud-kubernetes#491]
as a spring boot project, it can be started as a java main application locally.
what's the way to debug my micro-services in local debug env with no kubernetes and no dockers ?

**Comment by ryanjbaxter** [comment]
Are you asking how to debug your application without running inside kubernetes?  Or are you asking how to debug your application while it is running inside of kubernetes?

**Comment by zzzhy** [comment]
debug application without running inside kubernetes, just as a java application in my idea debug frame

**Comment by ryanjbaxter** [comment]
I am confused as to how this has anything to do with Spring Cloud Kubernetes.

**Comment by liangguohun** [comment]
his mean is how can  run the application on windows 10  and work with the other module in kubernetes, i want to know too.
