### ISSUE TITLE
Can Kubernetes Client get endpoints from another namespace using externalName? 

### ISSUE THREAD

**Issue by guilhermecgs** [spring-cloud/spring-cloud-kubernetes#495]
I have a kubernetes cluster with serviceA on namespaceA and serviceB on namespaceB.

I want, from serviceA, use kubernetes service discovery to programmatically list serviceB. I am planning to use spring cloud kubernetes ( @EnableDiscoveryClient ).

However, there is a company wide policy to block the use of the configuration below that should have solved the problem: spring.cloud.kubernetes.discovery.all-namespaces=true

If I set ExternalName = namespaceA.serviceb will it work?

https://stackoverflow.com/questions/37221483/service-located-in-another-namespace

**Comment by ryanjbaxter** [comment]
> However, there is a company wide policy to block the use of the configuration below that should have solved the problem: spring.cloud.kubernetes.discovery.all-namespaces=true

Does this mean there is a policy in your kubernetes deployment keeping this from working?

> If I set ExternalName = namespaceA.serviceb will it work?

I am not sure what `ExternalName` is can you elaborate?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
