### ISSUE TITLE
better integration with istio service observability 

### ISSUE THREAD

**Issue by zzzhy** [spring-cloud/spring-cloud-kubernetes#501]
our project is using spring cloud and the service mesh tool is istio.
we found it when using `spring-cloud-starter-kubernetes-ribbon` component, there turns out no edges in kiali graph tab between pods or services.
I think the reason is that istio only collects data or metrics which just goes through k8s service, while ribbon flows to pod directly.
any instructions or suggestions will be of great appreciation.

**Comment by ryanjbaxter** [comment]
You can tell ribbon to use services

https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.1.2.RELEASE/reference/html/#ribbon-discovery-in-kubernetes
