### ISSUE TITLE
The Ribbon is optional

### ISSUE THREAD

**Issue by lavecoral** [spring-cloud/spring-cloud-kubernetes#502]
The `spring-cloud-starter-netflix-ribbon` in `spring-cloud-kubernetes-ribbon` is optional，so if the project don't add ribbon dependency, the RestTemplate can't use client LoadBalance. But it's not mentioned in the document.

**Comment by rafaelrenanpacheco** [comment]
Related to #530

**Comment by spencergibb** [comment]
`spring-cloud-kubernetes-ribbon` no longer exists in 1.1.x or master
