### ISSUE TITLE
Update fabric8 client to 4.8.0

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-kubernetes#515]
So far is see even master still uses older client io.fabric8 kubernetes-client 4.4.1 which is not tagged as compatible with 1.17, is it?
https://github.com/fabric8io/kubernetes-client#compatibility-matrix

Can your confirm or deny for compatibility and if not , is there an estimated ETA for a release?

**Comment by rafaelrenanpacheco** [comment]
I'm using `spring-cloud-starter-kubernetes-ribbon` on a Kubernetes 1.17 cluster for server side service discovery (`spring.cloud.kubernetes.ribbon.mode=SERVICE`), and so far it is working just fine.

**Comment by Haybu** [comment]
probably to a few days ago release of 4.9.0
