### ISSUE TITLE
Support list of propertysource

### ISSUE THREAD

**Issue by iwho** [spring-cloud/spring-cloud-kubernetes#519]
i debug this condition is false
<img width="938" alt="MacHi 2020-01-23 15-15-52" src="https://user-images.githubusercontent.com/5604926/72963962-853df980-3df3-11ea-925c-cf6b2cf6728a.png">
<img width="512" alt="MacHi 2020-01-23 15-19-20" src="https://user-images.githubusercontent.com/5604926/72964058-c2a28700-3df3-11ea-87c6-9aa00a4c9001.png">

**Comment by timpeeters** [comment]
@iwho I suspect this is caused/duplicated by: https://github.com/spring-cloud/spring-cloud-commons/issues/664

Temporarily reverting to Hoxton.RELEASE instead of Hoxton.SR1 will probably solve the issue.

**Comment by simsibimsiwimsi** [comment]
I believe @timpeeters is right..  We used the same fix (reverting to Hoxton.RELEASE) which works for now..

**Comment by spencergibb** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-commons/issues/664

**Comment by spencergibb** [comment]
Reopening, the fix should happen here as s-c-k8s should support the new list of property sources.

**Comment by ryanjbaxter** [comment]
This should have been fixed by https://github.com/spring-cloud/spring-cloud-kubernetes/pull/526
