### ISSUE TITLE
Rework integration test running so mac users can run them 

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-kubernetes#523]
Use something like docker or testcontainers (/cc @bsideup).

It should be simple to run and run the same way in circleci, jenkins, linux and mac.

Currently only run from circle via https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/.circleci/config.yml

**Comment by bsideup** [comment]
JFYI it is possible to run kind with Testcontainers, I've seen some experiments with it.
Let me know if you need help running it, I can prototype something.

**Comment by ryanjbaxter** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-kubernetes/issues/236
