### ISSUE TITLE
ConfigMap reload doesn't work: "The current number of Confimap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place"

### ISSUE THREAD

**Issue by neev-dev** [spring-cloud/spring-cloud-kubernetes#524]
**Describe the bug**
Apply the changes to a config map doesn't result in the config getting updated

**Sample**
This is what I could figure out based on debugging:

* Initially loaded config is in “BootstrapPropertySource”; name is “bootstrapProperties-configmap.{value-of-spring-application-name}.{namespace}”. Properties are present as they are in the config map and they get wired into the bean annotated with @Configuration and @ConfigurationProperties (w/ prefix) as expected.
<< configmap change is applied >>
* ConfigMap change is detected; EventBasedConfigurationChangeDetector’s onEvent gets invoked. Configmap param contains the new data.
* locateMapPropertySources comes back with one change - a ConfigMapPropertySource instance with the name “configmap.{value-of-spring-application-name}.{namespace}”.
* findPropertySources() loops through all the sources in list to check if anyone is an instance of ConfigMapPropertySource. Since “BootstrapPropertySource” is not an instance of ConfigMapPropertySource, doesn’t consider it as part of the managed sources return list. At the end findPropertySources() returns an empty list.
* Changed() method in ConfigurationChangeDetector logs "The current number of Confimap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place”.
* The configuration change is not considered for refreshing the config bean.

Also, I can only load one config map (with the same name as the application). spring.cloud.kubernetes.config.sources seem to get ignored.

Tried with spring.cloud.k8s  versions 1.1.1.RELEASE and 1.0.5 with Spring cloud versions Hoxton.SR1 and Greewich.SR4.

**Comment by Algeran** [comment]
I also got this problem.

All tests under spring-boot-starter-parent 2.2.4.RELEASE

Tried with spring-cloud-starter-kubernetes-config with spring-cloud-dependencies version Hoxton.SR1.
- with Hoxton.SR1(Dec, 2019) and  spring-cloud-starter-kubernetes-config 1.1.1.RELEASE (default for Hoxton.SR1) reload is not working
- with Greenwich.SR5(Feb, 2020) and  spring-cloud-starter-kubernetes-config 1.0.5.RELEASE (default) reload is not working
- with Greenwich.SR4(Nov, 2019) and  spring-cloud-starter-kubernetes-config 1.0.4.RELEASE (default) **all works as expected**, properties reconfigured
- with Hoxton.RELEASE(Nov, 2019) and  spring-cloud-starter-kubernetes-config 1.1.0.RELEASE (default) **all works as expected**, properties reconfigured

Then I removed from pom.xml spring-cloud-dependencies at all and leave only dependency spring-cloud-starter-kubernetes-config with direct version:
- with version 1.1.1.RELEASE reload not working.
- with version 1.1.0.RELEASE **all works as expected**, properties reconfigured
- with version 1.0.1.RELEASE **all works as expected**, properties reconfigured


So, i guess that something that brokes logic of reloading properties was added after spring-cloud-dependencies Greenwich.SR4 and Hoxton.RELEASE (after Nov, 2019). And the same broken logic was added directly to spring-cloud-starter-kubernetes dependencies version 1.1.1.RELEASE.

**Comment by trks1970** [comment]
Same here. Hoxton.SR1 with kubernetes-config 1.1.1.RELEASE does not work,.

**Comment by lao974** [comment]
Same here. spring-cloud-starter-kubernetes-config 1.1.1.RELEASE gives this error, 1.1.0.RELEASE works fine with spring-boot-starter-parent 2.2.4.RELEASE.
I would suggest increasing the level of "...No reload will take place" log message from debug to warn or info at least. Could have saved me some hours of config experimentation if it was more visible.

**Comment by Zetten** [comment]
With Hoxton.SR3 I'm still seeing this warning (and the failure to reload) when using mounted Secrets.

My pods are configured with property env vars pointing at the ConfigMaps and mounted Secrets-as-volumes:

```
      SPRING_CLOUD_KUBERNETES_CONFIG_SOURCES_0_NAME:       configmap-foo
      SPRING_CLOUD_KUBERNETES_CONFIG_SOURCES_0_NAMESPACE:  mynamespace
      SPRING_CLOUD_KUBERNETES_CONFIG_SOURCES_1_NAME:       configmap-bar
      SPRING_CLOUD_KUBERNETES_CONFIG_SOURCES_1_NAMESPACE:  mynamespace
      SPRING_CLOUD_KUBERNETES_SECRETS_PATHS:               /var/run/secrets/mynamespace
      SPRING_CLOUD_KUBERNETES_SECRETS_PATHS_0:             /var/run/secrets/mynamespace/secret-foo
      SPRING_CLOUD_KUBERNETES_SECRETS_PATHS_1:             /var/run/secrets/mynamespace/secret-bar
```

And during startup these are picked up during bootstrap and set as PropertySources, but the warning continues and reloading is disabled. Note that in my example only one Secret has only one property - if multiple properties exist then each is set as a property source.

```
2020-04-15 16:17:00.148  INFO 1 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-configmap.configmap-foo.mynamespace'}, BootstrapPropertySource {name='bootstrapProperties-configmap.configmap-bar.mynamespace'}]
2020-04-15 16:17:00.164  INFO 1 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-key.in.my.secret-properties'}]
...
2020-04-15 16:17:04.368  WARN 1 --- [//10.43.0.1/...] .r.EventBasedConfigurationChangeDetector : The current number of Confimap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place
2020-04-15 16:17:04.372  WARN 1 --- [//10.43.0.1/...] .r.EventBasedConfigurationChangeDetector : The current number of Confimap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place
2020-04-15 16:17:04.373  WARN 1 --- [//10.43.0.1/...] .r.EventBasedConfigurationChangeDetector : The current number of Confimap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place
```

Perhaps I've just misconfigured something, but it was working previously.

**Comment by cirodev** [comment]
I have the same error with the Hoxton.SR4 version of spring cloud. The configuration is not reloaded.

**Comment by Biglr** [comment]
Facing the same issue currently.

I've setup everything the same as in [the reload example](https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-examples/kubernetes-reload-example) but after changing the Configmaps, the console output states
`The current number of Confimap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place`

**Comment by imitbn** [comment]
This issue is still actual for `SecretsPropertySource` and `spring.cloud.kubernetes.secrets.enableApi=false`

**Comment by easymammoth** [comment]
I'm facing the same issue and tried Hoxton.SR7 / 1.1.5.RELEASE, but got the same error.

Any hope for a fix ? Or any solution to have reload working with mounted configMaps and secrets ?

**Comment by mih-kopylov** [comment]
@easymammoth we've made a workaround: added a custom configuration `spring.cloud.kubernetes.properties` to define paths to configuration files and registered two beans: a third `PropertySourceLocator` and a `@Scheduled` method that reads provided files and triggers `ConfigurationUpdateStrategy` in case those files' content is changed. 
So it looks like an extension of `spring-cloud-kubernetes-config` that works with additional `application.properties` files.

**Comment by easymammoth** [comment]
Thanks for your reply @mih-kopylov 
I'll try to build a workaround that suits my needs from your suggestion, until a fix is available.

**Comment by LeonardoBonacci** [comment]
Any update on this issue?

**Comment by easymammoth** [comment]
@LeonardoBonacci This won't be fixed, as this is by design.
For a way to implement reload, see this comment on duplicate issue : 
https://github.com/spring-cloud/spring-cloud-kubernetes/issues/579#issuecomment-692095175

**Comment by Alos** [comment]
I have seen this happening with already running applications. Without making changes to the ConfigMap or the binary. The application will start writing warnings to the logs:

```
"The current number of ConfigMap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place"
```

**Comment by ryanjbaxter** [comment]
We added some debugging to the latest versions to help elaborate why this might happen, you can enable debug logging to help provide more insight.

**Comment by gowtham789** [comment]
Please look into this, https://github.com/spring-cloud/spring-cloud-kubernetes#54-propertysource-reload .

**Comment by mih-kopylov** [comment]
> Please look into this, https://github.com/spring-cloud/spring-cloud-kubernetes#54-propertysource-reload . 

@gowtham789 it's not so obvious what exactly is helpful in that section.
Could you please emphasize or describe the idea?
