### ISSUE TITLE
sping-cloud-kubernetes compatibility with kubernetes version

### ISSUE THREAD

**Issue by nengbowan** [spring-cloud/spring-cloud-kubernetes#529]

**Comment by nengbowan** [comment]
should be list like https://github.com/fabric8io/kubernetes-client#compatibility-matrix

**Comment by spencergibb** [comment]
We should link to the matrix since that is what we use as a client

**Comment by nengbowan** [comment]
problem occoured when i do the demo , reload config map , the error is  "on project spring-cloud-kubernetes-example-reload: Failed to create Deployment from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executin
g: POST at: https://192.168.99.100:8443/apis/extensions/v1beta1/namespaces/default/deployments. Message"  , 
demo runtime environment is under below:
OS system : windows toolbox 
kubernetes Version : minikube V1.7.3
use branch : 1.0.x 

and i search the reason , look at  the compatibility-matrix , url is https://github.com/fabric8io/kubernetes-client#compatibility-matrix;
and i modified the version of kubernetes client , 
but it also can not work ,so i suggest this ,
can u give me some suggestions ， i will appreciate u .

**Comment by nengbowan** [comment]
![图片](https://user-images.githubusercontent.com/24314744/75841368-860d7680-5e08-11ea-9b49-0978b77c179f.png)

error detail

**Comment by nengbowan** [comment]
request url https://192.168.99.100:8443/apis/extensions/v1beta1/namespaces/default/deployments

response is 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {
    
  },
  "code": 404
}

**Comment by ryanjbaxter** [comment]
@nengbowan are these two separate issues?

**Comment by nengbowan** [comment]
today , i replace the minikube version (v1.7.3 the latest version )to v1.1.1 and kubectl client v1.1.1 , and error is encoureed , kubectl  version print message , connot connect localhost:8080 , so i replace it with v1.4.13 and the problem is resolved , but minikube dashboard can not start , the message is X http://127.0.0.1:61097/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/ is not responding properly: Temporary Error: unexpected response code: 503,

the main problem is not up , when i use the maven plugin command , 
mvn clean package fabric8:deploy -Pkubernetes  and build success 
then kubectl get pods is not running , the reason is can not pull image , 
so i package it with jar then build to image , then push to docker hub , then minikube ssh pull it , 
and tag it , it also can not work , it's status is restart , so i log it,  then i don
t know next step what shoud i do , to resolver this problem ,

the best opertion i guess is : uninstall minikue , install the latest version v1.7.3 but it can not deploy to kubernetes automaticly  , but other else can work better , or which version u can suggest me to install , or branch to checkout

**Comment by nengbowan** [comment]
> 
> 
> @nengbowan are these two separate issues?

no , i guess , the minikube 1.7.3 removed the rest api , so deployt error , so for make it better ,  yesterday , i change minikube 1.1.1 but the problems become more , which version of minikube can make it better with current branch 1.0.x

**Comment by nengbowan** [comment]
ooh , i get it , reload configmap demo shoud run 'minikube docker-env' , that i just run last line , not whole  , but the next problem ..
`
[INFO] Using namespace: default
[INFO] Creating a Deployment from kubernetes.yml namespace default name spring-cloud-reload
[ERROR] Failed to create Deployment from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.99.100:8443/apis/extensions/v1beta1/namespaces/default/deployments. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).. Deployment(apiVersion=extensions/v1beta1, kind=Deployment, metadata=ObjectMeta(annotations={fabric8.io/git-commit=faebe99cbcf16c33af75a0012328e364cbaab3d8, fabric8.io/metrics-path=dashboard/file/kubernetes-pods.json/?var-project=spring-cloud-kubernetes-example-reload&var-version=1.0.6.BUILD-SNAPSHOT, fabric8.io/scm-con-url=scm:git:git://github.com/spring-cloud-incubator/spring-cloud-kubernetes.git/spring-cloud-kubernetes-examples/spring-cloud-kubernetes-example-reload, fabric8.io/scm-url=https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/spring-cloud-kubernetes-examples/spring-cloud-kubernetes-example-reload, fabric8.io/iconUrl=img/icons/spring-boot.svg, fabric8.io/git-branch=1.0.x, fabric8.io/scm-devcon-url=scm:git:ssh://git@github.com/spring-cloud-incubator/spring-cloud-kubernetes.git/spring-cloud-kubernetes-examples/spring-cloud-kubernetes-example-reload, fabric8.io/scm-tag=HEAD, fabric8.io/docs-url=scp://static.springframework.org/var/www/domains/springframework.org/static/htdocs/spring-cloud/docs/spring-cloud-kubernetes-example-reload/1.0.6.BUILD-SNAPSHOT/spring-cloud-kubernetes/spring-cloud-kubernetes-examples/spring-cloud-kubernetes-example-reload}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, initializers=null, labels={app=spring-cloud-kubernetes-example-reload, provider=fabric8, version=1.0.6.BUILD-SNAPSHOT, group=org.springframework.cloud}, name=spring-cloud-reload, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=DeploymentSpec(minReadySeconds=null, paused=null, progressDeadlineSeconds=null, replicas=1, revisionHistoryLimit=2, rollbackTo=null, selector=LabelSelector(matchExpressions=[], matchLabels={app=spring-cloud-kubernetes-example-reload, provider=fabric8, group=org.springframework.cloud}, additionalProperties={}), strategy=null, template=PodTemplateSpec(metadata=ObjectMeta(annotations={fabric8.io/git-commit=faebe99cbcf16c33af75a0012328e364cbaab3d8, fabric8.io/metrics-path=dashboard/file/kubernetes-pods.json/?var-project=spring-cloud-kubernetes-example-reload&var-version=1.0.6.BUILD-SNAPSHOT, fabric8.io/scm-con-url=scm:git:git://github.com/spring-cloud-incubator/spring-cloud-kubernetes.git/spring-cloud-kubernetes-examples/spring-cloud-kubernetes-example-reload, fabric8.io/scm-url=https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/spring-cloud-kubernetes-examples/spring-cloud-kubernetes-example-reload, fabric8.io/iconUrl=img/icons/spring-boot.svg, fabric8.io/git-branch=1.0.x, fabric8.io/scm-devcon-url=scm:git:ssh://git@github.com/spring-cloud-incubator/spring-cloud-kubernetes.git/spring-cloud-kubernetes-examples/spring-cloud-kubernetes-example-reload, fabric8.io/scm-tag=HEAD, fabric8.io/docs-url=scp://static.springframework.org/var/www/domains/springframework.org/static/htdocs/spring-cloud/docs/spring-cloud-kubernetes-example-reload/1.0.6.BUILD-SNAPSHOT/spring-cloud-kubernetes/spring-cloud-kubernetes-examples/spring-cloud-kubernetes-example-reload}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, initializers=null, labels={app=spring-cloud-kubernetes-example-reload, provider=fabric8, version=1.0.6.BUILD-SNAPSHOT, group=org.springframework.cloud}, name=null, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, affinity=null, automountServiceAccountToken=null, containers=[Container(args=[], command=[], env=[EnvVar(name=KUBERNETES_NAMESPACE, value=null, valueFrom=EnvVarSource(configMapKeyRef=null, fieldRef=ObjectFieldSelector(apiVersion=null, fieldPath=metadata.namespace, additionalProperties={}), resourceFieldRef=null, secretKeyRef=null, additionalProperties={}), additionalProperties={})], envFrom=[], image=cloud/spring-cloud-kubernetes-example-reload:snapshot-200307-090313-0454, imagePullPolicy=IfNotPresent, lifecycle=null, livenessProbe=Probe(exec=null, failureThreshold=null, httpGet=HTTPGetAction(host=null, httpHeaders=[], path=/health, port=IntOrString(IntVal=8080, Kind=null, StrVal=null, additionalProperties={}), scheme=HTTP, additionalProperties={}), initialDelaySeconds=180, periodSeconds=null, successThreshold=null, tcpSocket=null, timeoutSeconds=null, additionalProperties={}), name=spring-boot, ports=[ContainerPort(containerPort=8080, hostIP=null, hostPort=null, name=http, protocol=TCP, additionalProperties={}), ContainerPort(containerPort=9779, hostIP=null, hostPort=null, name=prometheus, protocol=TCP, additionalProperties={}), ContainerPort(containerPort=8778, hostIP=null, hostPort=null, name=jolokia, protocol=TCP, additionalProperties={})], readinessProbe=Probe(exec=null, failureThreshold=null, httpGet=HTTPGetAction(host=null, httpHeaders=[], path=/health, port=IntOrString(IntVal=8080, Kind=null, StrVal=null, additionalProperties={}), scheme=HTTP, additionalProperties={}), initialDelaySeconds=10, periodSeconds=null, successThreshold=null, tcpSocket=null, timeoutSeconds=null, additionalProperties={}), resources=null, securityContext=SecurityContext(capabilities=null, privileged=false, readOnlyRootFilesystem=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, additionalProperties={}), stdin=null, stdinOnce=null, terminationMessagePath=null, terminationMessagePolicy=null, tty=null, volumeMounts=[], workingDir=null, additionalProperties={})], dnsPolicy=null, hostAliases=[], hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], initContainers=[], nodeName=null, nodeSelector=null, restartPolicy=null, schedulerName=null, securityContext=null, serviceAccount=null, serviceAccountName=null, subdomain=null, terminationGracePeriodSeconds=null, tolerations=[], volumes=[], additionalProperties={}), additionalProperties={}), additionalProperties={}), status=null, additionalProperties={})
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.99.100:8443/apis/extensions/v1beta1/namespaces/default/deployments. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure (OperationSupport.java:470)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode (OperationSupport.java:409)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse (OperationSupport.java:379)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse (OperationSupport.java:343)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate (OperationSupport.java:226)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate (BaseOperation.java:773)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create (BaseOperation.java:356)
    at io.fabric8.kubernetes.api.Controller.doCreateResource (Controller.java:1082)
    at io.fabric8.kubernetes.api.Controller.applyResource (Controller.java:1071)
    at io.fabric8.kubernetes.api.Controller.applyEntity (Controller.java:282)
    at io.fabric8.kubernetes.api.Controller.apply (Controller.java:227)
    at io.fabric8.maven.plugin.mojo.build.ApplyMojo.applyEntities (ApplyMojo.java:414)
    at io.fabric8.maven.plugin.mojo.build.ApplyMojo.executeInternal (ApplyMojo.java:390)
    at io.fabric8.maven.plugin.mojo.AbstractFabric8Mojo.execute (AbstractFabric8Mojo.java:74)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:13 min
[INFO] Finished at: 2020-03-07T09:03:21+08:00
[INFO] ------------------------------------------------------------------------
`

**Comment by nengbowan** [comment]
it can be work with  specialfied with namespace default , but can not get configmap , ignoring  , so i repakcage source config  with print stacktrace , the message is , "User "system:serviceaccount:default:default" cannot get resource "configmaps" in API group "" in the namespace "default"."

**Comment by nengbowan** [comment]
problem get complete well , just also can not automatic deploy app to minikube  , the service account problem has been done  , with docs/src/main/asciidoc/security-service-accounts.adoc 
![image](https://user-images.githubusercontent.com/24314744/76137439-f241e180-6077-11ea-8a1a-0d22c22f72e9.png), so i closed this question , thanks a lot 
half automatic is enough ,just work on develop version
