### ISSUE TITLE
Remove references of spring-cloud-kubernetes-ribbon from docs, samples and poms

### ISSUE THREAD

**Issue by yuchen001** [spring-cloud/spring-cloud-kubernetes#530]
When I upgrade springCloudVersion from SR2 to SR3, spring-cloud-kubernetes appear a problem.
Then spring-cloud-starter-kubernetes-all does not include spring-cloud-kubernetes-ribbon. I went to include alone dependency of spring-cloud-kubernetes-ribbon, but it is failing. spring-cloud-kubernetes-ribbon has not 1.1.2.RELEASE

**Comment by rafaelrenanpacheco** [comment]
Same here, I'm stuck with SR2 because of this issue. This is a simplified pom.xml from my project that breaks with SR3:

```xml
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.2.5.RELEASE</version>
    <relativePath/> <!-- lookup parent from repository -->
</parent>
<properties>
    <java.version>11</java.version>
    <spring-cloud.version>Hoxton.SR3</spring-cloud.version>
</properties>
<dependencies>
    <! -- other dependencies -->
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-kubernetes-ribbon</artifactId>
    </dependency>
</dependencies>
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>${spring-cloud.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

And the output when building the package:

```
[WARNING] The POM for org.springframework.cloud:spring-cloud-starter-kubernetes-ribbon:jar:1.1.2.RELEASE is missing, no dependency information available

[ERROR] Failed to execute goal on project backend: Could not resolve dependencies for project br.com.quadralivre:backend:jar:0.0.1-SNAPSHOT: Failure to find org.springframework.cloud:spring-cloud-starter-kubernetes-ribbon:jar:1.1.2.RELEASE in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
```

**Comment by windcat** [comment]
spring-cloud-kubernetes-ribbon was moved out of Hoxton SR3.
You can use Spring Cloud Loadbalancer
pom.xml added
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
```
application.properties set `spring.cloud.loadbalancer.ribbon.enabled=false`

**Comment by spencergibb** [comment]
That's not correct. The ribbon module was removed long before Hoxton. All you need is the spring cloud starter Netflix ribbon if you want ribbon or as mentioned above you can use spring cloud load balancer

**Comment by rafaelrenanpacheco** [comment]
Hello @spencergibb 

In my case I need is "Ribbon client-side load balancer with server list obtained from Kubernetes Endpoints", which is documented here: https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.1.2.RELEASE/reference/html/#starters

How will I get Kubernetes "client-side load balancer with server list obtained from Kubernetes Endpoints" if I use the deprecated "spring cloud starter Netflix ribbon" or the new "spring cloud load balancer"?

From a user perspective, this I what I get:

- Open https://spring.io/projects/spring-cloud and get the current version, which is Hoxton SR3.
- Open https://spring.io/projects/spring-cloud-kubernetes documentation (which is under the Spring Cloud umbrela)
- Go to https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.1.2.RELEASE/reference/html/#starters which shows 4 available starters to choose from.
- Choose `spring-cloud-starter-kubernetes-ribbon`
- Run the project and get the `The POM for org.springframework.cloud:spring-cloud-starter-kubernetes-ribbon:jar:1.1.2.RELEASE is missing, no dependency information available` error

Is there another way to have client side load balance with kubernetes?

**Comment by spencergibb** [comment]
The documentation is wrong. We'll use this to track updates to the docs

**Comment by ahrytsiuk** [comment]
@spencergibb what do you mean by

> The ribbon module was removed long before Hoxton

It is still present even in the latest `spring-cloud-kubernetes-dependencies` - https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-dependencies/pom.xml#L85

And since version is set to `${project.version}` - it is failing to resolve dependency starting from `spring-cloud-kubernetes-dependencies:1.1.2.RELEASE`
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-kubernetes-ribbon</artifactId>
    <version>${project.version}</version>
</dependency>
```
Because latest release is - `spring-cloud-starter-kubernetes-ribbon:1.1.1.RELEASE`

**Comment by spencergibb** [comment]
@ahrytsiuk that is also an error and needs to be removed from the poms as well.

**Comment by wabrit** [comment]
Apologies for posting here, but I'm unclear as to the resolution for this error if you're using e.g. Hoxton.SR6 and have the `spring-cloud-starter-kubernetes-ribbon dependency` in your POM. Is it simply to remove that dependency? Many thanks.

**Comment by damon008** [comment]
@wind57
Where can I see cases to prove what you said? please provide the url of case.
The case of solutions for access to pods for the other namespace. because our applications maybe not In the same namespace. For example:
```
ns-app          diff-ns-service-deployment-d88b9c4fd-m26t8     1/1     Running   0          6d
system-server   cas-server-deployment-7c84d467f5-4qq6f         1/1     Running   0          7d18h
system-server   cas-server-deployment-7c84d467f5-wjkkw         1/1     Running   0          7d18h
system-server   gateway-service-deployment-766b6747bf-w5twt    1/1     Running   0          5d23h
system-server   rest-service-deployment-cc7c5b559-kkf7f        1/1     Running   0          4d16h
system-server   rest-service-deployment-cc7c5b559-wnsvt        1/1     Running   0          4d16h
```
`diff-ns-service` want to access the app named `rest-service`, but it in the namespace of `system-server`, not in namespace named `ns-app`.

All in all, I hope app named `diff-ns-service` can access the app of `rest-service` By LB, like this : `http://rest-service-service/***`, in the url, `rest-service-service` is the Service of app `rest-service`.

**Comment by damon008** [comment]
I also want to know, In version of Hoxton.SR12, The Ribbon is optional or not?

**Comment by damon008** [comment]
We hope more of cases can be provided for diff verison of spring-cloud-kubernetes.

**Comment by spencergibb** [comment]
Ribbon is optional. There is no longer a ribbon module in spring cloud kubernetes I'm Hoxton. Ribbon is deprecated and removed in 2020.0.0.

**Comment by damon008** [comment]
@spencergibb  In version of `Hoxton.SR12`, how can I solve the case of this:

For example:
```
ns-app          diff-ns-service-deployment-d88b9c4fd-m26t8     1/1     Running   0          6d
system-server   cas-server-deployment-7c84d467f5-4qq6f         1/1     Running   0          7d18h
system-server   cas-server-deployment-7c84d467f5-wjkkw         1/1     Running   0          7d18h
system-server   gateway-service-deployment-766b6747bf-w5twt    1/1     Running   0          5d23h
system-server   rest-service-deployment-cc7c5b559-kkf7f        1/1     Running   0          4d16h
system-server   rest-service-deployment-cc7c5b559-wnsvt        1/1     Running   0          4d16h
```
`diff-ns-service` want to access the app named `rest-service`, but it in the namespace of `system-server`, not in namespace named `ns-app`.

All in all, I hope app named `diff-ns-service` can access the app of `rest-service` By LB, like this : `http://rest-service-service/***`, in the url, `rest-service-service` is the Service of app `rest-service`.

**Comment by damon008** [comment]
@spencergibb  Can you provided the complete dependencies and cases?

**Comment by damon008** [comment]
@spencergibb  If the ribbon module will be removed, how can we realize the app of Hystrix? Also Can use `Netflix Hystrix` when discard ribbon?

**Comment by spencergibb** [comment]
Ribbon and hystrix are managed in spring cloud Netflix

**Comment by damon008** [comment]
@spencergibb  Yeah, but the cases of LB base on `Hoxton.SR12` and ribbon, CAN you provide？

**Comment by damon008** [comment]
In Hoxton.SR12: I CAN also use ribbon:
```
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-kubernetes-ribbon</artifactId>
        </dependency>
```

but it CAN not solve the case of `Support mutual requests for pods under different namespaces #901`.

**Comment by spencergibb** [comment]
No, that dependency doesn't exist in Hoxton. Use spring-cloud-starter-netflix-ribbon. Note that Hoxton has not been supported for some time.

**Comment by damon008** [comment]
@spencergibb  What? Hoxton has not been supported? or ribbon not be supported in Hoxton ?

**Comment by spencergibb** [comment]
Ribbon is part of Hoxton, but not later releases. https://github.com/spring-cloud/spring-cloud-release/wiki/Supported-Versions#supported-releases

**Comment by damon008** [comment]
@spencergibb  If not use ribbon,:
```
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
```
How can set the LB of timeout.and the LB clients like this:
```
backend:
  ribbon:
    client:
      enabled: true
    ServerListRefreshInterval: 5000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 1000
  eager-load:
    enabled: true
    clients: A,B,C
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
```

**Comment by damon008** [comment]
@spencergibb I CAN not understand what you said. I know Spring Cloud Kubernetes 1.1.10.RELEASE in the Hoxton.SR12. how can I  solve the cases: `mutual requests for pods under different namespaces`

**Comment by marcellodesales** [comment]
Why would we use ribbon when kubernetes services would do the load balancing transparently? 

@damon008 because a deployment is the driving force of Pods and they will be placed in a fixed namespace... I don't think there's such scheduler in k8s that would place pods in different namespaces...
