### ISSUE TITLE
similar to bug 497 

### ISSUE THREAD

**Issue by nengbowan** [spring-cloud/spring-cloud-kubernetes#533]
spring boot 1.5.3 
spring cloud kubernetes    v1.1.1

#https://github.com/spring-cloud/spring-cloud-kubernetes/issues/497

getInputStream:172, ClassPathResource (org.springframework.core.io)
<init>:50, SimpleMetadataReader (org.springframework.core.type.classreading)
getMetadataReader:98, SimpleMetadataReaderFactory (org.springframework.core.type.classreading)
createMetadataReader:89, ConcurrentReferenceCachingMetadataReaderFactory (org.springframework.boot.type.classreading)
getMetadataReader:76, ConcurrentReferenceCachingMetadataReaderFactory (org.springframework.boot.type.classreading)
getMetadataReader:93, SimpleMetadataReaderFactory (org.springframework.core.type.classreading)
getAnnotationMetadata:213, AutoConfigurationSorter$AutoConfigurationClass (org.springframework.boot.autoconfigure)
getAnnotationValue:198, AutoConfigurationSorter$AutoConfigurationClass (org.springframework.boot.autoconfigure)
readBefore:186, AutoConfigurationSorter$AutoConfigurationClass (org.springframework.boot.autoconfigure)
<init>:158, AutoConfigurationSorter$AutoConfigurationClass (org.springframework.boot.autoconfigure)
<init>:115, AutoConfigurationSorter$AutoConfigurationClasses (org.springframework.boot.autoconfigure)
getInPriorityOrder:57, AutoConfigurationSorter (org.springframework.boot.autoconfigure)
sort:241, AutoConfigurationImportSelector (org.springframework.boot.autoconfigure)
selectImports:98, AutoConfigurationImportSelector (org.springframework.boot.autoconfigure)
processDeferredImportSelectors:547, ConfigurationClassParser (org.springframework.context.annotation)
parse:185, ConfigurationClassParser (org.springframework.context.annotation)
processConfigBeanDefinitions:308, ConfigurationClassPostProcessor (org.springframework.context.annotation)
postProcessBeanDefinitionRegistry:228, ConfigurationClassPostProcessor (org.springframework.context.annotation)
invokeBeanDefinitionRegistryPostProcessors:270, PostProcessorRegistrationDelegate (org.springframework.context.support)
invokeBeanFactoryPostProcessors:93, PostProcessorRegistrationDelegate (org.springframework.context.support)
invokeBeanFactoryPostProcessors:686, AbstractApplicationContext (org.springframework.context.support)
refresh:524, AbstractApplicationContext (org.springframework.context.support)
refresh:122, EmbeddedWebApplicationContext (org.springframework.boot.context.embedded)
refresh:737, SpringApplication (org.springframework.boot)
refreshContext:370, SpringApplication (org.springframework.boot)
run:314, SpringApplication (org.springframework.boot)
run:1162, SpringApplication (org.springframework.boot)
run:1151, SpringApplication (org.springframework.boot)
main:12, RibbonWithServiceApplication (com.fsy.demo)

![图片](https://user-images.githubusercontent.com/24314744/76742410-04283080-67ac-11ea-86a2-5b93be20ed3d.png)

**Comment by spencergibb** [comment]
Spring boot 1.x is no longer supported. Please upgrade to 2.1.12 and try again

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
