### ISSUE TITLE
why use ribbon in k8s?How about clusterIp?

### ISSUE THREAD

**Issue by zhuenjun** [spring-cloud/spring-cloud-kubernetes#541]
I think clusterIp Instead of ribbon,,,,

**Comment by spencergibb** [comment]
For most cases that's probably fine. But there will always be cases when the user needs to choose the load balancing algorithm.

**Comment by mteodori** [comment]
as a k8s service is already a load balancer, isn't suggesting another on top an anti pattern?

**Comment by spencergibb** [comment]
Not in all cases

**Comment by mteodori** [comment]
I would like to understand better the use case, as in activiti cloud we started with eureka and then after moving to k8s all discovery and load balancing did look better served and managed by the platform rather than having an extra layer in between

**Comment by ryanjbaxter** [comment]
There might be certain apps served better by client side load balancing, especially in cases where they may need more control of it.  When load balancing is placed at the platform level, the app has no control over how that happens.

**Comment by ojhughes** [comment]
clusterIp only supports round robins. You need to configure IPVS on the cluster for more LB algorithms [1]. This is a non-trivial change and most vendors don't support it today. In the future, client side LB will be less compelling as the server side options improve but today client side is the only option if you want a more sophisticated algo. 

Another reason - Client Side LB will work on any cloud, not just k8s, which is useful for some people

1: https://kubernetes.io/blog/2018/07/09/ipvs-based-in-cluster-load-balancing-deep-dive/

**Comment by mteodori** [comment]
thank you all for the clarifications!

**Comment by gaochundong** [comment]
thanks
