### ISSUE TITLE
can you pull the version 1.1.2.RELEASE. to mvnrepository when i use Hoxton.SR3 it whi

### ISSUE THREAD

**Issue by flowclouds** [spring-cloud/spring-cloud-kubernetes#543]

**Comment by flowclouds** [comment]
![image](https://user-images.githubusercontent.com/40859714/78327516-a8351880-75af-11ea-833a-e4757a3a2bde.png)
![image](https://user-images.githubusercontent.com/40859714/78327528-af5c2680-75af-11ea-9b68-59ca25e06fdb.png)

**Comment by spencergibb** [comment]
That screenshot doesn't explain anything. Can you please explain your problem?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by rafaelrenanpacheco** [comment]
I'm guessing this is related to #530, in which case this is a duplicated issue.

**Comment by flowclouds** [comment]
yes,thanks i know change dependencies,
