### ISSUE TITLE
Spring cloud gateway is not working in kubernetes

### ISSUE THREAD

**Issue by narasimhamurthyk3** [spring-cloud/spring-cloud-kubernetes#545]
Hi Team,

I am developing micro-services with following configurations

Eureka discovery service with spring cloud gateway and oAuth2 authentication

All configurations working perfectly in my local IDE and in tomcat server also in docker.

Now I am trying to run in kubernetes cluster and in kubernetes everything is working except spring cloud api gateway..

Request to share your experience.
Did any one implemented spring cloud gateway with eureka discovery service in kubernetes.

**Comment by narasimhamurthyk3** [comment]
Hi after doing debug I found the issue is in eureka server 

As I am using lb:

**Comment by ryanjbaxter** [comment]
There is no point in using Eureka with Kubernetes.  Spring Cloud Kubernetes provides its own DiscoveryClient implementation.

https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.1.1.RELEASE/reference/html/#discoveryclient-for-kubernetes

**Comment by narasimhamurthyk3** [comment]
@ryanjbaxter thanks for your advice.

I am able to fix that issue with ip address 
eureka:
  instance:
     prefer-ip-address: true
