### ISSUE TITLE
Event mode isn't working for ConfigMap in a namespace

### ISSUE THREAD

**Issue by anoophp777** [spring-cloud/spring-cloud-kubernetes#559]
I've a ConfigMap in a namespace **some-ns.** I've a **@Scheduled** task which prints from the ConfigMap. I've also configured **_mode: event_**. This doesn't pickup the configuration change.

However, if I change the mode from event to polling, it picks up the config changes.

I have a sample example in my GitHub so its easy to reproduce.

https://github.com/anoophp777/scheduler-configmap-hotrefresh

Follow the readme file. To reproduce the issue, you can run the ./build-deploy-to-kubernetes.sh

and modify any property in the ConfigMap and run kubectl replace -f kube-configmap.yml.

If you change the mode from event to polling you can see the issue doesn't recur.

**Why doesn't the event work but polling does?**

**Comment by Haybu** [comment]
it works just fine with versions s-boot 2.3.0.RELEASE and s-cloud Hoxton.SR5

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
