### ISSUE TITLE
Does Spring cloud kubernetes service discovery works for selected namespaces?

### ISSUE THREAD

**Issue by srinathsingari** [spring-cloud/spring-cloud-kubernetes#566]
Currently I see, spring.cloud.kubernetes.discovery.all-namespaces=true -> discovers the services from all the namespaces in the entire cluster.

spring.cloud.kubernetes.discovery.all-namespaces=false -> discovers the services in the current namespace, i,e the namespace in which the application has been deployed.

Is there any property something like - spring.cloud.kubernetes.discovery.namespaces= namespace-a, namespace-b, namespace-c

So that I can discover services only in specific namespaces as needed.

**Comment by Haybu** [comment]
correct, either current namespace or all namespaces are currently supported, no selectable ones yet.

**Comment by sherifkayad** [comment]
@Haybu is there a way that one could customize / extend the Kubernetes Client with code to enforce certain namespaces?
