### ISSUE TITLE
Suspect incorrect configuration applied in KubernetesAutoConfiguration

### ISSUE THREAD

**Issue by ilmtee** [spring-cloud/spring-cloud-kubernetes#572]
**Describe the bug**
I suspect that an issue connecting to cluster using password is caused by password being set incorrectly in KubernetesAutoConfiguration class.

**Sample**
`				.withPassword(or(kubernetesClientProperties.getProxyPassword(),
						base.getProxyPassword()))
`
If this is meant to set password instead of proxyPassword, a comment to explain why would probably be prudent.

**Comment by spencergibb** [comment]
should probably be `withProxyPassword`

**Comment by spencergibb** [comment]
Duplicates #564
