### ISSUE TITLE
Add support for Dekorate

### ISSUE THREAD

**Issue by piomin** [spring-cloud/spring-cloud-kubernetes#575]
**Is your feature request related to a problem? Please describe.**
I think it's worth to consider built-in support for dekorate (http://dekorate.io/).

**Describe the solution you'd like**
Currently there is support for Spring Boot in Dekorate (https://github.com/dekorateio/dekorate/tree/master/frameworks/spring-boot). It is also able to detect spring-cloud-kubernetes and generate for example RoleBinding required for running app with Spring Cloud Kubernetes.

**Comment by spencergibb** [comment]
what would we do considering deokorate already has this support?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by piomin** [comment]
Well, we could include that dependency, provide ability to use some properties with prefix spring.cloud.kubernetes.* and after that add such information in documentation  (not everybody knows that library)

**Comment by ryanjbaxter** [comment]
Why not put this in Dekorate itself?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
