### ISSUE TITLE
Code sections in documentation are unreadable

### ISSUE THREAD

**Issue by adzubla** [spring-cloud/spring-cloud-kubernetes#576]
The color theme of code sections make them almost impossible to read... Black fonts over dark background.

https://cloud.spring.io/spring-cloud-kubernetes/1.1.x/reference/html/

![Screenshot_20200630_122819](https://user-images.githubusercontent.com/9607562/86146619-d6eb5e00-bace-11ea-8bd1-88eb93fff6c1.png)

**Comment by spencergibb** [comment]
I believe this has been fixed https://docs.spring.io/spring-cloud-kubernetes/docs/1.1.x-SNAPSHOT/reference/html/

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
