### ISSUE TITLE
Can Kubernetes secrets be used in bootstrap?

### ISSUE THREAD

**Issue by cpatil7** [spring-cloud/spring-cloud-kubernetes#578]
Hello Team,
We are trying to deploy spring boot micro-services on AKS and secrets would be mounted on a volume(/mnt/application-store).
Reference Architecture, similar to this -https://github.com/Azure-Samples/piggymetrics

Pre-requisite
1. Added a reference to “spring-cloud-starter-kubernetes-config” in build.gradle file
2. Properties to be set in DockerFile
-Dspring.cloud.kubernetes.secrets.enabled=true","-Dspring.cloud.kubernetes.secrets.paths=/mnt/application-store"

1. Spring boot config server -> which provides the configuration for other services.Its Application.yml as below
![image](https://user-images.githubusercontent.com/40123664/86265502-7862d480-bbe1-11ea-9a0a-f0e618cfd0f5.png)

Once config server is up & running in AKS, we are able to login using the password mentioned in the secret path, this implies that Application.yml was able to read the value for CONFIG-SERVICE-PASSWORD from secret path

2. In Registry(Eureka Server) bootstrap.yml file, we were expecting CONFIG-SERVICE-PASSWORD parameter to read value from secrets, while connecting to Config server.
![image](https://user-images.githubusercontent.com/40123664/86265886-063ebf80-bbe2-11ea-8dff-0be5155b0663.png)

However, when Registry was up & running, noticed that it was try to connect to config server through null/empty hence we received 401 unauthorized as shown below
![image](https://user-images.githubusercontent.com/40123664/86266202-78170900-bbe2-11ea-9918-1a1f65938c55.png)
 
Would like to know if there are know limitation that values configured in bootstrap.yml file will not be able to resolve values from secrets path

**Other options tried, could not succeed**
1. We tried mentioned kubernetes secrets enabled=true & path=/mnt/application-store in bootstrap.yml file even that didnot work.
2. Tried with initContainer to make sure that secrets are available in the mentioned path before the Application container starts

**Please note we are using Azure Key Vault CSI driver for mounting secrets on POD container**

Any pointer on this would be helpful.

**Comment by cpatil7** [comment]
@spencergibb - Please would be able to have a look and provide your inputs this is a blocker for production

**Comment by spencergibb** [comment]
It's likely an ordering problem between bootstrap configuration for config server and Kubernetes secrets.

**Comment by spencergibb** [comment]
Even besides ordering problems, values fetched in one property source locator (k8s secrets) are currently not available to other property source locators (these are interfaces defined in spring-cloud-commons). It is a chicken and egg problem.

**Comment by cpatil7** [comment]
@spencergibb - Thanks for your quick response, do we need some time to investigate?  because it looks like secrets are mounted and available for consumption but for some reason bootstrap.yml is not able to pick the values

**Comment by spencergibb** [comment]
I told you why you can't see the values in bootstrap. They are obtained in bootstrap and not available until the regular application context.

**Comment by cpatil7** [comment]
@spencergibb - Thanks for your support & great work around support for spring cloud kubernetes. Closing the ticket.

**Comment by Haybu** [comment]
what's about the config server to turn around and source the bounded password. I.e., the config server to define
CONFIG-SERVICE-PASSWORD = ${CONFIG-SERVICE-PASSWORD} on one of its native classpath://shared property resources.

**Comment by cpatil7** [comment]
@spencergibb @spring-issuemaster  - Do you think it would be good feature to be considered for any future releases

**Comment by ryanjbaxter** [comment]
@cpatil7 what feature specifically?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by voodemsanthosh** [comment]
> @spencergibb - Thanks for your support & great work around support for spring cloud kubernetes. Closing the ticket.

Hey, I am would like to know the work around for it. We also keeping config server username and password in Kubernates secrets and those are not loading on bootstrap the application.

cc @[cpatil7](https://github.com/cpatil7)

**Comment by ryanjbaxter** [comment]
Could you not provide the value as an environment variable in the deployment.yaml?
https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

**Comment by voodemsanthosh** [comment]
> Could you not provide the value as an environment variable in the deployment.yaml? https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

@ryanjbaxter Yes, I can use env variables. I would like to make more secure by using Vault, so thinking to have my creds in Vault and reading from Vault.

**Comment by ryanjbaxter** [comment]
I'm confused then, what does this have to do with Spring Cloud Kubernetes?

**Comment by voodemsanthosh** [comment]
@ryanjbaxter,

Here is my requirement,

We have config server and config client.
config client connect config server using username/password to read config client properties.

bootstrap.yml
--------------------
spring:
  application:
    name: template
  cloud:
    config:
      failFast: true
      enabled: true 
      uri: http://localhost:8888
      username: ${spring.cloud.config.username}
      password: ${spring.cloud.config.password}
      name: template
 
    --------------------
Now I want to secure config server username/password in Kubernates secrets and on config client deployment we need to read username/password from Kubernates secrets and connect config server.

`
      username: ${spring.cloud.config.username}
      password: ${spring.cloud.config.password}
`
should read from Kubernate secrets on template service deployment.

Please let me know if you have any questions.

**Comment by ryanjbaxter** [comment]
My suggestion is to have the username and password values set as environment variables populates by secrets from Kubernetes when deployed.  In other words you wouldn't need spring cloud kubernetes at all to do that.

**Comment by voodemsanthosh** [comment]
@ryanjbaxter I have fixed this now.

I have added config server creds to kubernates secrets and reading at config client level using below keys

     username: ${SPRING_CLOUD_CONFIG_USERNAME}
     password: ${SPRING_CLOUD_CONFIG_PASSWORD}

Thank you all your support and help !!!.
