### ISSUE TITLE
In multi port service, the port name cannot be filtered

### ISSUE THREAD

**Issue by odeng888** [spring-cloud/spring-cloud-kubernetes#581]
version: 1.1.4.RELEASE 

There is a bug:

Class: KubernetesServicesServerList  and KubernetesEndpointsServerList->getUpdatedListOfServers()
> for (ServicePort servicePort : service.getSpec().getPorts()) {
	if (Utils.isNotNullOrEmpty(this.getPortName())
	   **here->**	|| this.getPortName().endsWith(servicePort.getName())) {
				result.add(new Server(concatServiceFQDN(service),
								servicePort.getPort()));
		}
	}

why is Or relationship？

**Comment by ryanjbaxter** [comment]
I am not sure what the problem is, can describe what the consequence is?

**Comment by ryanjbaxter** [comment]
There was also some proposed changes to this logic here https://github.com/spring-cloud/spring-cloud-kubernetes/pull/634

I am unsure if it is related or not.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
