### ISSUE TITLE
Optional property to get notReadyAddress instances.

### ISSUE THREAD

**Issue by claitonp** [spring-cloud/spring-cloud-kubernetes#584]
Hi,

You could add an optional property to get the **notReadyAddress** instances in the classes:

1. KubernetesDiscoveryClient - method getNamespaceServiceInstances ();
2. KubernetesCatalogWatch - method catalogServicesWatch ()

Example:  spring.cloud.kubernetes.discovery.notReadyAddress.enabled,  default false.

```
private List<ServiceInstance> getNamespaceServiceInstances(EndpointSubsetNS es, String serviceId) {
	...
	List<EndpointAddress> addresses = s.getAddresses();
	for (EndpointAddress endpointAddress : addresses) {
		...
	}
	
       // HERE /////////////////////////////
	if (notReadyAddressEnabled) 
		List<EndpointAddress> notReadyAddresses = s.getNotReadyAddresses();
		for (EndpointAddress endpointAddress : notReadyAddresses) {  // the same logic addresses.
		   ...
		}
	}
        //////////////////////////

	return instances;  // return instances addresses e notReadyAddresses.
}
```

Thanks
Claiton

**Comment by spencergibb** [comment]
Can you please describe why you would want this?

**Comment by claitonp** [comment]
For better monitoring integration. For example with spring boot admin and spring cloud kubernentes, to get the bad instances.

**Comment by spencergibb** [comment]
I'm afraid I don't see how that is helpful. Why would a user of spring cloud kubernetes want the bad instances?

**Comment by claitonp** [comment]
In Spring Cloud Gateway I use Spring Cloud Kubernetes to get only good instances and two other applications.

I also use Spring Cloud Kubernetes in the SBA and in this one it would be interesting to get the good and bad instances, for a better visualization on the wallboard.

Bad instances using Spring Cloud Kubernetes are removed from the wallboard view.

[wallboard ](https://user-images.githubusercontent.com/8779225/37558711-84f93dc2-2a18-11e8-8e1b-10ad60f8e80a.png)

**Comment by stevengibbszions** [comment]
@spencergibb  - I agree that this would be a useful feature.  When monitoring spring boot microservices with a tool like Spring Boot Admin, you could maintain visibility of a service endpoints (and the reason's why its failing probes, for example) if the service discovery mechanism returned the bad endpoints also.  That endpoint might be "live" but not "ready".  

In the current state, if the pod goes to "not ready" then you lose visibility.

I'd be interested in doing a PR if you were open to the idea.

**Comment by patpatpat123** [comment]
+1
