### ISSUE TITLE
Security Vulnerabilities reported in Spring Cloud Kubernetes

### ISSUE THREAD

**Issue by RishuK** [spring-cloud/spring-cloud-kubernetes#587]
Issue found in : 

spring-cloud-kubernetes-config-1.1.4.RELEASE.jar
spring-cloud-kubernetes-core-1.1.4.RELEASE.jar

Please check this link: 

https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Akubernetes&cpe_product=cpe%3A%2F%3Akubernetes%3Akubernetes&cpe_version=cpe%3A%2F%3Akubernetes%3Akubernetes%3A1.1.4

Any workarounds or solutions for this yet?

**Comment by spencergibb** [comment]
Duplicates #586
