### ISSUE TITLE
Missing documentation for 1.1.5 RELEASE and no version compatibility matrix

### ISSUE THREAD

**Issue by gdubya** [spring-cloud/spring-cloud-kubernetes#601]
According to [the 'learn' documentation](https://spring.io/projects/spring-cloud-kubernetes#learn) the latest GA release is version 1.1.3, however [in maven central](https://search.maven.org/artifact/org.springframework.cloud/spring-cloud-starter-kubernetes-all) it looks like the latest is 1.1.5.

Is there a reason the documentation is falling behind the actual latest release version?

Some of the links on the 'learn' page also give 404s (e.g. [1.0.4 RELEASE](https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.0.4.RELEASE/)).

Also, is there a version compatibility matrix somewhere? we are using an older version of spring boot (2.1.x) but i don't think that's compatible with spring-cloud-kubernetes 1.1.x.

**Comment by lanmingle** [comment]
I think this should be just a transitional version, the focus of the follow-up is to eliminate Netflix related.

**Comment by spencergibb** [comment]
We're in the middle of a release

**Comment by gdubya** [comment]
Ah ok. Can i refine the scope of this issue then to just a request for a Kubernetes / Spring Boot version compatibility matrix on the 'overview' page for Spring Cloud Kubernetes, similar to [Spring for Apache Kafka](https://spring.io/projects/spring-kafka) client compatibility?

**Comment by ryanjbaxter** [comment]
Compatibility can be found here https://spring.io/projects/spring-cloud
