### ISSUE TITLE
Modular spring boot app doesn't boot due to InvalidModuleDescriptorException

### ISSUE THREAD

**Issue by fransguelinckx** [spring-cloud/spring-cloud-kubernetes#611]
# Describe the bug
**spring-cloud-kubernetes version**: 1.1.5.RELEASE
**spring-boot version**: 2.3.3.RELEASE
The app has a module-info.java file.

When booting the application, the console shows the following error:
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for /Users/fransg/.m2/repository/io/fabric8/kubernetes-model-rbac/4.10.3/kubernetes-model-rbac-4.10.3.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Provider class io.fabric8.kubernetes.internal.InternalResourceMappingProvider not in module

Process finished with exit code 1
```

When I use version 2.0.0-M3 of spring-cloud-kubernetes, it works without errors. My guess is that it's because there is a dependency on an old version of io.fabric8:kubernetes-client: 4.9.0.
When I bump the Kubernetes-client version to 4.11.0, it gives me the same error again.

My concern is that it gets broken again when a new 2.0.0 snapshot of spring-cloud-kubernetes gets released, because I see that the client library gets bumped in recent commits.

# Sample
I made a simple spring boot app that reproduces the bug: https://github.com/fransguelinckx/demo
It has three branches that contains the scenarios I described above.
* **1.1.5.RELEASE**: broken
* **2.0.0-M3**: works
* **2.0.0-M3-with-fabric8-4.11.0**: broken

**Comment by ryanjbaxter** [comment]
can you tell me how to reproduce this issue with the sample?

**Comment by fransguelinckx** [comment]
Apparently the issue only occurs when I try to start the application in IntelliJ with a spring boot run configuration. I can't reproduce the issue when I build and run the spring boot jar, so that sounds like an IntelliJ issue?

**Comment by ryanjbaxter** [comment]
Yeah, or something specific to your environment.  I will close this for now.
