### ISSUE TITLE
Wrong type of watchReconnectLimit in KubernetesClientProperties

### ISSUE THREAD

**Issue by hudi1** [spring-cloud/spring-cloud-kubernetes#614]
I am pretty sure that watchReconnectLimit in KubernetesClientProperties:

```
private Duration watchReconnectLimit;
```

should not be Duration but Integer. Default value in kubernetes configs:

```
  private int watchReconnectInterval = 1000;
  private int watchReconnectLimit = -1;
```
and even in documentation there is no duration as default value:

https://cloud.spring.io/spring-cloud-kubernetes/1.1.x/reference/html/appendix.html

**Comment by ryanjbaxter** [comment]
Why?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
