### ISSUE TITLE
Add spring boot starter to create/update ConfigMap and Secrets in Kubernetes

### ISSUE THREAD

**Issue by diwanc** [spring-cloud/spring-cloud-kubernetes#620]
**Is your feature request related to a problem? Please describe.**
`spring-cloud-kubernetes` allows applications on bootstrap to read externalized properties from "pre-existing" kubernetes ConfigMaps and Secrets. Its however a prerequisite for the ConfigMaps/Secrets to be created by someone already. It would  be nice to bring in the other way of spring boot and kubernetes integration to create ConfigMaps and Secrets in kubernetes from the files (properties and yamls) that application developers typically provide in the resources folder of the application code.

**Describe the solution you'd like**
Usecase would be for spring app developers  in a single LOB or multiple LOBs to collaborate and add application properties/yaml files in a spring app repo in git following standard conventions, say frontend-application.properties, db-connector-application.properties etc. On running this app in k8s, automatically create corresponding configmaps which other apps frontend and db-connector can read and load the properties from, using existing `spring-cloud-kubernetes-config`. Similar feature can be extended to Secrets too

**Describe alternatives you've considered**

**Additional context**

Seeking feedback on this enhancement proposal. I am interested in contributing to this feature if the usecase makes sense

**Comment by spencergibb** [comment]
I'm going to mark it as for team discussion, but I'm pretty sure this is out of scope for this project.

**Comment by diwanc** [comment]
@spencergibb Thanks. Would be good to know thoughts on this. Also is there another project that deals with this kind of integration?

**Comment by spencergibb** [comment]
After some conversation, we've decided to close this. All spring cloud projects dealing with configuration are read only. We don't want to create config maps.
