### ISSUE TITLE
why not use /${service}.${namespace}/** as the path pattern?

### ISSUE THREAD

**Issue by junneyang** [spring-cloud/spring-cloud-kubernetes#629]
1、environment info:
spring-cloud-kubernetes + spring-cloud-gateway

2、enable gateway discovery locator
spring.cloud.gateway:discovery.locator.enabled = true

3、then gateway generate the default route like：
Path=/serviceName/**   URI=lb:serviceName

my question is：how to support multiple namespace service proxy？
i suggest the router like this：
Path=/serviceName.namespace/**   URI=lb:serviceName.namespace

or in other word, if i have two same service in different namespace, how to access the service by gateway?
or how can i change the default route generator?

thanks for your help!

**Comment by spencergibb** [comment]
Can you please provide more information than just a title?

**Comment by junneyang** [comment]
@spencergibb  provide some info, looking forward to your help, thanks

**Comment by spencergibb** [comment]
3 things need to happen
1. all namespaces support would need to be enabled
2. You can update the filters via properties to match on metadata.namespace
3. You would need to configure loadbalancer with namespace filter (again based on metadata @OlgaMaciaszek can comment more on that).

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by junneyang** [comment]
> 3 things need to happen
> 
> 1. all namespaces support would need to be enabled
> 2. You can update the filters via properties to match on metadata.namespace
> 3. You would need to configure loadbalancer with namespace filter (again based on metadata @OlgaMaciaszek can comment more on that).


thanks, but if i have two same service-name in different namespace, how to access these two services respectively?

**Comment by spencergibb** [comment]
@junneyang the 3 things I listed will provide that. They just need to happen across 3 different projects and I know you can do the first two.

**Comment by junneyang** [comment]
> @junneyang the 3 things I listed will provide that. They just need to happen across 3 different projects and I know you can do the first two.

thanks
