### ISSUE TITLE
Cannot find the service from gateway 

### ISSUE THREAD

**Issue by superleo-cn** [spring-cloud/spring-cloud-kubernetes#630]
Hi, I tried to setup a gateway and springboot application by spring-cloud-kubernetes, however, the gateway is not able to find the springboot application.

- spring-boot: 2.2.6.RELEASE
- spring-cloud: Hoxton.SR5
- spring-cloud-kubernetes: 1.1.3

The application is very simple, I have uploaded my demo under below link:

[https://github.com/superleo-cn/k8s-demo](https://github.com/superleo-cn/k8s-demo)

**Comment by spencergibb** [comment]
Can you please describe "the gateway is not able to find the springboot application" and provide instructions on how to recreate the problem. It would also be worth updating to Hoxton.SR8 and boot 2.2.10 or 2.3.3

**Comment by superleo-cn** [comment]
After the deployment, we can get the below services:

```bash
~  kubectl get svc -n k8s-demo                                                                                                                                                                                               
NAME              TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
cfd-rest          NodePort   10.106.89.244   <none>        8020:30001/TCP   109s
gateway-service   NodePort   10.106.247.2    <none>        9000:30000/TCP   109s

```
For Example,  if I directly access the springboot application `cfd-rest`, 

```bash

curl -i http://localhost:30001/cfd/orders/123456

```

We can directly get the output from console:

```bash
HTTP/1.1 200
Content-Type: application/json
Transfer-Encoding: chunked
Date: Mon, 14 Sep 2020 15:35:52 GMT

{"code":"ca5586cc-241f-4213-986b-9ae3c05c87f9","orderId":"123456"}

``` 

But If I access it from gateway:

```bash

curl -i http://localhost:30000/cfd/orders/123456

```

The error message pops up:

```bash

Whitelabel Error Page
This application has no configured error view, so you are seeing this as a fallback.

Mon Sep 14 15:30:52 GMT 2020
[5ed38292-9] There was an unexpected error (type=Service Unavailable, status=503).
Unable to find instance for cfd-rest

```


The gateway is very simple, just like this:

```java

@Slf4j
@EnableScheduling
@SpringBootApplication
@EnableDiscoveryClient
public class GatewayApplication {

    public static void main(String[] args) {
        SpringApplication.run(GatewayApplication.class, args);
    }

    @Bean
    public RouteLocator routes(RouteLocatorBuilder builder) {
        return builder.routes()
                .route("cfd-rest", r -> r.path("/cfd/**").uri("lb://cfd-rest"))
                .build();
    }

}




```

**Comment by spencergibb** [comment]
Unfortunately that little bit of gateway isn't enough. What are your dependencies and configuration?

**Comment by superleo-cn** [comment]
> Can you please describe "the gateway is not able to find the springboot application" and provide instructions on how to recreate the problem. It would also be worth updating to Hoxton.SR8 and boot 2.2.10 or 2.3.3

Just now, I upgraded to 

spring-boot: 2.2.9.RELEASE
spring-cloud: Hoxton.SR8
spring-cloud-kubernetes: 1.1.6

everything works fine.  Please close the issue.

**Comment by superleo-cn** [comment]
> Unfortunately that little bit of gateway isn't enough. What are your dependencies and configuration?

The update-to-date dependencies of springboot/spring cloud can resolve the issue.
