### ISSUE TITLE
how can i override the default KubernetesDiscoveryClient ?

### ISSUE THREAD

**Issue by junneyang** [spring-cloud/spring-cloud-kubernetes#633]
is there any way to change the default KubernetesDiscoveryClient ,thanks for your help

**Comment by ryanjbaxter** [comment]
If you provide your own bean of `KubernetesDiscoveryClient` we should use that.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
