### ISSUE TITLE
Activate the kubernetes profile without API requests

### ISSUE THREAD

**Issue by josecv** [spring-cloud/spring-cloud-kubernetes#656]
**Is your feature request related to a problem? Please describe.**
Currently, when spring-cloud-kubernetes starts up, it decides to activate the `kubernetes` profile based on whether a `get pod` call succeeds. This requires that the API server be up and reachable, and it requires that the application have permissions to `get pods`.

**Describe the solution you'd like**
Activation of the `kubernetes` profile could be based, for example, on the presence of an [environment variable](https://stackoverflow.com/a/54130803)

**Describe alternatives you've considered**
I guess the alternative could be to manually activate the profile, but then the issue is that each microservice that uses `spring-cloud-kubernetes` would have to be configured to activate the profile when running in kubernetes.

**Comment by ThomasVitale** [comment]
@ryanjbaxter can I help with this task?

**Comment by ryanjbaxter** [comment]
@ThomasVitale for sure!  We would appreciate it!

**Comment by ho-autonomic** [comment]
why don't we add `generateSimplePermissions: true` to the base chart? from the wiki: https://autonomic-ai.atlassian.net/wiki/spaces/DnD/pages/1319764138/2020-10-15+Default+service+account+losing+kubernetes+permissions

all cases need `generateSimplePermissions: true`.

**Comment by ThomasVitale** [comment]
@ryanjbaxter I opened a PR here: https://github.com/spring-cloud/spring-cloud-kubernetes/pull/671

I added a check for the presence of the KUBERNETES_SERVICE_HOST env var. I did some research and couldn't find a final confirmation that the env var is always set (there have been a few issues registered about it), so I also kept the existing check as a fallback. What do you think?
