### ISSUE TITLE
Informer Based Discovery Client Should Default To Current Namespace

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-kubernetes#678]
Currently the informer based discovery client needs cluster wider permissions.  This is due to a limitation in the Kubernetes Java Client.

See https://github.com/kubernetes-client/java/pull/1409

We will need to update the Kubernetes Java Client version and revert these changes
https://github.com/spring-cloud/spring-cloud-kubernetes/commit/40cef547ced165f4ddc3adfd753b442f29b45b57#diff-4a16634dd21836d945914f0b1c0a5ce44df4246dd23394a19d1801e3c7350b53L12

**Comment by yue9944882** [comment]
thanks!

**Comment by ryanjbaxter** [comment]
@yue9944882 could we get a new release of the Kubernetes Java Client so we can include this in the upcoming 2020.0.0 release?

**Comment by yue9944882** [comment]
@ryanjbaxter sure, hopefully we will be seeing a new release this week i think https://github.com/kubernetes-client/java/issues/1441
