### ISSUE TITLE
Move informer based discovery client integration test to use Kind

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-kubernetes#679]
Merge this [PR](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/677) first and then move the IT

https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-integration-tests/discovery/kubernetes-client-discovery

**Comment by yue9944882** [comment]
@ryanjbaxter i will take care of this ;)

**Comment by ryanjbaxter** [comment]
Thanks!

**Comment by wind57** [comment]
@ryanjbaxter looks like this one can be closed.
