### ISSUE TITLE
Support Updating Metadata in KubernetesServiceInstance

### ISSUE THREAD

**Issue by locorider** [spring-cloud/spring-cloud-kubernetes#70]
Currently **getMetadata()** in **KubernetesServiceInstance** returns
``` java
Collections.EMPTY_MAP
```
But other libraries like the *axon-distributed-commandbus-springcloud* use Metadata to store information like load factor. ([SpringCloudCommandRouter.java](https://github.com/AxonFramework/AxonFramework/blob/axon-3.0.x/distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouter.java#L98))

It would be great if there would be some kind of support for those use cases.

**Comment by spencergibb** [comment]
See 1e71319f9f7baa73a378f16da37ad1ee5d976754
