### ISSUE TITLE
Move To Kubernetes Java Client 11.0.0

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-kubernetes#705]

**Comment by ryanjbaxter** [comment]
@yue9944882 I tried to move to the latest release but it looks like some of the autoconfiguration has perhaps changed.  When the informer discovery client auto configuration runs the `Lister` beans are not being created.

```
Parameter 2 of method kubernetesInformerDiscoveryClient in org.springframework.cloud.kubernetes.client.discovery.KubernetesDiscoveryClientAutoConfiguration$KubernetesInformerDiscoveryConfiguration required a bean of type 'io.kubernetes.client.informer.cache.Lister' that could not be found.
```

Debugging, `KubernetesInformerFactoryProcessor` does not seem to find the annotations.

**Comment by yue9944882** [comment]
@ryanjbaxter am trying to reproduce that in https://github.com/spring-cloud/spring-cloud-kubernetes/pull/708, but it seems to be blocking on some other errors.. i will investigate

**Comment by tony-clarke-amdocs** [comment]
I would suggest you do not adopt 11.0.0. See this [defect](https://github.com/kubernetes-client/java/issues/1533)

**Comment by ryanjbaxter** [comment]
@tony-clarke-amdocs actually I already did this
https://github.com/spring-cloud/spring-cloud-kubernetes/pull/708

Under what circumstances does that error occur?

**Comment by ryanjbaxter** [comment]
Closed in #708

**Comment by tony-clarke-amdocs** [comment]
> @tony-clarke-amdocs actually I already did this
> #708
> 
> Under what circumstances does that error occur?

As soon as the resourceVersion is too old. Typically just need to wait 10 minutes or so. It's not adoptable in this state.

**Comment by ryanjbaxter** [comment]
And it occurs for any resource?  I noticed the stacktrace in the issue was specific to ConfigMaps...

**Comment by tony-clarke-amdocs** [comment]
> And it occurs for any resource? I noticed the stacktrace in the issue was specific to ConfigMaps...

Yes, any resource where a list/watch had been made. In the defect I opened on the K8S client, I referenced the breaking commit. They acknowledged it's a defect.

**Comment by ryanjbaxter** [comment]
@yue9944882 any chance we can get a fix for this and a release?
