### ISSUE TITLE
spring-cloud-gateway looking for unmapped configmap on startup

### ISSUE THREAD

**Issue by vishakvinod** [spring-cloud/spring-cloud-kubernetes#709]
I am trying to deploy an instance of spring-cloud-gateway on my kubernetes cluster with dynamic loading of routes from a ConfigMap. Weirdly on startup it tries to lookup for a configmap named "gateway" in the namespace as shown below 
```
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [ConfigMap]  with name: [gateway]  in namespace: [wb-test]  failed.
```
I have attached the full log [here](https://github.com/spring-cloud/spring-cloud-kubernetes/files/5731909/gateway.log).

Is this an expected behavior ? 

I am using `spring-boot-dependencies : 2.3.7.RELEASE` and `spring-cloud : Hoxton.SR9`

Its not to do with any kubernetes role mapping bcz its able to read the configmap as shown in the logs towards the end.

**Comment by ryanjbaxter** [comment]
What is `spring.application.name` set to?

**Comment by vishakvinod** [comment]
This is the value set for `spring.appliaction.name`
```yaml
spring:
  application:
    name: gateway
```

**Comment by ryanjbaxter** [comment]
As the documentation says Spring Cloud Kubernetes will use `spring.application.name` for the name of the configmap it tries to look up. See https://docs.spring.io/spring-cloud-kubernetes/docs/1.1.7.RELEASE/reference/html/#configmap-propertysource
