### ISSUE TITLE
Missing artifacts from maven central

### ISSUE THREAD

**Issue by smarijic** [spring-cloud/spring-cloud-kubernetes#716]
Hi,

I apologise upfront if I've missed something on my end but as far as I can see v2.0.0 release tagged 17 days ago is not available on maven central. Build breaks wihile trying to pull spring-cloud-starter-kubernetes-all with spring cloud 2020.0.0.

Can anyone give more details on this?

Thanks

**Comment by spencergibb** [comment]
Please see the release notes https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#renamed-starters

**Comment by ryanjbaxter** [comment]
See https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#renamed-starters
