### ISSUE TITLE
Need Configuration Watcher Example

### ISSUE THREAD

**Issue by sundarvc** [spring-cloud/spring-cloud-kubernetes#717]
Hi Team,

Can you provide me with a working example of a Watcher. All I could find was an example of the deprecated Reload PropertySource here - https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-examples/kubernetes-reload-example.

Thanks,
Sundar

**Comment by ryanjbaxter** [comment]
The integration test is a pretty good example
https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-configuration-watcher-it

**Comment by sundarvc** [comment]
Thanks.

**Comment by ryanjbaxter** [comment]
Welcome, I will close this issue for now.  If you have other questions please let us know.
