### ISSUE TITLE
How do I get the metadata of each instance

### ISSUE THREAD

**Issue by CosmosNi** [spring-cloud/spring-cloud-kubernetes#719]
I have two instances， instance A1，instanceA2,they point to the same service s1。

I configured metadata in A1，version=v1

I configured metadata in A2，version=v2

when i   execute  discoveryClient.getInstances(name)，I can only get the metadata of S1,such like 'version/region',I can't get this data.

How can I solve this problem

 yaml Examples

apiVersion: v1
kind: Service
metadata:
  name: discovery-springcloud-example-c
  labels:
    app: discovery-springcloud-example-c
    service: discovery-springcloud-example-c
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: discovery-springcloud-example-c
***
---	
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-springcloud-example-a-v1
  labels:
    app: discovery-springcloud-example-a
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-springcloud-example-a
  template:
    metadata:
      labels:
        app: discovery-springcloud-example-a
        group: example-service-group
        version: v1
        region: common
        env: env1
        zone: zone1
***
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-springcloud-example-a-v2
  labels:
    app: discovery-springcloud-example-a
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-springcloud-example-a
  template:
    metadata:
      labels:
        app: discovery-springcloud-example-a
        group: example-service-group
        version: v1
        region: common
        env: env1
        zone: zone1
    spec:
     ***

**Comment by ryanjbaxter** [comment]
Are you saying you can only get the `metadata` from the service and not from the individual pods?

**Comment by CosmosNi** [comment]
> Are you saying you can only get the `metadata` from the service and not from the individual pods?

Thanks for your response. 

Just as you described it. i want to get metadata from the individual pods

just like eureka
instance A 
eureka.instance.metadataMap.group=example-service-group
eureka.instance.metadataMap.version=1.0

instance B
eureka.instance.metadataMap.group=example-service-group
eureka.instance.metadataMap.version=1.1

When I call discoveryClient.getInstances(name) , The metadata for each instance is unique,For example, version is configured above

I want this result, what should I do

**Comment by ryanjbaxter** [comment]
Right now we just retrieve the metadata for the service not the individual pods.

If you could get the metadata for the pods how would you use that information?

**Comment by CosmosNi** [comment]
> Right now we just retrieve the metadata for the service not the individual pods.
> 
> If you could get the metadata for the pods how would you use that information?

Thanks for your response.

We expect to get the POD metadata for instance filtering,and we use metadata for grayscale publication.

At Eureka, Consul, we have implemented the corresponding functionality.But on the sck, we met resistance.

We tried to do this by modifying a lot of the source code,this may conflict with the sck's escalation.

So, can you help us solve it at the sck level.

**Comment by ryanjbaxter** [comment]
> We expect to get the POD metadata for instance filtering,and we use metadata for grayscale publication.

If requests are being handled by the service in Kubernetes how would you target a specific pod if you had the metadata?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
