### ISSUE TITLE
Does Spring Cloud Kubernetes support to disable label filter?

### ISSUE THREAD

**Issue by HaojunRen** [spring-cloud/spring-cloud-kubernetes#720]
We have A service which has 2 instances:
1. A1，its labels has version:1.0
2. A2，its labels has version:2.0

We also have B service has 1 instance with no version label

Now we want to execute KubernetesDiscoveryClient.getServices and getInstances("A") in B instance.

Hope to  retrieve getServices result with [A, B]，retrieve   getInstances("A") with 2 A instances

That means how to disable label filter whatever we add version label. Maybe the answer is "Remove that label", that does not  do any help for us. 

Thanks for a lot!

**Comment by ryanjbaxter** [comment]
I am not sure based on the information above why the discovery client would be filtering the services.  Maybe you could provide a concrete example?

**Comment by HaojunRen** [comment]
Thanks for your response. I will provide an example.

Now here is Another question:
In https://github.com/spring-cloud/spring-cloud-kubernetes/blob/c0e154fb83/spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesDiscoveryClient.java, in the following method, there is a logic with "withLabels", in my understanding, getInstances(serviceId) will compare local service labels with remote services labels, if they are NOT matched, remote services will be filtered by labels. And if i remove all additional labels, getInstances works fine. If wrong, please correct me. 

public List<Endpoints> getEndPointsList(String serviceId) {
		return this.properties.isAllNamespaces()
				? this.client.endpoints().inAnyNamespace().withField("metadata.name", serviceId)
						.withLabels(properties.getServiceLabels()).list().getItems()
				: this.client.endpoints().withField("metadata.name", serviceId)
						.withLabels(properties.getServiceLabels()).list().getItems();
	}

**Comment by HaojunRen** [comment]
Another question, why return null with getMetadata in k8s Registration?

**Comment by HaojunRen** [comment]
Refer to the example
https://github.com/CosmosNi/spring-cloud-kubernetes-demo

**Comment by ryanjbaxter** [comment]
Right now the `DiscoveryClient` only returns metadata for the service and not the pod.  If you could get the metadata for the pods, what would you use it for?

**Comment by ryanjbaxter** [comment]
Yes you either need to set `spring.cloud.kubernetes.discovery.labels` or remove them from your service yaml.

> Another question, why return null with getMetadata in k8s Registration?

Can you point me where you see this?

**Comment by HaojunRen** [comment]
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/c0e154fb83cfec663e73c95dd3dbdd476bb4174a/spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/registry/KubernetesRegistration.java


	@Override
	public Map<String, String> getMetadata() {
		return null;
	}

**Comment by ryanjbaxter** [comment]
The only place that class is used is in this class
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/c0e154fb83cfec663e73c95dd3dbdd476bb4174a/spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/registry/KubernetesAutoServiceRegistration.java

But that class has been deprecated and not used anywhere

**Comment by HaojunRen** [comment]
Thanks for your answer. Another 2 question:
1. which one should I select? spring.cloud.kubernetes.discovery.labels or spring.cloud.kubernetes.discovery.serviceLabels?

2. those configs are set to Spring Boot application.properties or yml? It means they are INSTANCE Label(MetaData), not related with k8s pod . Everyone Instance has its own metadata? Am I right?

**Comment by ryanjbaxter** [comment]
1. Sorry i meant `spring.cloud.kubernetes.discovery.serviceLabels`
2. yes in application configuration properties or environment variables or configmaps etc.  These are labels from the metadata of the service not the pod

**Comment by HaojunRen** [comment]
If i set spring.cloud.kubernetes.discovery.serviceLabels.abc=1, it can not be found via the method of  getInstances of KubernetesDiscoveryClient, you can refer to my example. In Spring Cloud i set
spring.cloud.consul.discovery.metadata.abc=1
It can be got via ConsulDiscoveryClient getInstances.

Is it different with Spring Cloud Kubernetes and Spring Cloud Consul or Eureka?

**Comment by spencergibb** [comment]
In consul and eureka, those values get set in the registry, kubernetes is service discovery only since "registration" is part of the platform.

**Comment by HaojunRen** [comment]
Thanks very much

**Comment by HaojunRen** [comment]
My personal opinion
Spring Cloud Kubernetes can keep the same behavior with Consul, Eureka, Nacos. Users use spring.cloud.kubernetes.discovery.metadata(NOT labels) to Etcd, they can resolve their features via Spring Cloud, and no need to know more too much k8s technology, some people which use consul, euraka have no more difficult to switch to Spring Cloud Kubernetes and use MetaData they define to do gray or blue green relalease as hope

**Comment by ryanjbaxter** [comment]
The problem is those values need to be in your deployment yaml, that is what is informing the registry.  Unless Spring Cloud Kubernetes modified things on startup, which is not something I think we should do, there is no working around this.

**Comment by HaojunRen** [comment]
But why not keep Spring Cloud MetaData and Kubernetes Labels with two different things?That means:
1. Service instances can be filtered by Kubernetes Labels in deployment yaml, that is Kubernetes platform function. ServiceInstance class can expose getLabels
2. Service instances can be filtered by Spring Cloud MetaData in application.properties, that is Spring Cloud native SDK function. ServiceInstance class can expose getMetaData

People who use Consul or Eureka would like to do their business logic via java coding and NOT CARE ABOUT Kubernetes Technology. For example I want to resolve somethings in Spring Cloud layer rather than in Kubernetes layer, the code in Spring Cloud Consul can be re-used in Spring Cloud Kubernetes, NOT write it again. Just write once, run anywhere

**Comment by ryanjbaxter** [comment]
`ServiceInstance` is a common interface, what would `getLabels` mean in the context of other service regustries?  Labels are very much a Kubernetes concept.

Additionally now you are mixing concepts.  `spring.cloud.kubernetes.discovery.metadata` is used to add metadata to the registry when the service is registered.  But in the context of Spring Cloud Kubernetes is means something different?  It is something used to filter `ServiceInstances`?  It doesn't make sense to me.

**Comment by HaojunRen** [comment]
Refer to https://github.com/spring-cloud/spring-cloud-kubernetes/blob/c0e154fb83/spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesDiscoveryClient.java

code:

public List<Endpoints> getEndPointsList(String serviceId) {		return this.properties.isAllNamespaces()				? this.client.endpoints().inAnyNamespace().withField("metadata.name", serviceId)						.withLabels(properties.getServiceLabels()).list().getItems()				: this.client.endpoints().withField("metadata.name", serviceId)						.withLabels(properties.getServiceLabels()).list().getItems();	}

ServiceInstances is filtered by "withLables", i dont want this function, i want to filter by myself such as like Consul or Eureka MetaData. 

For example A service invokes B servce, in A deployment yaml defines label.region=a, B defineS label.region=b, A can found B via A side KubernetesDiscoveryClient.getInstances. Labels are just only custom attributes, why default set them to filter? i can not understand

**Comment by ryanjbaxter** [comment]
This filtering occurs ever if you don't set `spring.cloud.kubernetes.discovery.serviceLabels`?

**Comment by HaojunRen** [comment]
I means whatever servicelabels are set or not, I want to have a config to enable/disable filtering. Let customers to determine filter work or not, just like spring.cloud.kubernetes.discovery.filter.enabled=false

**Comment by spencergibb** [comment]
Doesn't leaving spring.cloud.kubernetes.discovery.serviceLabels blank do that already?

**Comment by HaojunRen** [comment]
Removal labes can fine, but customers want to use labels to do another, for examle they want to add
label.version, label.email, label.telephone etc to store customization information to etcd. Those can help them to query service instances with customization via Etcd Open API. Dose it make sense?

**Comment by HaojunRen** [comment]
At least we do that in Consul server. If this requirement impacts Spring Cloud Kubernetes, I think let us stop the discussion. I have a lot of thanks for you all

**Comment by spencergibb** [comment]
I didn't say don't set labels, I said don't set `spring.cloud.kubernetes.discovery.serviceLabels ` which would filter on labels.

**Comment by ryanjbaxter** [comment]
> I didn't say don't set labels, I said don't set spring.cloud.kubernetes.discovery.serviceLabels which would filter on labels.

Yes this is what I am saying as well.

**Comment by HaojunRen** [comment]
Sorry, maybe I have not discribed this issue so clearly. The correct labels i say should be "instanceLabels", not "serviceLabels", that means service instances can be filtered with instances level, for example, A Service discovery B service, A has 1 instance with instance label for version=2.0, B has 3 instances with Instance label version=1.0, 2.0, 3.0. So the logic will be A only can discovery B Instance with version=2.0(because A Instance version also is 2.0), B 1.0 and 3.0 will be filtered.

So the requirement is
1. i want to get instance labels in ServiceInstance
2. i want to filter instances in Spring Cloud Kubernetes LoadBalance by Instance lables

I think the behavior will be same with Consul or Eureka mode

**Comment by HaojunRen** [comment]
So that is how to get Instance MetaData(labes) or how to get pod MetaData(labels)?

**Comment by ryanjbaxter** [comment]
The Kubernetes DiscoveryClient implementation uses metadata from the Kubernetes service, not the individual pods.  The logic is that you will not be sending requests directly to the pods but instead through the Kubernetes service.  So there is no way to get the DiscoveryClient to retreive the pod metadata.

There was a similar question here https://github.com/spring-cloud/spring-cloud-kubernetes/issues/719

I don't understand how you would then use the pod metadata to tell the Kubernetes service to target certain instances.

**Comment by HaojunRen** [comment]
for example, A Service discovery B service, A has 1 instance with instance label for version=2.0, B has 3 instances with Instance label version=1.0, 2.0, 3.0. So the logic will be A only can discovery B Instance with version=2.0(because A Instance version also is 2.0), B 1.0 and 3.0 will be filtered

How to support this feature in Spring Cloud Kubernetes, It is easy to support in Consul. Please tell me

**Comment by ryanjbaxter** [comment]
I understand what you are trying to do....

Say it is possible to do and you are able to get the metadata from the pods....how then do you make a request from service A to service B when the request needs to go through the kubernetes service for B?

**Comment by HaojunRen** [comment]
Sorry, i dont understand your question. But let me guess it. My answer will be:
When A and B deploy into Kubernetes, A invokes B through Feign or RestTemplate, before the invoking, A should do the Kubernetes Loadbalancer to filter the   B instances by "instance label". So I think it has two things
1. instance label or metadata must should be store into Etcd server, they are template.metadata.label in yaml?
2. serviceInstance class should provide get instance labels by method "getMetadata()", that will be same with all other Spring Cloud Discovery Middlewares(consul,euraka, zookeeper, nacos). That means getMetadata should be return Instance MetaData(not service MetaData).

I think Spring Cloud Kubernetes must follow all Spring Cloud Common RULE, so people are easy to accept Spring Cloud Kubernetes when they transfer from Spring Cloud Consul, Spring Cloud Eureka...

Spring Cloud Kubernetes is just an implementation of Spring Cloud Common, people are easy to learn Kubernetes via Spring Cloud Kubernetes and no need to know more Kubernetes technology

**Comment by spencergibb** [comment]
Many have been using this project for a long time and this is not a common request.

**Comment by HaojunRen** [comment]
i dont know America or other countries' customers, in China a lot of companies such as banks, educations, they all want that common requirement, and we call it "Gray Release", "Blue Green Release" or "Canary Releases"

**Comment by ryanjbaxter** [comment]
> A invokes B through Feign or RestTemplate

Yup but those HTTP requests are going through the Kubernetes service for B which is doing the load balancing.

**Comment by HaojunRen** [comment]
@spencergibb 
Please refer to https://github.com/spring-cloud/spring-cloud-kubernetes/issues/496, i guess he maybe has this kind of requirement. Thanks a lot
