### ISSUE TITLE
The local development environment

### ISSUE THREAD

**Issue by Taogang00** [spring-cloud/spring-cloud-kubernetes#721]
spring-cloud-kubernetes combines the advantages of springcolud and k8s, but it also brings about problems: the local development environment cannot be debugged, for example, the local development of B service, B service depends on A service, A service is Deployed in k8s, service B cannot discover and call A through the service discovery mechanism of k8s in the local development environment. How should this be solved?

**Comment by ryanjbaxter** [comment]
This is not a problem unique to spring cloud kubernetes, it is a problem with any cloud platform and any library.  Some tools you might find useful are Skaffold and Telepresence.
