### ISSUE TITLE
spring-cloud-kubernetes-client-config: There are test failures

### ISSUE THREAD

**Issue by misteruly** [spring-cloud/spring-cloud-kubernetes#729]
###  error  logs

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project spring-cloud-kubernetes-client-config: There are test failures.
[ERROR] 
[ERROR] Please refer to /root/spring-cloud-kubernetes/spring-cloud-kubernetes-client-config/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /root/spring-cloud-kubernetes/spring-cloud-kubernetes-client-config && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/bin/java org.apache.maven.surefire.booter.ForkedBooter /root/spring-cloud-kubernetes/spring-cloud-kubernetes-client-config/target/surefire 2021-02-08T10-16-37_554-jvmRun1 surefire8604575714711624704tmp surefire_176119616544952001294tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.springframework.cloud.kubernetes.client.config.reload.KubernetesClientEventBasedSecretsChangeDetectorTests
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /root/spring-cloud-kubernetes/spring-cloud-kubernetes-client-config && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/bin/java org.apache.maven.surefire.booter.ForkedBooter /root/spring-cloud-kubernetes/spring-cloud-kubernetes-client-config/target/surefire 2021-02-08T10-16-37_554-jvmRun1 surefire8154200958579932372tmp surefire_187004999196254891497tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.springframework.cloud.kubernetes.client.config.reload.KubernetesClientEventBasedConfigMapChangeDetectorTests
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /root/spring-cloud-kubernetes/spring-cloud-kubernetes-client-config && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/bin/java org.apache.maven.surefire.booter.ForkedBooter /root/spring-cloud-kubernetes/spring-cloud-kubernetes-client-config/target/surefire 2021-02-08T10-16-37_554-jvmRun1 surefire8604575714711624704tmp surefire_176119616544952001294tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.springframework.cloud.kubernetes.client.config.reload.KubernetesClientEventBasedSecretsChangeDetectorTests
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /root/spring-cloud-kubernetes/spring-cloud-kubernetes-client-config && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/bin/java org.apache.maven.surefire.booter.ForkedBooter /root/spring-cloud-kubernetes/spring-cloud-kubernetes-client-config/target/surefire 2021-02-08T10-16-37_554-jvmRun1 surefire8154200958579932372tmp surefire_187004999196254891497tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.springframework.cloud.kubernetes.client.config.reload.KubernetesClientEventBasedConfigMapChangeDetectorTests
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:510)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:457)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:298)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
[ERROR]         at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
[ERROR]         at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /root/spring-cloud-kubernetes/spring-cloud-kubernetes-client-config && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/bin/java org.apache.maven.surefire.booter.ForkedBooter /root/spring-cloud-kubernetes/spring-cloud-kubernetes-client-config/target/surefire 2021-02-08T10-16-37_554-jvmRun1 surefire8154200958579932372tmp surefire_187004999196254891497tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.springframework.cloud.kubernetes.client.config.reload.KubernetesClientEventBasedConfigMapChangeDetectorTests
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:115)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:444)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:420)
[ERROR]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[ERROR]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[ERROR]         at java.lang.Thread.run(Thread.java:748)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :spring-cloud-kubernetes-client-config

**Comment by wind57** [comment]
is that against `master` branch? also, what _exact_ command was used to run this + java version? Obviously if this would fail, this project would not be possible to be released, so something fishy here.

**Comment by misteruly** [comment]
yes,it is master branch. openjdk version "1.8.0_282"

**Comment by wind57** [comment]
I assume you simply do `mvn clean install`? I admit that I see this every "now and then" across projects, but have never seen it here before. Have you been [here](https://stackoverflow.com/questions/23260057/the-forked-vm-terminated-without-saying-properly-goodbye-vm-crash-or-system-exi) for some potential solutions? Some that obviously, do not require to change anything in `master`, otherwise it would not make sense

**Comment by misteruly** [comment]
master  directory       ./mvnw    install     @wind57

**Comment by ryanjbaxter** [comment]
Not sure why you are seeing this issue.  Both of our CI builds on Jenkins and CircleCI are passing fine.
