### ISSUE TITLE
Why can't we provide more granular permissions to service account

### ISSUE THREAD

**Issue by wlane** [spring-cloud/spring-cloud-kubernetes#735]
We are running a program using spring cloud kuberenetes in Amazon EKS. We want to grant the specified configmap permission to service accout, but it always printed out error like this:

o.s.c.k.c.ConfigMapPropertySource        : Can't read configMap with name: [xxxxxxxxxx] in namespace:[xxxxxxx]. Ignoring.

The version of spring-cloud-kubernetes:
spring-cloud-kubernetes-core-1.1.6.RELEASE

Our Role and RoleBingind are as belows:

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  &emsp; namespace: YOUR-NAME-SPACE
 &emsp; name: namespace-reader
rules:
&emsp;- verbs:
      &emsp;&emsp;- get
      &emsp;&emsp;- list
      &emsp;&emsp;- watch
    &emsp;apiGroups:
      &emsp;&emsp;- ''
      &emsp;&emsp;- extensions
      &emsp;&emsp;- apps
    &emsp;resources:
      &emsp;&emsp;- configmaps
    &emsp;resourceNames:
      &emsp;&emsp;- application-config
    &emsp;- verbs:
      &emsp;&emsp;- get
      &emsp;&emsp;- list
      &emsp;&emsp;- watch
    &emsp;apiGroups:
      &emsp;&emsp;- ''
      &emsp;&emsp;- extensions
      &emsp;&emsp;- apps
    &emsp;resources:
      &emsp;&emsp;- pods
      &emsp;&emsp;- services
      &emsp;&emsp;- endpoints
      &emsp;&emsp;- secrets
 
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
&emsp;name: namespace-reader-binding
subjects:
&emsp;- kind: ServiceAccount
&emsp;name: xxxx-sa
&emsp;namespace: YOUR-NAME-SPACE
&emsp;apiGroup: ""
roleRef:
&emsp;kind: Role
&emsp;name: namespace-reader
&emsp;apiGroup: ""

And when we deleted the resourceNames part, it could start successfully. I went through the reference document:
https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/index.html
and only found one sentence:
"On a production system you’ll likely want to provide more granular permissions."

Is there an example anywhere, or maybe can add this to the document?
Thank you very much.

**Comment by ryanjbaxter** [comment]
So when you remove
```
 resourceNames:
  - application-config
```
Everything works?

The exception should be logged, can you provide the stacktrace?

Can you provide the CongiMap YAML?

**Comment by wlane** [comment]
> So when you remove
> 
> ```
>  resourceNames:
>   - application-config
> ```
> 
> Everything works?
> 
> The exception should be logged, can you provide the stacktrace?
> 
> Can you provide the CongiMap YAML?

**Comment by wlane** [comment]
Thanks for you comment.

Yes, when I remove resourceNames, everything works.

We found there were more errors in the program's startup log like this:
can not read configmap "application-config-prod" 
or
can not read configmap "application-config-kubernetes"

But we didn't create configmap named application-config-prod or application-config-kubernetes, we just had application-config.
And after we added these two names to resourceName:
resourceNames:
  - application-config
  - application-config-prod
  - application-config-kubernetes
everything also worked fine, even though application-config-prod and application-config-kubernetes didn't exist.

We still don't know how can this happen, and we are comminicating with our development team to see if they specify these names.

I‘ll keep you updated, thanks.

**Comment by ryanjbaxter** [comment]
Are you enabling `prod` and `kubernetes` Spring profiles?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by wlane** [comment]
Sorry for the late reply. We've gone on vacation because of chinese new year holiday, and BTW, happy chinese new year.

We are enabling prod spring profile using parameter spring.profiles.active , but we do not enable kubernetes spring profile. We don't know why it comes.

**Comment by ryanjbaxter** [comment]
Happy Chinese New Year to you as well!!!!

The `kubernetes` profile automatically gets added when you run the application in k8s.

**Comment by ryanjbaxter** [comment]
I guess I am missing something so are there just warnings or are there errors?

**Comment by wlane** [comment]
Thanks.
There are errors.
The program can not find kubernetes profile, so it reported errors and stopped running.
Does it mean we have to configure resourcename application-config-kubernetes?

**Comment by ryanjbaxter** [comment]
Ah yes, not I understand, the formatting of your yaml above was confusing me.

Yes we will look for those configmaps as well so you would need to allow access to them.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
