### ISSUE TITLE
spring-cloud-kubernetes-client-autoconfig sets ApiClient as DefaultClient

### ISSUE THREAD

**Issue by tony-clarke-amdocs** [spring-cloud/spring-cloud-kubernetes#736]
See [here](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-client-autoconfig/src/main/java/org/springframework/cloud/kubernetes/client/KubernetesClientAutoConfiguration.java#L51). The ApiClient created marks itself as the default client, which displaces any previously set default client. 

- It seems wrong for an add in library to mark it self as default
- Why is it necessary since we have a bean we can use as the client?

**Comment by ryanjbaxter** [comment]
Can you describe more about how that is causing an issue for you?

**Comment by tony-clarke-amdocs** [comment]
Consider an application that is already using the kubernetes-client. They have defined their own apiClient (maybe it points to a different cluster) and set it as the default apiClient. Now when they add this dependency it will displace their default client and breaks their application.

**Comment by ryanjbaxter** [comment]
Thats where I thought you were going :)

Could you not just create your own bean and not set the default in that case?

In that case we would then use your API client I believe...which might also be desirable in some cases I think.

**Comment by tony-clarke-amdocs** [comment]
> In that case we would then use your API client I believe...which might also be desirable in some cases I think.
No, the existing default client maybe configured with a different client context (user/cluster/namespace).

In addition, why does KubernetesClientAutoConfiguration need to set its apiclient as the default? If this is needed to get the tests to pass then I think its just covering up another bug -> somewhere else in the code it's accessing the apiclient via the default apiclient and not using it's own apiClient bean.

**Comment by ryanjbaxter** [comment]
> In addition, why does KubernetesClientAutoConfiguration need to set its apiclient as the default?

I don't have a good reason for that to tell you the truth.  I can look into removing that code and seeing what breaks.  I don't think the reason has to do with tests, not to say they wont break, but that wasn't a driving factor.
