### ISSUE TITLE
Nebulous documentation 

### ISSUE THREAD

**Issue by DennisGoermannMD** [spring-cloud/spring-cloud-kubernetes#737]
**Describe the bug**
Hello, it could be possible that i stupid, but a fast readme reader will use (copy and waste^^) both dependencies from chapter "Starter". I make the stupid mistake, to take both, the fabric8 and the kubernetes java client dependency. 

I think a small reformation of the documentation whould avoid this: So you could use seperate boxes for the dependcy. A explizit note would be also avoid this.
**Sample**
Take a look at the readme.md chapter "Starter"

**Comment by ryanjbaxter** [comment]
I am not sure what you are suggesting as far as changes, could you be a bit more explicit?

I am assuming you are talking about this section?
https://github.com/spring-cloud/spring-cloud-kubernetes#2-starters

**Comment by DennisGoermannMD** [comment]
Hello, yes right. I talking about this section https://github.com/spring-cloud/spring-cloud-kubernetes#2-starters and want to avoid that other (stupid^^) users make the same mistake as me. The documentation look likes, you could copy and paste the dependencies, but this will not work.
