### ISSUE TITLE
Fabric8ProfileEnvironmentPostProcessor seems to do a bit "too little"

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#741]
Sorry for a bad description, I could not come up with a better one. 

This is not really a bug, but more of a question to see if it's OK for me to fix this or not. Currently, `Fabric8ProfileEnvironmentPostProcessor` has `isInsideKubernetes` defined as:

```
	@Override
	protected boolean isInsideKubernetes(Environment environment) {
		try (DefaultKubernetesClient client = new DefaultKubernetesClient()) {
			final Fabric8PodUtils podUtils = new Fabric8PodUtils(client);
			return environment.containsProperty(KUBERNETES_SERVICE_ENV_VAR) || podUtils.isInsideKubernetes();
		}
	}
```

it checks for `KUBERNETES_SERVICE_ENV_VAR` being present in Environment. 

On the other hand `podUtils::isInsideKubernetes`, specifically checks if "currently we are inside k8s". Though, besides the `KUBERNETES_SERVICE_ENV_VAR` property, it also checks `HOSTNAME` and the presence of both `/var/run/secrets/kubernetes.io/serviceaccount/token` and `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`.

IMO, the check `environment.containsProperty(KUBERNETES_SERVICE_ENV_VAR)` is too "thin" to prove if we are currently inside kubernetes or not. 

This long description is to propose the change to become:

```
	@Override
	protected boolean isInsideKubernetes(Environment environment) {
		try (DefaultKubernetesClient client = new DefaultKubernetesClient()) {
			final Fabric8PodUtils podUtils = new Fabric8PodUtils(client);
			return podUtils.isInsideKubernetes();
		}
	}
```

The change itself is trivial, but will require some changes for the tests to correctly work. 

I will take this and work on it, only if you agree on the change. Thank you.

**Comment by ryanjbaxter** [comment]
I personally like the fact that we can use the environment variable to indicate we are in kubernetes.  I can see it potentially being useful for developers trying to test something on their machine without actually having to deploy the app to k8s.

**Comment by wind57** [comment]
you are probably right, I have not thought about it this way. This makes sense. Closing.

**Comment by wind57** [comment]
@ryanjbaxter what if we do still a minor change here? instead of:

```
protected static final String KUBERNETES_SERVICE_ENV_VAR = "KUBERNETES_SERVICE_HOST";

	@Override
	protected boolean isInsideKubernetes(Environment environment) {
		try (DefaultKubernetesClient client = new DefaultKubernetesClient()) {
			final Fabric8PodUtils podUtils = new Fabric8PodUtils(client);
			return environment.containsProperty(KUBERNETES_SERVICE_ENV_VAR) || podUtils.isInsideKubernetes();
		}
	}
```

change it to:

```
@Override
	protected boolean isInsideKubernetes(Environment environment) {
		try (DefaultKubernetesClient client = new DefaultKubernetesClient()) {
			final Fabric8PodUtils podUtils = new Fabric8PodUtils(client);
			return environment.containsProperty(Fabric8PodUtils.KUBERNETES_SERVICE_HOST) || podUtils.isInsideKubernetes();
		}
	}
```

may be less confusing?

**Comment by ryanjbaxter** [comment]
Basically just using `Fabric8PodUtils` instead of defining the variable name ourselves?

**Comment by wind57** [comment]
yes. I will take that in a future PR. It's a minor thing, indeed
