### ISSUE TITLE
Failures when building in ActuatorEndpointIT

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#742]
I have seen some intermittent build failures in `ActuatorEndpointIT`. I have narrowed it down to the fact that `docker.io/springcloud/spring-cloud-kubernetes-core-k8s-client-it:2.0.2-SNAPSHOT` is missing and it must be present because of `image: docker.io/springcloud/spring-cloud-kubernetes-core-k8s-client-it:2.0.2-SNAPSHOT` in `spring-cloud-kubernetes-core-k8s-client-it-deployment.yaml`.

If I build locally that image, deploy and run the test - everything passes. 

Is there a reason that image is missing at `docker.io`? What is the process of pushing it in there to begin with? 

Thank you.

**Comment by ryanjbaxter** [comment]
It should be built when this part of the script runs and be in the local docker registry...then pushed to kind.
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-integration-tests/run.sh#L120

**Comment by ryanjbaxter** [comment]
I ran this today on circleci and the build passed
https://app.circleci.com/pipelines/github/spring-cloud/spring-cloud-kubernetes/606/workflows/4a7f9e7d-9093-453e-a528-8db6e9570a38

**Comment by wind57** [comment]
that is rather weird. I am trying to run some builds for two days now, and all fail at that point. Like this one, for example: https://app.circleci.com/pipelines/github/spring-cloud/spring-cloud-kubernetes/617/workflows/afda9097-36f2-4866-911f-be54af8d046d/jobs/1670

**Comment by ryanjbaxter** [comment]
Yeah I have been noticing that, I also ran a build locally and it passed as well.  Our Jenkins builds have been passing too.  Let me see if I can build the PRs locally

**Comment by ryanjbaxter** [comment]
@wind57 I tried to build https://github.com/spring-cloud/spring-cloud-kubernetes/pull/714 and got the same errors locally.  If I merge in the most recent changes into your branch it built fine, can you give that a try?

**Comment by wind57** [comment]
thank you Ryan and sorry for taking your time with this. all PRs now pass.
