### ISSUE TITLE
KubernetesCatalogWatch should allow changes when k8s services names are changing

### ISSUE THREAD

**Issue by Meliodas18** [spring-cloud/spring-cloud-kubernetes#743]
I've noticed that when I'm adding or deleting one of my kubernetes services, KubernetesCatalogWatch is sending to my spring cloud gateway a heartbeat and my gateway routes are updated.

However, if I'm changing the name of my service, it remains the same pod name at the end so the catalog will not update, and my gateway will not too.

Is there any reasons why we have this behaviour or is this a bug ?

**Comment by ryanjbaxter** [comment]
What is the side effect of this problem in the gateway?  Are you automatically creating routes based on service discovery?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by Meliodas18** [comment]
Hi,

Sorry for this late response.

Yes I'm creating my routes based on service discovery.

Let's say you have a first pod/service called podA/serviceA.

If you add a new pod/service (podB/serviceB), the gateway will automatically find there is a new podB/serviceB and create the corresponding route.

If you remove the podB/serviceB, the gateway will remove the corresponding route.

So far, it works as I expected and automatically.

But if you rename podA/serviceA to podA/serviceC (you just rename your service's name), then the gateway will not update its routes. If you call your gateway (for instance http://gateway/serviceC/myendpoint), the gateway will not find your routes since no update occured.
