### ISSUE TITLE
is there an example using Spring Cloud Kubernetes Configuration Watcher?

### ISSUE THREAD

**Issue by zhangyuxuan1992** [spring-cloud/spring-cloud-kubernetes#744]
**Is your feature request related to a problem? Please describe.**
I see there is an example using yaml config, but you guys recommended using watcher instead and I couldn't find example.
 cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        strategy: refresh
        period: 60000
      config:
        sources:

**Comment by ryanjbaxter** [comment]
See https://docs.spring.io/spring-cloud-kubernetes/docs/2.0.1/reference/html/#spring-cloud-kubernetes-configuration-watcher

**Comment by zhangyuxuan1992** [comment]
I do set my configmap the same name with my springboot application name. but when I changed the configMaps, no actuator/refresh is POSTed by spring-cloud-kubernetes-configuration-watcher. Can I change spring-cloud-kubernetes-configuration-watcher's loglevel somehow to see if it knew the configMaps is changed and did it send POST or not?

**Comment by ryanjbaxter** [comment]
you can set `logging.level.org.springframework.cloud.kubernetes=DEBUG`

**Comment by zhangyuxuan1992** [comment]
thanks, now I can see more logs.
and I am seeing this log
`spring-cloud-kubernetes-configuration-watcher-deployment-7v7rfn spring-cloud-kubernetes-configuration-watcher 2021-02-25 05:02:14.298 DEBUG 1 --- [/10.100.0.1/...] .w.HttpBasedConfigMapWatchChangeDetector : Scheduling remote refresh event to be published for ConfigMap celerx-backend to be published in 120000 milliseconds`
why is a configmap changed event needs to be published in 2 mins later?

**Comment by ryanjbaxter** [comment]
Because it can take up to 2 minutes for the configmap changes to be reflected in the mounted volume

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by quangthe** [comment]
> Because it can take up to 2 minutes for the configmap changes to be reflected in the mounted volume

Is there any ways to make changes reflected faster?

**Comment by ryanjbaxter** [comment]
Its a limitation of Kubernetes, i am not sure

**Comment by neo-feng** [comment]
> See https://docs.spring.io/spring-cloud-kubernetes/docs/2.0.1/reference/html/#spring-cloud-kubernetes-configuration-watcher

this is not an example, could you please share a sample? I cannot find a sample configuration for config watcher.

**Comment by neo-feng** [comment]
@zhangyuxuan1992 hi, I'm trying to create a sample using config watcher with no success, I noticed you have successfully set it up according to your logs above, would you mind sharing your sample code with me?

**Comment by zhangyuxuan1992** [comment]
> @zhangyuxuan1992 hi, I'm trying to create a sample using config watcher with no success, I noticed you have successfully set it up according to your logs above, would you mind sharing your sample code with me?

sure. I assume you are chinese too. You can give me you wechat account on private so that I can share my code with you

**Comment by neo-feng** [comment]
> > @zhangyuxuan1992 hi, I'm trying to create a sample using config watcher with no success, I noticed you have successfully set it up according to your logs above, would you mind sharing your sample code with me?
> 
> sure. I assume you are chinese too. You can give me you wechat account on private so that I can share my code with you

private message was removed by GitHub, please drop a message to my email neo.feng@outlook.com, and I'll send you wechat id
