### ISSUE TITLE
errror  java -jar  spring-cloud-kubernetes-***.jar

### ISSUE THREAD

**Issue by misteruly** [spring-cloud/spring-cloud-kubernetes#750]
[root@master-cluster target]# java -jar   spring-cloud-kubernetes-fabric8-autoconfig-2.0.2-SNAPSHOT.jar
no main manifest attribute, in spring-cloud-kubernetes-fabric8-autoconfig-2.0.2-SNAPSHOT.jar

[root@master-cluster target]# java -jar  spring-cloud-kubernetes-client-autoconfig-2.0.2-SNAPSHOT.jar
no main manifest attribute, in spring-cloud-kubernetes-client-autoconfig-2.0.2-SNAPSHOT.jar

[root@master-cluster target]# java -jar  spring-cloud-kubernetes-client-discovery-2.0.2-SNAPSHOT.jar 
no main manifest attribute, in spring-cloud-kubernetes-client-discovery-2.0.2-SNAPSHOT.jar

why???   What's the right way to do it??

**Comment by ryanjbaxter** [comment]
They are not executable jars, what are you trying to accomplish exactly?

**Comment by misteruly** [comment]
@ryanjbaxter    Pack it into a container and run it on K8S，Is that the right way to run it？？

**Comment by ryanjbaxter** [comment]
No these are libraries you would use to help build your application.  I suggest you read the docs
https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#why-do-you-need-spring-cloud-kubernetes
