### ISSUE TITLE
Add Debug Logging To ConfigurationChangeDetector

### ISSUE THREAD

**Issue by pjjeffrey** [spring-cloud/spring-cloud-kubernetes#753]
This is something that would benefit greatly with a debug log entry listing the differences in the property sources.
The issue has been searched for a few times and it would provide a lot of help in tracking down the cause.
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/00ff21d5e5af0c19c5236d510efc566cfbd93946/spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/reload/ConfigurationChangeDetector.java#L87

**Comment by ryanjbaxter** [comment]
its currently logged at a warn level, you are proposing we log it at debug level?

**Comment by pjjeffrey** [comment]
It would be good to have debug level logging showing what is actually in the source lists.
I have been looking to why I'm having this issue. It seems one list is correct and the other is empty.
Now that I have this information, I am adding debug logging in other locations to figure out why the second list is empty.

**Comment by ryanjbaxter** [comment]
@pjjeffrey is this something you would like to make a PR for?

**Comment by pjjeffrey** [comment]
Sure, I would be happy to contribute.

**Comment by ryanjbaxter** [comment]
That would be great!  When you have the changes ready shoot over a PR!

**Comment by pjjeffrey** [comment]
I am not able to push my branch to the repo. I get the following error.
ERROR: Permission to spring-cloud/spring-cloud-kubernetes.git denied to pjjeffrey.

**Comment by ryanjbaxter** [comment]
@pjjeffrey you create a fork of the repo and then submit a PR to this repo so we can review the changes and merge them in.

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by pjjeffrey** [comment]
Ok, I'll figure this out tomorrow. Thanks for the info.
