### ISSUE TITLE
properties to change the default service account to be used with k8s

### ISSUE THREAD

**Issue by vsirimalla** [spring-cloud/spring-cloud-kubernetes#758]
I need to change the default service account that's used to list the kubernetes resources.
It is using "`system:anonymous`" by default, we need to change that.

I have looked for the properties from Appendix, could not find any useful properties that I could use to change the default service account to be used.

**Comment by ryanjbaxter** [comment]
The service account being used can be specified in the deployment manifest.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
