### ISSUE TITLE
remove lombok usage

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-kubernetes#764]

**Comment by msamad** [comment]
@spencergibb Could you kindly provide some information why spring cloud team has decided to remove lombok? It will be very valuable to get your views on it please

**Comment by wind57** [comment]
relying in such external dependencies is never a good idea. You can read [this](https://stackoverflow.com/questions/65380359/lomboks-access-to-jdk-compilers-internal-packages-incompatible-with-java-16) where a bunch of people (including myself) argued about it. The overall idea is that `lombok` relies of `jdk.compiler` internal package, on an API that is supposed to be internal only. So when jdk-16 came out - it stopped working, you needed a fix and proper settings enabled. So, when jdk-17 or 20 for example comes out - will lombok stop working at all?

These are all things that make this tool too volatile for usage in a such largely used project like spring. Now add the fact that `records` exist - and us, in spring, would need that even less, if at all.

**Comment by wind57** [comment]
btw, we never removed it - I just added a PR [for that](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/853)

**Comment by msamad** [comment]
@wind57 Thanks for the info, appreciate it. :)
