### ISSUE TITLE
Prefix the property name of secrets and configmaps

### ISSUE THREAD

**Issue by patrickheinzelmann** [spring-cloud/spring-cloud-kubernetes#765]
I had to read the multiple secrets to connect to the Strimzi. As Strimzi is auto-generating the the secrets, the secrets contain the same properties (sasl.jaas.config, ...).

Is possible to prefix the properties to support multiple secrets (or configmaps) with the same properties?

For example:

If the secret "consumer" would have the prefix "kafka.consumer", the value of K8 secret property would accessible by "kafka.consumer.sasl.jaas.config" in Spring.

If the secret "producer" would have the prefix "kafka.producer", the value of K8 secret property would accessible by "kafka.producer.sasl.jaas.config" in Spring.

Or can I remap the secrets and configmaps in different way?

**Comment by ryanjbaxter** [comment]
I am trying to understand better the problem.

You have multiple secrets, each with the same property?

For example,

Secret 1
sasl.jaas.config=....

Secret 2
sasl.jaas.config=....

Secret 3
sasl.jaas.config=....

Any you are trying to use these secrets within the same application?

**Comment by patrickheinzelmann** [comment]
Exactly as you have described it!

I have multiple secrets, each with with the same properties and the secrets should be used with the same applications.

My problem is that I can't influence the secret creation itself as the secrets will be generated by the Strimzi (Kafka) Operator.

One secret contains the config for the communication with the Kafka handling the communication between the microservices.

Another secret contains the config for the Kafka which triggers the webhooks or sends the notifications to the UI.

**Comment by patrickheinzelmann** [comment]
@ryanjbaxter I looked into the code of the secrets configuration.

If you would add an additional config parameter **prefix** to the sources configuration like this:

`spring.cloud.kubernetes.secrets.sources.prefix`

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/f43b5c1a45e958f65b46fdd04a8a37b745e5755d/spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/SecretsConfigProperties.java#L102

Then you could provide the new parameter prefix to method getSourceData in KubernetesClientSecretsPropertySource

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/1a136a52680ad733edc5e52e18155f61d7799a0c/spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientSecretsPropertySource.java#L48

which then can provide the prefix to putAll. If prefix is set, the name (aka **k**) will be prefix otherwhise it will simple use k as name.

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/1a136a52680ad733edc5e52e18155f61d7799a0c/spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/SecretsPropertySource.java#L45


Would do you think about this approach?

**Comment by ryanjbaxter** [comment]
I wonder if you could use the name of the secret as the prefix, with the option to specify your own if you wanted.  Thoughts?

**Comment by patrickheinzelmann** [comment]
@ryanjbaxter Using the name of the secret's source as prefix would work for me.  The values of name and prefix would have been the same anyway.

My idea behind the separate property "prefix" was to control the usage of the prefix mechanism to have backward compatibility that the secrets aren't automatically prefix. But this can be controlled by an other config setting.

**Comment by ryanjbaxter** [comment]
We would certainly need it to be optional, at least for now.  So a property to opt into the functionality would be necessary.  We could also add a warning if there is already a property source with the same name.  Make sense?

**Comment by patrickheinzelmann** [comment]
@ryanjbaxter Make sense to me!

**Comment by ryanjbaxter** [comment]
Is this something you would like to contribute?

**Comment by patrickheinzelmann** [comment]
@ryanjbaxter I have implemented the support and created a pull request.

https://github.com/spring-cloud/spring-cloud-kubernetes/pull/818

**Comment by wind57** [comment]
@ryanjbaxter  and this one too
