### ISSUE TITLE
Postgresql Metadata Configuration

### ISSUE THREAD

**Issue by kumarprashant2103** [spring-cloud/spring-cloud-kubernetes#770]
Hi,
We are setting up SCDF on the Kubernetes cluster through kubectl.  We are using PostgreSQL for the Metadata process. We got the set up done, and we can see various tables created in the Postgresql, and we can access SCDF UI, but when we try to add any task or try to import repository, then we are getting this error message : 

“could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet “

**Comment by ryanjbaxter** [comment]
Seems like you opened the issue in the wrong repo, try opening it here https://github.com/spring-cloud/spring-cloud-dataflow
