### ISSUE TITLE
Spring Cloud Kubernetes 2.0.2 pulls outdated io.kubernetes dependency  

### ISSUE THREAD

**Issue by Alos** [spring-cloud/spring-cloud-kubernetes#781]
Spring Cloud Kubernetes 2.0.2 pulls an outdated dependency that contains a known vulnerability:

org.bouncycastle:bcprov-ext-jdk15on:jar:1.66
org.bouncycastle:bcpkix-jdk15on:jar:1.66

A newer version of the io.kubernetes client has the newer 1.68 version. 

https://snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-1052818

**Comment by Alos** [comment]
@ryanjbaxter do you think this will be fixed in 2.0.3?

**Comment by ryanjbaxter** [comment]
@Alos which version are you looking at specifically?

**Comment by Alos** [comment]
Spring Cloud Kubernetes 2.0.2 pulls io.kubernetes:client-java:11.0.1:

<img width="614" alt="Screen Shot 2021-05-13 at 1 27 01 PM" src="https://user-images.githubusercontent.com/25460/118183572-1cff9680-b3ef-11eb-931d-8222c3a37704.png">

**Comment by ryanjbaxter** [comment]
Sorry I mean which version of io.kubernetes had the updated dependencies?

**Comment by Alos** [comment]
https://github.com/kubernetes-client/java/blob/master/pom.xml

**Comment by ryanjbaxter** [comment]
@Alos I am going to delete this issue because its security related, please email me at rbaxter[at]vmware.com

**Comment by Alos** [comment]
Understood
