### ISSUE TITLE
Spring Cloud Kubernetes pulls Kubernetes Client not compatible with Java 16

### ISSUE THREAD

**Issue by Alos** [spring-cloud/spring-cloud-kubernetes#782]
The dependency `spring-cloud-starter-kubernetes-client-all` uses a Kubernetes client version that does not work with Java 16

https://github.com/kubernetes-client/java/issues/1638

**Comment by Alos** [comment]
Thanks for looking into it :)

**Comment by yue9944882** [comment]
@ryanjbaxter @Alos for clarification, the client is actually compatible w/ Java 16. it's the junit environment stubbing failing in the client library. anyway we're working on fixing it.
