### ISSUE TITLE
Spring Cloud Kubernetes Loadbalancer gives pod ip address instead of service url when spring.cloud.kubernetes.loadbalancer.mode=SERVICE

### ISSUE THREAD

**Issue by pearsonradu** [spring-cloud/spring-cloud-kubernetes#783]
**Problem**
I am trying to use Spring Boot with Spring Cloud Kubernetes to discovery services with the loadbalancer in `SERVICE` mode. I have followed the documentation from https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/index.html where it says to set `spring.cloud.kubernetes.loadbalancer.mode=SERVICE` and include the following dependency

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-fabric8-loadbalancer</artifactId>
</dependency>
```

In my sample project I have created two identical applications, _app a_ and _app b_, both of which use the loadbalancer dependency and have loadbalancer set to `SERVICE` mode. After running my `k8s.yaml` file this is the output:

![image](https://user-images.githubusercontent.com/62548051/117340211-a69ee980-ae6e-11eb-940c-86034cba3c95.png)

The last line of _app a_ and _app b_ logs show the ip address of the pod where I would have expected it to be something like `service-a.default.svc.cluster.local` as mentioned in the documentation. To get the address output I am calling
`System.out.println(discoveryClient.getInstances("service-b").get(0).getUri().toString());` for _app a_ and `        System.out.println(discoveryClient.getInstances("service-a").get(0).getUri().toString());` for _app b_.

Any guidance would be greatly appreciated.

**Sample**
https://github.com/pearsonradu/spring-cloud-kubernetes-loadbalancer-service-example

Versions:
- Docker Desktop: 3.1.0
- Kubernetes: 1.19.3
- Spring Boot: 2.4.5
- Spring Cloud: 2020.0.2

Includes
- _app a_ 
- _app b_
- _k8s_ configuration

**Comment by pearsonradu** [comment]
I have added in the changes for calling `getHost`. It is returning the same IP address as `getUri`.

![image](https://user-images.githubusercontent.com/62548051/117680039-cc820200-b17e-11eb-90ba-572023ffe257.png)

**Comment by ryanjbaxter** [comment]
The sample repo no longer exists

**Comment by ryanjbaxter** [comment]
The reason is because that setting has no effect on the DiscoveryClient implementation.  The LoadBalancer setting actives this class and this is what will provide the service to the load balancer https://github.com/spring-cloud/spring-cloud-kubernetes/blob/9364fb9f4c19eef5ea74656c6d3d8db309a74ad9/spring-cloud-kubernetes-fabric8-loadbalancer/src/main/java/org/springframework/cloud/kubernetes/fabric8/loadbalancer/Fabric8ServicesListSupplier.java

**Comment by pearsonradu** [comment]
Thank you for that clarification. Is there a recommended way to get the service URL for a discovered service? I would like to configure a `WebClient` bean with a configured `baseUrl`. Ideally the `WebClient` would be annotated `@Loadbalanced` but I'm not sure how to direct it to the Kubernetes service?

**Comment by ryanjbaxter** [comment]
Why not just do this?
https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#webclinet-loadbalancer-client

**Comment by pearsonradu** [comment]
What is the advantage of using `@Loadbalanced` when I would be manually pointing to the Kubernetes service? Is it (from the link you provided) `The URI needs to use a virtual host name (that is, a service name, not a host name). The Spring Cloud LoadBalancer is used to create a full physical address.` Does that mean the `@Loadbalanced` webclient will do some manipulations on the URI?

**Comment by ryanjbaxter** [comment]
If you add `@Loadbalanced` to your `WebClient` using the `SERVICE` mode setting in Spring Cloud Kubernetes, you can then do `webClientBuilder.build().get().uri("http://service-b")` and that should end up resolving to `http://service-b.default.svc.cluster.local` when the request is made

**Comment by pearsonradu** [comment]
Great, I appreciate the help. I will give that a shot and get back to you.

**Comment by pearsonradu** [comment]
Using the `@Loadbalanced` annotation seemed to do the trick! The request is successful with the annotation present and when it is removed the request fails. Enabling SERVICE mode points to the cluster address and switching to POD points to the IP address. Thank you for the clarification!
