### ISSUE TITLE
Documentation points to fabric8 examples instead of examples using this dependency

### ISSUE THREAD

**Issue by Alos** [spring-cloud/spring-cloud-kubernetes#785]
The following [section](https://github.com/spring-cloud/spring-cloud-kubernetes#53-propertysource-reload) Lists an example that points to 

https://github.com/fabric8io/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-examples/kubernetes-reload-example

**Comment by ryanjbaxter** [comment]
I guess I am missing the problem, which dependency are you referring to?
