### ISSUE TITLE
[Question] Property source reload deprecation

### ISSUE THREAD

**Issue by tippl** [spring-cloud/spring-cloud-kubernetes#786]
Hello, according to the docs the automatic reload is deprecated and replaced by the configuration watcher.

I was planning on using this feature, however the new config watcher is unusable for me. Because at work, we can't just deploy "random" apps from docker hub.

Is there a way to achieve property reload in the same capacity as has been deprecated, without having to install configuration watcher? Since that is not an option for me and i assume for a lot more users that have at least somewhat enforced security limitations on their clusters.

**Comment by Alos** [comment]
The documentation points to [this](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#spring-cloud-kubernetes-configuration-watcher) however its not clear to me how to enable this "refresh" endpoint in my app. It's not documented in https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints

**Comment by tippl** [comment]
Yes, the /refresh endpoint an option, but it adds a step to the act of editing a config in config map by requiring you to call an endpoint manually.
Adding to the fact, with further emergence of software for CI/CD and/or GitOPS, spearating users further from the cluster itself, which leads to everyone who can possibly edit a config having to keep a postman collection for all apps they manage, or having to write a tool to send the request for them.

Ideally i'm looking for an option that matches the current deprecated feature without having to install another deployment into my cluster.

Final point i would like to make is, hardware is not free. The act of starting the configuration watcher in a namespace takes the minimal resources for an app to start cpu and memory-wise, detracting from the resources available for the app itself to run. (which is probably not negligible, considering the watcher seems to be a spring-boot app itself) And i'm not even mentioning the cases with 10, 20 or more apps with separate namespaces, all using up the minimal guaranteed resource allocation by the cluster.

**Comment by Alos** [comment]
> Yes, the /refresh endpoint an option, but it adds a step to the act of editing a config in config map by requiring you to call an endpoint manually.

You can use the Spring Cloud Kubernetes Configuration Watcher to have the watcher automatically poke the services. 

What I want know is HOW to enable the refresh endpoint. I've tried it on my apps and it does not work.

**Comment by pukkaone** [comment]
As a simpler alternative to Spring Cloud Kubernetes Configuration Watcher, I would like to see https://github.com/spring-cloud/spring-cloud-commons/issues/605 implemented. You volume mount ConfigMap's into the container file system. The application reads the volume-mounted configuration files. The application watches for changes to the configuration files.

**Comment by tippl** [comment]
Definitely agree, either a mechanism that uses the mouted config map along with watching the map to change over API, or just plain and regular watching the file tree on filesystem for change.

Either of those seems like a way better option compared to having to have a separate application watching the configs for you and then notifying of the change.

**Comment by spencergibb** [comment]
@tippl build the docker image yourself?

**Comment by tippl** [comment]
This would not solve my issue with it being another deployment using up server and human resources just to do it's thing which has to be paid from our budget. Which is why i feel that watching the files for change from within the library would be probably the best solution.

Another reason for this would be that if i wanted to build the image myself, that adds maintenance steps for myself or my team to manage the apps. For example the steps would be as follows:
* Manually download the code
* Perform required modifications for it to work under available base images
* Manually push to docker registry for all clusters
* Create/Update the deployment for all required instances (tens of instances across multiple clusters)

Which would leave me on the hook for any future maintenance - one such example would be regular updates to comply with security regulations and regularily perform above steps again to mitigate possible vulnerabilities found in any libraries found in the app.

As such, we cannot use the configuration watcher and the configuration reload feature in the current state.

**Comment by spencergibb** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-commons/issues/605
