### ISSUE TITLE
Keep consistent with SpringCloud default behavior

### ISSUE THREAD

**Issue by carrypann** [spring-cloud/spring-cloud-kubernetes#794]
**Is your feature request related to a problem? Please describe.**
Bootstrap is no longer enabled by default after SpringCloud 2020.0+,  while SpringCloud Kubernetes still requires it by including `spring-cloud-starter-bootstrap`. Why not keep consistent with SpringCloud's default behavior?

SpringBoot 2.4+ brings the new syntax `spring.connfig.import` to import external config data, means that we don't need `bootstrap.yaml` any more.  Considering that `spring-cloud-consul-config` has been supported this syntax, so we removed `bootstrap.yaml`, and put `spring.application.name` to `application.yaml`, which results in `spring-cloud-kubernetes-config` not working.

**Comment by ryanjbaxter** [comment]
It is needed because of the way Spring Cloud Kubernetes Config loads ConfigMaps and Secrets as property sources.  It needs to happen in the bootstrap phase.  We suggest though that you mount these as volumes and then leverage `spring.config.import` to add them as property sources instead of using the config module.

**Comment by carrypann** [comment]
Thanks for your reply. I know that I can mount config files as volumes, but I want to specific difference config name to import, like `spring.cloud.kubernetes.config.sources[0].name=xxx`, however, `spring.config.import=configtree` does not support this feature.

Since `spring.config.import=configtree` can import external config without bootstrap context, Spring Cloud Kubernetes Config can also loads ConfigMaps and Secrets by providing an k8s implementation of `org.springframework.boot.context.config.ConfigDataLoader`, is this right?

**Comment by ryanjbaxter** [comment]
This is kind of interesting, something I have not really thought about.

So what is missing with `spring.config.import` is the ability to look up files based on `spring.application.name`?

As a side note have you looked into using `spring.cloud.kubernetes.config.paths`?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
