### ISSUE TITLE
Move To Fabric8 5.x.x 

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-kubernetes#802]

**Comment by wind57** [comment]
This is why I asked you about branches. This defect is in `main`, but the current tag is `2020.0.x`... so can't you cherry-pick that commit into `2.0.x`? I mean I could do that too + backport the two fixes I made today, but I am just wondering. 

May be you want fabric8 `5.x.x` in `main` also, which is again fine, but some clarity into this defect would not hurt

**Comment by ryanjbaxter** [comment]
Yes it should be in main only because its a major dep version jump
