### ISSUE TITLE
Failed to build/deploy Kubernetes Spring Cloud LoadBalancer Example 

### ISSUE THREAD

**Issue by dkoh703** [spring-cloud/spring-cloud-kubernetes#826]
Hi, 
I tried to build/deploy the Kubernetes Spring Cloud LoadBalancer Example by running the command below:

mvn clean install fabric8:deploy -Dfabric8.generator.from=fabric8/java-jboss-openjdk8-jdk -Pkubernetes

But it failed on the Greeting Service as below. 

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Spring Cloud LoadBalancer Example 2.1.0-SNAPSHOT:
[INFO] 
[INFO] Spring Cloud LoadBalancer Example .................. SUCCESS [07:44 min]
[INFO] Spring Cloud LoadBalancer :: Name Service .......... SUCCESS [01:54 min]
[INFO] Spring Cloud LoadBalancer :: Greeting Service ...... FAILURE [ 15.995 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:14 min
[INFO] Finished at: 2021-07-10T15:21:56+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project greeting-service: Could not resolve dependencies for project org.springframework.cloud:greeting-service:jar:2.1.0-SNAPSHOT: The following artifacts could not be resolved: org.springframework.cloud:spring-cloud-starter-kubernetes-fabric8-loadbalancer:jar:2.1.0-SNAPSHOT, org.springframework.cloud:spring-cloud-starter-kubernetes-fabric8:jar:2.1.0-SNAPSHOT: Could not find artifact org.springframework.cloud:spring-cloud-starter-kubernetes-fabric8-loadbalancer:jar:2.1.0-SNAPSHOT in spring-snapshots (https://repo.spring.io/snapshot) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :greeting-service

**Comment by ryanjbaxter** [comment]
We branched the repo to begin work on our next release train.  We are still working through some build issues so some artifacts are missing.  It would be better to use the 2.0.x branch for now until we resolve things.
