### ISSUE TITLE
ReactiveDiscoveryClientHealthIndicator - Always using 192.168.0.1 for API call 

### ISSUE THREAD

**Issue by patpatpat123** [spring-cloud/spring-cloud-kubernetes#832]
Hello Spring Cloud Kubernetes Team,

Currently, the ```ReactiveDiscoveryClientHealthIndicator``` seems to always call ```192.168.0.1```

For instance:

```
[ndedElastic-564] s.c.c.d.h.DiscoveryClientHealthIndicator : Error
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://192.168.0.1/api/v1/namespaces/mynamespace/services. Message: upstream connect error or disconnect/reset before headers. reset reason: connection failure.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:570) ~[kubernetes-client-4.13.3.jar!/:na]
```

Advices from Kubernetes is: _"Within the cluster, the best practice is to use the cluster IP of the API server. Outside of the cluster, use the external VIP."_

Unfortunately, the the IP used is always ```192.168.0.1```.

Issue: While Spring Cloud Kubernetes detects the use in Kubernetes, shouldn't it use directly the appropriate IP instead?

Also, is it possible to allow the override of the ```192.168.0.1``` to something configurable please?

Thank you

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by patpatpat123** [comment]
of course @ryanjbaxter

Thanks for looking at this by the way.
Here is the minimal project.

Actually, it is very minimal in terms if code, because the issue is not there, so you will only see one .java file with a main.

The issue I believe is the combination of spring cloud Kubernetes with liveness/readiness probe drilling down all the way to Kube health.

With the minimal project I linked, I reproduced with AKS and a private kubernetes offering.
After building the jar + dockerizing it + deploying in any kubernetes instance, you should be seeing the app being polled regularly for health check. The result should be something like this: 

```
{
    "status": "UP",
    "components": {
        "kubernetes": {
            "status": "UP",
            "details": {
                "nodeName": "aaa",
                "podIp": "bbb",
                "hostIp": "ccc",
                "namespace": "ddd",
                "podName": "eee",
                "serviceAccount": "fff",
                "inside": true,
                "labels": {
                    "app": "question",
                    "pod-template-hash": "ggg"
                }
            }
        },
        "livenessState": {
            "status": "UP"
        },
        "ping": {
            "status": "UP"
        },
        "reactiveDiscoveryClients": {
            [...]
        },
        "readinessState": {
            "status": "UP"
        },
        "refreshScope": {
            "status": "UP"
        }
    },
    "groups": [
        "liveness",
        "readiness"
    ]
}
``` 

And upon the health check: ```ReactiveDiscoveryClientHealthIndicator``` seems to always call ```192.168.0.1```

From Kubernetes: "Within the cluster, the best practice is to use the cluster IP of the API server. Outside of the cluster, use the external VIP."

**Comment by ryanjbaxter** [comment]
I am unable to reproduce this locally using a Kind cluster, are you able to reproduce it outside of AWS?

**Comment by patpatpat123** [comment]
Thank you @ryanjbaxter
I can confirm this is reproducible with AWS and a private Kubernetes as a service.
Will try to reproduce using Minikube etc on local.

May I ask, is it possible to change this default address or to override it not to look at 192.168.0.1 please?
Or may I ask which part of the project is it constructing this IP please?

**Comment by ryanjbaxter** [comment]
I set up my own EKS cluster last night and tried to reproduce it there and was not able to.

>May I ask, is it possible to change this default address or to override it not to look at 192.168.0.1 please?

You can try setting `spring.cloud.kubernetes.client.masterUrl` and see if that helps.

**Comment by patpatpat123** [comment]
This property worked. Many thanks @ryanjbaxter
