### ISSUE TITLE
config watcher working sample

### ISSUE THREAD

**Issue by neo-feng** [spring-cloud/spring-cloud-kubernetes#833]
Is config watcher working now? I cannot find any working sample anywhere. And mixed samples with old reload solution found everywhere, you cannot even tell which one is working, the old reload or new wathcer.

**Comment by ryanjbaxter** [comment]
If you want to look at a working example take a look at the integration test https://github.com/spring-cloud/spring-cloud-kubernetes/tree/main/spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-configuration-watcher-it

**Comment by neo-feng** [comment]
Thanks for your reply, 3 quick questions:
1. Is dependency spring-cloud-starter-kubernetes-config still required in the new config watcher solution? (which is not in the example)
2. Is mount volume required n the new config watcher solution? which is not required in old reload solution. 
3. Should I reload my properties myself in my app's callback method like onApplicationEvent() in the example? or it works just like old reload solution, my app don't have to write code to do the refresh (which I didn't see in the example)

**Comment by ryanjbaxter** [comment]
>Is dependency spring-cloud-starter-kubernetes-config still required in the new config watcher solution? (which is not in the example)
Nope not needed

>Is mount volume required n the new config watcher solution? which is not required in old reload solution.
Not required but we prefer you mount ConfigMaps and Secrets so the app does not need to use the k8s api directly

>Should I reload my properties myself in my app's callback method like onApplicationEvent() in the example? or it works just like old reload solution, my app don't have to write code to do the refresh (which I didn't see in the example)
The config watcher will notify the app that its configuration has changed after the mounted configmap or secret has been changed, so when the refresh event in the app is executed it will pick up the new configuration, there is no code you need to add

>Is the new config watcher solution ready for production usage? any known issues ?
Yes it is ready

**Comment by neo-feng** [comment]
Thanks for your quick reply, 3 more quick questions.
1. To use http implementation, the only 2 dependencies I need are:  spring-boot-starter-actuator and spring-cloud-kubernetes-discovery, is that correct?
2. Should config watcher be deployed in another pod, or as sidecar in my app's pod?  
3. Could you please share a working bootstrap.yml for http implementation?

**Comment by ryanjbaxter** [comment]
> To use http implementation, the only 2 dependencies I need are: spring-boot-starter-actuator and spring-cloud-kubernetes-discovery, is that correct?

I don't see why you would need the discovery dependency

> Should config watcher be deployed in another pod, or as sidecar in my app's pod?

I wrote it to be deployed in another pod.  It should be a service that can be used by multiple apps.

> Could you please share a working bootstrap.yml for http implementation?
For the config watcher?

**Comment by neo-feng** [comment]
> > To use http implementation, the only 2 dependencies I need are: spring-boot-starter-actuator and spring-cloud-kubernetes-discovery, is that correct?
> >  I don't see why you would need the discovery dependency

So for http the only dependency is pring-boot-starter-actuator?

> > Should config watcher be deployed in another pod, or as sidecar in my app's pod?
> > I wrote it to be deployed in another pod. It should be a service that can be used by multiple apps.

My understanding is that config watcher invokes app's refresh interface instead of being invoked by app, so why do we need a service to expose it? Please let me know if I miss anything.

> > Could you please share a working bootstrap.yml for http implementation?
> > For the config watcher?

No, the config for my app.

**Comment by ryanjbaxter** [comment]
>So for http the only dependency is pring-boot-starter-actuator?

Yes

>My understanding is that config watcher invokes app's refresh interface instead of being invoked by app, so why do we need a service to expose it? Please let me know if I miss anything.

You don't need a service, no.

> No, the config for my app.

The only configuration you would need is to make sure the actuator `/refresh` endpoint is exposed if you are using HTTP to receive the refresh notification 
https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#refresh-scope

**Comment by neo-feng** [comment]
I finally get it work -- after updating configmap, watcher detected it and send post request to refresh application. 
It works fine when watcher just deployed, however, after 45 minutes, I modified configmap again, watcher had no response, changes were not detected (no logs). I uses latest watcher image.

Is it a known issue?

**Comment by ryanjbaxter** [comment]
Not that I am aware of.  You can open a separate issue and we can discuss it.  Please provide details of where it is deployed and turn on debug logging and provide the logs from the config watcher.

**Comment by neo-feng** [comment]
> Not that I am aware of. You can open a separate issue and we can discuss it. Please provide details of where it is deployed and turn on debug logging and provide the logs from the config watcher.

I will open a new issue, another strange thing:
To expose actuator/refresh I have to add spring-cloud-starter-kubernetes-fabric8-config as dependency,  I successfully exposed a lot of other actuator interfaces without spring-cloud-starter-kubernetes-fabric8-config, but for refresh  I have to add spring-cloud-starter-kubernetes-fabric8-config.

Dose this make sense to you?

**Comment by ryanjbaxter** [comment]
Nope

**Comment by neo-feng** [comment]
Ask a question on best practices of config watcher. Say I have 10 microservices, each has its own configmap, and each have 10 instances(pods), how many config watchers instances should I provisioned? should the 10 microservices share 1 watcher or each have their own watcher (10 in total)?
