### ISSUE TITLE
load balance like istio canary release

### ISSUE THREAD

**Issue by akaxb** [spring-cloud/spring-cloud-kubernetes#848]
dose spring cloud kubernetes can lb service like istio , can filter by pod label， for example，http request from jack will access version 1, and  tom will access version 2

in eureka,  we can set the app metadata such as version:1

in kubernetes，we can deploy service with version label，but，how to choose the ture instance by label，i think，its a good feature to support canary release

**Comment by ryanjbaxter** [comment]
I have not tried this myself, but you might be able to leverage hint based load balancing to accomplish this
https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#spring-cloud-loadbalancer-hints

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
