### ISSUE TITLE
what is defference between 'spring-cloud-starter-kubernetes-client-all' and 'spring-cloud-starter-kubernetes-all'

### ISSUE THREAD

**Issue by yjYinch** [spring-cloud/spring-cloud-kubernetes#862]
spring-cloud-starter-kubernetes-client-all, if I have imported spring-cloud-dependencies in parent pom, I need not to set version in spring-cloud-starter-kubernetes-client-all dependencies.
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-client-all</artifactId>
</dependency>
```
however, if I import spring-cloud-starter-kubernetes-all dependency, I need to set the version. so I just want to know what is difference between `spring-cloud-starter-kubernetes-client-all` and `spring-cloud-starter-kubernetes-all` if I just want to use `@EnableDiscoveryClient` annotation.
spring-cloud-starter-kubernetes-all:
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-all</artifactId>
    <version>1.1.10.RELEASE</version>
</dependency>
```

**Comment by ryanjbaxter** [comment]
What version of Spring Cloud are you using?

**Comment by yjYinch** [comment]
> What version of Spring Cloud are you using?

2020.0.0

**Comment by ryanjbaxter** [comment]
`spring-cloud-kubernetes-all` does not exist in that version.

You need to choose `spring-cloud-starter-kubernetes-client-all` or `spring-cloud-starter-kubernetes-fabric8-all`

**Comment by yjYinch** [comment]
> `spring-cloud-kubernetes-all` does not exist in that version.
> 
> You need to choose `spring-cloud-starter-kubernetes-client-all` or `spring-cloud-starter-kubernetes-fabric8-all`

All right, thank you.
