### ISSUE TITLE
kubernetes load balancer mode service and caching

### ISSUE THREAD

**Issue by madaram** [spring-cloud/spring-cloud-kubernetes#869]
**kubernetes load balancer mode service and caching**

Hello, I use **spring-boot-dependencies 2.3.11.RELEASE** with **spring-cloud-dependencies Hoxton.SR8** and dependency spring-cloud-starter-kubernetes-loadbalancer. I configured my application with **spring.cloud.kubernetes.loadbalancer.mode=SERVICE** and it works perfectly. 

However I also have **spring.cloud.loadbalancer.cache.enabled** present but cache is not used. Debugging the load balancer shows that no CachingServiceInstanceListSupplier is involved, only KubernetesServicesListSupplier.

We experienced Kubernetes API slownesses on our production platform and then caching would be very interesting for us.

Would you have any suggestion to enable caching when using spring.cloud.kubernetes.loadbalancer.mode=SERVICE ? Or to decorate KubernetesServicesListSupplier (like what CachingServiceInstanceListSupplier does) when SERVICE mode in activated ?

Thank you for your help.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
