### ISSUE TITLE
Integration tests failing 

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#874]
We currently have an issue where integration tests are failing, specifically `ActuatorEndpointIT` in `spring-cloud-kubernetes-core-k8s-client-it`. It is an interesting issue and it took a bit to find out what is going on.

If I go into the root of that project and issue : 

```
mvn spring-boot:build-image -Dspring-boot.build-image.imageName=docker.io/springcloud/spring-cloud-kubernetes-core-k8s-client-it:2.0.5-SNAPSHOT
```

As a result I will get a docker image saved locally. If I want to run that image now:

```
docker run -it -p 8080:8080 springcloud/spring-cloud-kubernetes-core-k8s-client-it:2.0.5-SNAPSHOT
```

I will get : 

```
Setting Active Processor Count to 6
Calculating JVM memory based on 634364K available memory
Calculated JVM Memory Configuration: -XX:MaxDirectMemorySize=10M -Xmx192921K -XX:MaxMetaspaceSize=134242K -XX:ReservedCodeCacheSize=240M -Xss1M (Total Memory: 634364K, Thread Count: 50, Loaded Class Count: 21287, Headroom: 0%)
Enabling Java Native Memory Tracking
Adding 128 container CA certificates to JVM truststore
Spring Cloud Bindings Enabled
Picked up JAVA_TOOL_OPTIONS: -Djava.security.properties=/layers/paketo-buildpacks_bellsoft-liberica/java-security-properties/java-security.properties -XX:+ExitOnOutOfMemoryError -XX:ActiveProcessorCount=6 -XX:MaxDirectMemorySize=10M -Xmx192921K -XX:MaxMetaspaceSize=134242K -XX:ReservedCodeCacheSize=240M -Xss1M -XX:+UnlockDiagnosticVMOptions -XX:NativeMemoryTracking=summary -XX:+PrintNMTStatistics -Dorg.springframework.cloud.bindings.boot.enable=true
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff8b1c122f7, pid=1, tid=0x00007ff8b2d7a700
#
# JRE version:  (8.0_302-b08) (build )
# Java VM: OpenJDK 64-Bit Server VM (25.302-b08 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0xb2a2f7]  VirtualMemoryTracker::add_reserved_region(unsigned char*, unsigned long, NativeCallStack const&, MemoryType, bool)+0x77
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /workspace/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://bell-sw.com/support
#

[error occurred during error reporting , id 0xb]
```

On the other hand, if I change the `pom.xml` and include: 

```
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<image>
						<env>
							<BP_JVM_VERSION>11.*</BP_JVM_VERSION>
						</env>
					</image>
				</configuration>
			</plugin>
		</plugins>
```

`docker run` will now work just fine. This might be related to the latest release [here](https://github.com/paketo-buildpacks/bellsoft-liberica/releases/tag/v8.7.0)?. 

To confirm this, I would need to downgrade to `8.6.0`, but I am yet to figure out how to do this (if it's possible at all).

**Comment by wind57** [comment]
[here it is](https://github.com/paketo-buildpacks/bellsoft-liberica/issues/131), it only took 1/2 a day to figure out what is going on _before_ I found it :) anyway, a fix is coming soon

**Comment by ryanjbaxter** [comment]
Shouldnt the fix come from the buildpack?

**Comment by wind57** [comment]
we can have an interim fix and when that fix is propagated, we can get rid of this interim fix. 
this way we can merge a few pending stories, in the meanwhile. wdyt? I'll take care of this, of course.

**Comment by ryanjbaxter** [comment]
Thats fine but I a curious what you had in mind for the fix?

It seems like we would have to add a parameter when every container is started....

**Comment by wind57** [comment]
@ryanjbaxter  [exactly right](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/875/files)

**Comment by KatieKoslosky** [comment]
In case this helps anyone else - I worked around this by adding this argument to my mvn spring-boot:build-image command: -Dspring-boot.build-image.builder=paketobuildpacks/builder:0.1.160-base

(I chose 0.1.160 arbitrarily because it was the active version last time we had a successful release. You can probably find the most recent version that uses Bellsoft Liberica 8.6.0 here: https://github.com/paketo-buildpacks/base-builder/tags )

**Comment by wind57** [comment]
right, a different builder would help because they don't add those native memory tracking option (and other related too) in that image.

We do not want a different builder, but simply disabling one single flag. From the years that I have been coding, I used `jcmd` with `NMT` _once_, for code cache debug. And since this is for tests only in our case, we do not even care about this flag.

Nevertheless, your idea is good for someone who might come here for a different reason; same idea of choosing a builder is in the bug description too, btw.

**Comment by ryanjbaxter** [comment]
I actually prefer specifying the builder for now.  The changes are much smaller
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/2.0.x/spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/pom.xml#L85
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/2.0.x/spring-cloud-kubernetes-integration-tests/run.sh#L123

Lets leave this issue open until the buildpack issue is fixed and we can revert the above changes.
