### ISSUE TITLE
Spring Cloud Kubernetes Secrets ProperySources Don't Use Active Profiles

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-kubernetes#880]
Unlike the ConigMap PropertySource implementations (both Fabric8 and Kubernetes client), the Secrets PropertySource implementations don't take into account active profiles.  Seems like they should for the sake of consistency.

**Comment by ryanjbaxter** [comment]
Yeah ran into it working on this pr
https://github.com/spring-cloud/spring-cloud-kubernetes/pull/881/files#diff-78b603db3110784f23a8f456fb8377306be36ae3856cfb37414a5dbcc96c4d3cR236

**Comment by wind57** [comment]
@ryanjbaxter can be closed, as supported was added
