### ISSUE TITLE
Proposal and feedback required 

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#883]
We have introduced an unexpected change for some of our users with the namespace resolution, for example see [here](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/876). I added that change. 

The issue is that to properly read config maps and secrets getting the namespace is mandatory, as we can not default or imply it. The situation is slightly more complicated because kubernetes-native client requires a namespace to be present, otherwise we currently have [this issue](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/861).

To put it very simple: if we want to read a secret or a config map, we must have a namespace. 

This opens an interesting discussion. A namespace makes sense only when you are in an actual cluster, of course. 

What if you are not in a cluster (see the first link), but you still want to be able to start your application (or dependent applications). I can think of another reason - what if you have `spring-cloud-kubernetes-XXX-config` on the classpath, but start (without a cluster) an un-related feature? 

Before we introduce namespace resolution concept, we used to log an error, but never fail. After introduction of that concept, we now fail. Of course users are surprised, I can't blame them. 

We have `@ConditionalOnKubernetesSecretsEnabled` and `@ConditionalOnKubernetesConfigEnabled` or even `@ConditionalOnKubernetesEnabled`, but this adds more work for users. Also this brakes their expectations from a previous version. Again, this sort of makes sense, imo. 

What if we could disable reading secrets and config maps entirely (not dependent on those conditionals), unless we are in a cluster? This would not be complicated at all, as a matter of fact. 

We already have this post processor (same idea exists for fabric8 client):

```
public class KubernetesClientProfileEnvironmentPostProcessor extends AbstractKubernetesProfileEnvironmentPostProcessor {

	@Override
	protected boolean isInsideKubernetes(Environment environment) {
		CoreV1Api api = new CoreV1Api();
		KubernetesClientPodUtils utils = new KubernetesClientPodUtils(api, environment.getProperty(NAMESPACE_PROPERTY));
		return environment.containsProperty(ENV_SERVICE_HOST) || utils.isInsideKubernetes();
	}
}
```

Reusing this is not an option, because `KubernetesClientPodUtils::isInsideKubernetes` requires a namespace for it to work and it's exactly what we are trying to not do. 
We could start implementing this by simply looking if `KUBERNETES_SERVICE_HOST` is present (that is what `environment.containsProperty(ENV_SERVICE_HOST)` does).

We are basically going to say that : if that env property is present, try to read config maps and/or secrets; do nothing otherwise. This is not bullet proof, but should be good enough to narrow users expectations. 

If that is not going to be enough and we will get reports of not being so, we can always go a little deeper and replicate/extract the idea used here in `KubernetesClientPodUtils`:

```
	private V1Pod internalGetPod() {
		try {
			if (isServiceHostEnvVarPresent() && isHostNameEnvVarPresent() && isServiceAccountFound()) {
				return client.readNamespacedPod(hostName, namespace, null, null, null);
			}
		}
		catch (Throwable t) {
			LOG.warn("Failed to get pod with name:[" + hostName + "]. You should look into this if things aren't"
					+ " working as you expect. Are you missing serviceaccount permissions?", t);
		}
		return null;
	}
```

specifically I am talking about `isServiceHostEnvVarPresent` and `isHostNameEnvVarPresent` and `isServiceAccountFound`.

For the time being simply checking for `KUBERNETES_SERVICE_HOST` should work for the vast majority of users.

wdyt?

**Comment by pukkaone** [comment]
Spring Boot also [auto-detects Kubernetes by checking for `*_SERVICE_HOST` and `*_SERVICE_PORT` environment variables](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#deployment.cloud.kubernetes).
