### ISSUE TITLE
Drop @ConditionalOnKubernetesEnabled in favor of @ConditionalOnCloudPlatform

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#893]
The knowledge if we are currently running in a k8s cluster (among some other checks) is mainly done via `@ConditionalOnKubernetesEnabled`. At least we use this one to either provide or not k8s related beans. This check should be done using spring-boot : `@ConditionalOnCloudPlatform`

**Comment by wind57** [comment]
@ryanjbaxter what do you think if we take this into the release on Nov 30? If you agree - this will become my next priority.

**Comment by ryanjbaxter** [comment]
Makes sense

**Comment by wind57** [comment]
I have two question here : 

- I will change the documentation to point that the logic for kubernetes awareness has changed. Do I also need to document or mention the fact that this behavior has changed since `2021.0.0`?
- It seems that this change must be present in a certain "migration guid", but I do not know where (and if) such exists.

Ryan need your guidance a bit.

**Comment by ryanjbaxter** [comment]
I would be fine highlighting this in a section at the top of the documentation around functional changes in behavior when upgrading to 2.1.x.

**Comment by wind57** [comment]
[PR for this is out](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/908)

**Comment by ryanjbaxter** [comment]
I talked this over with the team and it was decided we should wait till our next major release

**Comment by wind57** [comment]
Thats fine, when time comes.
