### ISSUE TITLE
Update to spring cloud style documentation

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-kubernetes#9]

**Comment by cmoulliard** [comment]
@spencergibb Is there a guide describing such style convention ?

**Comment by spencergibb** [comment]
No, there is no guide, but it should follow the other projects https://github.com/spring-cloud/spring-cloud-netflix/tree/master/docs

Basically, all the docs live there in asciidoc format, including the readme.

**Comment by spencergibb** [comment]
Closed via #263
