### ISSUE TITLE
Add new module - Turbine discovery

### ISSUE THREAD

**Issue by cmoulliard** [spring-cloud/spring-cloud-kubernetes#90]
As NetFlix OSS proposes a nice [solution](https://github.com/Netflix/Turbine/wiki) to aggregate the  streams of server send events - Turbine, we should integrate also the Turbine Discovery project [developed under the Kubeflix github org](https://github.com/fabric8io/kubeflix/tree/master/turbine-discovery) within Spring Cloud Kuerbernetes in order to provide the Discovery feature when the application is running top of the kubernetes platform.

As we already offer such a feature for Ribbon & Hystrix, this is logic to provide it for Turbine too

**Comment by spencergibb** [comment]
spring-cloud-netflix has support for using turbine with [CommonsInstanceDiscovery](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-turbine/src/main/java/org/springframework/cloud/netflix/turbine/CommonsInstanceDiscovery.java) which s-c-k8s implements. Is there anything else needed?

**Comment by cmoulliard** [comment]
I will review the existing [code](CommonsInstanceDiscovery ) to see if it fits our requirements implemented in [TurbineDiscovery](https://github.com/fabric8io/kubeflix/blob/master/turbine-discovery/src/main/java/io/fabric8/kubeflix/turbine/TurbineDiscovery.java) to grab the endpoints where the `hystrix_enabled` label is `true`

**Comment by iocanel** [comment]
The kubeflix turbine discovery module aimed, at non spring users. For spring users, using the discovery module of spring cloud kubernetes, should actually work (though I haven't tried it).

On the other hand, the kubeflix discovery module does have some extra goodies, like support cross namespace aggregation, filtering services by label etc. If it makes sense, to have those for spring cloud kubernetes I don't mind bringin that code over.

**Comment by cmoulliard** [comment]
According to our discussion, here are the actions that I propose to do :  

- [ ] Test Turbine with Spring Cloud Discovery mechanism to see if works base on an example or test case
- [ ]  Add cross namespace aggregation feature
- [ ]  Add filtering services by label
- [ ]  Anything else ?

**Comment by spencergibb** [comment]
Turbine has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
