### ISSUE TITLE
Mockserver dependency must be upgraded

### ISSUE THREAD

**Issue by pandrez** [spring-cloud/spring-cloud-kubernetes#900]
As the fabric8 kubernetes client version is now `5.5.0`, the `io.fabric8:mockwebserver` dependency must also be upgraded from `0.1.2`to `0.1.8` [link to the maven repository](https://mvnrepository.com/artifact/io.fabric8/kubernetes-server-mock/5.5.0)

Without this upgrade, there are some classes missing (for example, `io.fabric8.mockwebserver.crud.AttributeType`) which makes some requests  to the mockserver fail with a `NoClassDefFoundError`

**Comment by wind57** [comment]
@ryanjbaxter  I was looking at his one today a bit and before I even do anything here, I would to ask a small question. 

We had [this PR, that upgraded to 5.5.0](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/836/files). It is present in `main` branch, but not in `2.0.x`.

I do not really have a good understanding how releases are made and of what branches... Can you please comment here? 

Moreover, there are many things in `2.0.x`, but not in `main` and also in reverse. Thank you.

**Comment by ryanjbaxter** [comment]
The 2.0.x branch is for Spring Cloud 2020.0.x release train
The main branch is for Spring Cloud 2021.0.x release train

We try to merge what we can into the 2.0.x branch and then merge it forward.  So everything in 2.0.x should also be in main.

There may be things in main that are not in 2.0.x because there are new features we are part of the 2021.0.x release.

**Comment by wind57** [comment]
thank you @ryanjbaxter, that makes sense.

**Comment by wind57** [comment]
@pandrez while we fixed this one, can you explain against what release where you testing and what where your steps? This is only possible to do from our `main` branch, so exactly what release where you using then? thank you

**Comment by pandrez** [comment]
@wind57 I was testing with Spring Cloud 2021.0.x release train, which will be the first one to use fabric8 5.x version!
Like you said, this is only needed on the main branch.

Thank you for your support!

**Comment by wind57** [comment]
@pandrez thank you for the feedback. To be fair, I was more interested in this part of my questions: "what where your steps?". I am still wondering what where you doing, initially to hit this issue. Where you writing your own tests that relied on transitive test dependencies? If so, I am still wondering how they ended up on your classpath...

What I really hoped for is a very simple and minimal example.
