### ISSUE TITLE
Remove some deprecation we have in ConfigMap and Secrets implementation

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#909]
ConfigMaps and Secrets functionality has recently seen quite a lot of changes and enhancements.  Due to that, there are some deprecated things in our code base. I am proposing to remove some of them in the major release going in on Nov. 30. 

wdyt?

**Comment by ryanjbaxter** [comment]
Actually we need to wait for our next major release, 2.1.0 is still considered a minor release

**Comment by wind57** [comment]
Thats OK, I will manage this one until it is ready to go. Thank you
