### ISSUE TITLE
If base on spring-cloud-starter-kubernetes-loadbalancer, not Ribbon. How can realize retries in applications

### ISSUE THREAD

**Issue by damon008** [spring-cloud/spring-cloud-kubernetes#912]
**Is your feature request related to a problem? Please describe.**
I hope that realize retries in applications based on `spring-cloud-starter-kubernetes-loadbalancer`.
**Describe the solution you'd like**
I hope that realize retries in applications based on `spring-cloud-starter-kubernetes-loadbalancer`.

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanjbaxter** [comment]
You should be using Spring Coud Loadbalancer to retry requests
https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#retrying-failed-requests

**Comment by damon008** [comment]
@ryanjbaxter  If I want to `spring-cloud-starter-kubernetes-ribbon`, but I found that it can not support mutual requests for pods under different namespaces based on `spring-cloud-starter-kubernetes-ribbon` #913

**Comment by ryanjbaxter** [comment]
I responded there, but that is unrelated to this issue.  Can we close this issue?

**Comment by damon008** [comment]
@ryanjbaxter  If based on spring-cloud-starter-kubernetes-loadbalancer,we hope provide more features with it, like retry,timeout,LB Policy and so on, those features provided by ribbon.

**Comment by ryanjbaxter** [comment]
We won't be adding any more features to Ribbon.  Netflix has put it in maintenance.
