### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#921]
Looks like one more interesting build issue here :  https://app.circleci.com/pipelines/github/spring-cloud/spring-cloud-kubernetes/1215/workflows/0b8d952e-d4c6-4036-941c-d3ff876b417d/jobs/2314

Specifically: 

```
Upgrade your pricing plan to take advantage of longer build times

context deadline exceeded
```

@ryanjbaxter do you know anything about this?

**Comment by ryanjbaxter** [comment]
I was hoping this was just a temporary issue but I guess not.  I wonder if installing microk8s is taking way too long for some reason?
We will need to look into it.

**Comment by wind57** [comment]
It looks like build time from github is maxex to 1h? It looks like this to me from the build, but I have not found this in the docs. 

On another note, why do we have microk8s _and_ kind integration tests? Do you happen to know?

**Comment by ryanjbaxter** [comment]
Yeah I googled it quickly but didn't come up with anything either.  I've been out of the office the past 2 days and will be out till Monday so I haven't looked into it.

The microk8s are left overs from the original community project.  I've been trying to find time to move them to kind.  Just haven't found the time yet

**Comment by wind57** [comment]
Oh! Ill create a defect if it does not exist and try to move them, if I have time too. Happy time off!

**Comment by ryanjbaxter** [comment]
I'm pretty much convinced that the problem here is that we have hit the limits of our free tier usage and now we are only allowed to run a build for an hour.  I am going to try and get confirmation from CircileCi as well.

**Comment by wind57** [comment]
I was looking into this yesterday, but my account does not allow me to do that. I guess that is something you should be able to, but I am just guessing.

**Comment by ryanjbaxter** [comment]
And removing microk8s won't solve this particular issue either because the build will still likely take the same amount of time (roughly)

**Comment by wind57** [comment]
you're right, totally. Just wanted to put that out

**Comment by ryanjbaxter** [comment]
FYI its a limit of the free tier
https://discuss.circleci.com/t/context-deadline-exceeded/42030

**Comment by wind57** [comment]
interesting how this has triggered a major refactor of the pipeline. I love it!
