### ISSUE TITLE
[Suggestion] Add a new module containing Openshift Template or Kubernetes List

### ISSUE THREAD

**Issue by cmoulliard** [spring-cloud/spring-cloud-kubernetes#93]
I would like to propose to create a new maven module containing yaml/json config files of related technology (E.g. Hystrix Dashboard, Turbine Server, ...) that we could deploy on Kubernetes/Openshift to play with Spring Cloud Kubernetes Hystrix, Spring Cloud Kubernetes Zipkin, ...

Openshift Templates

- [Hystrix Dashboard](https://github.com/snowdrop/openshift-templates/blob/master/hystrix-dashboard/hystrix-dashboard.yml)
- [Turbine Server](https://github.com/snowdrop/openshift-templates/blob/master/turbine-server/turbine-server.yml)

**Comment by spencergibb** [comment]
I don't think this is the right place for this.
