### ISSUE TITLE
Spammy logging from KubernetesClientConfigMapPropertySource

### ISSUE THREAD

**Issue by cfredri4** [spring-cloud/spring-cloud-kubernetes#932]
This started being logged after updating to latest version. With default settings this is logged every 15 seconds. Surely this should be debug and not info?

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/3351926041a630aee0961ba0e1be8f035e4ba2ca/spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientConfigMapPropertySource.java#L62

**Comment by ryanjbaxter** [comment]
Are you using polling refresh configuration?

**Comment by cfredri4** [comment]
Sorry I forgot to mention this, yes I use polling (with default period of 15 seconds).
