### ISSUE TITLE
Context load test fails with Spring Boot 2.6.1 and Spring Cloud 2021.0.0

### ISSUE THREAD

**Issue by Alos** [spring-cloud/spring-cloud-kubernetes#934]
**Describe the bug**
While running the contextLoads test Spring Cloud Kubernetes fails with the following:

```
Error creating bean with name 'kubernetesKubectlCreateProcessor': Unsatisfied dependency expressed through field 
'apiClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with
 name 'defaultApiClient' defined in class path resource 
[io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.class]: Bean 
instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: 
Failed to instantiate [io.kubernetes.client.openapi.ApiClient]: Factory method 'defaultApiClient' threw exception;
 nested exception is java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "expiryObj" is null
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
'defaultApiClient' defined in class path resource [io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.class]:
 Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException:
 Failed to instantiate [io.kubernetes.client.openapi.ApiClient]: Factory method 'defaultApiClient' threw exception; 
nested exception is java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "expiryObj" is null
...
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.kubernetes.client.openapi.ApiClient]: 
Factory method 'defaultApiClient' threw exception; nested exception is java.lang.NullPointerException: 
Cannot invoke "Object.getClass()" because "expiryObj" is null
...
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "expiryObj" is null
	at io.kubernetes.client.util.authenticators.GCPAuthenticator.isExpired(GCPAuthenticator.java:54)
	at io.kubernetes.client.util.KubeConfig.getAccessToken(KubeConfig.java:214)
```

Is there a way to tell Spring Cloud Kubernetes to not try to access the API and authenticate while running JUnit tests?

**Comment by Alos** [comment]
I tried adding 

bootstrap.properties:
```
spring.cloud.kubernetes.discovery.enabled=false
spring.cloud.kubernetes.enabled=false
```


application.yaml:
```yaml
spring:
  application:
    name: cat-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gcp:
      datastore:
        emulator:
          port: 8182
          enabled: true
          consistency: 1
    kubernetes:
      enabled: false
      loadbalancer:
        enabled: false
```

**Comment by Alos** [comment]
I've added a sample project you can look at: 

https://github.com/Alos/SpringCloudKubernetesIssue934

**Comment by wind57** [comment]
I am on the phone typing this, but that kubectl processor looks very familiar, and we had a flag to disable it... Can you search in the closed recently issues? If not, I can look at this closer in the upcoming days

**Comment by Alos** [comment]
Let me look into closed issues and report back

**Comment by Alos** [comment]
I think its related to #927 but I'm not sure how to proceed to disable the flag on the current version.

**Comment by wind57** [comment]
Can't you set `kubernetes.informer.enabled=false` property?

**Comment by ryanjbaxter** [comment]
Yes try setting `kubernetes.informer.enabled=false` its autoconfiguration from the underlying kubernetes client kicking in.

**Comment by ryanjbaxter** [comment]
Try also setting `kubernetes.manifests.enabled=false`

**Comment by Alos** [comment]
Yep, this worked! Thanks @ryanjbaxter!

Adding:

```
kubernetes.informer.enabled=false
kubernetes.manifests.enabled=false
```
to my `bootstrap.properties` in java/test/resources worked!

**Comment by ryanjbaxter** [comment]
I'm working on an downstream fix in the kubernetes java client as we speak to fix this.  The informer auto configuration should catch any exception while creating the APIClient and just create a default one.
https://github.com/kubernetes-client/java/pull/1963

**Comment by wind57** [comment]
Ah yes! This is how I remember it... Thank u for the reminder for myself too

**Comment by ryanjbaxter** [comment]
I have updated the dependency to 11.0.4 in the 2.0.x branch but we need to fix in the 13.0.x branch as well for spring cloud k8s 2.1.x.  I have created a PR here to cherry pick the commit.  https://github.com/kubernetes-client/java/pull/2079

**Comment by Alos** [comment]
Hey @ryanjbaxter, I just tried building with Spring Cloud `spring-cloud-dependencies:2021.0.0` and still experiencing the issue, should I wait for the next version to see these changes applied by default without adding the `bootstrap.properties` changes?

**Comment by ryanjbaxter** [comment]
Can you try using snapshot builds?
