### ISSUE TITLE
Configuration Watcher Not Working

### ISSUE THREAD

**Issue by sdaskam1** [spring-cloud/spring-cloud-kubernetes#936]
I have been trying to get the Configuration Watcher working with a small spring boot app but am not having any luck so far. And I haven't found any good working examples online.

I have a couple of issues:
1) The application properties aren't being loaded from the config map when the application first starts up unless I include the spring-cloud-starter-kubernetes-fabric8-config dependency and reload is enabled (I thought that was being deprecated).
2) The Config Watcher doesn't seem to be picking up the changes that I make to the config map (as far as I can tell).

Here is the repo containing my code and kube config:
https://github.com/sdaskam1/ConfigWatcher

**Comment by ryanjbaxter** [comment]
1.) The configmap needs to be mounted as a volume in the container and spring boot needs to be pointed at the file
2.) Try enabling logging in the configuration watcher to see if it shows why its not making a request to the refresh endpoint `logging.level.org.springframework.cloud.kubernetes=TRACE`

**Comment by sdaskam1** [comment]
Thanks Ryan! That makes sense. I also found a working example which has those features:
https://github.com/neo-feng/configwatcherdemo

**Comment by ryanjbaxter** [comment]
There are also examples in the integration tests in spring cloud kubernetes.  Can we close this issue now?

**Comment by sdaskam1** [comment]
I did have one more question. Is it possible to have a single configuration watcher in the default namespace that monitors config maps in a bunch of different namespaces?

**Comment by ryanjbaxter** [comment]
There is an issue open for that already https://github.com/spring-cloud/spring-cloud-kubernetes/issues/740#issuecomment-946146436

**Comment by mbaykara** [comment]
@sdaskam1 I saw your example but as you asked in first commend 1. removing dependencies. So in your example you are still adding the `spring-cloud-starter-kubernetes-fabric8-config` dependency to the `pom.xml`. Do I need to add them to configure the watcher?
