### ISSUE TITLE
[spring-cloud-kubernetes-configuration-watcher] Shared ConfigMap refresh

### ISSUE THREAD

**Issue by dkirrane** [spring-cloud/spring-cloud-kubernetes#937]
**Is your feature request related to a problem? Please describe.**
Refresh all SpringBoot applications reading a shared ConfigMap.

**Describe the solution you'd like**
My requirement is to have a shared ConfigMap. All SpringBoot applications read it.
When this ConfigMap gets updated then `spring-cloud-kubernetes-configuration-watcher` would refresh all SpringBoot applications using it.

**Comment by ryanjbaxter** [comment]
I think this is similar to https://github.com/spring-cloud/spring-cloud-kubernetes/issues/740
We need a way for an app to say its interested in being notified of changes in configmaps/secrets other than the one that match its name.
