### ISSUE TITLE
Question: POM file managing the dependencies + versions of the project

### ISSUE THREAD

**Issue by cmoulliard** [spring-cloud/spring-cloud-kubernetes#94]
Which maven module is supposed to be used to manage as a parent pom, the dependencies + versions declared for Spring Cloud Kubernetes

The pom.xml file, part of the root folder of the project, contains a section with versions 

```
<properties>
		<!-- Dependency Versions -->
		<spring-cloud-commons.version>1.2.0.RELEASE</spring-cloud-commons.version>
		<spring-cloud-netflix.version>1.3.0.RELEASE</spring-cloud-netflix.version>
		<spring-cloud-sleuth.version>1.2.0.RELEASE</spring-cloud-sleuth.version>

		<!-- Maven Plugin Versions -->
		<maven-compiler-plugin.version>3.5</maven-compiler-plugin.version>
		<maven-deploy-plugin.version>2.8.2</maven-deploy-plugin.version>
		<maven-failsafe-plugin.version>2.19.1</maven-failsafe-plugin.version>
		<maven-surefire-plugin.version>2.19.1</maven-surefire-plugin.version>
		<fabric8.maven.plugin.version>3.2.28</fabric8.maven.plugin.version>
		<gmavenplus-plugin.version>1.2</gmavenplus-plugin.version>
	</properties>
```

while this is also the case for the pom.xml created under `spring-cloud-kubernetes-dependencies`

```
<properties>
		<arquillian.version>1.1.13.Final</arquillian.version>
		<arquillian-cube.version>1.3.2</arquillian-cube.version>
		<kubernetes-client.version>2.2.0</kubernetes-client.version>
		<mockwebserver.version>0.0.12</mockwebserver.version>
		<restassured.version>3.0.2</restassured.version>
		<spock-spring.version>1.0-groovy-2.3</spock-spring.version>
	</properties>
```

We should perhaps manage in one place the versions + dependencies & dependencyManagement ?

**Comment by spencergibb** [comment]
We have to be careful because of the way the release train is structured. Things that the release train supplies (commons, netflix, sleuth) shouldn't be in `spring-cloud-kubernetes-dependencies`. `spring-cloud-kubernetes-dependencies` should be for dependencies that clients will need that are needed by this project.

**Comment by cmoulliard** [comment]
Thanks for the info Spencer. We should maybe document such info within the Developer Guide @spencergibb ?

As `<fabric8.maven.plugin.version>3.2.28</fabric8.maven.plugin.version>` is specific to this project  I propose to move it under `spring-cloud-kubernetes-dependencies`. Make sense @iocanel ?

**Comment by spencergibb** [comment]
I believe this is taken care of.
