### ISSUE TITLE
KubernetesProfileEPP needs extensional permissions.

### ISSUE THREAD

**Issue by LeoBarykin** [spring-cloud/spring-cloud-kubernetes#944]
**Is your feature request related to a problem? Please describe.**
I am using spring-cloud for refreshing configs in runtime via config maps reload feature. The problem is that I need to approve all roles my service account has with cybersecurity department. In current version it needs 'list pods' role in KubernetesProfileEnvironmentPostProcessor. Now it checks presence of profile after listing pods which leads to KubernetesCloudException.

**Describe the solution you'd like**
In my opinion,  the check of environment cad be added to second 'if' operator in postProcessEnvironment()

**Describe alternatives you've considered**
Is there any way just to disable this EnvironmentPostProcessor via config or java opts? I can not come up with solution myself so far.

**Comment by wind57** [comment]
I've tried to read your description a few times, but I still don't understand what problem you are facing :( 

Are you talking about `KubernetesClientProfileEnvironmentPostProcessor`? There are two implementations of `AbstractKubernetesProfileEnvironmentPostProcessor` - fabric8 and native client, which are you using?

Can you may be provide a bit more verbosity of what you mean with:

> In current version it needs 'list pods' role in KubernetesProfileEnvironmentPostProcessor. Now it checks presence of profile after listing pods which leads to KubernetesCloudException.

this will help me understand the problem better.

**Comment by LeoBarykin** [comment]
Hello, @wind57 ! Thank you for your answer! I am sorry for being unclear, let me try to explain it.
I found that there is no class `KubernetesProfileEnvirinmentPostProcessor` in this repo currently. So probably I am using an outdated version
My dependency is: 
`'org.springframework.cloud:spring-cloud-starter-kubernetes-all:2.0.0-M2'`
Could you please tell me the correct dependency which I need to achieve config maps property source and reloading it in runtime? Or is it in another repository?
