### ISSUE TITLE
Unable to get available services using discoveryclient. List always empty

### ISSUE THREAD

**Issue by CosbyBs86** [spring-cloud/spring-cloud-kubernetes#957]
Hello all,
 I'm struggling with this since days. I have the following configuration:

pom.xml
`
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-discoveryclient</artifactId>
`

application.xml

cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
          primary-port-name: "default-http"
    kubernetes:
      discovery:
        namespace: "default"
        enabled: true
        all-namespaces: true
        discovery-server-url: "http://test-discoveryserver"
      reload:
        enabled: true
        mode: polling
        period: 5000

main.java
`
// Classe main
@SpringBootApplication
@EnableDiscoveryClient
@RestController
@EnableScheduling
public class GatewayApplication {

  private static final Logger LOGGER = LoggerFactory.getLogger(GatewayApplication.class);

  @Autowired
   private DiscoveryClient client;

  // Costruttore protetto - la classe non deve essere istanziata
  protected GatewayApplication() {
    // Costruttore protetto - la classe non deve essere istanziata
  }

  @GetMapping("/services")
  public List<String> services() {
    return client.getServices();
  }

  @Bean
  public RestTemplate restTemplate() {
    return new RestTemplate();
  }

  //Main spring application intitializer
  public static void main(String[] args) {
    //Start SpringApplication
    SpringApplication.run(GatewayApplication.class, args);
  }
`

if I try to call, passing from the gateway, an API exposed by another microservice (i.e. http://127.0.0.1:8080/service-name/api) the call is correctly routed on the target microservice (so the discovery is working fine), but if I call the http://127.0.0.1:8080/services API obtaining the list of available microservices i always get an empty array.

What am I missing? Can you support me please?

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by CosbyBs86** [comment]
[test-app.zip](https://github.com/spring-cloud/spring-cloud-kubernetes/files/7891104/test-app.zip)

Here you go. this is the gateway is creating the issue. I hope this can help you.

**Comment by CosbyBs86** [comment]
[test-app.zip](https://github.com/spring-cloud/spring-cloud-kubernetes/files/7891110/test-app.zip)
Here you go. I hope this can help you. Deploying this in a microservices kubernetes environment behave as I wrote above

**Comment by ryanjbaxter** [comment]
And this happens when running in kubernetes?  Is there anything in the logs?

**Comment by CosbyBs86** [comment]
Hello,
No I don't have anything weird on the logs. If I check the "client"
variable description, it is a "Composite discovery client" with only one
instance bound. The instance is a "Simple discovery client instance". Is
that correct?
I'm using a discovery server service deployed in the cluster and if i call
its own /apps API i do see the whole list of available services.

Thank you
Davide

Il mar 18 gen 2022, 18:42 Ryan Baxter ***@***.***> ha scritto:

**Comment by CosbyBs86** [comment]
Hello @ryanjbaxter,
 with the example you provided me the getServices() is working fine. I need time to figure out why with my project i'm running on this issue. The source code looks very similar (I would say looks the same :) ). Probably is something on the POM file. I'll investigate into this and let you know in this thread tomorrow. Maybe is something related to the fact I'm running a Spring Gateway application instead of a Spring MVC?

**Comment by ryanjbaxter** [comment]
Ah that just made a light bulb off, try autowiring `ReactiveDiscoveryClient` rather than `DiscoveryClient`.

**Comment by CosbyBs86** [comment]
Hello @ryanjbaxter 
you made my days. Using ReactiveDiscoveryClient rather than DiscoveryClient is working fine with my source code. Routing is working and getServices() call as well. May I ask you where it is mentioned to use ReactiveDiscoveryClient in gateway application? I would suggest you to improve the documentation about Discovery client. I surfed online a lot but didn't find a real working example. Also https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/ is not mentioning this. Many thanks for your support.

**Comment by ryanjbaxter** [comment]
Because the Gateway uses WebFlux and needs to be reactive, we have to use the reactive version of the `DiscoveryClient`.  This all happens under the covers via autoconfiguration.
