### ISSUE TITLE
Doc: Cover Hystrix

### ISSUE THREAD

**Issue by cmoulliard** [spring-cloud/spring-cloud-kubernetes#96]
The README page doesn't cover SCK Hystrix. We should detail what the SCK Hystrix allows to do or offers as feature.

Currently, it will initialize a `HystrixRequestContext context = HystrixRequestContext.initializeContext();` for every HTTP request and close it, end of the request

See Hystrix doc about [RequestContext](https://netflix.github.io/Hystrix/javadoc/com/netflix/hystrix/strategy/concurrency/HystrixRequestContext.html)

**Comment by spencergibb** [comment]
What does SCK do with Hystrix beyond what is provided by s-c-netflix?

**Comment by cmoulliard** [comment]
The idea of the HystrixRequestContext is to share between different threads the info coming from a request. Here is a use case describing that [idea](https://jfconavarrete.wordpress.com/2014/09/15/make-spring-security-context-available-inside-a-hystrix-command/)

As the code implemented here is not specific to Kubernetes or even OpenShift, I'm also sceptical about the pertinence of this module under SCK ....

@iocanel As you pushed [this code](https://github.com/fabric8io/spring-cloud-kubernetes/commit/f14e3f2f58a7052019e6e00faf29a9ebda552343), do you remember why you added HystrixRequestContextServletFilter ?

**Comment by spencergibb** [comment]
There is no longer any hystrix specific code here.
