### ISSUE TITLE
Configuration-Watcher - Support for different management server ports

### ISSUE THREAD

**Issue by lemoony** [spring-cloud/spring-cloud-kubernetes#973]
For our  service, we use a different management port:
`management.port: 8081`

Because of this, the configuration watcher fails to call the `/refresh` endpoint:

`403 Forbidden from POST http://<xxxxx>:8080/actuator/refresh`

Please provide a way to make this work without changing the management port to 8080. Maybe it's possible to provide the port number via a label similiar to what is suggested in #740.

We can't migrate to the Configuration Watcher until this issue as well as #740 (which is somehow similiar) are resolved. I very much like the idea of the watcher, but as of now it is missing configuration options. Pleas don't remove the PropertySource Reload feature until these issues have been resolved.

**Comment by ryanjbaxter** [comment]
See https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#non-default-management-port-and-actuator-path

**Comment by lemoony** [comment]
Ha, i totally missed that in den documentation. I'm sorry and thank you for the hint!
