### ISSUE TITLE
Watch connection expired: too old resource version

### ISSUE THREAD

**Issue by zyzyzy523** [spring-cloud/spring-cloud-kubernetes#975]
After the application is started for a period of time, the log keeps outputting Watch connection expired: too old resource version.

pom:
         <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-kubernetes-client</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-kubernetes-client-config</artifactId>
            <version>2.1.0</version>
        </dependency>

configure:
spring.cloud.kubernetes.reload.enabled=true

![image](https://user-images.githubusercontent.com/48322364/155054222-525b41a4-6d50-4243-911c-447828cb408e.png)

**Comment by ryanjbaxter** [comment]
That is not coming from spring cloud kubernetes, its coming from the kubernetes java client which we use.  There is nothing we can do to change it.  I assume everything is working as expected?
