### ISSUE TITLE
Investigate Using Testcontainers K3s Module For Integration Tests

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-kubernetes#981]
Can we eliminate the use of a full blow Kubernetes environment (currently Kind) and use Testcontainers and K3s?
https://www.testcontainers.org/modules/k3s/

**Comment by wind57** [comment]
Neat idea! I could take a look :)

**Comment by wind57** [comment]
just tagging the [PR](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/984) in here for visibility

**Comment by wind57** [comment]
@ryanjbaxter  can be closed also...
